### ISSUE TITLE
Error trying to run Flow Launcher 1.9.2 setup exe. Crashes on startup.

### ISSUE THREAD

**Issue by jafin** [Flow-Launcher/Flow.Launcher#1014]
**Describe the bug/issue**
Error trying to run Flower Launcher 1.9.2 setup exe

**To Reproduce**
1. Download Flow-Launcher-Setup (1.9.2)
2. Run
3. Straight away it errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/127927/152964969-3213def7-2b51-4c50-baa9-ee5c7de22e90.png)

**Your System**
```
Windows build number: 22000.469
Flow Launcher version: 1.9.2  (have 1.9.1 installed)
```
2022-02-08 20:03:49> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Squirrel.UnsafeUtility.<>c__DisplayClass0_0.<EnumerateProcesses>b__0(Int32 i)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Squirrel.UnsafeUtility.EnumerateProcesses()
   at Squirrel.UpdateManager.InstallHelperImpl.KillAllProcessesBelongingToPackage()
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Squirrel.UnsafeUtility.<>c__DisplayClass0_0.<EnumerateProcesses>b__0(Int32 i)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Squirrel.UnsafeUtility.EnumerateProcesses()
   at Squirrel.UpdateManager.InstallHelperImpl.KillAllProcessesBelongingToPackage()
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---

## Workaround
Run the check for update inside the app from 1.9.1 and it updated to 1.9.2

**Comment by jjw24** [comment]
Hey how's it going? This seems to be an issue with the installer flow is using. I think logging off or rebooting the computer might fix the problem. Let us know how you go.

**Comment by jafin** [comment]
@jjw24 I've updated to 1.9.2 via the app. .  Because of this, I'm not in a position to very the installer again.  I'll close this since I can repro it now.
