### ISSUE TITLE
Issue with twitchy on Flow.Launcher

### ISSUE THREAD

**Issue by nhgjhhbjhbhb** [Flow-Launcher/Flow.Launcher#1015]
Hi, i ran into an issue with twitchy for Flow.Launcher :

> Flow Launcher version: 1.9.2
OS Version: Microsoft Windows NT 10.0.19043.0
IntPtr Length: 8
x64: True

>Python Path: 
Date: 02/09/2022 19:49:26
Exception:
System.IO.InvalidDataException: Twitchy|Exception ignored in: <function Launcher.__del__ at 0x000002CD45020790>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\FlowLauncher\Plugins\Twitchy-2.1.0\lib\flox\launcher.py", line 59, in __del__
    self.__call__()
  File "C:\Users\user\AppData\Roaming\FlowLauncher\Plugins\Twitchy-2.1.0\lib\flox\__init__.py", line 96, in __call__
    return super().__call__()
  File "C:\Users\user\AppData\Roaming\FlowLauncher\Plugins\Twitchy-2.1.0\lib\flox\launcher.py", line 41, in __call__
    results = request_method(*request_parameters)
  File "C:\Users\user\AppData\Roaming\FlowLauncher\Plugins\Twitchy-2.1.0\lib\flox\__init__.py", line 127, in _query
    self.query(query)
  File "C:\Users\user\AppData\Roaming\FlowLauncher\Plugins\Twitchy-2.1.0\plugin\twitchy.py", line 48, in query
    channels = self.client.search.channels(query, limit=LIMIT)
  File "C:\Users\user\AppData\Roaming\FlowLauncher\Plugins\Twitchy-2.1.0\lib\twitch\api\search.py", line 18, in channels
    response = self._request_get('search/channels', params=params)
  File "C:\Users\user\AppData\Roaming\FlowLauncher\Plugins\Twitchy-2.1.0\lib\twitch\api\base.py", line 53, in _request_get
    response.raise_for_status()
  File "C:\Users\user\AppData\Roaming\FlowLauncher\Plugins\Twitchy-2.1.0\lib\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.twitch.tv/kraken/search/channels?query=martav&limit=10&offset=0

  > at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Have you provided an API key in settings? Twitch requires a key to access its search. 


Also Twitch is sun setting their old API and may not work intermittently.

**Comment by jjw24** [comment]
Closing. Please try the solution above, if still an issue feel free to reopen.
