### ISSUE TITLE
[Explorer] Explorer Search Plugin gives exceptions

### ISSUE THREAD

**Issue by harrynull** [Flow-Launcher/Flow.Launcher#1026]
**Describe the bug/issue**
The explorer search plugin often throws exceptions (probably due to bad escaping) when I am using calculator and drastically slowing down calculations.

Note: May or may not be relevant but I noticed that the explorer search plugin checks the reserved string patterns only at the beginning of the string (https://github.com/Flow-Launcher/Flow.Launcher/blob/dev/Plugins/Flow.Launcher.Plugin.Explorer/Search/WindowsIndex/IndexSearch.cs#L20), which means that something like `123"'456` will almost definitely cause an exception.

**To Reproduce**
1. Calculate something in the form like `123/12345.123`
2. The log should be spammed with errors from explorer search plugin.
3. If not, try 1 again but with a slightly different number (e.g. keep adding numbers after the decimal).

**Your System**
```
Windows build number: Windows 11, 21H2
Flow Launcher version: 1.9.2
```
**Flow Launcher Error Log**

I added some logs to print out the exact query performed. Hope that will help.

```
16:19:08.1880-05:00 - FATAL - FaultyLogger - Wrong logger message format <SELECT TOP 100 "System.FileName", "System.ItemUrl", "System.ItemType", "System.ItemPathDisplay" FROM "SystemIndex" WHERE (System.ItemPathDisplay LIKE '123/1241324.122311%' OR CONTAINS(System.FileName,'"123/1241324.122311*"',1033)) AND scope='file:' ORDER BY System.FileName>
16:19:08.4394-05:00 - FATAL - FaultyLogger - Wrong logger message format <SELECT TOP 100 "System.FileName", "System.ItemUrl", "System.ItemType", "System.ItemPathDisplay" FROM "SystemIndex" WHERE (System.ItemPathDisplay LIKE '123/1241324.12231%' OR CONTAINS(System.FileName,'"123/1241324.12231*"',1033)) AND scope='file:' ORDER BY System.FileName>
16:19:08.6456-05:00 - FATAL - FaultyLogger - Wrong logger message format <SELECT TOP 100 "System.FileName", "System.ItemUrl", "System.ItemType", "System.ItemPathDisplay" FROM "SystemIndex" WHERE (System.ItemPathDisplay LIKE '123/1241324.1223%' OR CONTAINS(System.FileName,'"123/1241324.1223*"',1033)) AND scope='file:' ORDER BY System.FileName>
16:19:08.9038-05:00 - FATAL - FaultyLogger - Wrong logger message format <SELECT TOP 100 "System.FileName", "System.ItemUrl", "System.ItemType", "System.ItemPathDisplay" FROM "SystemIndex" WHERE (System.ItemPathDisplay LIKE '123/1241324.122%' OR CONTAINS(System.FileName,'"123/1241324.122*"',1033)) AND scope='file:' ORDER BY System.FileName>
16:19:09.2525-05:00 - FATAL - FaultyLogger - Wrong logger message format <SELECT TOP 100 "System.FileName", "System.ItemUrl", "System.ItemType", "System.ItemPathDisplay" FROM "SystemIndex" WHERE (System.ItemPathDisplay LIKE '123/1241324.12%' OR CONTAINS(System.FileName,'"123/1241324.12*"',1033)) AND scope='file:' ORDER BY System.FileName>
16:19:09.5053-05:00 - FATAL - FaultyLogger - Wrong logger message format <SELECT TOP 100 "System.FileName", "System.ItemUrl", "System.ItemType", "System.ItemPathDisplay" FROM "SystemIndex" WHERE (System.ItemPathDisplay LIKE '123/1241324.1%' OR CONTAINS(System.FileName,'"123/1241324.1*"',1033)) AND scope='file:' ORDER BY System.FileName>
16:19:09.7014-05:00 - FATAL - FaultyLogger - Wrong logger message format <SELECT TOP 100 "System.FileName", "System.ItemUrl", "System.ItemType", "System.ItemPathDisplay" FROM "SystemIndex" WHERE (System.ItemPathDisplay LIKE '123/1241324.%' OR CONTAINS(System.FileName,'"123/1241324.*"',1033)) AND scope='file:' ORDER BY System.FileName>
16:19:09.8903-05:00 - FATAL - FaultyLogger - Wrong logger message format <SELECT TOP 100 "System.FileName", "System.ItemUrl", "System.ItemType" FROM "SystemIndex" WHERE CONTAINS(System.FileName,'"123/1241324*"',1033) AND scope='file:' ORDER BY System.FileName>
16:19:10.0900-05:00 - FATAL - FaultyLogger - Wrong logger message format <SELECT TOP 100 "System.FileName", "System.ItemUrl", "System.ItemType" FROM "SystemIndex" WHERE CONTAINS(System.FileName,'"123/124132*"',1033) AND scope='file:' ORDER BY System.FileName>
16:19:10.4214-05:00 - FATAL - FaultyLogger - Wrong logger message format <SELECT TOP 100 "System.FileName", "System.ItemUrl", "System.ItemType" FROM "SystemIndex" WHERE CONTAINS(System.FileName,'"123/1241321*"',1033) AND scope='file:' ORDER BY System.FileName>
16:19:11.5280-05:00 - FATAL - FaultyLogger - Wrong logger message format <SELECT TOP 100 "System.FileName", "System.ItemUrl", "System.ItemType", "System.ItemPathDisplay" FROM "SystemIndex" WHERE (System.ItemPathDisplay LIKE '123/1241321.%' OR CONTAINS(System.FileName,'"123/1241321.*"',1033)) AND scope='file:' ORDER BY System.FileName>
16:19:11.7862-05:00 - FATAL - FaultyLogger - Wrong logger message format <SELECT TOP 100 "System.FileName", "System.ItemUrl", "System.ItemType", "System.ItemPathDisplay" FROM "SystemIndex" WHERE (System.ItemPathDisplay LIKE '123/1241321.1%' OR CONTAINS(System.FileName,'"123/1241321.1*"',1033)) AND scope='file:' ORDER BY System.FileName>
16:19:12.3965-05:00 - FATAL - FaultyLogger - Wrong logger message format <SELECT TOP 100 "System.FileName", "System.ItemUrl", "System.ItemType", "System.ItemPathDisplay" FROM "SystemIndex" WHERE (System.ItemPathDisplay LIKE '123/1241321.12%' OR CONTAINS(System.FileName,'"123/1241321.12*"',1033)) AND scope='file:' ORDER BY System.FileName>
16:19:13.6801-05:00 - FATAL - FaultyLogger - Wrong logger message format <SELECT TOP 100 "System.FileName", "System.ItemUrl", "System.ItemType", "System.ItemPathDisplay" FROM "SystemIndex" WHERE (System.ItemPathDisplay LIKE '123/1241321.1%' OR CONTAINS(System.FileName,'"123/1241321.1*"',1033)) AND scope='file:' ORDER BY System.FileName>
16:19:13.8815-05:00 - FATAL - FaultyLogger - Wrong logger message format <SELECT TOP 100 "System.FileName", "System.ItemUrl", "System.ItemType", "System.ItemPathDisplay" FROM "SystemIndex" WHERE (System.ItemPathDisplay LIKE '123/1241321.%' OR CONTAINS(System.FileName,'"123/1241321.*"',1033)) AND scope='file:' ORDER BY System.FileName>
16:19:14.0856-05:00 - FATAL - FaultyLogger - Wrong logger message format <SELECT TOP 100 "System.FileName", "System.ItemUrl", "System.ItemType" FROM "SystemIndex" WHERE CONTAINS(System.FileName,'"123/1241321*"',1033) AND scope='file:' ORDER BY System.FileName>
16:19:14.2825-05:00 - FATAL - FaultyLogger - Wrong logger message format <SELECT TOP 100 "System.FileName", "System.ItemUrl", "System.ItemType" FROM "SystemIndex" WHERE CONTAINS(System.FileName,'"123/124132*"',1033) AND scope='file:' ORDER BY System.FileName>
16:19:22.2111-05:00 - FATAL - UnHandledException - 
## Exception
System.Data.OleDb.OleDbException: IErrorInfo.GetDescription failed with E_FAIL(0x80004005).
   Source: Flow.Launcher.Plugin.Explorer
   TargetAssembly: Flow.Launcher.Plugin.Explorer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
   TargetModule: Flow.Launcher.Plugin.Explorer.dll
   TargetSite: Void LogException(System.String, System.Exception)
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.IndexSearch.LogException(String message, Exception e)
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.IndexSearch.ExecuteWindowsIndexSearchAsync(String indexQueryString, String connectionString, Query query, CancellationToken token)
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.IndexSearch.WindowsIndexSearchAsync(String searchString, Func`1 createQueryHelper, Func`2 constructQuery, List`1 exclusionList, Query query, CancellationToken token)
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.WindowsIndexFilesAndFoldersSearchAsync(Query query, String querySearchString, CancellationToken token)
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token)
   at Flow.Launcher.Plugin.Explorer.Main.QueryAsync(Query query, CancellationToken token)
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by azoz773** [comment]
الو

في الاثنين، ١٤ فبراير، ٢٠٢٢ ١٢:٢٩ ص Harry ***@***.***> كتب:

**Comment by taooceros** [comment]
Although I cannot reproduce the error, I do have realized the calculator plugin has some latency (or results miss) when query includes operator. I will check with debugging later.
