### ISSUE TITLE
Problem when running HelloWorldNode plugin

### ISSUE THREAD

**Issue by orrosman** [Flow-Launcher/Flow.Launcher#1035]
**Describe the bug/issue**
I have spaces in path to the NodeJS plugin, changed the node.bat to adjust for that.
Now the plugin have an issue finding modules.

**To Reproduce**
1. change node.bat from `node %plugin_dir%/main.js%*` to `node "%plugin_dir%/main.js%*"` (added apostrophes)
2.  run plugin with `hn` command through Flow Launcher

**Your System**
```
Microsoft Windows [Version 10.0.19044.1526]
Flow Launcher version: 1.9.2
```
**Flow Launcher Error Log**

```
Flow Launcher version: 1.9.2
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 02/21/2022 10:58:44
Exception:
System.IO.InvalidDataException: Hello World Node.js|node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\Or Rosman\AppData\Roaming\FlowLauncher\Plugins\Hello World Node.js-1.0.0\main.js{"method":"query","parameters":[""],"settings":null}'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 308
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 308
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 323
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by jjw24** [comment]
Hey how's it going, thanks for the issue, will take a look later.

**Comment by jjw24** [comment]
partial fix: https://github.com/Flow-Launcher/Flow.Launcher.Plugin.HelloWorldNodeJS/pull/1

Need to investigate if still an issue finding modules.

**Comment by jjw24** [comment]
This problem should be addressed already, if not the case please reopen.
