### ISSUE TITLE
Flow Launcher version: 1.9.2 Obsidian Plugin

### ISSUE THREAD

**Issue by slallani** [Flow-Launcher/Flow.Launcher#1038]
Got this error when trying to run the Obsidian plugin:

Flow Launcher version: 1.9.2
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 02/26/2022 13:47:35
Exception:
System.IO.InvalidDataException: Obsidian Notes|Traceback (most recent call last):
  File "C:\Users\Shoeb Lallani\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.0.1\run.py", line 9, in <module>
    from plugin.main import Obsidian
  File "C:\Users\Shoeb Lallani\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.0.1\plugin\main.py", line 3, in <module>
    from flox import Flox
  File "C:\Users\Shoeb Lallani\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.0.1\lib\flox\__init__.py", line 4, in <module>
    from .flox import Flox
  File "C:\Users\Shoeb Lallani\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.0.1\lib\flox\flox.py", line 37, in <module>
    _version = ".".join(map(str, max(_versions)))
ValueError: max() arg is an empty sequence

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
This is a function Flox uses to determine the latest Flow Launcher program directory. It's odd it would have trouble finding the folder.

Can you please send a screenshot of your `%LocalAppData%\FlowLauncher` Directory?

**Comment by slallani** [comment]
Never mind, it started to work suddenly. Thank you for helping!

**Comment by Garulf** [comment]
> Never mind, it started to work suddenly. Thank you for helping!

No problem! Closing but feel free to reopen if the problem appears again!
