### ISSUE TITLE
C:\Users\Anup\AppData\Roaming\FlowLauncher\Logs\1.9.2\2022-02-28.txt

### ISSUE THREAD

**Issue by anup514** [Flow-Launcher/Flow.Launcher#1044]
Flow Launcher version: 1.9.2
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 02/28/2022 20:13:43
Exception:
SpotifyAPI.Web.APIException: Player command failed: Premium required
   at SpotifyAPI.Web.Http.APIConnector.ProcessErrors(IResponse response)
   at SpotifyAPI.Web.Http.APIConnector.DoRequest(IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.SendAPIRequestDetailed(Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers)
   at SpotifyAPI.Web.Http.APIConnector.Put(Uri uri, IDictionary`2 parameters, Object body)
   at SpotifyAPI.Web.PlayerClient.TransferPlayback(PlayerTransferPlaybackRequest request)
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPluginClient.SetDevice(String deviceId) in D:\a\Flow.Launcher.Plugin.SpotifyPremium\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPluginClient.cs:line 398
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPlugin.<>c__DisplayClass26_0.<GetDevices>b__3(ActionContext _) in D:\a\Flow.Launcher.Plugin.SpotifyPremium\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPlugin.cs:line 395
   at Flow.Launcher.ViewModel.MainViewModel.<InitializeKeyCommands>b__19_9(Object index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 207
   at Flow.Launcher.ViewModel.RelayCommand.Execute(Object parameter) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\RelayCommand.cs:line 25
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by taooceros** [comment]
I think you are using the spotify plugin? It requires premium.
