### ISSUE TITLE
Using Sonarr plugin

### ISSUE THREAD

**Issue by kevin182** [Flow-Launcher/Flow.Launcher#1045]
[2022-02-27.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8149665/2022-02-27.txt)

Flow Launcher version: 1.9.2
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 02/27/2022 18:59:26
Exception:
System.IO.InvalidDataException: Sonarr Search|Traceback (most recent call last):
  File "C:\Users\kevin\AppData\Roaming\FlowLauncher\Plugins\Sonarr Search-0.1.0\run.py", line 12, in <module>
    SonarrSearch()
  File "C:\Users\kevin\AppData\Roaming\FlowLauncher\Plugins\Sonarr Search-0.1.0\lib\flox\__init__.py", line 108, in __init__
    super().__init__(self.api)
  File "C:\Users\kevin\AppData\Roaming\FlowLauncher\Plugins\Sonarr Search-0.1.0\lib\flox\launcher.py", line 30, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\kevin\AppData\Roaming\FlowLauncher\Plugins\Sonarr Search-0.1.0\lib\flox\__init__.py", line 114, in _query
    self.query(query)
  File "C:\Users\kevin\AppData\Roaming\FlowLauncher\Plugins\Sonarr Search-0.1.0\plugin\main.py", line 48, in query
    self.series_results(query)
  File "C:\Users\kevin\AppData\Roaming\FlowLauncher\Plugins\Sonarr Search-0.1.0\plugin\main.py", line 54, in series_results
    shows = get_sonarr_series(self.sr)
  File "C:\Users\kevin\AppData\Roaming\FlowLauncher\Plugins\Sonarr Search-0.1.0\lib\flox\utils.py", line 28, in wrapper
    data = func(*args, **kwargs)
  File "C:\Users\kevin\AppData\Roaming\FlowLauncher\Plugins\Sonarr Search-0.1.0\plugin\main.py", line 15, in get_sonarr_series
    shows = sonarr.get_series()
  File "C:\Users\kevin\AppData\Roaming\FlowLauncher\Plugins\Sonarr Search-0.1.0\lib\pyarr\sonarr_api.py", line 484, in get_series
    res = self.request_get(path)
  File "C:\Users\kevin\AppData\Roaming\FlowLauncher\Plugins\Sonarr Search-0.1.0\lib\pyarr\request_api.py", line 52, in request_get
    return res.json()
  File "C:\Users\kevin\AppData\Roaming\FlowLauncher\Plugins\Sonarr Search-0.1.0\lib\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 308
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 308
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 323
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Looks like the Sonarr server responded with an empty response probably due to a connection error. 

Please make sure all your settings are correct, the server is working, and you have a connection to the server. 

If the problem persists please provide the some info about your Sonarr installation. Like the Os and version.

**Comment by Garulf** [comment]
Upon review this error may be related to Python 3.10. They changed and removed some things from the JSON module that may be causing your error. Please try Python 3.8 and see if the problem occurs.

**Comment by kevin182** [comment]
Python 3.10 is working now. I just had to restart FlowLauncher and it started working.
