### ISSUE TITLE
Dictionary plugin unable to open database

### ISSUE THREAD

**Issue by anup514** [Flow-Launcher/Flow.Launcher#1046]
Flow Launcher version: 1.9.2
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 03/01/2022 05:27:57
Exception:
code = CantOpen (14), message = System.Data.SQLite.SQLiteException (0x800007FF): unable to open database file
   at System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
   at System.Data.SQLite.SQLiteConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Dictionary.ECDict.QueryAsync(String word, CancellationToken token) in D:\a\Flow.Launcher.Dictionary\Flow.Launcher.Dictionary\src\ECDict.cs:line 37
   at Dictionary.Main.FirstLevelQueryAsync(Query query, CancellationToken token) in D:\a\Flow.Launcher.Dictionary\Flow.Launcher.Dictionary\src\Dictionary.cs:line 158
   at Dictionary.Main.QueryAsync(Query query, CancellationToken token) in D:\a\Flow.Launcher.Dictionary\Flow.Launcher.Dictionary\src\Dictionary.cs:line 345
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by deefrawley** [comment]
Hi Anup,
When adding a new issue it is really helpful to tell us what you were doing and/or what plugin you were using when the error occurred. Thanks

**Comment by jjw24** [comment]
Closing. Feel free to reopen if problem persists.
