### ISSUE TITLE
Error with Dictionary plugin

### ISSUE THREAD

**Issue by david-6399** [Flow-Launcher/Flow.Launcher#1048]
System.Net.WebException: Hôte inconnu. ([nullptr_t.coding.net:443](https://github.com/Flow-Launcher/Flow.Launcher/issues/nullptr_t.coding.net:443))
---> System.Net.Http.HttpRequestException: Hôte inconnu. ([nullptr_t.coding.net:443](https://github.com/Flow-Launcher/Flow.Launcher/issues/nullptr_t.coding.net:443))
---> System.Net.Sockets.SocketException (11001): Hôte inconnu.
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
at System.Net.Sockets.Socket.g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
at System.Net.Http.ConnectHelper.ConnectAsync(Func3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.ConnectHelper.ConnectAsync(Func3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
at System.Net.HttpWebRequest.SendRequest(Boolean async)
at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
--- End of inner exception stack trace ---
at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
at System.Net.WebClient.GetWebResponseTaskAsync(WebRequest request)
at System.Net.WebClient.DownloadBitsAsync(WebRequest request, Stream writeStream, AsyncOperation asyncOp, Action`3 completionDelegate)
at Dictionary.DictDownloadManager.PerformDownload() in D:\a\Flow.Launcher.Dictionary\Flow.Launcher.Dictionary\src\DictDownloadManager.cs:line 62
at System.Threading.Tasks.Task.<>c.b__140_0(Object state)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
Hey @david-6399, error looks like it's trying to download dictionary data for dictionary plugin. Were you trying to use the Dictionary plugin? Please let us know the action you were doing so we can replicate the error.

@harrynull would this be something coming from the Dictionary plugin?

**Comment by david-6399** [comment]
how can i set Dictionary

**Comment by jjw24** [comment]
> how can i set Dictionary

It should show something like this, where you press enter and it will download the data file required for the plugin, is this where you are getting the error after pressing enter?

![image](https://user-images.githubusercontent.com/26427004/156137341-6bfe8467-a1bb-43ea-a6d4-58e9943c57fc.png)
