### ISSUE TITLE
FlowYoutube Not Working

### ISSUE THREAD

**Issue by GladiatorsTV** [Flow-Launcher/Flow.Launcher#1051]
Flow Launcher version: 1.9.2
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 03/01/2022 20:50:05
Exception:
System.IO.InvalidDataException: FlowYouTube|Exception ignored in: <function Launcher.__del__ at 0x000001F25E407E50>
Traceback (most recent call last):
  File "C:\Users\Shubh\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-0.2.0\lib\flox\launcher.py", line 59, in __del__
    self.__call__()
  File "C:\Users\Shubh\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-0.2.0\lib\flox\__init__.py", line 96, in __call__
    return super().__call__()
  File "C:\Users\Shubh\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-0.2.0\lib\flox\launcher.py", line 41, in __call__
    results = request_method(*request_parameters)
  File "C:\Users\Shubh\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-0.2.0\lib\flox\__init__.py", line 127, in _query
    self.query(query)
  File "C:\Users\Shubh\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-0.2.0\plugin\main.py", line 27, in query
    self._results = utils.cache(query, max_age=MAX_CACHE_AGE, dir=path)(self.search)(query)
  File "C:\Users\Shubh\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-0.2.0\lib\flox\utils.py", line 39, in wrapper
    data = func(*args, **kwargs)
  File "C:\Users\Shubh\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-0.2.0\plugin\main.py", line 35, in search
    self.result(item, executor)
  File "C:\Users\Shubh\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-0.2.0\plugin\main.py", line 41, in result
    download_thumbs = strtobool(self.settings.get('download_thumbs', True))
  File "distutils\util.py", line 313, in strtobool
AttributeError: 'bool' object has no attribute 'lower'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 613
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 587
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2022-03-01.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8162648/2022-03-01.txt)

**Comment by GladiatorsTV** [comment]
It's Still Broken
[2022-03-02.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8168780/2022-03-02.txt)

Flow Launcher version: 1.9.2
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 03/02/2022 15:55:18
Exception:
System.IO.InvalidDataException: FlowYouTube|Exception ignored in: <function Launcher.__del__ at 0x0000021619142D30>
Traceback (most recent call last):
  File "C:\Users\Shubh\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-0.2.1\lib\flox\launcher.py", line 59, in __del__
    self.__call__()
  File "C:\Users\Shubh\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-0.2.1\lib\flox\__init__.py", line 96, in __call__
    return super().__call__()
  File "C:\Users\Shubh\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-0.2.1\lib\flox\launcher.py", line 41, in __call__
    results = request_method(*request_parameters)
  File "C:\Users\Shubh\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-0.2.1\lib\flox\__init__.py", line 127, in _query
    self.query(query)
  File "C:\Users\Shubh\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-0.2.1\plugin\main.py", line 26, in query
    self._results = utils.cache(query, max_age=MAX_CACHE_AGE, dir=path)(self.search)(query)
  File "C:\Users\Shubh\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-0.2.1\lib\flox\utils.py", line 43, in wrapper
    with open(cache_file, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Shubh\\AppData\\Local\\Temp\\FlowYouTube\\linus tech tips'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 308
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 308
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 323
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
I suspect this is because the old version crashed while writing to cache. Does this still happen when using a new never before used search term?

**Comment by Garulf** [comment]
> Yes I Even Did Clean Reinstall Of The Who Program (I Even Removed It From Every Windows Library) But It Still Crashes And Even Though I Have The Latest Version Of Python Installed

Okay then it seems to be having trouble creating the cache directory. Could you please navigate to this directory: `C:\Users\Shubh\AppData\Local\Temp` and determine if the folder named: `FlowYouTube` was created there.

If this is the case I can fix this in a few moments for you.

**Comment by GladiatorsTV** [comment]
There Is A Folder Called "**flowlauncher**" With A Zip Archive Called "**FlowYouTube-0.2.1**"

**Comment by GladiatorsTV** [comment]
Thank You It Finally Works
