### ISSUE TITLE
Issue when using Python 3.10 to open FlowYoutube plugin

### ISSUE THREAD

**Issue by lihuelworks** [Flow-Launcher/Flow.Launcher#1053]
Flow Launcher version: 1.9.2
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: C:\Python310\pythonw.exe
Date: 03/01/2022 19:56:04
Exception:
System.ComponentModel.Win32Exception (740): The requested operation requires elevation.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 247
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2022-03-01.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8165276/2022-03-01.txt)

**Comment by taooceros** [comment]
What's the query trigger the error?

**Comment by lihuelworks** [comment]
> What's the query trigger the error?

"yt anything searched", also happens with the steam search extension. Thought it was portable mode, so I disabled it but it's the same issue.

**Comment by taooceros** [comment]
> > What's the query trigger the error?
> 
> "yt anything searched", also happens with the steam search extension. Thought it was portable mode, so I disabled it but it's the same issue.

I feel like the flow is unable to execute your python executable (which probably is installed in a place that requires privilege). You can set the python path of flow to be empty, and let it download the portable python, which should not have these kind of access issue.

**Comment by lihuelworks** [comment]
Noted. I'll try that right now. Is there any way to reset the python location? I'm currently trying uninstalling and re-installing the plugin to prompt the python location dialog to reappear, but no dice

**Comment by taooceros** [comment]
> Noted. I'll try that right now. Is there any way to reset the python location? I'm currently trying uninstalling and re-installing the plugin to prompt the python location dialog to reappear, but no dice

just empty the python directory entry in the setting 
![image](https://user-images.githubusercontent.com/45326534/156264327-32ee2ac3-bef4-4138-a7fd-6c88eed3bce2.png)

**Comment by lihuelworks** [comment]
Done, did the trick and now plugins work back to normal. Thanks!
