### ISSUE TITLE
Problem with the Obsidian Plugin and Python Path

### ISSUE THREAD

**Issue by fnfontana** [Flow-Launcher/Flow.Launcher#1091]
--> **[LOG-FILE.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8324437/2022-03-22.txt)**

---

Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 03/22/2022 10:07:16
Exception:
System.IO.InvalidDataException: Obsidian Notes|Exception ignored in: <function Launcher.__del__ at 0x0000023799DD0940>
Traceback (most recent call last):
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.0\lib\flox\launcher.py", line 59, in __del__
    self.__call__()
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.0\lib\flox\__init__.py", line 96, in __call__
    return super().__call__()
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.0\lib\flox\launcher.py", line 41, in __call__
    results = request_method(*request_parameters)
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.0\lib\flox\__init__.py", line 127, in _query
    self.query(query)
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.0\plugin\main.py", line 38, in query
    context=[vault.id, str(note.path), note.checklists()]
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.0\plugin\obsidian.py", line 105, in checklists
    for line in self.content().splitlines():
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.0\plugin\obsidian.py", line 86, in content
    return f.read()
  File "C:\Users\ffont\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 483: character maps to <undefined>

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 613
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 587
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Simple encoding issue, fixed in the latest version 1.1.1! Please update by typing:
```
pm update Obsidian Notes
```
