### ISSUE TITLE
Raindrop Plugin Error

### ISSUE THREAD

**Issue by fnfontana** [Flow-Launcher/Flow.Launcher#1093]
**Log FIle:** [2022-03-23.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8332901/2022-03-23.txt)

---

Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 03/23/2022 09:22:56
Exception:
System.IO.InvalidDataException: FlowRaindrop|Traceback (most recent call last):
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Flow-Raindrop-50764d48-4bad-464b-82ba-219d74c5ef09\lib\requests\compat.py", line 12, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Flow-Raindrop-50764d48-4bad-464b-82ba-219d74c5ef09\run.py", line 9, in <module>
    from plugin.main import FlowRainDrop
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Flow-Raindrop-50764d48-4bad-464b-82ba-219d74c5ef09\plugin\main.py", line 3, in <module>
    from raindropio import API, CollectionRef, Raindrop, Collection
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Flow-Raindrop-50764d48-4bad-464b-82ba-219d74c5ef09\lib\raindropio\__init__.py", line 23, in <module>
    from .api import API, create_oauth2session  # noqa
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Flow-Raindrop-50764d48-4bad-464b-82ba-219d74c5ef09\lib\raindropio\api.py", line 8, in <module>
    import requests
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Flow-Raindrop-50764d48-4bad-464b-82ba-219d74c5ef09\lib\requests\__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Flow-Raindrop-50764d48-4bad-464b-82ba-219d74c5ef09\lib\requests\exceptions.py", line 11, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Flow-Raindrop-50764d48-4bad-464b-82ba-219d74c5ef09\lib\requests\compat.py", line 14, in <module>
    import charset_normalizer as chardet
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Flow-Raindrop-50764d48-4bad-464b-82ba-219d74c5ef09\lib\charset_normalizer\__init__.py", line 24, in <module>
    from .api import from_bytes, from_fp, from_path, normalize
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Flow-Raindrop-50764d48-4bad-464b-82ba-219d74c5ef09\lib\charset_normalizer\api.py", line 10, in <module>
    from .cd import (
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Flow-Raindrop-50764d48-4bad-464b-82ba-219d74c5ef09\lib\charset_normalizer\cd.py", line 7, in <module>
    from .assets import FREQUENCIES
ModuleNotFoundError: No module named 'charset_normalizer.assets'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 587
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by fnfontana** [comment]
After updating to Release v0.0.2
**Log File:** [2022-03-23.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8332950/2022-03-23.txt)

---

Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 03/23/2022 09:28:58
Exception:
System.IO.InvalidDataException: FlowRaindrop|Traceback (most recent call last):
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Flow-Raindrop-50764d48-4bad-464b-82ba-219d74c5ef09\lib\requests\compat.py", line 12, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Flow-Raindrop-50764d48-4bad-464b-82ba-219d74c5ef09\run.py", line 9, in <module>
    from plugin.main import FlowRainDrop
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Flow-Raindrop-50764d48-4bad-464b-82ba-219d74c5ef09\plugin\main.py", line 3, in <module>
    from raindropio import API, CollectionRef, Raindrop, Collection
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Flow-Raindrop-50764d48-4bad-464b-82ba-219d74c5ef09\lib\raindropio\__init__.py", line 23, in <module>
    from .api import API, create_oauth2session  # noqa
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Flow-Raindrop-50764d48-4bad-464b-82ba-219d74c5ef09\lib\raindropio\api.py", line 8, in <module>
    import requests
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Flow-Raindrop-50764d48-4bad-464b-82ba-219d74c5ef09\lib\requests\__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Flow-Raindrop-50764d48-4bad-464b-82ba-219d74c5ef09\lib\requests\exceptions.py", line 11, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Flow-Raindrop-50764d48-4bad-464b-82ba-219d74c5ef09\lib\requests\compat.py", line 14, in <module>
    import charset_normalizer as chardet
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Flow-Raindrop-50764d48-4bad-464b-82ba-219d74c5ef09\lib\charset_normalizer\__init__.py", line 24, in <module>
    from .api import from_bytes, from_fp, from_path, normalize
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Flow-Raindrop-50764d48-4bad-464b-82ba-219d74c5ef09\lib\charset_normalizer\api.py", line 10, in <module>
    from .cd import (
  File "C:\Users\ffont\AppData\Roaming\FlowLauncher\Plugins\Flow-Raindrop-50764d48-4bad-464b-82ba-219d74c5ef09\lib\charset_normalizer\cd.py", line 7, in <module>
    from .assets import FREQUENCIES
ModuleNotFoundError: No module named 'charset_normalizer.assets'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 613
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 587
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by fnfontana** [comment]
Update

After run the command `pip install chardet`, the issue was solved to me.

**Comment by Garulf** [comment]
Are you using version v0.0.2?

**Comment by fnfontana** [comment]
Yes, i've downloaded directly of your repository releases.

**Comment by Garulf** [comment]
Not sure why it would give you that error and im glad you were able to get it working. 

Packaging the requests library causes a lot of weird import issues with `chardet` and and `charset_normalizer` that I'm unable to fully nail down. I'm closing for now and will continue to research alternative fixes.
