### ISSUE TITLE
Explorer plugin UnauthorizedAccessException

### ISSUE THREAD

**Issue by MrFDarcy** [Flow-Launcher/Flow.Launcher#1101]
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 03/29/2022 07:57:13
Exception:
System.UnauthorizedAccessException: Retrieving the COM class factory for component with CLSID {7D096C5F-AC08-4F1F-BEB7-5C22C517CE39} failed due to the following error: 80070005 Access is denied. (0x80070005 (E_ACCESSDENIED)).
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.QueryConstructor.CreateQueryHelper() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\QueryConstructor.cs:line 38
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.QueryConstructor.CreateBaseQuery() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\QueryConstructor.cs:line 18
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.QueryConstructor.QueryForAllFilesAndFolders(String userSearchString) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\QueryConstructor.cs:line 108
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.IndexSearch.WindowsIndexSearchAsync(String searchString, Func`1 createQueryHelper, Func`2 constructQuery, List`1 exclusionList, Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\IndexSearch.cs:line 104
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.WindowsIndexFilesAndFoldersSearchAsync(Query query, String querySearchString, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 189
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 74
   at Flow.Launcher.Plugin.Explorer.Main.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Main.cs:line 61
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 587
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
You have an UnauthorizedAccessException, meaning either the location you are trying to search is restricted or may be your Flow is not run with enough privileges. Try running it as admin.

**Comment by jjw24** [comment]
Closing. Feel free to reopen if still having the same issue.
