### ISSUE TITLE
Error while searching for Dictionary

### ISSUE THREAD

**Issue by tghimanshu** [Flow-Launcher/Flow.Launcher#1102]
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 03/29/2022 11:54:14
Exception:
System.Net.WebException: An exception occurred during a WebClient request.
 ---> System.IO.IOException: The decryption operation failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090330): The specified data could not be decrypted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebClient.DownloadBitsAsync(WebRequest request, Stream writeStream, AsyncOperation asyncOp, Action`3 completionDelegate)
   --- End of inner exception stack trace ---
   at Dictionary.DictDownloadManager.PerformDownload() in D:\a\Flow.Launcher.Dictionary\Flow.Launcher.Dictionary\src\DictDownloadManager.cs:line 62
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
Hey @tghimanshu how's it going. Were you just selecting to download the dictionary data after installing the plugin? What happens if you redownload it?

@harrynull

**Comment by jjw24** [comment]
Closing. Please reopen if still getting the same issue.
