### ISSUE TITLE
Spotify is not working when I am trying to use it using flow launcher

### ISSUE THREAD

**Issue by SuperLeo-Programmer** [Flow-Launcher/Flow.Launcher#1105]
This is the error which is occuring
[2022-03-30.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8378921/2022-03-30.txt)

**Comment by Garulf** [comment]
Are you using a Spotify Premium account?

Log:
```
SpotifyAPI.Web.APIException: Player command failed: Premium required
   Source: SpotifyAPI.Web
   TargetAssembly: SpotifyAPI.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
   TargetModule: SpotifyAPI.Web.dll
   TargetSite: Void ProcessErrors(SpotifyAPI.Web.Http.IResponse)
   at SpotifyAPI.Web.Http.APIConnector.ProcessErrors(IResponse response)
   at SpotifyAPI.Web.Http.APIConnector.DoRequest(IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.SendAPIRequestDetailed(Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers)
   at SpotifyAPI.Web.Http.APIConnector.Put(Uri uri, IDictionary`2 parameters, Object body)
   at SpotifyAPI.Web.PlayerClient.TransferPlayback(PlayerTransferPlaybackRequest request)
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPluginClient.SetDevice(String deviceId) in D:\a\Flow.Launcher.Plugin.SpotifyPremium\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPluginClient.cs:line 398
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPlugin.<>c__DisplayClass26_0.<GetDevices>b__3(ActionContext _) in D:\a\Flow.Launcher.Plugin.SpotifyPremium\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPlugin.cs:line 395
   at Flow.Launcher.ViewModel.MainViewModel.<InitializeKeyCommands>b__19_9(Object index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 207
   at Flow.Launcher.MainWindow.OnPreviewMouseButtonDown(Object sender, MouseButtonEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 355
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   ```

**Comment by SuperLeo-Programmer** [comment]
> Are you using a Spotify Premium account?
> 
> Log:
> 
> ```
> SpotifyAPI.Web.APIException: Player command failed: Premium required
>    Source: SpotifyAPI.Web
>    TargetAssembly: SpotifyAPI.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
>    TargetModule: SpotifyAPI.Web.dll
>    TargetSite: Void ProcessErrors(SpotifyAPI.Web.Http.IResponse)
>    at SpotifyAPI.Web.Http.APIConnector.ProcessErrors(IResponse response)
>    at SpotifyAPI.Web.Http.APIConnector.DoRequest(IRequest request)
>    at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request)
>    at SpotifyAPI.Web.Http.APIConnector.SendAPIRequestDetailed(Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers)
>    at SpotifyAPI.Web.Http.APIConnector.Put(Uri uri, IDictionary`2 parameters, Object body)
>    at SpotifyAPI.Web.PlayerClient.TransferPlayback(PlayerTransferPlaybackRequest request)
>    at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPluginClient.SetDevice(String deviceId) in D:\a\Flow.Launcher.Plugin.SpotifyPremium\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPluginClient.cs:line 398
>    at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPlugin.<>c__DisplayClass26_0.<GetDevices>b__3(ActionContext _) in D:\a\Flow.Launcher.Plugin.SpotifyPremium\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPlugin.cs:line 395
>    at Flow.Launcher.ViewModel.MainViewModel.<InitializeKeyCommands>b__19_9(Object index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 207
>    at Flow.Launcher.MainWindow.OnPreviewMouseButtonDown(Object sender, MouseButtonEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 355
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>    at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
>    at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> ```

yes I am

**Comment by SuperLeo-Programmer** [comment]
> otifyA

what should I do with the log file?

**Comment by SuperLeo-Programmer** [comment]
> Are you using a Spotify Premium account?
> 
> Log:
> 
> ```
> SpotifyAPI.Web.APIException: Player command failed: Premium required
>    Source: SpotifyAPI.Web
>    TargetAssembly: SpotifyAPI.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
>    TargetModule: SpotifyAPI.Web.dll
>    TargetSite: Void ProcessErrors(SpotifyAPI.Web.Http.IResponse)
>    at SpotifyAPI.Web.Http.APIConnector.ProcessErrors(IResponse response)
>    at SpotifyAPI.Web.Http.APIConnector.DoRequest(IRequest request)
>    at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request)
>    at SpotifyAPI.Web.Http.APIConnector.SendAPIRequestDetailed(Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers)
>    at SpotifyAPI.Web.Http.APIConnector.Put(Uri uri, IDictionary`2 parameters, Object body)
>    at SpotifyAPI.Web.PlayerClient.TransferPlayback(PlayerTransferPlaybackRequest request)
>    at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPluginClient.SetDevice(String deviceId) in D:\a\Flow.Launcher.Plugin.SpotifyPremium\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPluginClient.cs:line 398
>    at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPlugin.<>c__DisplayClass26_0.<GetDevices>b__3(ActionContext _) in D:\a\Flow.Launcher.Plugin.SpotifyPremium\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPlugin.cs:line 395
>    at Flow.Launcher.ViewModel.MainViewModel.<InitializeKeyCommands>b__19_9(Object index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 207
>    at Flow.Launcher.MainWindow.OnPreviewMouseButtonDown(Object sender, MouseButtonEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 355
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>    at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
>    at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> ```

what should i do with this ? should I paste it somewehre?

**Comment by Garulf** [comment]
I'd recommend creating an issue with the plugin owner at: https://github.com/fow5040/Flow.Launcher.Plugin.SpotifyPremium
