### ISSUE TITLE
Nexusmods plugin crashed flow launcher, when i type "nx eldenring"

### ISSUE THREAD

**Issue by CUR5EDFLVME** [Flow-Launcher/Flow.Launcher#1124]
[2022-04-12.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8471976/2022-04-12.txt)

Please open new issue in: 
1. upload log file: C:\Users\cur5e\AppData\Roaming\FlowLauncher\Logs\1.9.3\2022-04-12.txt
2. copy below exception message

Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 04/12/2022 15:09:21
Exception:
System.IO.InvalidDataException: nexusmods-search|Traceback (most recent call last):
  File "C:\Users\cur5e\AppData\Roaming\FlowLauncher\Plugins\nexusmods-search-0.2.2\run.py", line 12, in <module>
    NexusmodsSearch()
  File "C:\Users\cur5e\AppData\Roaming\FlowLauncher\Plugins\nexusmods-search-0.2.2\plugin\nexusmods_search.py", line 14, in __init__
    super().__init__()
  File "C:\Users\cur5e\AppData\Roaming\FlowLauncher\Plugins\nexusmods-search-0.2.2\lib\flox\__init__.py", line 107, in __init__
    super().__init__(self.api)
  File "C:\Users\cur5e\AppData\Roaming\FlowLauncher\Plugins\nexusmods-search-0.2.2\lib\flox\launcher.py", line 30, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\cur5e\AppData\Roaming\FlowLauncher\Plugins\nexusmods-search-0.2.2\lib\flox\__init__.py", line 113, in _query
    self.query(query)
  File "C:\Users\cur5e\AppData\Roaming\FlowLauncher\Plugins\nexusmods-search-0.2.2\plugin\nexusmods_search.py", line 39, in query
    subtitle = f"{game['name']} - Downloads: {item['downloads']}"
TypeError: 'NoneType' object is not subscriptable

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 308
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 308
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 323
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Hi @CUR5EDFLVME !

This issue should be fixed with plugin version `v0.2.3`. Please update by typing: 
```
pm update nexusmods-search
```
