### ISSUE TITLE
log error

### ISSUE THREAD

**Issue by wym23** [Flow-Launcher/Flow.Launcher#1125]
[2022-04-13.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8482474/2022-04-13.txt)

Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.22593.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 04/13/2022 22:59:51
Exception:
System.Exception: Update.exe not found, not a Squirrel-installed app?
   at Squirrel.UpdateManager.getUpdateExe()
   at Squirrel.UpdateManager.getApplicationName()
   at Squirrel.UpdateManager..ctor(String urlOrPath, String applicationName, String rootDirectory, IFileDownloader urlDownloader)
   at Flow.Launcher.Core.Updater.GitHubUpdateManager(String repository) in C:\projects\flow-launcher\Flow.Launcher.Core\Updater.cs:line 133
   at Flow.Launcher.Core.Updater.GitHubUpdateManager(String repository) in C:\projects\flow-launcher\Flow.Launcher.Core\Updater.cs:line 137
   at Flow.Launcher.Core.Updater.UpdateAppAsync(IPublicAPI api, Boolean silentUpdate) in C:\projects\flow-launcher\Flow.Launcher.Core\Updater.cs:line 43
   at Flow.Launcher.ViewModel.SettingWindowViewModel.UpdateApp() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\SettingWindowViewModel.cs:line 52
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by taooceros** [comment]
Could you try reinstalling flow. It seems that an essential component is missing.

**Comment by jjw24** [comment]
Let us know how you go @wym23
