### ISSUE TITLE
launcher dictionary plugin error 

### ISSUE THREAD

**Issue by s192516** [Flow-Launcher/Flow.Launcher#1141]
Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues/new
1. upload log file: C:\Users\huali\Documents\FlowLauncher\app-1.9.3\UserData\Logs\1.9.3\2022-04-22.txt
2. copy below exception message

Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 04/22/2022 23:34:40
Exception:
code = CantOpen (14), message = System.Data.SQLite.SQLiteException (0x800007FF): unable to open database file
   at System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
   at System.Data.SQLite.SQLiteConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Dictionary.ECDict.QueryAsync(String word, CancellationToken token) in D:\a\Flow.Launcher.Dictionary\Flow.Launcher.Dictionary\src\ECDict.cs:line 37
   at Dictionary.Main.FirstLevelQueryAsync(Query query, CancellationToken token) in D:\a\Flow.Launcher.Dictionary\Flow.Launcher.Dictionary\src\Dictionary.cs:line 158
   at Dictionary.Main.QueryAsync(Query query, CancellationToken token) in D:\a\Flow.Launcher.Dictionary\Flow.Launcher.Dictionary\src\Dictionary.cs:line 345
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by taooceros** [comment]
@harrynull please take a look.

**Comment by harrynull** [comment]
Please open file explorer, paste `%LocalAppData%\Flow.Dictionary\` into your address bar, and delete the file `ultimate.db`.
Restart flow launcher and it should prompt you to redownload the dictionary file.
If that does not work, or if you prefer, you can also download the dictionary file from [GitHub](https://github.com/skywind3000/ECDICT-ultimate/releases/download/1.0.0/ecdict-ultimate-sqlite.zip) or [Chinese Mirror Site](https://nullptr_t.coding.net/p/ECDICT-sqlite/d/ECDICT-sqlite/git/raw/master/ecdict-ultimate-sqlite.zip), uncompress it, and place the downloaded .db file to where it was.
