### ISSUE TITLE
Flow Launcher Exception

### ISSUE THREAD

**Issue by Orhugo** [Flow-Launcher/Flow.Launcher#1145]
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 04/23/2022 10:59:16
Exception:
System.Net.WebException: The operation has timed out.
   at System.Net.FileWebRequest.GetResponse()
   at MS.Internal.WpfWebRequestHelper.GetResponse(WebRequest request)
   at MS.Internal.WpfWebRequestHelper.GetResponseStream(WebRequest request, ContentType& contentType)
   at System.Windows.ResourceDictionary.set_Source(Uri value)
   at Flow.Launcher.Core.Resource.Theme.CurrentThemeResourceDictionary() in C:\projects\flow-launcher\Flow.Launcher.Core\Resource\Theme.cs:line 137
   at Flow.Launcher.Core.Resource.Theme.GetResourceDictionary() in C:\projects\flow-launcher\Flow.Launcher.Core\Resource\Theme.cs:line 147
   at Flow.Launcher.Core.Resourc
[2022-04-23.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8546558/2022-04-23.txt)
e.Theme.ChangeTheme(String theme) in C:\projects\flow-launcher\Flow.Launcher.Core\Resource\Theme.cs:line 91
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 93
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 50
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by taooceros** [comment]
It looks like this happens when you are trying to switch a theme? Could you share which theme are you switching to?

**Comment by Orhugo** [comment]
![Atom Theme](https://user-images.githubusercontent.com/53238187/164942540-6349b755-ac1b-4143-9ee7-c6464baf38d7.jpg)
I've chosen this theme

**Comment by taooceros** [comment]
Atom? I will give it a test later

**Comment by jjw24** [comment]
I can't seem to replicate the issue. @Orhugo does the error happen on switching to other themes?

**Comment by Orhugo** [comment]
I've changed to other theme and it seems to be going well.

**Comment by jjw24** [comment]
Does it error again when you switch back?
