### ISSUE TITLE
Python download mirror failure

### ISSUE THREAD

**Issue by Marlon5775** [Flow-Launcher/Flow.Launcher#1146]
[2022-04-23.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8546698/2022-04-23.txt)

Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 04/23/2022 12:16:37
Exception:
System.AggregateException: One or more errors occurred. (Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzulässig. (npm.taobao.org:80))
 ---> System.Net.Http.HttpRequestException: Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzulässig. (npm.taobao.org:80)
 ---> System.Net.Sockets.SocketException (10013): Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzulässig.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Droplex.Downloader.Get(String url, String filePath)
   at Droplex.DroplexPackage.Drop(App app, String zipExtractPath)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Flow.Launcher.Core.Plugin.PluginsLoader.PythonPlugins(List`1 source, PluginsSettings settings) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginsLoader.cs:line 160
   at Flow.Launcher.Core.Plugin.PluginsLoader.Plugins(List`1 metadatas, PluginsSettings settings) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginsLoader.cs:line 25
   at Flow.Launcher.Core.Plugin.PluginManager.LoadPlugins(PluginsSettings settings) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 105
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 69
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 50
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by taooceros** [comment]
It looks like an internet exception. Could you check whether you are able to connect to npm.taobao.org?

**Comment by Marlon5775** [comment]
![image](https://user-images.githubusercontent.com/104256126/164938226-0095dcd0-a565-4db2-9d4a-6ccc29ade8e3.png)

Is this the right page?

**Comment by taooceros** [comment]
> (Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzulässig. (npm.taobao.org:80))

This is the error message, but I am not sure why that happens. Do you have any proxy setting?

**Comment by Marlon5775** [comment]
As far as I know my proxy settings are not messed up but I have a parental control called Norton family

**Comment by taooceros** [comment]
I think it tries downloading python but fail. You can manually install one and put the installed path to flow's setting (embedded is supported).

**Comment by taooceros** [comment]
Also it is possible that the original mirror is switching its domain, so the httpclient fail to download because of redirecting. I will update the mirror link in the specific repo.

**Comment by Marlon5775** [comment]
> I think it tries downloading python but fail. You can manually install one and put the installed path to flow's setting (embedded is supported).

Where can i download python?

**Comment by jjw24** [comment]
Hi, you can download it here:
https://www.python.org/ftp/python/3.9.10/python-3.9.10-embed-amd64.zip

Extract the zip file to your UserData folder then when prompted/or from Settings select that folder (should be containing python.exe).

**Comment by Marlon5775** [comment]
Thanks its working now😃

**Comment by jjw24** [comment]
Fixed in pre-release.
