### ISSUE TITLE
Which service for Program plugin ?

### ISSUE THREAD

**Issue by Zaanza** [Flow-Launcher/Flow.Launcher#1153]
Hi
**Describe the bug/issue**
When I add a folder to the Program plugin I get an error.

**To Reproduce**
I have many Windows services disabled, I can't find the correct one, and I'm 100% sure that's the problem, it doesn't seem to be sysmain.

**Your System**
```
Windows build number: 10.0.22000.318
Flow Launcher version: 1.9.3
```
**Flow Launcher Error Log**
System.Runtime.InteropServices.COMException (0x80070422): The service cannot be started, either because it is disabled or because it has no enabled devices associated with it. (0x80070422)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.Management.Deployment.IPackageManagerMethods.FindPackagesForUser(IObjectReference _obj, String userSecurityId)
   at Windows.Management.Deployment.PackageManager.FindPackagesForUser(String userSecurityId)
   at Flow.Launcher.Plugin.Program.Programs.UWP.CurrentUserPackages() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Program\Programs\UWP.cs:line 205
   at Flow.Launcher.Plugin.Program.Programs.UWP.All() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Program\Programs\UWP.cs:line 150
   at Flow.Launcher.Plugin.Program.Main.IndexUwpPrograms() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Program\Main.cs:line 141
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Plugin.Program.Main.IndexPrograms() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Program\Main.cs:line 149
   at Flow.Launcher.Plugin.Program.Views.ProgramSetting.ReIndexing() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Program\Views\ProgramSetting.xaml.cs:line 122
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by taooceros** [comment]
Well it is related to UWP PackageManager. You can ignore the exception if you don't want to index UWP apps. I am not sure which services is responsible for this, sorry.

**Comment by Zaanza** [comment]
Thank you for the answer, I found the service, its AppX Deployment Service (AppXSVC).
