### ISSUE TITLE
search error

### ISSUE THREAD

**Issue by spass-git** [Flow-Launcher/Flow.Launcher#1159]
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.22598.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 04/29/2022 20:30:56
Exception:
System.ComponentModel.Win32Exception (0x800401F5): Application not found
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Flow.Launcher.Plugin.SharedCommands.SearchWeb.OpenInBrowserTab(String url, String browserPath, Boolean inPrivate, String privateArg) in /_/Flow.Launcher.Plugin/SharedCommands/SearchWeb.cs:line 108
   at Flow.Launcher.PublicAPIInstance.OpenUrl(String url, Nullable`1 inPrivate) in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 220
   at Flow.Launcher.Plugin.WebSearch.Main.<>c__DisplayClass9_1.<QueryAsync>b__1(ActionContext c) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.WebSearch\Main.cs:line 77
   at Flow.Launcher.ViewModel.MainViewModel.<InitializeKeyCommands>b__19_9(Object index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 207
   at Flow.Launcher.ViewModel.RelayCommand.Execute(Object parameter) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\RelayCommand.cs:line 25
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by taooceros** [comment]
Which default web browser are you using @spass-git

**Comment by spass-git** [comment]
> What were you doing when this error happened? Were you using any plugins?

No, sometimes flow doesn't start automatically after booting so as usual I was running it as administrator and it showed up error . 
       After trying a couple of times it worked as before.

**Comment by spass-git** [comment]
> Which default web browser are you using @spass-git 

Brave

**Comment by jjw24** [comment]
Not sure about the not starting part and having to run as admin, but the error in the attached log looks like an issue when opening a web search, so might be to do with your brave setup. @spass-git can you show us the configuration please.
