### ISSUE TITLE
File manager by files-community / Files set to default and it doesnt work

### ISSUE THREAD

**Issue by ultra-black** [Flow-Launcher/Flow.Launcher#1160]
**Describe the bug/issue**
Whenever you try and use the file manager 
[Files](https://github.com/files-community/Files)
It says Errorr

**To Reproduce**
1. Go settings
2. Set to it to files (profile )and click done
3. Open a folder it would crash

**Screenshots**

**Your System**
```
Windows build number: Microsoft Windows [Version 10.0.19044.1645]
Flow Launcher version: 1.9.3
```
**Flow Launcher Error Log**
Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues/new
1. upload log file: C:\Users\darea\AppData\Roaming\FlowLauncher\Logs\1.9.3\2022-04-29.txt
2. copy below exception message

Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 04/29/2022 21:26:59
Exception:
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Flow.Launcher.PublicAPIInstance.OpenDirectory(String DirectoryPath, String FileName) in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 209
   at Flow.Launcher.Plugin.Explorer.Search.ResultManager.<>c__DisplayClass8_0.<CreateOpenCurrentFolderResult>b__0(ActionContext c) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\ResultManager.cs:line 117
   at Flow.Launcher.ViewModel.MainViewModel.<InitializeKeyCommands>b__19_9(Object index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 207
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

PS:
I know I missed doing something, I think it is setting the path for it, however I have no idea how since its in the application folder. Which I cant find out how to get the path out of it.

**Comment by ultra-black** [comment]
![chrome_L5CHqp3m4Z](https://user-images.githubusercontent.com/97588864/166006307-d248596d-9e9c-4f1a-936f-5b2652af95f5.png)

**Comment by taooceros** [comment]
It doesn't work for all path?

**Comment by taooceros** [comment]
![image](https://user-images.githubusercontent.com/45326534/166065978-0ff4790f-a636-4dc8-92f3-6951bb7f297c.png)
Could you check whether this is on?

**Comment by ultra-black** [comment]
Im on windows 10, I cant find this.

**Comment by taooceros** [comment]
win10 has the same setting. Try to find it under apps

**Comment by ultra-black** [comment]
![ApplicationFrameHost_2DBC4Xxljm](https://user-images.githubusercontent.com/97588864/166068283-d64bdc9d-785d-44d9-a4de-a138481367ce.png)
Well yeah.

**Comment by taooceros** [comment]
I can't reproduce though. Could you open a cmd and check whether you can open files by typing files?

**Comment by taooceros** [comment]
Open Command Prompt, and type files, and check whether files is opened.
![image](https://user-images.githubusercontent.com/45326534/166070011-d157835c-54b4-4dd8-b4e4-fc32d01cf833.png)

**Comment by ultra-black** [comment]
![cmd_hDYh6ilzA9](https://user-images.githubusercontent.com/97588864/166070270-b893cf35-0c6b-4dfd-b5b0-ec4e779b8197.png)

**Comment by taooceros** [comment]
I guess you can try restarting computer or switch on and off that setting option. It's not flow's issue but probably windows issue.

**Comment by ultra-black** [comment]
Doesnt work

**Comment by taooceros** [comment]
I don't have a lot of ways to help you with that. 
check this link. Probably it helps https://superuser.com/questions/1568956/windows-10-app-aliases-not-working

**Comment by ultra-black** [comment]
Thank you so much, that works.
