### ISSUE TITLE
Dictionary not working 

### ISSUE THREAD

**Issue by 999-nikhil** [Flow-Launcher/Flow.Launcher#1163]
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 04/30/2022 21:48:18
Exception:
code = CantOpen (14), message = System.Data.SQLite.SQLiteException (0x800007FF): unable to open database file
   at System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
   at System.Data.SQLite.SQLiteConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Dictionary.ECDict.QueryAsync(String word, CancellationToken token) in D:\a\Flow.Launcher.Dictionary\Flow.Launcher.Dictionary\src\ECDict.cs:line 37
   at Dictionary.Main.FirstLevelQueryAsync(Query query, CancellationToken token) in D:\a\Flow.Launcher.Dictionary\Flow.Launcher.Dictionary\src\Dictionary.cs:line 158
   at Dictionary.Main.QueryAsync(Query query, CancellationToken token) in D:\a\Flow.Launcher.Dictionary\Flow.Launcher.Dictionary\src\Dictionary.cs:line 355
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2022-04-28.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8597377/2022-04-28.txt)
[2022-04-29.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8597378/2022-04-29.txt)
[2022-04-30.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8597379/2022-04-30.txt)

**Comment by deefrawley** [comment]
Hi,

Have you downloaded the dicstionary file? Details are in the plugin repo:

![image](https://user-images.githubusercontent.com/18594055/166126873-e723b5ce-611c-414a-81a5-eae2dfa63860.png)
