### ISSUE TITLE
Steam Search Crash

### ISSUE THREAD

**Issue by khevmoore** [Flow-Launcher/Flow.Launcher#1164]
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.22610.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 04/30/2022 19:44:35
Exception:
System.IO.InvalidDataException: Steam Search|Traceback (most recent call last):
  File "C:\Users\Kevin\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.3\run.py", line 12, in <module>
    SteamSearch()
  File "C:\Users\Kevin\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.3\lib\flox\__init__.py", line 107, in __init__
    super().__init__(self.api)
  File "C:\Users\Kevin\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.3\lib\flox\launcher.py", line 30, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\Kevin\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.3\lib\flox\__init__.py", line 113, in _query
    self.query(query)
  File "C:\Users\Kevin\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.3\plugin\main.py", line 18, in query
    users = self._steam.loginusers()
  File "C:\Users\Kevin\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.3\plugin\steam.py", line 66, in loginusers
    LoginUser(ID=user, steam_path=self.path, **vdf['users'][user])
TypeError: LoginUser.__init__() missing 1 required positional argument: 'SkipOfflineModeWarning'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 587
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2022-04-30.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8598096/2022-04-30.txt)

**Comment by Garulf** [comment]
Sorry about that, unfortunately when you use an undocumented API you run into issues where stuff is changed from user to user.

This should be fixed in [version 4.0.4](https://github.com/Garulf/Steam-Search/releases/tag/v4.0.4)
