### ISSUE TITLE
Obsidian Plugin running into error as soon as typing begins

### ISSUE THREAD

**Issue by anvimea** [Flow-Launcher/Flow.Launcher#1180]
**Describe the bug/issue**
When trying to use the Obsidian plugin, the search crashes and an error log pops up.

**To Reproduce**
1. Begin to use the plugin by typing "ob "
2. Type anything after, e.g. "ob s"
3. Client crashes, error log (see below) pops up.

**Screenshots**

**Your System**
```
Windows build number: 10.0.19043.1645
Flow Launcher version: 1.9.3
```
**Flow Launcher Error Log**
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19043.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 05/05/2022 09:09:36
Exception:
System.IO.InvalidDataException: Obsidian Notes|Exception ignored in: <function Launcher.__del__ at 0x000002586DBFC040>
Traceback (most recent call last):
  File "C:\Users\nawhd\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.3\lib\flox\launcher.py", line 59, in __del__
    self.__call__()
  File "C:\Users\nawhd\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.3\lib\flox\__init__.py", line 96, in __call__
    return super().__call__()
  File "C:\Users\nawhd\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.3\lib\flox\launcher.py", line 41, in __call__
    results = request_method(*request_parameters)
  File "C:\Users\nawhd\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.3\lib\flox\__init__.py", line 127, in _query
    self.query(query)
  File "C:\Users\nawhd\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.3\plugin\main.py", line 26, in query
    for note in vault.notes():
  File "C:\Users\nawhd\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.3\plugin\obsidian.py", line 62, in notes
    for note in Path(self.path).glob('**/*.md'):
  File "pathlib.py", line 1139, in glob
  File "pathlib.py", line 586, in _select_from
  File "pathlib.py", line 533, in _select_from
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\nawhd\\iCloudDrive\\iCloud~md~obsidian\\PKM\\Misc.'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 308
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 308
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 323
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
It looks like iCloud is listing a file it hasn't downloaded locally?

**Comment by anvimea** [comment]
I doublechecked, it seems like the folder being named "Misc." was causing some errors in the sync. I renamed it to "Misc" and the error has disappeared.

Thanks!

**Comment by Garulf** [comment]
> I doublechecked, it seems like the folder being named "Misc." was causing some errors in the sync. I renamed it to "Misc" and the error has disappeared.
> 
> 
> 
> Thanks!

No problem! Glad you got it working!

I will add a catch for that error when I can so we can at least skip any files causing errors like that.
