### ISSUE TITLE
Error on opening parent folder of directory

### ISSUE THREAD

**Issue by NoFrans** [Flow-Launcher/Flow.Launcher#1181]
**What?** 
- Flow crashed and threw an error.

**When?** 
- This happened after I tried to open the parent directory of a folder.

**More info** 
- I'm using _Everything_ by _voidtools_ for searching. 

[2022-05-05.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8632536/2022-05-05.txt)

```
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 05/05/2022 11:24:48
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Flow.Launcher.ViewModel.MainViewModel.RemoveOldQueryResults(Query query) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 628
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)```

**Comment by 1234Brian** [comment]
👍

**Comment by jjw24** [comment]
Hey @NoFrans how's it going, does this happen consistently? Does it happen on every folder you open parent directory on?

**Comment by jjw24** [comment]
>Although it's a different issue, I also just want to let you know (I don't know if anyone has reported it) changing settings in Flow usually freezes the program and I have to kill it via task manager and reopen it. If it happens again, I'll post a separate bug post. I just wanted to put it out there however.

Please not already and is happening please post in seperate issue so we can track. Cheers.
