### ISSUE TITLE
Youtube plugin not working

### ISSUE THREAD

**Issue by Ahnaf-Hasan-Prinon** [Flow-Launcher/Flow.Launcher#1183]
Log file: [2022-05-06.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8641330/2022-05-06.txt)

Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 05/06/2022 20:16:44
Exception:
System.IO.InvalidDataException: FlowYouTube|Traceback (most recent call last):
  File "K:\ALL SOFTWARE\1Productive\FlowLauncher\app-1.9.3\UserData\Plugins\FlowYouTube-0.4.0\run.py", line 9, in <module>
    from plugin.main import FlowYouTube
  File "K:\ALL SOFTWARE\1Productive\FlowLauncher\app-1.9.3\UserData\Plugins\FlowYouTube-0.4.0\plugin\main.py", line 3, in <module>
    from flox import Flox, utils, ICON_BROWSER
  File "K:\ALL SOFTWARE\1Productive\FlowLauncher\app-1.9.3\UserData\Plugins\FlowYouTube-0.4.0\lib\flox\__init__.py", line 56, in <module>
    APP_ICONS = os.path.join(APP_DIR, "Images")
  File "ntpath.py", line 78, in join
TypeError: expected str, bytes or os.PathLike object, not tuple

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 587
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Okay! This is a known problem I introduced into the latest library my Plugins use. I'll try and get a fix soon™️

**Comment by jjw24** [comment]
Hey @Garulf has this been addressed?

**Comment by Garulf** [comment]
> Hey @Garulf has this been addressed?

Yes this should be resolved in the latest version.
