### ISSUE TITLE
Twitch plugin doesn't work

### ISSUE THREAD

**Issue by matheusgcastro** [Flow-Launcher/Flow.Launcher#1196]
Log: [2022-05-09.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8651661/2022-05-09.txt)

Exception message:

Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 05/09/2022 09:34:18
Exception:
System.IO.InvalidDataException: Twitchy|Exception ignored in: <function Launcher.__del__ at 0x0000022AA8ADA280>
Traceback (most recent call last):
  File "C:\Users\mathg\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.9.3\UserData\Plugins\Twitchy-2.1.0\lib\flox\launcher.py", line 59, in __del__
    self.__call__()
  File "C:\Users\mathg\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.9.3\UserData\Plugins\Twitchy-2.1.0\lib\flox\__init__.py", line 96, in __call__
    return super().__call__()
  File "C:\Users\mathg\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.9.3\UserData\Plugins\Twitchy-2.1.0\lib\flox\launcher.py", line 41, in __call__
    results = request_method(*request_parameters)
  File "C:\Users\mathg\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.9.3\UserData\Plugins\Twitchy-2.1.0\lib\flox\__init__.py", line 127, in _query
    self.query(query)
  File "C:\Users\mathg\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.9.3\UserData\Plugins\Twitchy-2.1.0\plugin\twitchy.py", line 44, in query
    featured_streams = self.client.streams.get_featured(5)
  File "C:\Users\mathg\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.9.3\UserData\Plugins\Twitchy-2.1.0\lib\twitch\api\streams.py", line 60, in get_featured
    response = self._request_get('streams/featured', params=params)
  File "C:\Users\mathg\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.9.3\UserData\Plugins\Twitchy-2.1.0\lib\twitch\api\base.py", line 53, in _request_get
    response.raise_for_status()
  File "C:\Users\mathg\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.9.3\UserData\Plugins\Twitchy-2.1.0\lib\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.twitch.tv/kraken/streams/featured?limit=5&offset=0

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Twitch closed down their older API which this plugin used. An update to the plugin is in the works but will need to be rewritten to use the new API Twitch requires.

**Comment by Garulf** [comment]
This is fixed in Twitchy version 4.0.0!

Due to changes in the API you will need to provide an OAuth token in order to use the newer version. Sadly there is no work around for this.
