### ISSUE TITLE
Flow Launcher got an error !! 

### ISSUE THREAD

**Issue by ravi9css** [Flow-Launcher/Flow.Launcher#1199]
Its not opening after command 
Even when i tried it give me this error!!
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 05/11/2022 23:08:25
Exception:
System.Security.SecurityException: Requested registry access is not allowed.
   at Microsoft.Win32.RegistryKey.InternalOpenSubKeyCore(String name, Boolean writable)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at Flow.Launcher.SettingWindow.StartupSet() in C:\projects\flow-launcher\Flow.Launcher\SettingWindow.xaml.cs:line 81
   at Flow.Launcher.App.AutoStartup() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 112
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 99
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 50
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
This is happening because the set startup option is enabled, and flow does not have the rights to edit your registry to set it. Any chance you can turn this option off in Flow's settings or run it as administrator?
