### ISSUE TITLE
steam not working after last windows 10 update

### ISSUE THREAD

**Issue by shuantsu** [Flow-Launcher/Flow.Launcher#1202]
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 05/14/2022 16:44:28
Exception:
System.IO.InvalidDataException: Steam Search|Traceback (most recent call last):
  File "C:\Users\shuan\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.4\run.py", line 12, in <module>
    SteamSearch()
  File "C:\Users\shuan\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.4\lib\flox\__init__.py", line 107, in __init__
    super().__init__(self.api)
  File "C:\Users\shuan\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.4\lib\flox\launcher.py", line 30, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\shuan\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.4\lib\flox\__init__.py", line 113, in _query
    self.query(query)
  File "C:\Users\shuan\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.4\plugin\main.py", line 18, in query
    users = self._steam.loginusers()
  File "C:\Users\shuan\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.4\plugin\steam.py", line 66, in loginusers
    LoginUser(ID=user, steam_path=self.path, **vdf['users'][user])
  File "<string>", line 13, in __init__
  File "C:\Users\shuan\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.4\plugin\loginusers.py", line 34, in __post_init__
    self.SkipOfflineModeWarning = bool(strtobool(self.SkipOfflineModeWarning))
  File "distutils\util.py", line 313, in strtobool
AttributeError: 'NoneType' object has no attribute 'lower'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 308
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 308
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 323
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Sorry about that. Valve can be strange with their naming conventions. 

It's fixed in the latest plugin version. Please update by typing `pm update`

Related: https://github.com/Flow-Launcher/Flow.Launcher/issues/1164

**Comment by shuantsu** [comment]
it fixed!
Thanks a lot
