### ISSUE TITLE
[SOLVED] garuf/steamSearch crash from >"AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by shobu13** [Flow-Launcher/Flow.Launcher#1208]
step to reproduce:
- launch steam
- do a search using steam search
- crash

Solved by:
uninstall & reinstall the plugin

maybe this will be usefull so even if i solve it, i post it.

Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 05/15/2022 14:40:33
Exception:
System.IO.InvalidDataException: Steam Search|Traceback (most recent call last):
  File "G:\_Random\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.4\run.py", line 12, in <module>
    SteamSearch()
  File "G:\_Random\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.4\lib\flox\__init__.py", line 107, in __init__
    super().__init__(self.api)
  File "G:\_Random\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.4\lib\flox\launcher.py", line 30, in __init__
    results = request_method(*request_parameters)
  File "G:\_Random\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.4\lib\flox\__init__.py", line 113, in _query
    self.query(query)
  File "G:\_Random\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.4\plugin\main.py", line 18, in query
    users = self._steam.loginusers()
  File "G:\_Random\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.4\plugin\steam.py", line 66, in loginusers
    LoginUser(ID=user, steam_path=self.path, **vdf['users'][user])
  File "<string>", line 13, in __init__
  File "G:\_Random\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.4\plugin\loginusers.py", line 34, in __post_init__
    self.SkipOfflineModeWarning = bool(strtobool(self.SkipOfflineModeWarning))
  File "distutils\util.py", line 313, in strtobool
AttributeError: 'NoneType' object has no attribute 'lower'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-laun
[2022-05-15.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8694952/2022-05-15.txt)
cher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 613
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 587
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Very odd, Flow Launcher should restart after installing a plugin. 

The log says it's using plugin version 4.04 yet the log shows code I removed from that version.

**Comment by jjw24** [comment]
>Solved by:
uninstall & reinstall the plugin

@shobu13 have you gotten this error since you reinstalled the plugin?

**Comment by shobu13** [comment]
No, it work fine until now On Jun 16, 2022 14:48, Jeremy Wu ***@***.***> wrote:

Solved by:
uninstall & reinstall the plugin

@shobu13 have you gotten this error since you reinstalled the plugin?

**Comment by slmpWesley** [comment]
I have the same error, but with the notion plugin, I already tried reinstalling notion, the plugin and the flow launcher, it didn't work.
Any other solution?
