### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Martinsitoo** [Flow-Launcher/Flow.Launcher#1209]
[2022-05-15.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8695080/2022-05-15.txt)

Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\marti\Documents\FlowLauncher\app-1.9.3\UserData\PythonEmbeddable\pythonw.exe
Date: 05/15/2022 08:39:29
Exception:
System.IO.InvalidDataException: Twitchy|Traceback (most recent call last):
  File "C:\Users\marti\Documents\FlowLauncher\app-1.9.3\UserData\Plugins\Twitchy-4.0.0\main.py", line 10, in <module>
    from plugin.twitchy import Twitchy
  File "C:\Users\marti\Documents\FlowLauncher\app-1.9.3\UserData\Plugins\Twitchy-4.0.0\plugin\twitchy.py", line 1, in <module>
    from flox import Flox, utils, ICON_APP_ERROR
  File "C:\Users\marti\Documents\FlowLauncher\app-1.9.3\UserData\Plugins\Twitchy-4.0.0\lib\flox\__init__.py", line 56, in <module>
    APP_ICONS = os.path.join(APP_DIR, "Images")
  File "ntpath.py", line 78, in join
TypeError: expected str, bytes or os.PathLike object, not tuple

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Hello @Martinsitoo What version of python are you using?

**Comment by Garulf** [comment]
I'm not sure what is causing this issue for some users as I cant reproduce it. 

I assume its something I did with the library it uses and will attempt to update that.

**Comment by Garulf** [comment]
I updated Twitchy to version 4.0.1 please update by typing `pm update twitchy` and see if this fixes your issue.

**Comment by Martinsitoo** [comment]
I typed it but it appears that all plugins are updated so I don't know if i should reboot the computer or also I was looking the last update on your account but I don't really know what to do.

**Comment by Martinsitoo** [comment]
I updated twitchy but still I get an error

**Comment by Garulf** [comment]
> I updated twitchy but still I get an error 

What's the error say after updating?

**Comment by Martinsitoo** [comment]
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 05/15/2022 17:06:21
Exception:
System.IO.InvalidDataException: Twitchy|Traceback (most recent call last):
  File "C:\Users\marti\Documents\FlowLauncher\app-1.9.3\UserData\Plugins\Twitchy-4.0.1\main.py", line 10, in <module>
    from plugin.twitchy import Twitchy
  File "C:\Users\marti\Documents\FlowLauncher\app-1.9.3\UserData\Plugins\Twitchy-4.0.1\plugin\twitchy.py", line 1, in <module>
    from flox import Flox, utils, ICON_APP_ERROR
  File "C:\Users\marti\Documents\FlowLauncher\app-1.9.3\UserData\Plugins\Twitchy-4.0.1\lib\flox\__init__.py", line 56, in <module>
    app_versions = LOCAL_APP_DIR.iterdir()
AttributeError: 'tuple' object has no attribute 'iterdir'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Still not sure why your system is returning a tuple....

Could you please type the following command into `powershell.exe`:

```
python -c 'import os;print(os.getenv(\"LOCALAPPDATA\"))'
```

Should print out whatever your system is reporting as your "local" appdata directory.

**Comment by Garulf** [comment]
This issue should be resolved with the latest plugin version. There was an issue with running this plugin in portable mode.
