### ISSUE TITLE
RemoveOldQueryResults - System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by raindropsfromsky** [Flow-Launcher/Flow.Launcher#1210]
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 05/16/2022 15:28:58
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Flow.Launcher.ViewModel.MainViewModel.RemoveOldQueryResults(Query query) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 668
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 660
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2022-05-16.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8699076/2022-05-16.txt)

**Comment by raindropsfromsky** [comment]
I am sorry I am not using a standard template for bug-reporting, but when FL crashed, its crash report itself provided this link, and provided the text for reporting.

If you do not like this way of reporting, please change the structure of your crash report.
Thanks for your understanding!

**Comment by taooceros** [comment]
Yeah I believe it is a hard to reproduce bug. I will add some check there to prevent it happen again.
