### ISSUE TITLE
Playnite Extension Error

### ISSUE THREAD

**Issue by crenshawda** [Flow-Launcher/Flow.Launcher#1217]
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 05/21/2022 11:25:37
Exception:
System.IO.InvalidDataException: Playnite|Exception ignored in: <function Launcher.__del__ at 0x0000021FDC9660E0>
Traceback (most recent call last):
  File "C:\Users\crens\scoop\apps\Flow-Launcher\current\app-1.9.3\UserData\Plugins\Playnite-1.5.3\lib\flox\launcher.py", line 58, in __del__
    self.__call__()
  File "C:\Users\crens\scoop\apps\Flow-Launcher\current\app-1.9.3\UserData\Plugins\Playnite-1.5.3\lib\flox\__init__.py", line 92, in __call__
    return super().__call__()
  File "C:\Users\crens\scoop\apps\Flow-Launcher\current\app-1.9.3\UserData\Plugins\Playnite-1.5.3\lib\flox\launcher.py", line 46, in __call__
    results = self.exception(e) or self._results
  File "C:\Users\crens\scoop\apps\Flow-Launcher\current\app-1.9.3\UserData\Plugins\Playnite-1.5.3\lib\flox\__init__.py", line 113, in exception
    self.issue_item(exception)
  File "C:\Users\crens\scoop\apps\Flow-Launcher\current\app-1.9.3\UserData\Plugins\Playnite-1.5.3\lib\flox\__init__.py", line 133, in issue_item
    trace = ''.join(traceback.format_exception(etype=type(e), value=e, tb=e.__traceback__)).replace('\n', '%0A')
TypeError: format_exception() got an unexpected keyword argument 'etype'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 613
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 587
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2022-05-21.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8747866/2022-05-21.txt)

**Comment by Garulf** [comment]
Ah! This is a Python 10 issue! They depreciated the class I was using to log exception messages. 

Please use Python 8-9 until the library is updated.

**Comment by Garulf** [comment]
Fixed in [version 1.5.4](https://github.com/Garulf/Playnite-Plugin/releases/tag/v1.5.4)
