### ISSUE TITLE
I love the way to report errors dude

### ISSUE THREAD

**Issue by Estebanduffourg** [Flow-Launcher/Flow.Launcher#1221]
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19043.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 05/24/2022 21:16:50
Exception:
System.IO.InvalidDataException: FlowYouTube|Traceback (most recent call last):
  File "D:\Flow-Launcher-Portable\FlowLauncher\app-1.9.3\UserData\Plugins\FlowYouTube-0.4.0\run.py", line 9, in <module>
    from plugin.main import FlowYouTube
  File "D:\Flow-Launcher-Portable\FlowLauncher\app-1.9.3\UserData\Plugins\FlowYouTube-0.4.0\plugin\main.py", line 3, in <module>
    from flox import Flox, utils, ICON_BROWSER
  File "D:\Flow-Launcher-Portable\FlowLauncher\app-1.9.3\UserData\Plugins\FlowYouTube-0.4.0\lib\flox\__init__.py", line 56, in <module>
    APP_ICONS = os.path.join(APP_DIR, "Images")
  File "ntpath.py", line 78, in join
TypeError: expected str, bytes or os.PathLike object, not tuple

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 613
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 587
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
This is happening from the YouTube plugin, we have a wip enhancement to report plugin related errors to the plugin developer. In the meantime will transfer this issue to the YouTube plugin repo.

**Comment by jjw24** [comment]
@Garulf has this error already been addressed?

**Comment by Garulf** [comment]
> @Garulf has this error already been addressed?

Yes this bug should be fixed in the latest version.
