### ISSUE TITLE
Error when Opening Steam Search

### ISSUE THREAD

**Issue by Derzz** [Flow-Launcher/Flow.Launcher#1224]
[2022-05-26.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8780703/2022-05-26.txt)

I got the following issue:

Flow Launcher version: 1.9.2
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 05/26/2022 12:56:39
Exception:
System.IO.InvalidDataException: Steam Search|Traceback (most recent call last):
  File "C:\Users\micha\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.5\lib\flox\launcher.py", line 30, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\micha\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.5\lib\flox\__init__.py", line 113, in _query
    self.query(query)
  File "C:\Users\micha\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.5\plugin\main.py", line 12, in query
    self.logger
  File "C:\Users\micha\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.5\lib\flox\__init__.py", line 283, in logger
    self.logfile,
  File "C:\Users\micha\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.5\lib\flox\__init__.py", line 272, in logfile
    file = f"{self.manifest['Name']}.log"
  File "C:\Users\micha\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.5\lib\flox\__init__.py", line 210, in manifest
    with open(os.path.join(self.plugindir, PLUGIN_MANIFEST), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\WINDOWS\\system32\\plugin.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\micha\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.5\run.py", line 12, in <module>
    SteamSearch()
  File "C:\Users\micha\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.5\lib\flox\__init__.py", line 107, in __init__
    super().__init__(self.api)
  File "C:\Users\micha\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.5\lib\flox\launcher.py", line 33, in __init__
    self.logger.exception(f'Exception while calling method: {request_method_name}')
  File "C:\Users\micha\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.5\lib\flox\__init__.py", line 283, in logger
    self.logfile,
  File "C:\Users\micha\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.5\lib\flox\__init__.py", line 272, in logfile
    file = f"{self.manifest['Name']}.log"
  File "C:\Users\micha\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.0.5\lib\flox\__init__.py", line 210, in manifest
    with open(os.path.join(self.plugindir, PLUGIN_MANIFEST), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\WINDOWS\\system32\\plugin.json'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 613
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 587
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Any help would be appreciated!

**Comment by Garulf** [comment]
I have no idea why it would even begin looking in your `c:\Windows` directory for the plugins manifest file.... All I can suggest is updating you Flow Launcher to 1.9.3 and seeing if the update + restart of Flow fixes your issue.

**Comment by Derzz** [comment]
Flow is updated and I deleted and reinstalled the plugin, but it comes up with the same error that it failed to load and would be disabled.

**Comment by Garulf** [comment]
> Flow is updated and I deleted and reinstalled the plugin, but it comes up with the same error that it failed to load and would be disabled.

Very strange... so now the plugin isn't loaded at all now? I am wondering if the plugin installation got messed up somehow. Please close Flow Launcher and navigate to: 

`C:\Users\micha\AppData\Roaming\FlowLauncher\Plugins`

Once there please delete the `Steam-Search-4.0.5` folder. Re-launch Flow Launcher and install the Steam plugin once more.

**Comment by Garulf** [comment]
Glad to hear your issue was resolved!
