### ISSUE TITLE
flowyoutube, steam search, and playnite can't use:  _init_ error

### ISSUE THREAD

**Issue by csc-chicken** [Flow-Launcher/Flow.Launcher#1236]
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 06/13/2022 11:41:42
Exception:
System.IO.InvalidDataException: Steam Search|Traceback (most recent call last):
  File "C:\Users\happy\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.1.0\run.py", line 9, in <module>
    from plugin.main import SteamSearch
  File "C:\Users\happy\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.1.0\plugin\main.py", line 6, in <module>
    from flox import Flox, ICON_SETTINGS
  File "C:\Users\happy\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.1.0\lib\flox\__init__.py", line 47, in <module>
    elif APPDATA.joinpath(FLOW_LAUNCHER_DIR_NAME).exits():
AttributeError: 'WindowsPath' object has no attribute 'exits'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 587
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Looks like a typo was introduced into the Flox by myself. I'll have a fix pushed out tonight.

**Comment by Garulf** [comment]
This issue should be fixed in [Steam Search v4.1.1](https://github.com/Garulf/Steam-Search) & [FlowYouTube v0.5.1](https://github.com/Garulf/FlowYouTube)
