### ISSUE TITLE
Plexy error- missing chardet module

### ISSUE THREAD

**Issue by KoreanPizzaGuy** [Flow-Launcher/Flow.Launcher#1249]
[2022-06-26.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/8987311/2022-06-26.txt)

Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 06/26/2022 21:03:29
Exception:
System.IO.InvalidDataException: Plexy|Traceback (most recent call last):
  File "C:\Users\janik\AppData\Roaming\FlowLauncher\Plugins\Plexy-1.1.0\lib\requests\compat.py", line 12, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\janik\AppData\Roaming\FlowLauncher\Plugins\Plexy-1.1.0\main.py", line 9, in <module>
    from plugin.plexy import Plexy
  File "C:\Users\janik\AppData\Roaming\FlowLauncher\Plugins\Plexy-1.1.0\plugin\plexy.py", line 9, in <module>
    from plexapi.server import PlexServer
  File "C:\Users\janik\AppData\Roaming\FlowLauncher\Plugins\Plexy-1.1.0\lib\plexapi\__init__.py", line 9, in <module>
    from plexapi.utils import SecretsFilter
  File "C:\Users\janik\AppData\Roaming\FlowLauncher\Plugins\Plexy-1.1.0\lib\plexapi\utils.py", line 15, in <module>
    import requests
  File "C:\Users\janik\AppData\Roaming\FlowLauncher\Plugins\Plexy-1.1.0\lib\requests\__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "C:\Users\janik\AppData\Roaming\FlowLauncher\Plugins\Plexy-1.1.0\lib\requests\exceptions.py", line 11, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "C:\Users\janik\AppData\Roaming\FlowLauncher\Plugins\Plexy-1.1.0\lib\requests\compat.py", line 14, in <module>
    import charset_normalizer as chardet
  File "C:\Users\janik\AppData\Roaming\FlowLauncher\Plugins\Plexy-1.1.0\lib\charset_normalizer\__init__.py", line 24, in <module>
    from .api import from_bytes, from_fp, from_path, normalize
  File "C:\Users\janik\AppData\Roaming\FlowLauncher\Plugins\Plexy-1.1.0\lib\charset_normalizer\api.py", line 10, in <module>
    from .cd import (
  File "C:\Users\janik\AppData\Roaming\FlowLauncher\Plugins\Plexy-1.1.0\lib\charset_normalizer\cd.py", line 7, in <module>
    from .assets import FREQUENCIES
ModuleNotFoundError: No module named 'charset_normalizer.assets'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
The Requests library can be very fickle when packaged. It _should_ work in most environments but it's impossible to account for all of them. If you know your way around python's pip you can navigate to the plugins root directory and type: `pip install --target ./lib -r requests`

**Comment by Garulf** [comment]
Please try this test version that should work:

https://github.com/Garulf/Plexy/suites/7189263201/artifacts/287088326

You'll have to manually install this by placing it in your plugins directory and restarting Flow Launcher.

**Comment by Garulf** [comment]
After testing I updated the plugin to fix this issue. Please feel free to reopen if needed.
