### ISSUE TITLE
Wallpaper Engine Plugin Error

### ISSUE THREAD

**Issue by Fielles** [Flow-Launcher/Flow.Launcher#1252]
Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues/new
1. upload log file: C:\Users\Eren-PC\AppData\Roaming\FlowLauncher\Logs\1.9.3\2022-06-27.txt
2. copy below exception message

Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 06/27/2022 22:47:36
Exception:
System.IO.InvalidDataException: Wallpaper Engine Profile Selector|Exception ignored in: <function Launcher.__del__ at 0x000001EB7D8C24C0>
Traceback (most recent call last):
  File "C:\Users\Eren-PC\AppData\Roaming\FlowLauncher\Plugins\Wallpaper Engine Profile Selector-0.0.2\lib\flox\launcher.py", line 59, in __del__
    self.__call__()
  File "C:\Users\Eren-PC\AppData\Roaming\FlowLauncher\Plugins\Wallpaper Engine Profile Selector-0.0.2\lib\flox\__init__.py", line 96, in __call__
    return super().__call__()
  File "C:\Users\Eren-PC\AppData\Roaming\FlowLauncher\Plugins\Wallpaper Engine Profile Selector-0.0.2\lib\flox\launcher.py", line 41, in __call__
    results = request_method(*request_parameters)
  File "C:\Users\Eren-PC\AppData\Roaming\FlowLauncher\Plugins\Wallpaper Engine Profile Selector-0.0.2\lib\flox\__init__.py", line 127, in _query
    self.query(query)
  File "C:\Users\Eren-PC\AppData\Roaming\FlowLauncher\Plugins\Wallpaper Engine Profile Selector-0.0.2\plugin\main.py", line 16, in query
    profiles = we.get_profiles(self.config_path, self.exe)
  File "C:\Users\Eren-PC\AppData\Roaming\FlowLauncher\Plugins\Wallpaper Engine Profile Selector-0.0.2\plugin\wallpaper_engine.py", line 21, in get_profiles
    config = get_config(wallpaper_engine_path)
  File "C:\Users\Eren-PC\AppData\Roaming\FlowLauncher\Plugins\Wallpaper Engine Profile Selector-0.0.2\plugin\wallpaper_engine.py", line 17, in get_config
    with open(full_path, 'r', encoding='utf-8') as f:
OSError: [Errno 22] Invalid argument: '"E:\\Steam\\steamapps\\common\\wallpaper_engine\\wallpaper32.exe"\\config.json'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
Let me know if you need help with Scoop.

**Comment by Garulf** [comment]
Fixed in latest version (0.1.0 at this time) with PR  https://github.com/Garulf/Wallpaper-Engine-Profile-Selector/pull/1
