### ISSUE TITLE
(Opening Directories) Flow Launcher got an error

### ISSUE THREAD

**Issue by rbarbosa34** [Flow-Launcher/Flow.Launcher#1259]
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 07/05/2022 10:50:55
Exception:
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Flow.Launcher.PublicAPIInstance.OpenDirectory(String DirectoryPath, String FileName) in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 209
   at Flow.Launcher.Plugin.Explorer.Search.ResultManager.<>c__DisplayClass8_0.<CreateOpenCurrentFolderResult>b__0(ActionContext c) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\ResultManager.cs:line 117
   at Flow.Launcher.ViewModel.MainViewModel.<InitializeKeyCommands>b__19_9(Object index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 207
   at Flow.Launcher.ViewModel.RelayCommand.Execute(Object parameter) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\RelayCommand.cs:line 25
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler
[2022-07-05.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9045310/2022-07-05.txt)
)

**Comment by taooceros** [comment]
![image](https://user-images.githubusercontent.com/45326534/177633806-939cc2e9-282e-4cf1-b428-c1da8114527f.png)
Could you check this setting?
