### ISSUE TITLE
Spotify plugin crashed

### ISSUE THREAD

**Issue by Evnoxay** [Flow-Launcher/Flow.Launcher#1263]
Hello,

When I write "Spo", the software crashes completely, I don't know why?

[2022-07-06.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9057671/2022-07-06.txt)

**Comment by taooceros** [comment]
```log
System.Net.Http.HttpRequestException: Received an invalid status line: 'SSH-2.0-OpenSSH_8.9p1 Ubuntu-3'.
   Source: System.Net.Http
   TargetAssembly: System.Net.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
   TargetModule: System.Net.Http.dll
   TargetSite: Void ParseStatusLine(System.Span`1[System.Byte], System.Net.Http.HttpResponseMessage)
   at System.Net.Http.HttpConnection.ParseStatusLine(Span`1 line, HttpResponseMessage response)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnel(Boolean async, HttpRequestHeaders headers, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at SpotifyAPI.Web.Http.NetHttpClient.DoRequest(IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.DoRequest(IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.SendAPIRequest[T](Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers)
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPluginClient.CheckTokenValidityAsync() in C:\Repos\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPluginClient.cs:line 110
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPlugin.QueryAsync(Query query, CancellationToken token) in C:\Repos\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPlugin.cs:line 168
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

I think the crash is because of spotify premium plugin. Could you check your connection?

**Comment by taooceros** [comment]
I am not sure about what this error means. Probably it's because some openssh issue? No idea how to fix it though.....Maybe we can let the author take a check whether the spotify api needs to be updated.

**Comment by Evnoxay** [comment]
yes

**Comment by Evnoxay** [comment]
News ?

**Comment by taooceros** [comment]
> News ?

I have no idea about this exception, and I cannot reproduce similar issue. Are you able to use the spotify plugin even though the error is thrown?

**Comment by fow5040** [comment]
> Hello,
> 
> When I write "Spo", the software crashes completely, I don't know why?
> 
> [2022-07-06.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9057671/2022-07-06.txt)

@Evnoxay I likewise have no clue - does this consistently happen on your machine? This error is bubbling up from very low in the Spotify API library we are using, at the point where the Flow plugin has no control over what is returned. Do you perhaps have some sort of HTTP/SSH proxy in place? This SSH version message is incredibly odd and has no place in a standard HTTP response.

**Comment by jjw24** [comment]
@Evnoxay what windows version are you using?
