### ISSUE TITLE
Flow Crash; Python Plugins

### ISSUE THREAD

**Issue by dan1mmm** [Flow-Launcher/Flow.Launcher#1264]
[2022-07-07.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9061538/2022-07-07.txt)

```
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 07/07/2022 15:50:16
Exception:
System.IO.InvalidDataException: Notion Search|Traceback (most recent call last):
  File "C:\Users\丹一梅\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\main.py", line 11, in <module>
    from plugin import NotionSearch
  File "C:\Users\丹一梅\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\plugin\__init__.py", line 8, in <module>
    from plugin.notion_search import NotionSearch
  File "C:\Users\丹一梅\AppData\Roaming\FlowLauncher\Plugins\Notion Search-0.1.5\plugin\notion_search.py", line 42
    if token := user_settings.get("notion_token"):
              ^
SyntaxError: invalid syntax

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
Happened everytime I tried run a python based plugin. I had my python installed before for other program, is this the main issue that caused this?

**Comment by Garulf** [comment]
Looks like this plugin uses features only available to Python 3.10. Which version of Python are you using?
