### ISSUE TITLE
Problems when using the * 

### ISSUE THREAD

**Issue by slipsby** [Flow-Launcher/Flow.Launcher#1266]
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 07/08/2022 00:41:18
Exception:
System.TypeInitializationException: The type initializer for 'Flow.Plugin.WindowWalker.Main' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at void Flow.Plugin.WindowWalker.Components.VirtualDesktopHelper.UpdateDesktopList() in D:/a/Flow.Plugin.WindowWalker/Flow.Plugin.WindowWalker/Components/VirtualDesktopHelper.cs:line 129
   at new Flow.Plugin.WindowWalker.Components.VirtualDesktopHelper(bool desktopListUpdate) in D:/a/Flow.Plugin.WindowWalker/Flow.Plugin.WindowWalker/Components/VirtualDesktopHelper.cs:line 73
   at static Flow.Plugin.WindowWalker.Main() in D:/a/Flow.Plugin.WindowWalker/Flow.Plugin.WindowWalker/Main.cs:line 35
   --- End of inner exception stack trace ---
   at Flow.Plugin.WindowWalker.Main.Query(Query query) in D:\a\Flow.Plugin.WindowWalker\Flow.Plugin.WindowWalker\Main.cs:line 44
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by slipsby** [comment]
Issue close No elp
