### ISSUE TITLE
failed to launch- registry access error

### ISSUE THREAD

**Issue by DaveZag** [Flow-Launcher/Flow.Launcher#1269]
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 07/09/2022 07:23:56
Exception:
System.Security.SecurityException: Requested registry access is not allowed.
   at Microsoft.Win32.RegistryKey.InternalOpenSubKeyCore(String name, Boolean writable)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at Flow.Launcher.SettingWindow.StartupSet() in C:\projects\flow-launcher\Flow.Launcher\SettingWindow.xaml.cs:line 81
   at Flow.Launcher.App.AutoStartup() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 112
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 99
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 50
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
Hey looks like the user account you are running flow with does not have registry access. I recommend run with an admin user account or one with access, then go flow's settings and switch off run at startup option, this is the option that requires registry access at startup.
