### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NinjaHyphen** [Flow-Launcher/Flow.Launcher#1274]
[2022-07-16.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9125425/2022-07-16.txt)
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: D:\Dhruv\2019.4.13f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten_Win\python\2.7.5.3_64bit\pythonw.exe
Date: 07/16/2022 14:03:33
Exception:
System.IO.InvalidDataException: General Converter|Traceback (most recent call last):
  File "C:\Users\dhruv\AppData\Roaming\FlowLauncher\Plugins\General Converter-1.1.2\main.py", line 10, in <module>
    from plugin import Main
  File "C:\Users\dhruv\AppData\Roaming\FlowLauncher\Plugins\General Converter-1.1.2\plugin\__init__.py", line 9, in <module>
    from plugin.settings import (
  File "C:\Users\dhruv\AppData\Roaming\FlowLauncher\Plugins\General Converter-1.1.2\plugin\settings.py", line 40
    PLUGIN_URL = f"https://github.com/{GITHUB_USERNAME}/{__package_name__}"
                                                                          ^
SyntaxError: invalid syntax

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
Hi there, it appears you are using python 2.7, please use 3.8.x, or recommend you let flow download the python package for you.

**Comment by taooceros** [comment]
Sorry for the late reply. You need a Python 3 to run flow's Python plugin.
