### ISSUE TITLE
Error with Steam Search plugin

### ISSUE THREAD

**Issue by fuze9455** [Flow-Launcher/Flow.Launcher#1301]
[2022-08-02.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9240954/2022-08-02.txt)

Flow Launcher version: 1.9.4
OS Version: Microsoft Windows NT 10.0.19042.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 08/02/2022 13:43:48
Exception:
System.IO.InvalidDataException: Steam Search|Traceback (most recent call last):
  File "D:\wbunk0\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.1.1\run.py", line 9, in <module>
    from plugin.main import SteamSearch
  File "D:\wbunk0\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.1.1\plugin\main.py", line 4, in <module>
    from steam import Steam, SteamLibraryNotFound, SteamExecutableNotFound
  File "D:\wbunk0\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.1.1\plugin\steam.py", line 8, in <module>
    from loginusers import LoginUsers, LoginUser
  File "D:\wbunk0\AppData\Roaming\FlowLauncher\Plugins\Steam Search-4.1.1\plugin\loginusers.py", line 1, in <module>
    from dataclasses import dataclass, Field
ModuleNotFoundError: No module named 'dataclasses'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 288
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 302
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 322
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
Hi there, did you let flow install python or, you selected from an existing location and if so what version of python are you using?

**Comment by Garulf** [comment]
Looks like an older version of Python. The Steam plugin requires Python 3.8 or higher to be used.

**Comment by jjw24** [comment]
@fuze9455 please switch to using python 3.8 or allow flow to download it for you. Please reopen if still an issue.

**Comment by fuze9455** [comment]
> @fuze9455 please switch to using python 3.8 or allow flow to download it for you. Please reopen if still an issue.

Yup, was the python version. Upgraded and all was good
