### ISSUE TITLE
FlowYouTube Exception

### ISSUE THREAD

**Issue by dragonmkww** [Flow-Launcher/Flow.Launcher#1303]
[2022-08-04.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9262879/2022-08-04.txt)

Flow Launcher version: 1.9.4
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 08/04/2022 15:55:38
Exception:
System.IO.InvalidDataException: FlowYouTube|Traceback (most recent call last):
  File "C:\Users\ctayl\scoop\apps\Flow-Launcher\current\app-1.9.4\UserData\Plugins\FlowYouTube-0.5.1\run.py", line 9, in <module>
    from plugin.main import FlowYouTube
  File "C:\Users\ctayl\scoop\apps\Flow-Launcher\current\app-1.9.4\UserData\Plugins\FlowYouTube-0.5.1\plugin\main.py", line 3, in <module>
    from flox import Flox, utils, ICON_BROWSER
  File "C:\Users\ctayl\scoop\apps\Flow-Launcher\current\app-1.9.4\UserData\Plugins\FlowYouTube-0.5.1\lib\flox\__init__.py", line 40, in <module>
    if str(APPDATA.joinpath(launcher_dir)) in str(CURRENT_WORKING_DIR):
  File "C:\Users\ctayl\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 851, in joinpath
    return self._make_child(args)
  File "C:\Users\ctayl\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 616, in _make_child
    drv, root, parts = self._parse_args(args)
  File "C:\Users\ctayl\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 288
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 302
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 322
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 587
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Sorry the library I use doesn't take into account of Scoops folder structure and is causing this crash. I'll see if I can get out a quick fix soon.

**Comment by jjw24** [comment]
Did we not expose the UserData location via API for python plugins?

**Comment by taooceros** [comment]
> Did we not expose the UserData location via API for python plugins?

No

**Comment by dragonmkww** [comment]
ok

**Comment by Garulf** [comment]
Fixed in version 1.0.0 (https://github.com/Garulf/FlowYouTube/pull/11)

Thanks for the heads up!

**Comment by dragonmkww** [comment]
Thanks for fixing!
