### ISSUE TITLE
Error occuring when trying to use steam plugin

### ISSUE THREAD

**Issue by Volyz** [Flow-Launcher/Flow.Launcher#1313]
Whenever i try to use the steam plugin, Flow Launcher get an error :

[2022-08-07.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9276752/2022-08-07.txt)

Flow Launcher version: 1.9.4
OS Version: Microsoft Windows NT 10.0.19043.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 08/07/2022 14:15:13
Exception:
System.IO.InvalidDataException: Steam Search|Traceback (most recent call last):
  File "C:\Users\Volyz\scoop\apps\FLow-Launcher\current\app-1.9.4\UserData\Plugins\Steam Search-4.1.1\run.py", line 9, in <module>
    from plugin.main import SteamSearch
  File "C:\Users\Volyz\scoop\apps\FLow-Launcher\current\app-1.9.4\UserData\Plugins\Steam Search-4.1.1\plugin\main.py", line 6, in <module>
    from flox import Flox, ICON_SETTINGS
  File "C:\Users\Volyz\scoop\apps\FLow-Launcher\current\app-1.9.4\UserData\Plugins\Steam Search-4.1.1\lib\flox\__init__.py", line 40, in <module>
    if str(APPDATA.joinpath(launcher_dir)) in str(CURRENT_WORKING_DIR):
  File "C:\devTools\python\Python39\lib\pathlib.py", line 961, in joinpath
    return self._make_child(args)
  File "C:\devTools\python\Python39\lib\pathlib.py", line 726, in _make_child
    drv, root, parts = self._parse_args(args)
  File "C:\devTools\python\Python39\lib\pathlib.py", line 680, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 288
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 302
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 322
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 587
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Hello @Volyz! 

This issue is caused Scoops installation structure and is related to: 

https://github.com/Flow-Launcher/Flow.Launcher/issues/1303

This isn't caused by Scoop but the way my plugin expects your plugin installation to be.

A fix will be fourth coming when I can sit down and write the code.

**Comment by Volyz** [comment]
hi @Garulf 

Thank you for the answer :) Don't worry, take your time and don't stress yourself out ! I was just trying Flow Launcher ( a great tool imho ).

Have a good day !

**Comment by Garulf** [comment]
This issue has been fixed with the latest version of the Plugin.
