### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by VolkRL** [Flow-Launcher/Flow.Launcher#1316]
[2022-08-09.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9288019/2022-08-09.txt)

Flow Launcher version: 1.9.4
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 08/09/2022 08:13:46
Exception:
System.AggregateException: One or more errors occurred. (Error while copying content to a stream.)
 ---> System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
   at Droplex.Downloader.Get(String url, String filePath)
   at Droplex.Downloader.Get(String url, String filePath)
   at Droplex.DroplexPackage.Drop(App app, String zipExtractPath)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Flow.Launcher.Core.Plugin.PluginsLoader.PythonPlugins(List`1 source, PluginsSettings settings) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginsLoader.cs:line 160
   at Flow.Launcher.Core.Plugin.PluginsLoader.Plugins(List`1 metadatas, PluginsSettings settings) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginsLoader.cs:line 25
   at Flow.Launcher.Core.Plugin.PluginManager.LoadPlugins(PluginsSettings settings) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 105
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 69
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 50
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
Hi @VolkRL, I think Flow failed to download Python, could you try restarting it to see if python gets re-downloaded please.
