### ISSUE TITLE
Flowlauncher crash after "Open Parent Folder"

### ISSUE THREAD

**Issue by NoFrans** [Flow-Launcher/Flow.Launcher#1332]
When clicking "Open parent folder" for any file, it crashes. A lot of the options have seem to be broken that weren't before. I can't recall most right now.

```
Flow Launcher version: 1.9.4
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 08/15/2022 18:46:37
Exception:
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Flow.Launcher.PublicAPIInstance.OpenDirectory(String DirectoryPath, String FileName) in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 209
   at Flow.Launcher.Plugin.Everything.Main.<>c__DisplayClass11_0.<LoadContextMenus>b__0(ActionContext _) in D:\a\Flow.Launcher.Plugin.Everything\Flow.Launcher.Plugin.Everything\Main.cs:line 268
   at Flow.Launcher.ViewModel.MainViewModel.<InitializeKeyCommands>b__19_9(Object index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 207
   at Flow.Launcher.ViewModel.RelayCommand.Execute(Object parameter) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\RelayCommand.cs:line 25
   at Flow.Launcher.MainWindow.OnPreviewMouseButtonDown(Object sender, MouseButtonEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 355
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.ContentElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.
```

Edit: I was attempting to open "OneCommander" parent directory. Which uses OneCommander (replacement to Windows Explorer). This happens with any directory, however.

**Comment by NoFrans** [comment]
So it looks like this only happens on one of my computers. Not the second one. I'm not sure why either. I tried uninstalling and reinstalling.

**Comment by taooceros** [comment]
please take a check on this setting 
![image](https://user-images.githubusercontent.com/45326534/184927821-88013119-6ba8-4fc5-bfbe-82ae4184421d.png)

**Comment by NoFrans** [comment]
I have to remember this for next time I reformat and restore my settings. Thank you, sorry for wasting your time. I appreciate you!

**Comment by taooceros** [comment]
No Problem!

**Comment by taooceros** [comment]
We currently didn't restore the setting when uninstalling, which should be done actually (I don't remember whether it is implemented yet).

**Comment by NoFrans** [comment]
> We currently didn't restore the setting when uninstalling, which should be done actually (I don't remember whether it is implemented yet).

Pardon my ignorance, I'm confused. What do you mean by restore setting when uninstalling?

**Comment by taooceros** [comment]
Sorry I write it poorly. It should be deleting the old setting file when uninstalling so next installing will create a new setting file.

**Comment by taooceros** [comment]
nvm it's not a great deal since we always want to preserve our setting when try to reinstall.

**Comment by taooceros** [comment]
Sure sure it's a very reasonable suggestion, and easy to implemeny. I will add that recently.

**Comment by NoFrans** [comment]
I appreciate you and this wonderful program. I cannot live without it! Also, while I have you here - I'm trying to figure out how to donate. I could have sworn I've seen "Donate" on the program. But I can't seem to find it. Do you have something setup?

**Comment by taooceros** [comment]
That will be wonderful! Thank you so much! 
You shall be able to do it easily here.
![image](https://user-images.githubusercontent.com/45326534/184932199-b3a4371b-26ae-4f54-b2d3-343c06dcb91f.png)
