### ISSUE TITLE
Flow Launcher Issue

### ISSUE THREAD

**Issue by MRZ-A** [Flow-Launcher/Flow.Launcher#1334]
[2022-08-18.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9372524/2022-08-18.txt)

Flow Launcher version: 1.9.4
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 08/18/2022 15:44:55
Exception:
System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding, Boolean overwriteFiles)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName)
   at Dictionary.DictDownloadManager.<>c__DisplayClass6_0.<PerformDownload>b__1() in D:\a\Flow.Launcher.Dictionary\Flow.Launcher.Dictionary\src\DictDownloadManager.cs:line 64
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Dictionary.DictDownloadManager.PerformDownload() in D:\a\Flow.Launcher.Dictionary\Flow.Launcher.Dictionary\src\DictDownloadManager.cs:line 64
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
Hey, this is related to dictionary plugin. What were you trying to do when you had this error?

@harrynull

**Comment by harrynull** [comment]
Thanks for letting me know. It seems that [dict file hosted by coding.net](https://github.com/harrynull/Flow.Launcher.Dictionary/blob/main/src/DictDownloadManager.cs#L41) no longer works because it now requires the user to be logged in. I guess I'll now have to find somewhere else to host that file.

The easiest solution is to either set a proxy in the settings so it downloads from github, or manually download it from github, unzip it, and place it into `%LocalAppData%\Flow.Dictionary\ultimate.db`.

**Comment by jjw24** [comment]
Thanks @harrynull 

Please follow here for new updates to this issue https://github.com/harrynull/Flow.Launcher.Dictionary/issues/16
