### ISSUE TITLE
issue- google search plugin

### ISSUE THREAD

**Issue by georgio909** [Flow-Launcher/Flow.Launcher#1343]
[2022-08-23.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9402659/2022-08-23.txt)
Flow Launcher version: 1.9.4
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 08/23/2022 15:48:46
Exception:
System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Wox.Plugin.GoogleSearch.GoogleSearch.Search(String query, Int32 limit) in C:\Workbench\Git\Wox.Plugin.GoogleSearch\Wox.Plugin.GoogleSearch\GoogleSearch.cs:line 30
   at Wox.Plugin.GoogleSearch.Main.Query(Query query) in C:\Workbench\Git\Wox.Plugin.GoogleSearch\Wox.Plugin.GoogleSearch\Main.cs:line 21
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Wox.Plugin.GoogleSearch.GoogleSearch.Search(String query, Int32 limit) in C:\Workbench\Git\Wox.Plugin.GoogleSearch\Wox.Plugin.GoogleSearch\GoogleSearch.cs:line 30
   at Wox.Plugin.GoogleSearch.Main.Query(Query query) in C:\Workbench\Git\Wox.Plugin.GoogleSearch\Wox.Plugin.GoogleSearch\Main.cs:line 21
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
Hey is it still happening to you and what were you trying to search?

**Comment by georgio909** [comment]
Hello dev! I hope you are having a good day
The bug shows up almost 50% of the times when I use the “gs” google search plugin, so I stopped using it, that’s all.

Georgio Kassis

**Comment by jjw24** [comment]
Hello, is the WebSearch plugin's Google search working for you all the time?
