### ISSUE TITLE
Failed to warn incorrect python path

### ISSUE THREAD

**Issue by Jessi810** [Flow-Launcher/Flow.Launcher#1344]
General Converter: https://github.com/deefrawley/Flow.Launcher.Plugin.GenConvert

[2022-08-23.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9402867/2022-08-23.txt)

Flow Launcher version: 1.9.4
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 08/23/2022 21:24:53
Exception:
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 247
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 322
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 613
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 587
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by taooceros** [comment]
Similar to #1342

**Comment by deefrawley** [comment]
Hi Jess. Are you using an existing Python install or did you let Flow install python the first time you installed the plugin?

**Comment by Jessi810** [comment]
Existing Python installation.

**Comment by taooceros** [comment]
> Existing Python installation.

Could you share the setting and your python version? I think the error is because flow cannot find specific python executable.

**Comment by Jessi810** [comment]
I fixed it already. You are right, the Python path I had doesn't have the exe files. And it was using this path for my Python: C:\Users\<user>\AppData\Local\Programs\Python\Python310

**Comment by Garulf** [comment]
Perhaps we should display a more constructive error message in these cases?

**Comment by jjw24** [comment]
> Perhaps we should display a more constructive error message in these cases?

Yeah good idea, let's add a fix to check for exe during python path selection.

**Comment by jjw24** [comment]
Fixed and available in current release.
