### ISSUE TITLE
Error sometimes on Open?/Search? a Program

### ISSUE THREAD

**Issue by Tobias3107** [Flow-Launcher/Flow.Launcher#1347]
The Error comes a few times today. I dont know why

The Program i search for is in a Folder structure that i placed in the settings. 

Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19042.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 08/26/2022 13:08:20
Exception:
System.AggregateException: One or more errors occurred. (Zugriff verweigert)
 ---> System.ComponentModel.Win32Exception (5): Zugriff verweigert
   at System.Diagnostics.Process.Kill()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2022-08-26.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9432625/2022-08-26.txt)

**Comment by jjw24** [comment]
I think based on the translation of 'Zugriff verweigert' - access denied, meaning one or more of your folder structure flow can not access. This could be the user you are using flow with does not have the access.

Have you tried with Administrator or an account with proper access to all those folders?

**Comment by Tobias3107** [comment]
> I think based on the translation of 'Zugriff verweigert' - access denied

Yes sure that is true. 

Its just popping up sometimes.

> Have you tried with Administrator or an account with proper access to all those folders?

I can open flow with administrator. But all the things i have to search will be find. So the Question is. 
Why needs to be popup sometimes? Or You havent filter out this things?
Is it not enougth that comes a call in the logs?

**Comment by taooceros** [comment]
The error seems to relate to killing cancelled jsonrpc process. I guess it is because your python is installed in `Program File`, which means flow has no access to kill it. Maybe we can suppress that error.
