### ISSUE TITLE
Running Obsidian Notes plugin returns error

### ISSUE THREAD

**Issue by fedderw** [Flow-Launcher/Flow.Launcher#1359]
Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues/new
1. upload log file: C:\Users\fedde\AppData\Roaming\FlowLauncher\Logs\1.9.4\2022-09-01.txt
2. copy below exception message

Flow Launcher version: 1.9.4
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\fedde\AppData\Roaming\FlowLauncher\PythonEmbeddable\pythonw.exe
Date: 09/01/2022 16:36:43
Exception:
System.IO.InvalidDataException: Obsidian Notes|Exception ignored in: <function Launcher.__del__ at 0x000001CF713C6F70>
Traceback (most recent call last):
  File "C:\Users\fedde\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.3\lib\flox\launcher.py", line 59, in __del__
    self.__call__()
  File "C:\Users\fedde\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.3\lib\flox\__init__.py", line 96, in __call__
    return super().__call__()
  File "C:\Users\fedde\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.3\lib\flox\launcher.py", line 41, in __call__
    results = request_method(*request_parameters)
  File "C:\Users\fedde\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.3\lib\flox\__init__.py", line 127, in _query
    self.query(query)
  File "C:\Users\fedde\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.3\plugin\main.py", line 38, in query
    context=[vault.id, str(note.path), note.checklists()]
  File "C:\Users\fedde\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.3\plugin\obsidian.py", line 106, in checklists
    for line in self.content().splitlines():
  File "C:\Users\fedde\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.3\plugin\obsidian.py", line 85, in content
    with open(self.path, 'r', encoding='utf-8', errors='replace') as f:
FileNotFoundError: [Errno 2] No such file or directory: "C:\\Users\\fedde\\OneDrive\\Documents\\2020-06-01-ObsidianWorkflows\\Workflows\\02 PARA_Starter_Kit_v2\\2. Areas\\Personal Development\\A spellbinding reading of Hermann Hesse's 100-year-old love letter to trees, a Chilean picture-book about life and death, an ode to love beyond labels.md"

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 288
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 302
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 322
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 613
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 587
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
I'm not sure why but it seems the plugin can no longer access the file 

`C:\Users\fedde\OneDrive\Documents\2020-06-01-ObsidianWorkflows\Workflows\02 PARA_Starter_Kit_v2\2. Areas\Personal Development\A spellbinding reading of Hermann Hesse's 100-year-old love letter to trees, a Chilean picture-book about life and death, an ode to love beyond labels.md`

Was it moved or deleted?

**Comment by fedderw** [comment]
No, it hasn't been deleted. Why would that matter? Why would it try to
access a deleted file?

**Comment by Garulf** [comment]
Not sure but according to the error log it can no longer access that file. Is the file in some sort of cloud drive folder and maybe it was temporarily unavailable?

**Comment by fedderw** [comment]
I think so. Is it possible to exclude this? This was just an example vault,
it's not the vault that I want to search.

**Comment by Garulf** [comment]
Currently the Obsidian plugin searches all vaults that Obsidian knows about. This could possibly be added in future versions.
