### ISSUE TITLE
Crash using Flow Launcher

### ISSUE THREAD

**Issue by grouchal** [Flow-Launcher/Flow.Launcher#1362]
Log: [2022-09-04.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9484773/2022-09-04.txt)

## Exception Message:

Flow Launcher version: 1.9.4
OS Version: Microsoft Windows NT 10.0.18363.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 09/04/2022 15:15:05
Exception:
System.AggregateException: One or more errors occurred. (Class not registered
)
 ---> System.Runtime.InteropServices.COMException (0x80070006): Class not registered

   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Interop.Kernel32.ProcessWaitHandle..ctor(SafeProcessHandle processHandle)
   at System.Diagnostics.Process.UpdateHasExited()
   at System.Diagnostics.Process.get_HasExited()
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.<>c__DisplayClass26_0.<ExecuteAsync>b__0() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 263
   at System.Threading.CancellationToken.<>c.<.cctor>b__26_0(Object obj)
   at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by taooceros** [comment]
We are already fixed this in the latest build. You can try here https://github.com/Flow-Launcher/Flow.Launcher/discussions/956.

**Comment by jjw24** [comment]
Closing, please use the preview build or the soon to be released v1.9.5.
