### ISSUE TITLE
Null exception: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by rp1231** [Flow-Launcher/Flow.Launcher#1366]
Flow Launcher version: 1.9.4
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 09/07/2022 01:06:27
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Flow.Launcher.Core.Plugin.PluginManager.ValidPluginsForQuery(Query query) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 178
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2022-09-07.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9500213/2022-09-07.txt)

**Comment by jjw24** [comment]
Feels like this is something we have addressed already? @taooceros

**Comment by taooceros** [comment]
Not sure. I will check
