### ISSUE TITLE
Unexpected  Crash 

### ISSUE THREAD

**Issue by Its-Satyajit** [Flow-Launcher/Flow.Launcher#1375]
```
Flow Launcher version: 1.9.4
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 09/09/2022 00:58:57
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Dictionary.Main.Save() in C:\Users\Null\Documents\Projects\Flow.Launcher.Dictionary\src\Dictionary.cs:line 375
   at Flow.Launcher.Core.Plugin.PluginManager.Save() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 52
   at Flow.Launcher.ViewModel.SettingWindowViewModel.Save() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\SettingWindowViewModel.cs:line 98
   at Flow.Launcher.PublicAPIInstance.SaveAppAllSettings() in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 82
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 102
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 50
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by jjw24** [comment]
Hi @harrynull, would this be related to Dictionary plugin's save functionality?

@Its-Satyajit is this error consistently happening for you?

**Comment by harrynull** [comment]
The dictionary's Save function simply calls `settings.Save()` and `settings` is asyncly initialized so maybe a race condition?

**Comment by jjw24** [comment]
Same as issue 1471, let's track it over there.
