### ISSUE TITLE
Flow Launcher got an error

### ISSUE THREAD

**Issue by secretqwerty10** [Flow-Launcher/Flow.Launcher#1379]
Flow Launcher version: 1.9.4
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 09/12/2022 23:15:25
Exception:
System.IO.InvalidDataException: HA-Commander|Exception ignored in: <function Launcher.__del__ at 0x0000021ADA405CA0>
Traceback (most recent call last):
  File "C:\Users\omarq\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-3.2.1\lib\flox\launcher.py", line 59, in __del__
    self.__call__()
  File "C:\Users\omarq\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-3.2.1\lib\flox\__init__.py", line 96, in __call__
    return super().__call__()
  File "C:\Users\omarq\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-3.2.1\lib\flox\launcher.py", line 41, in __call__
    results = request_method(*request_parameters)
  File "C:\Users\omarq\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-3.2.1\lib\flox\__init__.py", line 127, in _query
    self.query(query)
  File "C:\Users\omarq\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-3.2.1\plugin\main.py", line 45, in query
    self.client.api()
  File "C:\Users\omarq\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-3.2.1\plugin\homeassistant.py", line 112, in api
    return self.request("GET", "")
  File "C:\Users\omarq\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-3.2.1\plugin\homeassistant.py", line 75, in request
    response = self._session.request(
  File "C:\Users\omarq\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-3.2.1\lib\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\omarq\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-3.2.1\lib\requests\sessions.py", line 649, in send
    adapter = self.get_adapter(url=request.url)
  File "C:\Users\omarq\AppData\Roaming\FlowLauncher\Plugins\HA-Commander-3.2.1\lib\requests\sessions.py", line 742, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '192.168.178.8:8123/api/'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 288
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 302
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 322
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2022-09-12.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9551873/2022-09-12.txt)

**Comment by Garulf** [comment]
Looks like `http://` or `https://` is missing from your URL. Please provide an http scheme like so:

![image](https://user-images.githubusercontent.com/535299/189779296-87c4fd93-551c-42ed-a107-6f9d2e2f1ddf.png)
