### ISSUE TITLE
Notion Plugin error

### ISSUE THREAD

**Issue by Eslam21** [Flow-Launcher/Flow.Launcher#1384]
[2022-09-15.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9579177/2022-09-15.txt)
Flow Launcher version: 1.9.4
OS Version: Microsoft Windows NT 10.0.19043.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 09/15/2022 23:29:00
Exception:
System.IO.InvalidDataException: Notion Search|Traceback (most recent call last):
  File "C:\Users\eslam\AppData\Roaming\Python\Python310\site-packages\git\__init__.py", line 87, in <module>
    refresh()
  File "C:\Users\eslam\AppData\Roaming\Python\Python310\site-packages\git\__init__.py", line 76, in refresh
    if not Git.refresh(path=path):
  File "C:\Users\eslam\AppData\Roaming\Python\Python310\site-packages\git\cmd.py", line 341, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

**Comment by jjw24** [comment]
Hi, on first glance I see you are using 3.10 python, could you try version 3.8. You could also contact the plugin developer [here](https://github.com/danielduckworth/Flow.Launcher.Plugin.NotionSearch) regarding this error.
