### ISSUE TITLE
error while trying to use uninstall plugin

### ISSUE THREAD

**Issue by evetech2021** [Flow-Launcher/Flow.Launcher#1398]
[2022-09-21.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9615609/2022-09-21.txt)

Flow Launcher version: 1.9.4
OS Version: Microsoft Windows NT 10.0.22622.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 09/21/2022 15:41:43
Exception:
System.ComponentModel.Win32Exception (740): The requested operation requires elevation.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName, String arguments)
   at QuickUninstaller.Main.<>c__DisplayClass2_5.<Query>b__6(ActionContext e) in D:\a\Wox.Plugin.QuickUninstaller\Wox.Plugin.QuickUninstaller\QuickUninstaller\Main.cs:line 258
   at Flow.Launcher.ViewModel.MainViewModel.<InitializeKeyCommands>b__19_9(Object index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 207
   at Flow.Launcher.ViewModel.RelayCommand.Execute(Object parameter) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\RelayCommand.cs:line 25
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by evetech2021** [comment]
Yes, it did have admin access

**Comment by jjw24** [comment]
what app were you trying to uninstall?
