### ISSUE TITLE
Obsidian Plugin Launch error

### ISSUE THREAD

**Issue by SchittBull** [Flow-Launcher/Flow.Launcher#1399]
Flow Launcher version: 1.9.4
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 09/21/2022 15:10:57
Exception:
System.IO.InvalidDataException: Obsidian Notes|Traceback (most recent call last):
  File "C:\Users\manik\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\run.py", line 9, in <module>
    from plugin.main import Obsidian
  File "C:\Users\manik\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\plugin\main.py", line 3, in <module>
    from flox import Flox
  File "C:\Users\manik\AppData\Roaming\FlowLauncher\Plugins\Obsidian Notes-1.1.4\lib\flox\__init__.py", line 13, in <module>
    from functools import wraps, cached_property
ImportError: cannot import name 'cached_property' from 'functools' (C:\Users\manik\AppData\Local\Programs\Python\Python37-32\lib\functools.py)

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 288
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 302
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 322
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 613
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 587
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Hello @SchittBull, what version of Python are you using with Flow Launcher? Most if not all Python based plugins use Python 3.8 or higher.

**Comment by SchittBull** [comment]
I was on 3.7. Now I updated to the latest version, changed the path and it works. Thank you!

**Comment by Garulf** [comment]
> I was on 3.7. Now I updated to the latest version, changed the path and it works. Thank you!

No problem! Glad we resolved your issue.
