### ISSUE TITLE
crash upon entering folder

### ISSUE THREAD

**Issue by NolanNolan** [Flow-Launcher/Flow.Launcher#1415]
Flow Launcher version: 1.9.4
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 09/25/2022 18:48:26
Exception:
System.ComponentModel.Win32Exception (2): Den angivne fil blev ikke fundet.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Flow.Launcher.PublicAPIInstance.OpenDirectory(String DirectoryPath, String FileName) in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 209
   at Flow.Launcher.Plugin.Explorer.Search.ResultManager.<>c__DisplayClass8_0.<CreateOpenCurrentFolderResult>b__0(ActionContext c) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\ResultManager.cs:line 117
   at Flow.Launcher.ViewModel.MainViewModel.<InitializeKeyCommands>b__19_9(Object index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 207
   at Flow.Launcher.MainWindow.OnPreviewMouseButtonDown(Object sender, MouseButtonEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 355
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2022-09-25.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9641293/2022-09-25.txt)

**Comment by taooceros** [comment]
Could you check this setting?
![image](https://user-images.githubusercontent.com/45326534/192168082-4a135b3f-46de-4517-b442-eb9bd5310838.png)

**Comment by NolanNolan** [comment]
I just did and setting this to explore or Opus then works. But why is it possible to set it to find and what is it if it's not useable?

Hilsen Jørn

On 26. september 2022 00.19.41 Kevin Zhang ***@***.***> wrote:

Could you check this setting?
[image]<https://user-images.githubusercontent.com/45326534/192168082-4a135b3f-46de-4517-b442-eb9bd5310838.png>

**Comment by jjw24** [comment]
By default it should be using Windows Explorer.

**Comment by jjw24** [comment]
Closing, feel free to reopen if issue still persists.
