### ISSUE TITLE
Flow Launcher version: 1.9.4 OS Version: Microsoft Windows NT 10.0.19044.0 IntPtr Length: 8 x64: True

### ISSUE THREAD

**Issue by mrk088** [Flow-Launcher/Flow.Launcher#1426]
System.Security.SecurityException: Requested registry access is not allowed.
   at Microsoft.Win32.RegistryKey.InternalOpenSubKeyCore(String name, Boolean writable)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at Flow.Launcher.SettingWindow.StartupSet() in C:\projects\flow-launcher\Flow.Launcher\SettingWindow.xaml.cs:line 85
   at Flow.Launcher.App.AutoStartup() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 112
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 99
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 50
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by deefrawley** [comment]
WHat version of Flow are you running?

**Comment by mrk088** [comment]
1.9.4 for windows  x64

**Comment by jjw24** [comment]
Please update to v1.9.5, this bug is fixed.
