### ISSUE TITLE
Image conversation error- app_missing_img.png

### ISSUE THREAD

**Issue by cityhard** [Flow-Launcher/Flow.Launcher#1447]
[2022-10-05.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9715400/2022-10-05.txt)
Flow Launcher version: 1.9.5
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 10/05/2022 14:57:15
Exception:
System.TypeInitializationException: The type initializer for 'Flow.Launcher.Infrastructure.Image.ImageLoader' threw an exception.
 ---> System.OverflowException: The image data generated an overflow during processing.
 ---> System.ArithmeticException: Overflow or underflow in the arithmetic operation.
   --- End of inner exception stack trace ---
   at System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation()
   at System.Windows.Media.Imaging.ColorConvertedBitmap..ctor(BitmapSource source, ColorContext sourceColorContext, ColorContext destinationColorContext, PixelFormat format)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at System.Windows.Media.Imaging.BitmapImage..ctor(Uri uriSource, RequestCachePolicy uriCachePolicy)
   at System.Windows.Media.Imaging.BitmapImage..ctor(Uri uriSource)
   at Flow.Launcher.Infrastructure.Image.ImageLoader..cctor() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Image\ImageLoader.cs:line 21
   --- End of inner exception stack trace ---
   at Flow.Launcher.Infrastructure.Image.ImageLoader.Initialize() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Image\ImageLoader.cs:line 37
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 59
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 50
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by cityhard** [comment]
Well, problem is solved

**Comment by jjw24** [comment]
what was the solution?

**Comment by BlueDrink9** [comment]
I'm having this same error, and have been for a while. @cityhard what did you do to fix this?

**Comment by BlueDrink9** [comment]
I've tried deleting the flow directories in appdata, without success

**Comment by BlueDrink9** [comment]
It may be worth noting that I get this same error is Wox, too

**Comment by BlueDrink9** [comment]
I can delete every image in the Images/ app folder except `app_error.png` and `app_missing_img.png` and the message still appears. Deleting app_error stops anything at all from appearing, and deleting missing_img causes an error relating to not finding that file.

**Copying `app_error` and renaming it to replace `app_missing_img`** gets me past the error. Looks like `app_missing_img.png` is bad somehow

**Comment by cityhard** [comment]
i did nothind. just in few days problem solved by itself

**Comment by jjw24** [comment]
> I can delete every image in the Images/ app folder except `app_error.png` and `app_missing_img.png` and the message still appears. Deleting app_error stops anything at all from appearing, and deleting missing_img causes an error relating to not finding that file.
> 
> **Copying `app_error` and renaming it to replace `app_missing_img`** gets me past the error. Looks like `app_missing_img.png` is bad somehow

can you replace app_missing_img.png with another one and see if it still errors. If not then that could likely be the cause. Please let us know.

**Comment by jjw24** [comment]
> I can delete every image in the Images/ app folder except `app_error.png` and `app_missing_img.png` and the message still appears. Deleting app_error stops anything at all from appearing, and deleting missing_img causes an error relating to not finding that file.
> 
> **Copying `app_error` and renaming it to replace `app_missing_img`** gets me past the error. Looks like `app_missing_img.png` is bad somehow

can you check if it happens again after switching back?

**Comment by jjw24** [comment]
Thanks for taking the time to investigate this issue @BlueDrink9, really appreciate it.

@onesounds do you want to revamp this image or just re-save it?

**Comment by onesounds** [comment]
in now, re-save. If I made new image, I'll share the image here

**Comment by onesounds** [comment]
ok. I referred to the following document on this matter.
https://github.com/dotnet/wpf/issues/3884

This problem may occur when the color profile of the user is virtual and the color profile information is contained in the png.

@BlueDrink9 Please let me know what is your window version / color profile.

![image](https://user-images.githubusercontent.com/6903107/196597668-5d69bc43-ef7d-4be3-844e-63db55127cf6.png)


and then, Please let me know if there is any problem when you replace it with the attached image. 

This is new image (removed color profile info)
https://github.com/Flow-Launcher/Flow.Launcher/blob/2c87dd448124df56a2fd44393775338b9228be79/Flow.Launcher/Images/app_missing_img.png

If there is no problem, I will replace it with this image.

**Comment by jjw24** [comment]
Fix available in prerelease.
