### ISSUE TITLE
i am getting this exceptions

### ISSUE THREAD

**Issue by Jaysarna** [Flow-Launcher/Flow.Launcher#1472]
Flow Launcher version: 1.9.5
OS Version: Microsoft Windows NT 6.3.9600.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 10/13/2022 11:51:19
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Dictionary.Main.Save() in C:\Users\Null\Documents\Projects\Flow.Launcher.Dictionary\src\Dictionary.cs:line 375
   at Flow.Launcher.Core.Plugin.PluginManager.Save() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 53
   at Flow.Launcher.ViewModel.SettingWindowViewModel.Save() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\SettingWindowViewModel.cs:line 121
   at Flow.Launcher.SettingWindow.OnClosed(Object sender, EventArgs e) in C:\projects\flow-launcher\Flow.Launcher\SettingWindow.xaml.cs:line 246
   at System.Windows.Window.OnClosed(EventArgs e)
   at System.Windows.Window.WmDestroy()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
Same as https://github.com/Flow-Launcher/Flow.Launcher/issues/1471

**Comment by jjw24** [comment]
Let's track the issue over there.
