### ISSUE TITLE
BUG: The JSON value could not be converted to Flow.Launcher.Core.Plugin.JsonRPCRequestModel

### ISSUE THREAD

**Issue by Monochromish** [Flow-Launcher/Flow.Launcher#1493]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

I'm making a plugin and the commands work but after it's usage, it returns this error:

```
Flow Launcher version: 1.9.5
OS Version: Microsoft Windows NT 10.0.22623.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 10/20/2022 18:23:46
Exception:
System.Text.Json.JsonException: The JSON value could not be converted to Flow.Launcher.Core.Plugin.JsonRPCRequestModel. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.<>c__DisplayClass22_0.<ParseResults>b__0(ActionContext c) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 143
   at Flow.Launcher.ViewModel.MainViewModel.<InitializeKeyCommands>b__19_9(Object index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 207
   at Flow.Launcher.ViewModel.RelayCommand.Execute(Object parameter) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\RelayCommand.cs:line 25
   at Flow.Launcher.MainWindow.OnPreviewMouseButtonDown(Object sender, MouseButtonEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 355
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### To Reproduce

1. Use any command of the plugin
2. Error is displayed

Refer to video attached below

### Screenshots

Error Preview:

https://user-images.githubusercontent.com/79590499/196884729-46479d8e-29d6-416d-8555-b18a280891d7.mp4

Plugin Code:
![image](https://user-images.githubusercontent.com/79590499/196883824-571d63fd-d1b9-43c6-8919-4147de72e2d6.png)
![image](https://user-images.githubusercontent.com/79590499/196884149-8893ca8a-8770-4883-b9b7-3224f20dec5b.png)

### Flow Launcher Version

v1.9.5

### Windows Build Number

10.0.22623.746

### Error Log

Log file is attached
[2022-10-20.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9827392/2022-10-20.txt)

**Comment by jjw24** [comment]
Hey there, I'm afk, but a brief look seems to indicate json conversation error. I would run all your json files over an online json validator.

Let me know how u go.

**Comment by taooceros** [comment]
I believe it happens when you execute the result? Probably that's because the callback method doesn't print a valid json output (but weirdly we should have suppressed this error so we will give it a check recently).
