### ISSUE TITLE
Got this error

### ISSUE THREAD

**Issue by JPRial** [Flow-Launcher/Flow.Launcher#1499]
Flow Launcher version: 1.9.5
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 10/25/2022 02:38:10
Exception:
System.AggregateException: One or more errors occurred. (Controlador no válido.)
 ---> System.ComponentModel.Win32Exception (6): Controlador no válido.
   at System.Diagnostics.Process.Kill()
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.<>c__DisplayClass26_0.<ExecuteAsync>b__0() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 264
   at System.Threading.CancellationToken.<>c.<.cctor>b__26_0(Object obj)
   at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 627
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by taooceros** [comment]
You may try the latest dev. We should have fixed this. https://github.com/Flow-Launcher/Flow.Launcher/discussions/956

**Comment by jjw24** [comment]
@taooceros is this added?

**Comment by taooceros** [comment]
I feel like this is resolved

**Comment by taooceros** [comment]
Oh maybe not. This seems like a permission issue...
