### ISSUE TITLE
Flow launcher terminates silently

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/Flow.Launcher#1504]
Flow terminates silently after usage for a while, flow icon no longer in the taskbar and itself can not be triggered.

1. 
  [2022-09-15.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9606557/2022-09-15.txt)
Log for when it crashed. When clicking FL icon, it still does not open

_Originally posted by @tejaskerai in https://github.com/Flow-Launcher/Flow.Launcher/issues/1268#issuecomment-1252152090_

2. > It looks like it happened again, and trying to relaunch it doesn't work [2022-10-21.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9851242/2022-10-21.txt)

**Comment by tejaskerai** [comment]
Thanks for opening this issue. Thought this might be some useful information; while using FL, I've noticed that this mostly occurs after coming out of hibernation or a reboot, but also sometimes it will open and then crash and will not open again

**Comment by VictoriousRaptor** [comment]
> Thanks for opening this issue. Thought this might be some useful information; while using FL, I've noticed that this mostly occurs after coming out of hibernation or a reboot, but also sometimes it will open and then crash and will not open again

Next time when it happens, please check Event Viewer. It may contain some useful information.

**Comment by jjw24** [comment]
> Thanks for opening this issue. Thought this might be some useful information; while using FL, I've noticed that this mostly occurs after coming out of hibernation or a reboot, but also sometimes it will open and then crash and will not open again

You wouldn't happen to be using Windows with Parallel would you?

**Comment by tejaskerai** [comment]
Nope, not using parallels.

**Comment by tejaskerai** [comment]
> Next time when it happens, please check Event Viewer. It may contain some useful information.

The issue occurred today again. After coming out of hibernation and using flowlauncher, it opened and immediately crashed.
Attached Event viewer Log
![image](https://user-images.githubusercontent.com/38558558/199951413-2bb9c7c5-8ce0-4b1d-bce3-1aa37b9c0786.png)

**Comment by tejaskerai** [comment]
Another log that may be useful
[Report.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/9937454/Report.txt)

**Comment by VictoriousRaptor** [comment]
What plugins are you using? That dll is not shipped with flow so I guess it's related to a plugin?

**Comment by tejaskerai** [comment]
Looks like this dll is coming from Cylance PROTECT program. Which is system security software that cannot be uninstalled as this is a work laptop

**Comment by jjw24** [comment]
Hmm is it reporting flow? Are you able to scan flow with it to see if any thing comes up?

**Comment by SplitGemini** [comment]
<details>

```shell

17:53:02.4931+08:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
17:53:02.4936+08:00 - ERROR -  - 
Exception full name: System.IO.FileNotFoundException
Error status: KNOWN
Class name: UWP
Calling method: ImageFromPath
Program path: Not Avaliable
InnerException number: 1
Exception message: Unable to find the specified file.
Exception error type: HResult -2147024894
Exception thrown in called method: Not available
Possible interpretation of the error: Unable to get logo for Microsoft.Windows.SecHealthUI_cw5n1h2txyewy!SecHealthUI from  and located in C:\Windows\SystemApps\Microsoft.Windows.SecHealthUI_cw5n1h2txyewy
Possible resolution: Can be ignored and Flow Launcher should still continue, however the program may not be loaded
17:53:02.4936+08:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
17:53:04.1196+08:00 - FATAL - UnHandledException - 
## Exception

```
System.ArgumentException: The index is equal to or greater than the length of the array, or the number of elements in the dictionary is greater than the available space from index to the end of the destination array.
   Source: System.Collections.Concurrent
   TargetAssembly: System.Collections.Concurrent, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
   TargetModule: System.Collections.Concurrent.dll
   TargetSite: Void System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.CopyTo(System.Collections.Generic.KeyValuePair`2[TKey,TValue][], Int32)
   at System.Collections.Concurrent.ConcurrentDictionary`2.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.CopyTo(KeyValuePair`2[] array, Int32 index)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator(Int32 minIdx, Int32 maxIdx)+MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at Flow.Launcher.Infrastructure.Image.ImageCache.<>c__DisplayClass10_0.<<set_Item>g__SliceExtra|1>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Image\ImageCache.cs:line 77
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

```
</details>

**Comment by SplitGemini** [comment]
<details>
```shell
3:14:55.3195+08:00 - FATAL - UnHandledException - 
## Exception


System.Text.Json.JsonException: The JSON value could not be converted to System.Collections.Generic.List`1[Flow.Launcher.Core.Updater+GithubRelease]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
   Source: System.Text.Json
   TargetAssembly: System.Text.Json, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
   TargetModule: System.Text.Json.dll
   TargetSite: Void ThrowJsonException_DeserializeUnableToConvertValue(System.Type)
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Flow.Launcher.Core.Updater.GitHubUpdateManager(String repository) in C:\projects\flow-launcher\Flow.Launcher.Core\Updater.cs:line 125
   at Flow.Launcher.Core.Updater.GitHubUpdateManager(String repository) in C:\projects\flow-launcher\Flow.Launcher.Core\Updater.cs:line 137
   at Flow.Launcher.Core.Updater.UpdateAppAsync(IPublicAPI api, Boolean silentUpdate) in C:\projects\flow-launcher\Flow.Launcher.Core\Updater.cs:line 43
   at Flow.Launcher.App.<AutoUpdates>b__16_1(Object s, ElapsedEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 138
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```
</detials>

**Comment by SplitGemini** [comment]
Again.

<details>

```shell

System.Text.Json.JsonException: The JSON value could not be converted to System.Collections.Generic.List`1[Flow.Launcher.Core.Updater+GithubRelease]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
   Source: System.Text.Json
   TargetAssembly: System.Text.Json, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
   TargetModule: System.Text.Json.dll
   TargetSite: Void ThrowJsonException_DeserializeUnableToConvertValue(System.Type)
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Flow.Launcher.Core.Updater.GitHubUpdateManager(String repository) in C:\projects\flow-launcher\Flow.Launcher.Core\Updater.cs:line 125
   at Flow.Launcher.Core.Updater.GitHubUpdateManager(String repository) in C:\projects\flow-launcher\Flow.Launcher.Core\Updater.cs:line 137
   at Flow.Launcher.Core.Updater.UpdateAppAsync(IPublicAPI api, Boolean silentUpdate) in C:\projects\flow-launcher\Flow.Launcher.Core\Updater.cs:line 43
   at Flow.Launcher.App.<AutoUpdates>b__16_1(Object s, ElapsedEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 138
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

</details>

**Comment by SplitGemini** [comment]
> @SplitGemini what did you do before the error occurred e.g. hibernated computer? And can you consistently reproduce this error?
> 
> Also please check event log if anything jumps out.

After turning off automatic updates, the crash no longer occurs.

**Comment by tejaskerai** [comment]
> After turning off automatic updates, the crash no longer occurs.

This actually plays true for me too. But I am not 100% certain that this was the cause because I have tried some other things
