### ISSUE TITLE
errors opening files with plugin runner

### ISSUE THREAD

**Issue by jimrandell** [Flow-Launcher/Flow.Launcher#1583]
Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues/new
1. upload log file: C:\Users\jimr\AppData\Roaming\FlowLauncher\Logs\1.9.5\2022-11-28.txt
2. copy below exception message

Flow Launcher version: 1.9.5
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 11/28/2022 13:25:01
Exception:
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Wox.Plugin.Runner.Runner.RunCommand(ActionContext e, Command command, IEnumerable`1 terms) in D:\a\Wox.Plugin.Runner\Wox.Plugin.Runner\Wox.Plugin.Runner\Runner.cs:line 110
   at Wox.Plugin.Runner.Runner.<>c__DisplayClass4_1.<FuzzySearchCommand>b__2(ActionContext e) in D:\a\Wox.Plugin.Runner\Wox.Plugin.Runner\Wox.Plugin.Runner\Runner.cs:line 88
   at Flow.Launcher.ViewModel.MainViewModel.<InitializeKeyCommands>b__19_9(Object index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 207
   at Flow.Launcher.ViewModel.RelayCommand.Execute(Object parameter) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\RelayCommand.cs:line 25
   at Flow.Launcher.MainWindow.OnPreviewMouseButtonDown(Object sender, MouseButtonEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 355
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2022-11-28.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10104119/2022-11-28.txt)

**Comment by taooceros** [comment]
Sorry for the late response. The error seems to be you enter the wrong file path.

**Comment by jimrandell** [comment]
that sounds like me...will take another look
