### ISSUE TITLE
Error when trying to fetch update; Additionaly installing plugins does not work

### ISSUE THREAD

**Issue by jasoncaserta** [Flow-Launcher/Flow.Launcher#1590]
[2022-12-01.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10134334/2022-12-01.txt)

Flow Launcher version: 1.9.5
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/01/2022 11:40:13
Exception:
System.Runtime.InteropServices.COMException (0x803E0105): The notification platform is unavailable. (0x803E0105)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.UI.Notifications.IToastNotificationManagerStaticsMethods.CreateToastNotifier(IObjectReference _obj, String applicationId)
   at Windows.UI.Notifications.ToastNotificationManager.CreateToastNotifier(String applicationId)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.CreateToastNotifier()
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show(CustomizeToast customize)
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show()
   at Flow.Launcher.Notification.Show(String title, String subTitle, String iconPath) in C:\projects\flow-launcher\Flow.Launcher\Notification.cs:line 35
   at Flow.Launcher.PublicAPIInstance.<>c__DisplayClass13_0.<ShowMsg>b__0() in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 98
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Flow.Launcher.PublicAPIInstance.ShowMsg(String title, String subTitle, String iconPath, Boolean useMainWindowAsOwner) in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 96
   at Flow.Launcher.PublicAPIInstance.ShowMsg(String title, String subTitle, String iconPath) in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 92
   at Flow.Launcher.Core.Updater.UpdateAppAsync(IPublicAPI api, Boolean silentUpdate) in C:\projects\flow-launcher\Flow.Launcher.Core\Updater.cs:line 40
   at Flow.Launcher.ViewModel.SettingWindowViewModel.UpdateApp() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\SettingWindowViewModel.cs:line 52
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by taooceros** [comment]
It seems like Windows notification is not available on your computer. Which Windows version do you use?
