### ISSUE TITLE
Flow Launcher Exception. FL 1.9.5

### ISSUE THREAD

**Issue by dracp** [Flow-Launcher/Flow.Launcher#1595]
[2022-12-05.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10156535/2022-12-05.txt)

Flow Launcher version: 1.9.5
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/05/2022 18:28:32
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Flow.Launcher.ResultListBox.ResultList_PreviewMouseLeftButtonDown(Object sender, MouseButtonEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\ResultListBox.xaml.cs:line 104
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by taooceros** [comment]
Are you on the latest prerelease? I cannot really reproduce.

**Comment by dracp** [comment]
Yes.
22/12/05 FlowLauncher Beta Portable

**Comment by dracp** [comment]
![221205_Error_01](https://user-images.githubusercontent.com/102802425/205708289-e7d0db09-85cb-44fe-b213-414249364f6c.png)
![221205_Error_02](https://user-images.githubusercontent.com/102802425/205708317-2c9aebcc-1591-409a-aaed-4a2149b095d0.png)
![221205_Error_03](https://user-images.githubusercontent.com/102802425/205708358-cf25c5f3-9333-47b8-9ec4-034d18bfaa38.png)

**Comment by taooceros** [comment]
I see. Thank you for the report!
