### ISSUE TITLE
Error: Explorer does not work properly.

### ISSUE THREAD

**Issue by kananniftiyev** [Flow-Launcher/Flow.Launcher#1608]
[2022-12-08.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10186028/2022-12-08.txt)

Flow Launcher version: 1.9.5
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/08/2022 15:00:15
Exception:
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Flow.Launcher.PublicAPIInstance.OpenDirectory(String DirectoryPath, String FileName) in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 209
   at Flow.Launcher.Plugin.Explorer.Search.ResultManager.<>c__DisplayClass8_0.<CreateOpenCurrentFolderResult>b__0(ActionContext c) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\ResultManager.cs:line 117
   at Flow.Launcher.ViewModel.MainViewModel.<InitializeKeyCommands>b__19_9(Object index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 207
   at Flow.Launcher.ViewModel.RelayCommand.Execute(Object parameter) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\RelayCommand.cs:line 25
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by taooceros** [comment]
could you check this setting 
![image](https://user-images.githubusercontent.com/45326534/206520760-28c38bd2-2754-461d-b3ad-91289211729d.png)

**Comment by jjw24** [comment]
@taooceros if the Default File Manager is not set, shouldnt it use Windows Explorer by default?

**Comment by onesounds** [comment]
> @taooceros if the Default File Manager is not set to others, shouldnt it use Windows Explorer by default?

Does this mean that you want to open it with Explorer if the user incorrectly designates File Manager? in this case, This may be recognized to the user made the correct settings, but that Flow is opening the explorer incorrectly. A warning window that notifies that the settings are incorrect and initializes them is better.

**Comment by taooceros** [comment]
> @taooceros if the Default File Manager is not set to others, shouldnt it use Windows Explorer by default?

Should be
