### ISSUE TITLE
Windows Search service error

### ISSUE THREAD

**Issue by rammmma** [Flow-Launcher/Flow.Launcher#1628]
Flow Launcher version: 1.10.0
OS Version: Microsoft Windows NT 10.0.22622.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/13/2022 07:19:30
Exception:
Explorer Exception: 
Websites: https://github.com/Flow-Launcher/Flow.Launcher
Author: Jeremy Wu
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Retrieving the COM class factory for component with CLSID {7D096C5F-AC08-4F1F-BEB7-5C22C517CE39} failed due to the following error: 80070422 The service cannot be started, either because it is disabled or because it has no enabled devices associated with it. (0x80070422).
 ---> System.Runtime.InteropServices.COMException (0x80070422): Retrieving the COM class factory for component with CLSID {7D096C5F-AC08-4F1F-BEB7-5C22C517CE39} failed due to the following error: 80070422 The service cannot be started, either because it is disabled or because it has no enabled devices associated with it. (0x80070422).
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.QueryConstructor.CreateQueryHelper() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\QueryConstructor.cs:line 44
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.QueryConstructor.CreateBaseQuery() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\QueryConstructor.cs:line 24
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.QueryConstructor..ctor(Settings settings) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\QueryConstructor.cs:line 18
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndexSearchManager..ctor(Settings settings) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\WindowsIndexSearchManager.cs:line 20
   at Flow.Launcher.Plugin.Explorer.Settings.get_WindowsIndexSearchManager() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Settings.cs:line 63
   at Flow.Launcher.Plugin.Explorer.Settings.get_IndexProvider() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Settings.cs:line 71
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 91
   at Flow.Launcher.Plugin.Explorer.Main.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Main.cs:line 62
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass120_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 730
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 704
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
Hi there, is your Windows Search Service started? The error is suggesting it is unable to be started or disabled. You can switch to use Everything search engine also if the service is not available.

**Comment by jjw24** [comment]
@Flow-Launcher/team this error needs to be handled same as Explorer plugin did in 1.9.0.

**Comment by jjw24** [comment]
Please try this build and let me know if the issue is fixed https://ci.appveyor.com/api/buildjobs/u00is5g7sgpwb246/artifacts/Output%2FPackages%2FFlow-Launcher-Portable.zip

**Comment by rammmma** [comment]
> Please try this build and let me know if the issue is fixed 

Working very well. Everything ON, Windows index OFF
