### ISSUE TITLE
[Web Search Plugin] Encoding error makes unable to search

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#163]
**Describe the bug/issue**
I am unable to use the Web Search Plugin. By checking the log, it indicates that the customized encoding "GB2312" is not valid.

**Screenshots**
This is how it shows when try to search. The options disappear.
![image](https://user-images.githubusercontent.com/45326534/94015204-2516b180-fddf-11ea-9023-3a7ae502c808.png)

**Your System**
```
Windows build number: (run "ver" at a command prompt)
Flow Launcher version: (Settings => About) 
```
**Flow Launcher Error Log**

`2020-09-23 20:48:58.1752|ERROR|PluginManager.QueryForPlugin|-------------------------- Begin exception --------------------------
2020-09-23 20:48:58.1752|ERROR|PluginManager.QueryForPlugin|Exception for plugin <Web Searches> when query <g s>
2020-09-23 20:48:58.1752|ERROR|PluginManager.QueryForPlugin|Exception full name:
 <System.AggregateException>
2020-09-23 20:48:58.1752|ERROR|PluginManager.QueryForPlugin|Exception message:
 <One or more errors occurred. ('GB2312' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name'))>
2020-09-23 20:48:58.1752|ERROR|PluginManager.QueryForPlugin|Exception stack trace:
 <   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
   at Flow.Launcher.Plugin.WebSearch.Main.UpdateResultsFromSuggestion(List 1 results, String keyword, String subtitle, SearchSource searchSource, Query query) in C:\Workbench\Git\Flow.Launcher\Plugins\Flow.Launcher.Plugin.WebSearch\Main.cs:line 123
   at Flow.Launcher.Plugin.WebSearch.Main.Query(Query query) in C:\Workbench\Git\Flow.Launcher\Plugins\Flow.Launcher.Plugin.WebSearch\Main.cs:line 103
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<QueryForPlugin>b__0() in C:\Workbench\Git\Flow.Launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 163
   at Flow.Launcher.Infrastructure.Stopwatch.Debug(String message, Action action) in C:\Workbench\Git\Flow.Launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 16
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query) in C:\Workbench\Git\Flow.Launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 172>`

**Comment by taooceros** [comment]
This seems due to the issue that .net core doesn't support GB2312 encoding.

**Comment by jjw24** [comment]
Thanks for the PR, let me do some testing as well before approving.
