### ISSUE TITLE
Error Typing ANYTHING When Explorer Plugin Enabled- error due to windows index

### ISSUE THREAD

**Issue by medlir** [Flow-Launcher/Flow.Launcher#1630]
### Checks

- [x] I have checked that this issue has not already been reported.

### Problem Description

Trying to type any characters at all into Flow Launcher results in the error below after updating to 1.10.0, had no issues on previous versions.  Re-opening with my hotkey Ctrl+Space opens it with that character still typed, and typing another character results in the same error again.  Disabling the Explorer Plugin let's my WebSearch and other things work as expected.

Flow Launcher version: 1.10.0
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/13/2022 01:36:35
Exception:
Explorer Exception: 
Websites: https://github.com/Flow-Launcher/Flow.Launcher
Author: Jeremy Wu
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Invalid URI: The Authority/Host could not be parsed.
 ---> System.UriFormatException: Invalid URI: The Authority/Host could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndex.ExecuteWindowsIndexSearchAsync(String indexQueryString, String connectionString, CancellationToken token)+MoveNext() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\WindowsIndex.cs:line 56
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndex.ExecuteWindowsIndexSearchAsync(String indexQueryString, String connectionString, CancellationToken token)+MoveNext() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\WindowsIndex.cs:line 48
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndex.ExecuteWindowsIndexSearchAsync(String indexQueryString, String connectionString, CancellationToken token)+MoveNext() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\WindowsIndex.cs:line 48
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndex.ExecuteWindowsIndexSearchAsync(String indexQueryString, String connectionString, CancellationToken token)+MoveNext() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\WindowsIndex.cs:line 48
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndex.ExecuteWindowsIndexSearchAsync(String indexQueryString, String connectionString, CancellationToken token)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 102
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 102
   at Flow.Launcher.Plugin.Explorer.Main.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Main.cs:line 62
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass120_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 740
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 741
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

1. Launch Flow Launcher
2. Enable Explorer Plugin
3. Open Flow Launcher with hotkey
4. Try to type anything...

### Flow Launcher Version

v1.10.0

### Windows Build Number

10.0.19045.2311

### Error Log

[2022-12-13.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10215172/2022-12-13.txt)

**Comment by VictoriousRaptor** [comment]
@medlir @ralosant could you post the query that causes the error?

**Comment by ralosant** [comment]
For me, some examples are: es, we, lo, jk, sa, qw
I supose there are more examples but I just look for a few

**Comment by alexandremoratelli** [comment]
Hi there,

I found the same behaviour with Explorer plugin enabled (just the stacktrace is different) when I tryed to type anything (error happened on first letter). See the stacktrace and log attached.

**But, enabling the Explorer plugin and changing options "Index Search Engine", "Content Search Engine" and "Directory Recursive Search Engine" from value "Windows Index" to "Everything" (another search tool), Flow Launcher it is working fine.**

![image](https://user-images.githubusercontent.com/103728507/207463164-2e9258cb-13f3-4d7e-906f-fa2194e1baf8.png)

I have turned off Windows Search services a month and everything related a month ago (was using too much CPU and wasn't so good to justify that). So, based on observed behavior, looks like that issue is related to Windows Search service being down, off or something like this.

Cheers!

**Flow Launcher 1.10.0**

**Windows 11 Home
Version	22H2
Installed on	‎11/‎05/‎2022
OS build	22623.1028**


[stacktrace.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10222771/stacktrace.txt)

[2022-12-13 - Copy.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10222775/2022-12-13.-.Copy.txt)

**Comment by VictoriousRaptor** [comment]
> Hi there,
> 
> I found the same behaviour with Explorer plugin enabled (just the stacktrace is different) when I tryed to type anything (error happened on first letter). See the stacktrace and log attached.
> 
> **But, enabling the Explorer plugin and changing options "Index Search Engine", "Content Search Engine" and "Directory Recursive Search Engine" from value "Windows Index" to "Everything" (another search tool), Flow Launcher it is working fine.**
> 
> ![image](https://user-images.githubusercontent.com/103728507/207463164-2e9258cb-13f3-4d7e-906f-fa2194e1baf8.png)
> 
> I have turned off Windows Search services a month and everything related a month ago (was using too much CPU and wasn't so good to justify that). So, based on observed behavior, looks like that issue is related to Windows Search service being down, off or something like this.
> 
> Cheers!
> 
> **Flow Launcher 1.10.0**
> 
> **Windows 11 Home Version 22H2 Installed on ‎11/‎05/‎2022 OS build 22623.1028**
> 
> [stacktrace.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10222771/stacktrace.txt)
> 
> [2022-12-13 - Copy.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10222775/2022-12-13.-.Copy.txt)

Seems like your issue is related to #1628 , which is a bit different.

**Comment by enoversum** [comment]
Literally came here to report the same. Re-building the search index unfortunately yields no improvements. The people able to type more than one character are just quick typers, as soon as one character has been entered, the Explorer plugin crashes.

**Comment by medlir** [comment]
Rebuilding my index did resolve it for me as well.  My index contains only ~89K entries now instead of ~156K before the delete and reindex, so either there was cruft in there, or just data it didn't like that's just not currently in there.  Googling the error itself seems to imply in other cases it occured due to paths that were too long, especially when going above 260 characters, which makes me wonder if there was just data there it didn't like... still seems odd it only became a problem with the update, but happier for me at the moment.

**Comment by FadeMind** [comment]
Hi, In 1.10.0 search typing enviroments variables does reply nothing usefull. 
Sample
```
%appdata%
%tmp%
```
etc.

**Comment by taooceros** [comment]
> Hi, In 1.10.0 search typing enviroments variables does reply nothing usefull. Sample
> 
> ```
> %appdata%
> %tmp%
> ```
> 
> etc. 1.9.5 works great.

I notice that as well. Would like to share a fix in the recent few days

**Comment by jjw24** [comment]
> Flow Launcher version: 1.10.0 #1646

Could you please share the error message.

**Comment by ralosant** [comment]
After a couple of days, the same behavior appears again. It is not a global crash because some queries work, it returned to the previously reported behavior.

**Comment by jjw24** [comment]
Is the error in the log exactly the same? 

I am still unable to reproduce.

Does a rebuild of the index again fixes the problem?

**Comment by taooceros** [comment]
> Hi, In 1.10.0 search typing enviroments variables does reply nothing usefull. Sample
> 
> ```
> %appdata%
> %tmp%
> ```
> 
> etc. 1.9.5 works great.

It will be addressed soon
