### ISSUE TITLE
Flow closes immediatly after start typting.

### ISSUE THREAD

**Issue by fnfontana** [Flow-Launcher/Flow.Launcher#1636]
### **Note:** It starts to happen immediatly after update to version `1.10.0`

---

Flow Launcher version: 1.10.0
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/13/2022 09:55:05
Exception:
Explorer Exception: 
Websites: https://github.com/Flow-Launcher/Flow.Launcher
Author: Jeremy Wu
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Retrieving the COM class factory for component with CLSID {7D096C5F-AC08-4F1F-BEB7-5C22C517CE39} failed due to the following error: 80070422 O serviço não pode ser iniciado porque está desativado ou não tem dispositivos ativados associados. (0x80070422).
 ---> System.Runtime.InteropServices.COMException (0x80070422): Retrieving the COM class factory for component with CLSID {7D096C5F-AC08-4F1F-BEB7-5C22C517CE39} failed due to the following error: 80070422 O serviço não pode ser iniciado porque está desativado ou não tem dispositivos ativados associados. (0x80070422).
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.QueryConstructor.CreateQueryHelper() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\QueryConstructor.cs:line 44
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.QueryConstructor.CreateBaseQuery() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\QueryConstructor.cs:line 24
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.QueryConstructor..ctor(Settings settings) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\QueryConstructor.cs:line 18
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndexSearchManager..ctor(Settings settings) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\WindowsIndexSearchManager.cs:line 20
   at Flow.Launcher.Plugin.Explorer.Settings.get_WindowsIndexSearchManager() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Settings.cs:line 63
   at Flow.Launcher.Plugin.Explorer.Settings.get_IndexProvider() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Settings.cs:line 71
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 91
   at Flow.Launcher.Plugin.Explorer.Main.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Main.cs:line 62
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass120_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 730
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 704
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by taooceros** [comment]
Seems like this is because the Windows index service is not enabled. As a wordaround may you disable the index search option in explorer plugin?

**Comment by fnfontana** [comment]
> Seems like this is because the Windows index service is not enabled. As a wordaround may you disable the index search option in explorer plugin?

I have disabled the Windows search index on my PC, after I re-enable it, Flow this error message stops to appear. But what I find curious is that the search index was disabled for a month or so, and the previous version of Flow used to work flawlessly.

**Comment by jjw24** [comment]
Related to https://github.com/Flow-Launcher/Flow.Launcher/issues/1628

Closing this issue, please follow issue 1628 for updates.
