### ISSUE TITLE
crash flow launcher version:1.10.0

### ISSUE THREAD

**Issue by 9blau** [Flow-Launcher/Flow.Launcher#1649]
Flow Launcher version: 1.10.0
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/14/2022 17:59:07
Exception:
Explorador Exception: 
Websites: https://github.com/Flow-Launcher/Flow.Launcher
Author: Jeremy Wu
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Retrieving the COM class factory for component with CLSID {7D096C5F-AC08-4F1F-BEB7-5C22C517CE39} failed due to the following error: 80070422 No se puede iniciar el servicio, porque está deshabilitado o porque no tiene dispositivos habilitados asociados a él. (0x80070422).
 ---> System.Runtime.InteropServices.COMException (0x80070422): Retrieving the COM class factory for component with CLSID {7D096C5F-AC08-4F1F-BEB7-5C22C517CE39} failed due to the following error: 80070422 No se puede iniciar el servicio, porque está deshabilitado o porque no tiene dispositivos habilitados asociados a él. (0x80070422).
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.QueryConstructor.CreateQueryHelper() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\QueryConstructor.cs:line 44
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.QueryConstructor.CreateBaseQuery() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\QueryConstructor.cs:line 24
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.QueryConstructor..ctor(Settings settings) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\QueryConstructor.cs:line 18
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndexSearchManager..ctor(Settings settings) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\WindowsIndexSearchManager.cs:line 20
   at Flow.Launcher.Plugin.Explorer.Settings.get_WindowsIndexSearchManager() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Settings.cs:line 63
   at Flow.Launcher.Plugin.Explorer.Settings.get_IndexProvider() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Settings.cs:line 71
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 91
   at Flow.Launcher.Plugin.Explorer.Main.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Main.cs:line 62
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass120_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 730
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 704
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2022-12-14.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10230044/2022-12-14.txt)

**Comment by jjw24** [comment]
Relates to https://github.com/Flow-Launcher/Flow.Launcher/issues/1628, could you check if your Windows Search service is running. Explorer needs it to run searches, otherwise please switch to Everything search engine.

Will be rolling out a fix for managing this error.

**Comment by 9blau** [comment]
Hi ijw24,
The service was off. I'm changed that parameter and it's working. Thanks.
