### ISSUE TITLE
sudden error

### ISSUE THREAD

**Issue by GrandSireSmrgol** [Flow-Launcher/Flow.Launcher#1650]
Flow Launcher version: 1.10.0
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/14/2022 12:36:17
Exception:
Explorer Exception: 
Websites: https://github.com/Flow-Launcher/Flow.Launcher
Author: Jeremy Wu
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Invalid URI: The Authority/Host could not be parsed.
 ---> System.UriFormatException: Invalid URI: The Authority/Host could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndex.ExecuteWindowsIndexSearchAsync(String indexQueryString, String connectionString, CancellationToken token)+MoveNext() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\WindowsIndex.cs:line 56
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndex.ExecuteWindowsIndexSearchAsync(String indexQueryString, String connectionString, CancellationToken token)+MoveNext() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\WindowsIndex.cs:line 48
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndex.ExecuteWindowsIndexSearchAsync(String indexQueryString, String connectionString, CancellationToken token)+MoveNext() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\WindowsIndex.cs:line 48
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndex.ExecuteWindowsIndexSearchAsync(String indexQueryString, String connectionString, CancellationToken token)+MoveNext() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\WindowsIndex.cs:line 48
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndex.ExecuteWindowsIndexSearchAsync(String indexQueryString, String connectionString, CancellationToken token)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 102
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 102
   at Flow.Launcher.Plugin.Explorer.Main.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Main.cs:line 62
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass120_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 730
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 704
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
Please check if Windows Search service is running. And if it's running, please try to rebuild index (Open Windows Index option -> advanced -> rebuild index).

Related to #1630, closing.
