### ISSUE TITLE
Crash in Flow Launcher 1.10

### ISSUE THREAD

**Issue by atoooms** [Flow-Launcher/Flow.Launcher#1654]
log file:
[2022-12-15.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10234005/2022-12-15.txt)

exception message:
```
Flow Launcher version: 1.9.5
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/15/2022 13:28:11
Exception:
文件管理器 Exception: 
Websites: https://github.com/Flow-Launcher/Flow.Launcher
Author: Jeremy Wu
Version: 1.11.2
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: RPC 服务器不可用。 (0x800706BA)
 ---> System.Runtime.InteropServices.COMException (0x800706BA): RPC 服务器不可用。 (0x800706BA)
   at Microsoft.Search.Interop.CSearchQueryHelperClass.get_ConnectionString()
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndexSearchManager.WindowsIndexFilesAndFoldersSearchAsync(ReadOnlySpan`1 querySearchString, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\WindowsIndexSearchManager.cs:line 41
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndexSearchManager.SearchAsync(String search, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\WindowsIndexSearchManager.cs:line 62
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 91
   at Flow.Launcher.Plugin.Explorer.Main.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Main.cs:line 62
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass120_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 732
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 696
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by Garulf** [comment]
Related: https://github.com/Flow-Launcher/Flow.Launcher/issues/1654

**Comment by jjw24** [comment]
This is related to #1628 not 1630.

**Comment by jjw24** [comment]
@atoooms please try this build and let me know if the issue is fixed https://ci.appveyor.com/api/buildjobs/u00is5g7sgpwb246/artifacts/Output%2FPackages%2FFlow-Launcher-Portable.zip
