### ISSUE TITLE
ERROR - PLEASE HELP

### ISSUE THREAD

**Issue by danholman** [Flow-Launcher/Flow.Launcher#1663]
Flow Launcher version: 1.10.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/17/2022 04:57:59
Exception:
Explorer Exception: 
Websites: https://github.com/Flow-Launcher/Flow.Launcher
Author: Jeremy Wu
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: The RPC server is unavailable. (0x800706BA)
 ---> System.Runtime.InteropServices.COMException (0x800706BA): The RPC server is unavailable. (0x800706BA)
   at Microsoft.Search.Interop.CSearchQueryHelperClass.get_ConnectionString()
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndexSearchManager.WindowsIndexFilesAndFoldersSearchAsync(ReadOnlySpan`1 querySearchString, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\WindowsIndexSearchManager.cs:line 41
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndexSearchManager.SearchAsync(String search, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\WindowsIndexSearchManager.cs:line 62
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 91
   at Flow.Launcher.Plugin.Explorer.Main.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Main.cs:line 62
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass120_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 740
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 704
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
Same as https://github.com/Flow-Launcher/Flow.Launcher/issues/1628

This is happening because your Windows Search service is not running or disabled.

**Comment by jjw24** [comment]
Please try this build with a temporary fix  https://ci.appveyor.com/api/buildjobs/u00is5g7sgpwb246/artifacts/Output%2FPackages%2FFlow-Launcher-Portable.zip

We will roll out a proper fix soon

**Comment by SebasF1349** [comment]
I'm having the same crash:

```
Flow Launcher version: 1.10.0
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/16/2022 22:20:56
Exception:
Explorer Exception: 
Websites: https://github.com/Flow-Launcher/Flow.Launcher
Author: Jeremy Wu
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: El servidor RPC no está disponible. (0x800706BA)
 ---> System.Runtime.InteropServices.COMException (0x800706BA): El servidor RPC no está disponible. (0x800706BA)
   at Microsoft.Search.Interop.CSearchQueryHelperClass.get_ConnectionString()
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndexSearchManager.WindowsIndexFilesAndFoldersSearchAsync(ReadOnlySpan`1 querySearchString, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\WindowsIndexSearchManager.cs:line 41
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndexSearchManager.SearchAsync(String search, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\WindowsIndexSearchManager.cs:line 62
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 91
   at Flow.Launcher.Plugin.Explorer.Main.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Main.cs:line 62
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass120_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 740
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 741
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

I had the same crash 2/3 days before but didn't report as I saw a lot of messages already. I recreated the index and it stop crashing, but today started to do the same.

Tested the build attached in the previous message (just unzipped and run the updater), but I have the same crash.

Also, the Windows Search service is running:
![mmc_DTLjAEtgjx](https://user-images.githubusercontent.com/33849340/208216353-1ea6f492-148e-4265-9a57-2d3040f6a07f.png)

As other commented, changing the explorer plugin to use Everything make it work.
