### ISSUE TITLE
C:\Users\Home PC\AppData\Roaming\FlowLauncher\Logs\1.10.0\2022-12-17.txt

### ISSUE THREAD

**Issue by ahsanragtag93** [Flow-Launcher/Flow.Launcher#1664]
Flow Launcher version: 1.10.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/17/2022 07:40:35
Exception:
System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard Failed (0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.ComTypes.IDataObject.GetData(FORMATETC& format, STGMEDIUM& medium)
   at System.Windows.DataObject.OleConverter.GetDataFromOleHGLOBAL(String format, DVASPECT aspect, Int32 index)
   at System.Windows.DataObject.OleConverter.GetDataFromBoundOleDataObject(String format, DVASPECT aspect, Int32 index)
   at System.Windows.DataObject.OleConverter.GetData(String format, Boolean autoConvert, DVASPECT aspect, Int32 index)
   at System.Windows.DataObject.OleConverter.GetData(String format, Boolean autoConvert)
   at System.Windows.Clipboard.GetText(TextDataFormat format)
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass121_0.<ConstructQuery>b__0() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 767
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Flow.Launcher.ViewModel.MainViewModel.ConstructQuery(String queryText, IEnumerable`1 customShortcuts, IEnumerable`1 builtInShortcuts) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 763
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 741
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ahsanragtag93** [comment]
Flow launcher keeps showing me this error message after typing a few letters now and then. Please help!

**Comment by ahsanragtag93** [comment]
![image](https://user-images.githubusercontent.com/109924231/208217629-e2b6613b-7604-4bd7-a10e-2f46cc257c54.png)

**Comment by jjw24** [comment]
@ahsanragtag93 is this error fixed for you?
