### ISSUE TITLE
Flow Launcher error

### ISSUE THREAD

**Issue by swingwolf** [Flow-Launcher/Flow.Launcher#1696]
Flow Launcher version: 1.10.1
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/21/2022 08:18:13
Exception:
System.UnauthorizedAccessException: Access to the path 'C:\Program Files\[LOBOBLANCO\Bureau\FlowLauncher\app-1.10.1\UserData\Cache\Image.cache' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Flow.Launcher.Infrastructure.Storage.BinaryStorage`1.TryLoad(T defaultData) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Storage\BinaryStorage.cs:line 42
   at Flow.Launcher.Infrastructure.Image.ImageLoader.LoadStorageToConcurrentDictionary() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Image\ImageLoader.cs:line 81
   at Flow.Launcher.Infrastructure.Image.ImageLoader.Initialize() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Image\ImageLoader.cs:line 41
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 59
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 50
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
Hi, where is your flow launcher located? Error is indicating access permission to that location, perhaps move it to a different location or give the right access.

**Comment by swingwolf** [comment]
OK, Thank you.
