### ISSUE TITLE
My Notion Search Plugin

### ISSUE THREAD

**Issue by danielduckworth** [Flow-Launcher/Flow.Launcher#1735]
Hi all, I've seen a bunch of issues raised recently about the Notion Search plugin crashing.

Has something changed with the core Flow Launcher library I need to adapt the plugin for?

Here is a recent error log.

```bash
Please open new issue in: https://github.com/danielduckworth/Flow.Launcher.Plugin.NotionSearch/issues/new
1. upload log file: C:\Users\ezbie\AppData\Roaming\FlowLauncher\Logs\1.10.1\2022-12-23.txt
2. copy below exception message

Flow Launcher version: 1.10.1
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/23/2022 14:22:23
Exception:
Notion Search Exception: 
Websites: https://github.com/danielduckworth/Flow.Launcher.Plugin.NotionSearch
Author: Duckworth
Version: 0.1.5
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: INFO:root:Integration token found.
INFO:notional.session:Initialized Notion SDK client
INFO:notional.session:Retrieving current integration bot
INFO:root:API token is valid.
INFO:root:Processing results.

 ---> System.IO.InvalidDataException: INFO:root:Integration token found.
INFO:notional.session:Initialized Notion SDK client
INFO:notional.session:Retrieving current integration bot
INFO:root:API token is valid.
INFO:root:Processing results.

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 290
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 295
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 310
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass120_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 730
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 704
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

I'm not too familiar with the core library, so it would be useful to know if I need to redevelop the plugin or look into the `notional` SDK dependency which might have had a breaking change also.

Thanks!

**Comment by jjw24** [comment]
Hi there, we haven't introduced any breaking changes. I can't tell from the tracestack where the error is, can you confirm token usage with the API is correct?

How do I reproduce this error with the plugin, will give it a test when I am Infront of comp.

**Comment by danielduckworth** [comment]
> 

The error log came from a user report so I'm not sure how to reproduce that specific error. However, the plugin app crashes within a few seconds after being activated.

For the following error log the steps are:

1. Activvate flowlauncher with hot key
2. Enter assigned key for notion search (n for me).
3. Enter text
4. Crash

Note that it will also crash if no text is entered.

```bash
Please open new issue in: https://github.com/danielduckworth/Flow.Launcher.Plugin.NotionSearch/issues/new
1. upload log file: C:\Users\Daniel Duckworth\scoop\apps\flow-launcher\current\app-1.11.0\UserData\Logs\1.11.0\2023-01-05.txt
2. copy below exception message

Flow Launcher version: 1.11.0
OS Version: Microsoft Windows NT 10.0.22623.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\Daniel Duckworth\scoop\apps\flow-launcher\current\app-1.11.0\UserData\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 01/05/2023 21:37:07
Exception:
Notion Search Exception: 
Websites: https://github.com/danielduckworth/Flow.Launcher.Plugin.NotionSearch
Author: Duckworth
Version: 0.1.5
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: INFO:root:Integration token found.
INFO:notional.session:Initialized Notion SDK client
INFO:notional.session:Retrieving current integration bot
INFO:root:API token is valid.
INFO:root:Processing results.

 ---> System.IO.InvalidDataException: INFO:root:Integration token found.
INFO:notional.session:Initialized Notion SDK client
INFO:notional.session:Retrieving current integration bot
INFO:root:API token is valid.
INFO:root:Processing results.

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 292
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 307
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 811
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 785
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by taooceros** [comment]
I will give it a test. I can reproduce

**Comment by taooceros** [comment]
@danielduckworth this is the error I have encountered. Would you please take a look?

![image](https://user-images.githubusercontent.com/45326534/211126423-de8a9a6d-bf0b-4b2e-94c1-f8906b58fcf2.png)

**Comment by danielduckworth** [comment]
@taooceros Looks like it the Python sdk for Notion might be querying a property (`Status`) that doesn't exist.

**Comment by danielduckworth** [comment]
@jjw24 I've done some bug fixing, hopefully the issue is solved now. Will the manifest update automatically or is there something more I need to do for the updated version to be included?

**Comment by jjw24** [comment]
Hi @danielduckworth, if you have published a new release the manifest will be updated.

Closing this for now, feel free to reopen if further discussion is required :)
