### ISSUE TITLE
flow launcher got an error

### ISSUE THREAD

**Issue by GhostGamr** [Flow-Launcher/Flow.Launcher#1755]
[2023-01-01.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10328438/2023-01-01.txt)

Exception msg:

Flow Launcher version: 1.11.0
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\Rishu Mishra.DESKTOP-7S0PFJC\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 01/01/2023 12:16:17
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Flow.Launcher.MainWindow.VerticalCenter() in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 540
   at Flow.Launcher.MainWindow.InitializePosition() in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 212
   at Flow.Launcher.MainWindow.UpdatePosition() in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 499
   at Flow.Launcher.MainWindow.HideStartup() in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 515
   at Flow.Launcher.MainWindow.OnLoaded(Object sender, RoutedEventArgs _) in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 93
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by z1nc0r3** [comment]
> System.NotSupportedException: 'Alt+LeftAlt' key and modifier combination is not supported for KeyGesture.

It may be an issue with the shortcut key combination.
Can you launch FL using ALT + SPACE or did you change the shortcut key? Can you share some information on how this error occurred?

**Comment by GhostGamr** [comment]
i got this error during startup
and no i cant launch FL using alt + space (that was my shortcut)

**Comment by VictoriousRaptor** [comment]
> > System.NotSupportedException: 'Alt+LeftAlt' key and modifier combination is not supported for KeyGesture.
> 
> It may be an issue with the shortcut key combination. Can you launch FL using ALT + SPACE or did you change the shortcut key? Can you share some information on how this error occurred?

That's from the preview hotkey. @GhostGamr please navigate to your settings folder, find `Settings.json` and delete the line containing `"PreviewHotkey"`. That should fix the problem.
