### ISSUE TITLE
Please help me 出bug了救命

### ISSUE THREAD

**Issue by Ethan-Crisp** [Flow-Launcher/Flow.Launcher#1782]
[2023-01-12.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10394583/2023-01-12.txt)
Flow Launcher version: 1.11.0
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: E:\Python\pythonw.exe
Node Path: 
Date: 01/12/2023 01:21:22
Exception:
System.Net.WebException: An exception occurred during a WebClient request.
 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebClient.DownloadBitsAsync(WebRequest request, Stream writeStream, AsyncOperation asyncOp, Action`3 completionDelegate)
   --- End of inner exception stack trace ---
   at Dictionary.DictDownloadManager.PerformDownload() in C:\Users\Null\Documents\Projects\Flow.Launcher.Dictionary\src\DictDownloadManager.cs:line 62
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Ethan-Crisp** [comment]
命令行安装完dictionary之后，让我输入enter自动下载，结果就出错了

**Comment by VictoriousRaptor** [comment]
建议检查一下代理配置。

Suggest checking your proxy settings.

**Comment by Ethan-Crisp** [comment]
如果不开代理，下载会很慢，并且很多插件会显示下载失败



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月12日(星期四) 凌晨1:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Flow-Launcher/Flow.Launcher] Please help me 出bug了救命 (Issue #1782)





 
建议检查一下代理配置。
 
Suggest checking your proxy settings.

**Comment by Ethan-Crisp** [comment]
自行解决了

**Comment by taooceros** [comment]
感觉问题是fastgit那边坏了。。。但比较奇怪的是开了代理之后不应该会从镜像下载
