### ISSUE TITLE
这次没有使用代理，软件商店安装完之后输入d再回车下载

### ISSUE THREAD

**Issue by Ethan-Crisp** [Flow-Launcher/Flow.Launcher#1783]
[2023-01-12.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10397481/2023-01-12.txt)
Flow Launcher version: 1.11.0
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 01/12/2023 09:57:01
Exception:
System.Net.WebException: An exception occurred during a WebClient request.
 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebClient.DownloadBitsAsync(WebRequest request, Stream writeStream, AsyncOperation asyncOp, Action`3 completionDelegate)
   --- End of inner exception stack trace ---
   at Dictionary.DictDownloadManager.PerformDownload() in C:\Users\Null\Documents\Projects\Flow.Launcher.Dictionary\src\DictDownloadManager.cs:line 62
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by taooceros** [comment]
就在那个issue里讨论吧

**Comment by Ethan-Crisp** [comment]
目前已经解决，解决方式：将之前wox的ecdivct.db复制到flow dictionary的插件目录下，并且改名即可
![image](https://user-images.githubusercontent.com/44205688/212001317-965a3ae6-158b-433f-a535-808dcdbbc5bf.png)
![企业微信截图_16734927645033](https://user-images.githubusercontent.com/44205688/212001467-7b239045-0a1b-40b3-aba4-793c14d6adaf.png)
