### ISSUE TITLE
error: Flow Launcher got an error

### ISSUE THREAD

**Issue by hariom2002** [Flow-Launcher/Flow.Launcher#1793]
Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues/new

1. upload log file: C:\Users\Hariom\AppData\Roaming\FlowLauncher\Logs\1.11.0\2023-01-14.txt
2. copy below exception message

Flow Launcher version: 1.11.0
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 01/14/2023 00:53:19
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Flow.Launcher.MainWindow.VerticalCenter() in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 540
   at Flow.Launcher.MainWindow.InitializePosition() in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 212
   at Flow.Launcher.MainWindow.UpdatePosition() in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 499
   at Flow.Launcher.MainWindow.HideStartup() in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 515
   at Flow.Launcher.MainWindow.OnLoaded(Object sender, RoutedEventArgs _) in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 93
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
Hi there, what were you trying to do that resulted in this error?
