### ISSUE TITLE
thread must be STA error

### ISSUE THREAD

**Issue by Mae72DE** [Flow-Launcher/Flow.Launcher#1794]
Flow Launcher version: 1.11.0
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
IntPtr Length: 8
x64: True

Python Path: C:\Users\Mae\AppData\Local\Programs\Python\Python38\pythonw.exe
Node Path: 
Date: 01/14/2023 08:01:26
Exception:
System.InvalidOperationException: The calling thread must be STA, because many UI components require this.
   at System.Windows.Input.InputManager..ctor()
   at System.Windows.Input.InputManager.GetCurrentInputManagerImpl()
   at System.Windows.Input.KeyboardNavigation..ctor()
   at System.Windows.FrameworkElement.FrameworkServices..ctor()
   at System.Windows.FrameworkElement.EnsureFrameworkServices()
   at System.Windows.FrameworkElement..ctor()
   at System.Windows.Controls.Control..ctor()
   at System.Windows.Window..ctor()
   at Flow.Launcher.Msg..ctor() in C:\projects\flow-launcher\Flow.Launcher\Msg.xaml.cs:line 19
   at Flow.Launcher.Notification.LegacyShow(String title, String subTitle, String iconPath) in C:\projects\flow-launcher\Flow.Launcher\Notification.cs:line 44
   at Flow.Launcher.Notification.Show(String title, String subTitle, String iconPath) in C:\projects\flow-launcher\Flow.Launcher\Notification.cs:line 26
   at Flow.Launcher.ViewModel.MainViewModel.ReloadPluginDataAsync() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 190
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2023-01-14.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10416828/2023-01-14.txt)

**Comment by jjw24** [comment]
Hi there, what were you doing that resulted in this error?

**Comment by Mae72DE** [comment]
Sorry, don't remember. Tried to replace Keypirinha, to use more Open-Source-Software. But don't find the Key to open the Path of the Link. So I tried very much to find that Function.
Now I'm back to Keypirinha and Everything and my very old Computer is much faster again …
Flow.Launcher slows down my machine very much.

**Comment by jjw24** [comment]
Closing, please reopen if issue persists.
