### ISSUE TITLE
Error when trying to disable a startup program

### ISSUE THREAD

**Issue by TheBestPessimist** [Flow-Launcher/Flow.Launcher#1798]
Log
[2023-01-14.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10417455/2023-01-14.txt)

Exception message:
```
Flow Launcher version: 1.11.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: D:\all\all\Python\Python 3.11.1\pythonw.exe
Node Path: 
Date: 01/14/2023 15:45:26
Exception:
System.IO.InvalidDataException: Traceback (most recent call last):
  File "D:\all\all\FlowLauncher\app-1.11.0\UserData\Plugins\Windows Startup-1.0.2\run.py", line 12, in <module>
    WindowsStartup()
  File "D:\all\all\FlowLauncher\app-1.11.0\UserData\Plugins\Windows Startup-1.0.2\lib\flox\flox.py", line 104, in __init__
    super().__init__()
  File "D:\all\all\FlowLauncher\app-1.11.0\UserData\Plugins\Windows Startup-1.0.2\lib\flox\launcher.py", line 28, in __init__
    results = request_method(*request_parameters)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\all\all\FlowLauncher\app-1.11.0\UserData\Plugins\Windows Startup-1.0.2\plugin\windows_startup.py", line 86, in toggle
    self.change_program(prog, prog.toggle)
  File "D:\all\all\FlowLauncher\app-1.11.0\UserData\Plugins\Windows Startup-1.0.2\plugin\windows_startup.py", line 65, in change_program
    method()
  File "D:\all\all\FlowLauncher\app-1.11.0\UserData\Plugins\Windows Startup-1.0.2\plugin\startup.py", line 112, in toggle
    self.disable()
  File "D:\all\all\FlowLauncher\app-1.11.0\UserData\Plugins\Windows Startup-1.0.2\plugin\startup.py", line 107, in disable
    self._set_registry_value(self._base_key, self._reg_path, self.name, DISABLED)
  File "D:\all\all\FlowLauncher\app-1.11.0\UserData\Plugins\Windows Startup-1.0.2\plugin\startup.py", line 62, in _set_registry_value
    with reg.OpenKey(base_key, path, 0, reg.KEY_ALL_ACCESS) as key_root:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 292
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.<>c__DisplayClass19_0.<<ParseResults>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 139
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 276
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by jjw24** [comment]
Hi there, are you running flow with Administrator privileges? I imagine this plugin would need that for its operations.

**Comment by TheBestPessimist** [comment]
Not running as admin. However if Admin rights are needed for this, could the plugin ask me via the normal "allow this program to make changes to your computer"?

**Comment by jjw24** [comment]
This would probably need to be implemented by the plugin @Garulf

**Comment by TheBestPessimist** [comment]
no
