### ISSUE TITLE
error launching Flow-Launcher portable

### ISSUE THREAD

**Issue by GiorgioGithub** [Flow-Launcher/Flow.Launcher#1801]
Flow Launcher version: 1.11.0
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: 
[2023-01-15.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10419642/2023-01-15.txt)

Node Path: 
Date: 01/15/2023 08:15:45
Exception:
System.IO.IOException: Parametro non corretto. : 'D:\Flow-Launcher-Portable\FlowLauncher\app-1.11.0\Plugins'
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Flow.Launcher.Core.Plugin.PluginConfig.Parse(String[] pluginDirectories) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginConfig.cs:line 26
   at Flow.Launcher.Core.Plugin.PluginManager.LoadPlugins(PluginsSettings settings) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 103
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 72
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 51
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
Hi is this still happening? What were you trying to do that resulting in this error?

**Comment by GiorgioGithub** [comment]
The problem has been solved.
Thanks
Regards
Giorgio
Da: Jeremy Wu ***@***.***>
Inviato: domenica 15 gennaio 2023 21:39
A: Flow-Launcher/Flow.Launcher ***@***.***>
Cc: PRINA Giorgio ***@***.***>; Author ***@***.***>
Oggetto: Re: [Flow-Launcher/Flow.Launcher] error launching Flow-Launcher portable (Issue #1801)

Non si ricevono spesso messaggi di posta elettronica da ***@***.******@***.***>. Informazioni sul perché è importante<https://aka.ms/LearnAboutSenderIdentification>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hi is this still happening? What were you trying to do that resulting in this error?

-
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FFlow-Launcher%2FFlow.Launcher%2Fissues%2F1801%23issuecomment-1383246233&data=05%7C01%7Cgiorgio.prina%40biomerieux.com%7C9999bc4f4b924166110208daf73885d8%7Caec0543acc734fa49e2acf52adf9b788%7C0%7C0%7C638094119435392006%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EyP061tAZpMxeRWm6RUOKEzSCV0106PCGC0%2B%2BHz9%2B0k%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIY4GZGTO7D2YPSUHF5AAM3WSRN57ANCNFSM6AAAAAAT3WV3EQ&data=05%7C01%7Cgiorgio.prina%40biomerieux.com%7C9999bc4f4b924166110208daf73885d8%7Caec0543acc734fa49e2acf52adf9b788%7C0%7C0%7C638094119435392006%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=H6a6qC0lBa1ymvxmeTVXlHKmNM7VqwE%2FCF5rwir0N6I%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

AVIS : Ce courrier et ses pieces jointes sont destines a leur seul destinataire et peuvent contenir des informations confidentielles appartenant a bioMerieux. Si vous n'etes pas destinataire, vous etes informe que toute lecture, divulgation, ou reproduction de ce message et des pieces jointes est strictement interdite. Si vous avez recu ce message par erreur merci d'en prevenir l'expediteur et de le detruire, ainsi que ses pieces jointes. NOTICE: This message and attachments are intended only for the use of their addressee and may contain confidential information belonging to bioMerieux. If you are not the intended recipient, you are hereby notified that any reading, dissemination, distribution, or copying of this message, or any attachment, is strictly prohibited. If you have received this message in error, please notify the original sender immediately and delete this message, along with any attachments.
