### ISSUE TITLE
Cant Launch Flow Launcher after first restart of pc

### ISSUE THREAD

**Issue by xcrashdayx** [Flow-Launcher/Flow.Launcher#1823]
Welp i got super excited after i found this awesome tool. after the first restart it just crashed on me.
And as it asked me so nicely to upload a new issue...

[2023-01-20.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10464795/2023-01-20.txt)

Flow Launcher version: 1.11.0
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 01/20/2023 10:06:42
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Flow.Launcher.MainWindow.VerticalCenter() in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 540
   at Flow.Launcher.MainWindow.InitializePosition() in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 212
   at Flow.Launcher.MainWindow.UpdatePosition() in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 499
   at Flow.Launcher.MainWindow.HideStartup() in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 515
   at Flow.Launcher.MainWindow.OnLoaded(Object sender, RoutedEventArgs _) in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 93
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by xcrashdayx** [comment]
I cant even get it so start after a restart and reinstall, something is still in cache somewhere

**Comment by z1nc0r3** [comment]
Can you provide a fresh log file? 
Go to `C:\Users\[username]\AppData\Roaming\FlowLauncher\Logs\1.11.0` and rename `2023-01-20.txt` this file and try to start FL. It'll create a new log file.

**Comment by xcrashdayx** [comment]
[2023-01-20.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10466223/2023-01-20.txt)
new logfile after rename of the old one

**Comment by z1nc0r3** [comment]
Could be the same issue #1755

**Comment by xcrashdayx** [comment]
deleting "PreviewHotkey" in %APPDATA%\\FlowLauncher\Settings\Settings.json fixed the problem.
