### ISSUE TITLE
crash - Droplex access denied when installing Everything

### ISSUE THREAD

**Issue by NolanNolan** [Flow-Launcher/Flow.Launcher#1827]
Flow Launcher version: 1.11.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\JBM\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 01/21/2023 21:00:52
Exception:
System.IO.IOException: The process cannot access the file 'C:\Users\JBM\AppData\Local\Temp\Droplex\Everything1_4_1_1009' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Droplex.Downloader.Get(String url, String filePath)
   at Droplex.DroplexPackage.Drop(App app, String zipExtractPath)
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingDownloadHelper.PromptDownloadIfNotInstallAsync(String installedLocation, IPublicAPI api) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingDownloadHelper.cs:line 47
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingSearchManager.ClickToInstallEverythingAsync(ActionContext _) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingSearchManager.cs:line 48
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 276
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
[2023-01-21.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10472925/2023-01-21.txt)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by z1nc0r3** [comment]
Can you please provide the steps to reproduce if possible?

**Comment by NolanNolan** [comment]
Hi

It basically just crash after a while og use, but no other app does crash – only Flow Launcher, with this description:

Beskrivelse
A problem caused this program to stop interacting with Windows.
Sti for fejlbehæftet program:            C:\Users\FamilienBue\AppData\Local\FlowLauncher\app-1.11.0\Flow.Launcher.exe

Problemsignatur
Problemhændelsesnavn:                      AppHangB1
Application Name:                               Flow.Launcher.exe
Application Version:                             1.11.0.0
Application Timestamp:                       63558578
Hang Signature:                                   0000
Hang Type:                                          0
OS-version:                                          10.0.22621.2.0.0.256.48
Landestandard-id:                                1030
Additional Hang Signature 1:              00000000000000000000000000000000
Additional Hang Signature 2:              0000
Additional Hang Signature 3:              00000000000000000000000000000000
Additional Hang Signature 4:              0000
Additional Hang Signature 5:              00000000000000000000000000000000
Additional Hang Signature 6:              0000
Additional Hang Signature 7:              00000000000000000000000000000000

Ekstra oplysninger om problemet
Filsæt-id:                                              45e93f3d4c7468076cbc2c12ff88005f (2070578388791722079)



Hilsen Jørn

Fra: Lasith Manujitha ***@***.***>
Sendt: 23. januar 2023 08:20
Til: Flow-Launcher/Flow.Launcher ***@***.***>
Cc: Jørn Bue Madsen ***@***.***>; Author ***@***.***>
Emne: Re: [Flow-Launcher/Flow.Launcher] crash - app requested to upload log (Issue #1827)


Can you please provide the steps to reproduce if possible?

**Comment by jjw24** [comment]
This seems to be the same issue as #1792?

**Comment by jjw24** [comment]
This is the error:
`System.IO.IOException: The process cannot access the file 'C:\Users\JBM\AppData\Local\Temp\Droplex\Everything1_4_1_1009' because it is being used by another process.`

Can you remove this folder please C:\Users\JBM\AppData\Local\Temp\Droplex\Everything1_4_1_1009.

**Comment by NolanNolan** [comment]
Thanks, ill give it a try and let you know the result:-)

Nolan
