### ISSUE TITLE
BUG: UI Error. Search results are not displayed to the full width of the actual window the flow launcher thing pops up in 

### ISSUE THREAD

**Issue by rsmyst** [Flow-Launcher/Flow.Launcher#1841]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

For some reason, since the 1.12 update, the search results aren't actually using the whole window it pops up in. Very annoying. Besides that, there's also multiple errors popping up continuosly. 
![image](https://user-images.githubusercontent.com/30620767/214389474-eea4b239-2e61-4a20-b478-fb508e08e50f.png)

### To Reproduce

1. install 1.12
2. Open 1.12 flow launcher
3. Wait for it to crash and show errors (which i forcefully fixed by removing some old plugins) then it started
4. After it starts, use keyboard shortcut and watch it use only 2/3rd of the available space for displaying results. 

### Flow Launcher Version

1.12

### Windows Build Number

Microsoft Windows [Version 10.0.19045.2546]

### Error Log

Flow Launcher version: 1.12.0
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 01/24/2023 22:29:02
Exception:
System.TypeLoadException: Could not load type 'Flow.Launcher.Infrastructure.Storage.JsonStrorage`1' from assembly 'Flow.Launcher.Infrastructure, Version=1.12.0.0, Culture=neutral, PublicKeyToken=null'.
   at Flow.Launcher.Plugin.Everything.Main.Save()
   at Flow.Launcher.Core.Plugin.PluginManager.Save() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 53
   at Flow.Launcher.ViewModel.SettingWindowViewModel.Save() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\SettingWindowViewModel.cs:line 146
   at Flow.Launcher.SettingWindow.OnClosed(Object sender, EventArgs e) in C:\projects\flow-launcher\Flow.Launcher\SettingWindow.xaml.cs:line 228
   at System.Windows.Window.OnClosed(EventArgs e)
   at System.Windows.Window.WmDestroy()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by rsmyst** [comment]
> Does anything appear in the right hand part of the search results as it looks like the preview window is open. Hit F1 when showing results to see if that changes things. If it does, checkk that preview isn't set to on as default in the settings
> 
> ![image](https://user-images.githubusercontent.com/18594055/214403962-bca8175c-3981-4c20-8e44-5bb143cd7752.png)

Sorry, I reinstalled flow launcher fully after completely removing all plugins and everythhing since i got tired of it and the problem went away. Error doesn't happen now.
