### ISSUE TITLE
I got an error

### ISSUE THREAD

**Issue by ggeorge02** [Flow-Launcher/Flow.Launcher#1842]
Reinstalling flow launcher did not help. I installed the app for the first time today (24th Jan), on the same day as v1.12.0 came out, I don't have an idea if there is any correlation. I am not experienced in coding whatsoever

[2023-01-24.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10493450/2023-01-24.txt)

Flow Launcher version: 1.12.0
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 01/24/2023 20:52:18
Exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileNotFoundException: Unable to find the specified file.
   at System.IO.FileSystem.ReplaceFile(String sourceFullPath, String destFullPath, String destBackupFullPath, Boolean ignoreMetadataErrors)
   at System.IO.File.Replace(String sourceFileName, String destinationFileName, String destinationBackupFileName, Boolean ignoreMetadataErrors)
   at System.IO.File.Replace(String sourceFileName, String destinationFileName, String destinationBackupFileName)
   at Flow.Launcher.Infrastructure.Storage.JsonStorage`1.Save() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Storage\JsonStorage.cs:line 103
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Flow.Launcher.PublicAPIInstance.SavePluginSettings() in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 167
   at Flow.Launcher.PublicAPIInstance.SaveAppAllSettings() in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 79
   at Flow.Launcher.MainWindow.CheckFirstLaunch() in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 328
   at Flow.Launcher.MainWindow.OnLoaded(Object sender, RoutedEventArgs _) in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 92
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ggeorge02** [comment]
I installed spotify, google calendar and onenote plugins before uninstalling. Spotify runs well, calendar has an issue and onenote wasn't in the same folder as the other plugins, I deleted it using the windows built in search

**Comment by jjw24** [comment]
Hi there, sorry about this issue. We have become aware this issue with v1.12.0 exists for new installs, please download v1.11.0 and you will be able to update to the next release once we publish the hot fix.

Dup #1836
