### ISSUE TITLE
bug: Random error while using Flow launcher

### ISSUE THREAD

**Issue by saurabh-mhaisekar** [Flow-Launcher/Flow.Launcher#1844]
After installing latest version, I keep getting following error randomly.

```
Flow Launcher version: 1.12.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\Saurabh\AppData\Local\Microsoft\WindowsApps\python.exe
Node Path: 
Date: 01/25/2023 12:24:26
Exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileNotFoundException: Unable to find the specified file.
   at System.IO.FileSystem.ReplaceFile(String sourceFullPath, String destFullPath, String destBackupFullPath, Boolean ignoreMetadataErrors)
   at System.IO.File.Replace(String sourceFileName, String destinationFileName, String destinationBackupFileName, Boolean ignoreMetadataErrors)
   at System.IO.File.Replace(String sourceFileName, String destinationFileName, String destinationBackupFileName)
   at Flow.Launcher.Infrastructure.Storage.JsonStorage`1.Save() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Storage\JsonStorage.cs:line 103
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Flow.Launcher.PublicAPIInstance.SavePluginSettings() in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 167
   at Flow.Launcher.Core.Plugin.PluginManager.Save() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 53
   at Flow.Launcher.ViewModel.SettingWindowViewModel.Save() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\SettingWindowViewModel.cs:line 146
   at Flow.Launcher.SettingWindow.OnClosed(Object sender, EventArgs e) in C:\projects\flow-launcher\Flow.Launcher\SettingWindow.xaml.cs:line 228
   at System.Windows.Window.OnClosed(EventArgs e)
   at System.Windows.Window.WmDestroy()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by jjw24** [comment]
Dup of #1836 

Please use v1.11.0 instead. Fix will be released soon which you can update to :)
