### ISSUE TITLE
Error when opening userdata folder

### ISSUE THREAD

**Issue by legolasdimir** [Flow-Launcher/Flow.Launcher#1849]
I got a an error when running the following command `flow launcher userdata` 

Here is the logfile and the error message from flow.

[2023-01-25.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10502373/2023-01-25.txt)

Flow Launcher version: 1.12.1
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\bpruett\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 01/25/2023 11:13:08
Exception:
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'Files' with working directory 'C:\Users\bpruett\AppData\Local\FlowLauncher\app-1.12.1'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Flow.Launcher.PublicAPIInstance.OpenDirectory(String DirectoryPath, String FileName) in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 210
   at Flow.Launcher.Plugin.Sys.Main.<Commands>b__14_19(ActionContext c) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Sys\Main.cs:line 366
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 219
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 276
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by z1nc0r3** [comment]
Please try setting the **Explorer** as the **File Manager** in FL settings.

![Untitled](https://user-images.githubusercontent.com/64279853/214676671-deb48b9a-9069-49fd-a1e6-30304b23d215.png)

**Comment by legolasdimir** [comment]
Thank you for your assistance. That solved the issue.
