### ISSUE TITLE
Settings save error with v1.12.1

### ISSUE THREAD

**Issue by KOMNOOB** [Flow-Launcher/Flow.Launcher#1853]
[2023-01-27.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10515208/2023-01-27.txt)

Flow Launcher version: 1.12.1
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\K OMM\AppData\Local\Programs\Python\Python311\python.exe
Node Path: 
Date: 01/27/2023 08:45:31
Exception:
System.IO.FileNotFoundException: Unable to find the specified file.
   at System.IO.FileSystem.ReplaceFile(String sourceFullPath, String destFullPath, String destBackupFullPath, Boolean ignoreMetadataErrors)
   at System.IO.File.Replace(String sourceFileName, String destinationFileName, String destinationBackupFileName, Boolean ignoreMetadataErrors)
   at System.IO.File.Replace(String sourceFileName, String destinationFileName, String destinationBackupFileName)
   at Flow.Launcher.Infrastructure.Storage.JsonStorage`1.TryLoadBackup() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Storage\JsonStorage.cs:line 80
   at Flow.Launcher.Infrastructure.Storage.JsonStorage`1.Load() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Storage\JsonStorage.cs:line 52
   at Flow.Launcher.ViewModel.SettingWindowViewModel..ctor(Updater updater, IPortable portable) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\SettingWindowViewModel.cs:line 39
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 63
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 52
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
Hey there, do u know what u were doing when you got the error?

**Comment by KOMNOOB** [comment]
I just opened my pc and flow is in startup folder So I got the error.

**Comment by z1nc0r3** [comment]
Is this a fresh installation or an upgrade?

**Comment by KOMNOOB** [comment]
No I used for more than 2-3 months, ofc I updated when it prompted me to

**Comment by taooceros** [comment]
ok it is a bug...which happens when the original file doesn't exist. I will fix it now

**Comment by KOMNOOB** [comment]
What should I do now ?

**Comment by jjw24** [comment]
@KOMNOOB please try this fix here and let us know if addresses the problem https://ci.appveyor.com/api/buildjobs/fpolnta6i7na6npu/artifacts/Output%2FPackages%2FFlow-Launcher-Portable.zip

**Comment by KOMNOOB** [comment]
I got this output 
![image](https://user-images.githubusercontent.com/92045934/215255121-6e4870d0-e4aa-4f86-8697-062e49a18d08.png)

**Comment by KOMNOOB** [comment]
{"message":"Artifacts download limit (1024 MB/day) exceeded."}

**Comment by jjw24** [comment]
> @KOMNOOB please try this fix here and let us know if addresses the problem https://ci.appveyor.com/api/buildjobs/fpolnta6i7na6npu/artifacts/Output%2FPackages%2FFlow-Launcher-Portable.zip

Should be fine now.
