### ISSUE TITLE
Can't start Flow Launcher 

### ISSUE THREAD

**Issue by LABSTORM-MG** [Flow-Launcher/Flow.Launcher#1855]
Every time I try to launch Flow Launcher, I get this error message.
I have already tried to do the standard Windows uninstall, but I always get the same error message.
Is it necessary to delete all files to fix the problem? I would like to keep my settings...

[Logfile](https://github.com/Flow-Launcher/Flow.Launcher/files/10522158/2023-01-27.txt)

<details>
  <summary>exception message</summary>

  ```
Flow Launcher version: 1.12.1
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\labga\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exew
Node Path: 
Date: 01/27/2023 19:36:19
Exception:
System.IO.FileNotFoundException: Unable to find the specified file.
   at System.IO.FileSystem.ReplaceFile(String sourceFullPath, String destFullPath, String destBackupFullPath, Boolean ignoreMetadataErrors)
   at System.IO.File.Replace(String sourceFileName, String destinationFileName, String destinationBackupFileName, Boolean ignoreMetadataErrors)
   at System.IO.File.Replace(String sourceFileName, String destinationFileName, String destinationBackupFileName)
   at Flow.Launcher.Infrastructure.Storage.JsonStorage`1.TryLoadBackup() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Storage\JsonStorage.cs:line 80
   at Flow.Launcher.Infrastructure.Storage.JsonStorage`1.Load() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Storage\JsonStorage.cs:line 52
   at Flow.Launcher.ViewModel.MainViewModel..ctor(Settings settings) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 86
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 74
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 52
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
  ```
</details>

thx for the help :)

**Comment by jjw24** [comment]
Hi there, please try this fix here and let us know if addresses the problem https://ci.appveyor.com/api/buildjobs/fpolnta6i7na6npu/artifacts/Output%2FPackages%2FFlow-Launcher-Portable.zip

**Comment by jjw24** [comment]
Dup of #1853

**Comment by LABSTORM-MG** [comment]
worked but it overrode my settings :/ 
probably my bad...
thx for the help!!!
