### ISSUE TITLE
Explorer plugin error- Invalid URI: Authority/host could not be parsed

### ISSUE THREAD

**Issue by AarjavPatni** [Flow-Launcher/Flow.Launcher#1869]
Everytime I type something, the Explorer plugin shows the following error:
`Invalid URI: Authority/host could not be parsed`
An example is when I type sys to open System Information:
![image](https://user-images.githubusercontent.com/68058926/215797588-435bf5f2-5813-4da7-b293-c3ee5ef2bc33.png)

Here's more error info:
```WindowsIndex Search Exception:
 Flow.Launcher.Plugin.Explorer.Exceptions.SearchException: Invalid URI: The Authority/Host could not be parsed.
 ---> System.UriFormatException: Invalid URI: The Authority/Host could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndex.ExecuteWindowsIndexSearchAsync(String indexQueryString, String connectionString, CancellationToken token)+MoveNext() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\WindowsIndex.cs:line 56
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndex.ExecuteWindowsIndexSearchAsync(String indexQueryString, String connectionString, CancellationToken token)+MoveNext() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\WindowsIndex.cs:line 48
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndex.ExecuteWindowsIndexSearchAsync(String indexQueryString, String connectionString, CancellationToken token)+MoveNext() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\WindowsIndex.cs:line 48
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndex.ExecuteWindowsIndexSearchAsync(String indexQueryString, String connectionString, CancellationToken token)+MoveNext() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\WindowsIndex.cs:line 48
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndex.ExecuteWindowsIndexSearchAsync(String indexQueryString, String connectionString, CancellationToken token)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 109
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 109
   --- End of inner exception stack trace ---
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 122
   at Flow.Launcher.Plugin.Explorer.Main.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Main.cs:line 88```

**Comment by z1nc0r3** [comment]
Hey there, is this issue still exist? If then please ensure that the **Windows Indexing** is enabled and running. Or else please try selecting **Everything** as the **Explorer Plugin Search Engine**.

**Comment by AarjavPatni** [comment]
Yes I've changed the indexing to Everything now

**Comment by jjw24** [comment]
@AarjavPatni I want to be able to repro this error. Was your Windows Search service disabled or removed?

**Comment by AarjavPatni** [comment]
@jjw24 I'm not sure what you mean by _removing_ the Windows service. It's disabled now nevertheless.

**Comment by jjw24** [comment]
Hey there, by removed I meant actually that it does not exist in the Window Service list (which I have seen some in machines) when you had the error.

I think this error should be better captured because it doesn't mean anything to the end user. Let's keep this issue open, and I will also update the title.

**Comment by Spheres-cu** [comment]
I solved the problem by rebuilding the index of the Windows Search Service, opening the Windows Search options from the plugin settings and in the advanced options I did the rebuilding of the index, with that it stopped giving me the error
