### ISSUE TITLE
Got error when launching

### ISSUE THREAD

**Issue by wrbyepct** [Flow-Launcher/Flow.Launcher#1871]
Got error message when launching
![X4RmHAbPK0](https://user-images.githubusercontent.com/84783605/215943920-9d5f0c69-f15e-4518-b3bc-bcdc42fcaa62.png)
[D:\Flow laucher\FlowLauncher\app-1.12.1\UserData\Logs\1.12.1\2023-02-01.txt]() 

Flow Launcher version: 1.12.1
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: D:\Flow laucher\FlowLauncher\app-1.12.1\UserData\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 02/01/2023 12:09:31
Exception:
System.IO.FileNotFoundException: Unable to find the specified file.
   at System.IO.FileSystem.ReplaceFile(String sourceFullPath, String destFullPath, String destBackupFullPath, Boolean ignoreMetadataErrors)
   at System.IO.File.Replace(String sourceFileName, String destinationFileName, String destinationBackupFileName, Boolean ignoreMetadataErrors)
   at System.IO.File.Replace(String sourceFileName, String destinationFileName, String destinationBackupFileName)
   at Flow.Launcher.Infrastructure.Storage.JsonStorage`1.TryLoadBackup() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Storage\JsonStorage.cs:line 80
   at Flow.Launcher.Infrastructure.Storage.JsonStorage`1.Load() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Storage\JsonStorage.cs:line 52
   at Flow.Launcher.ViewModel.MainViewModel..ctor(Settings settings) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 87
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 74
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 52
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by z1nc0r3** [comment]
Please refer #1853

**Comment by jjw24** [comment]
Dup.

Please try the link mentioned in the comment.
