### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by hetingrui** [Flow-Launcher/Flow.Launcher#1906]
[2023-02-14.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10729807/2023-02-14.txt)

Flow Launcher version: 1.12.1
OS Version: Microsoft Windows NT 10.0.22623.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\Konata\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 02/14/2023 15:26:19
Exception:
System.Net.WebException: An exception occurred during a WebClient request.
 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebClient.DownloadBitsAsync(WebRequest request, Stream writeStream, AsyncOperation asyncOp, Action`3 completionDelegate)
   --- End of inner exception stack trace ---
   at Dictionary.DictDownloadManager.PerformDownload() in C:\Users\Null\Documents\Projects\Flow.Launcher.Dictionary\src\DictDownloadManager.cs:line 62
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by z1nc0r3** [comment]
Can you describe how the issue occured and steps to reproduce?

**Comment by deefrawley** [comment]
@hetingrui please try with the latest Flow version and if the problem still persists we can re-open this issue.
