### ISSUE TITLE
Hotkey registration failure pop up msg suggestion + Flow Launcher got an error

### ISSUE THREAD

**Issue by rp1231** [Flow-Launcher/Flow.Launcher#1923]
I got this popup on the start of flow launcher at windows startup:

![CpF6mahnmG](https://user-images.githubusercontent.com/47380919/219998287-ffa6391d-efcc-4672-9981-72162b2c09f4.png)

It would be better user experience if the popup had "flow launcher" in the title.
I use many programs that register shortcuts, and got confused as to which program this message came from.
I had to ultimately use autohotkey's windowspy to find which program it belonged to.

It would also be better if the error popup mentioned where the error originated from.
I got the popup because I had a Custom Query Hotkey set to the shortcut mentioned, which failed to register.
(Which again I had to hunt for as I had forgotten about it)
It would be better if the popup had mentioned that the error occured because the "Custom Query hotkey failed to register".

I deleted the custom query but forgot to close the pop up message and continued to use flow launcher, when I got 
this "Flow launcher got an error".
I have posted the two issues together as I suspect there maybe some relation between the two events?

[2023-02-20.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10778993/2023-02-20.txt)
Flow Launcher version: 1.13.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: C:\Python310\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 02/20/2023 08:07:02
Exception:
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Flow.Launcher.Helper.HotKeyMapper.LoadCustomPluginHotkey() in C:\projects\flow-launcher\Flow.Launcher\Helper\HotKeyMapper.cs:line 67
   at Flow.Launcher.Helper.HotKeyMapper.Initialize(MainViewModel mainVM) in C:\projects\flow-launcher\Flow.Launcher\Helper\HotKeyMapper.cs:line 23
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 89
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 52
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
>I deleted the custom query but forgot to close the pop up message and continued to use flow launcher, when I got
this "Flow launcher got an error".

Might be separate, what did you do after you deleted the custom query, did you search anything or did it just popped up immediately?
