### ISSUE TITLE
I opened Flow Launcher and it give me this error

### ISSUE THREAD

**Issue by Ulvdiaz** [Flow-Launcher/Flow.Launcher#1927]
[2023-02-22.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10807980/2023-02-22.txt)

Flow Launcher version: 1.13.0
OS Version: Microsoft Windows NT 10.0.22623.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\Ulvdi\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 02/22/2023 21:14:38
Exception:
System.NotSupportedException: 'Shift+D1' key and modifier combination is not supported for KeyGesture.
   at System.Windows.Input.KeyGesture..ctor(Key key, ModifierKeys modifiers, String displayString, Boolean validateGesture)
   at System.Windows.Input.KeyGestureConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object source)
   at Flow.Launcher.Converters.StringToKeyBindingConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture) in C:\projects\flow-launcher\Flow.Launcher\Converters\StringToKeyBindingConverter.cs:line 15
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by z1nc0r3** [comment]
Please read [#1755](https://github.com/Flow-Launcher/Flow.Launcher/issues/1755#issuecomment-1368983887)

**Comment by deefrawley** [comment]
Hi @Ulvdiaz. Did you change the Preview hot key in the Settings?
