### ISSUE TITLE
[Suggestion] Web search plugin / Make list of custom search engines sortable

### ISSUE THREAD

**Issue by LinguaOccultus** [Flow-Launcher/Flow.Launcher#1955]
Just a simple one: I would like to sort the custom search egines in the web search plugin. I removed the default ones and added quite a few and every know and then, the list gets longer. With time and amount of engines, it is very hard to handle and to overview. I also do add those engines to my browser and the other way round to sync them manually, which also. They are based on a list, but where I can sort the list in the browser (here: Vivaldi, a Chromium-based one) and move entries around, in Flow Launcher they are simply added at the end and not sortable and movable.

This makes longer lists very hard to manage, unfortunately! Yet, I find, a global and system-wide custom web search is one of the coolest and most important feature of Flow Launcher (which PowerToys Run still does not have ... *cough* *cough* :-D ), I find it could be a bit better supported.

Also, an automatic download of favicons would be much appreciated instead of being just able to manually add them, which is quite some work and a bit annoying.

**Comment by deefrawley** [comment]
Do you mean the list of search engines the Web Searches plugin settings page?

![image](https://user-images.githubusercontent.com/18594055/222839978-96265e65-b860-468f-b87e-dde4f4dd7bd3.png)

**Comment by LinguaOccultus** [comment]
Exactly. I know, I can sort them at least by clicking on the category on top of the columns, but I mean a custom sort which can be done manually.

By the way: when clicking on the very first, empty field (top of favicons column) it shows an error

`
Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues/new
1. upload log file: C:\Users\Tim\AppData\Roaming\FlowLauncher\Logs\1.13.0\2023-03-03.txt
2. copy below exception message

Flow Launcher version: 1.13.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 03/03/2023 23:20:43
Exception:
System.InvalidOperationException: Failed to compare two elements in the array.
 ---> System.ArgumentException: At least one object must implement IComparable.
   at System.Collections.Comparer.Compare(Object a, Object b)
   at MS.Internal.Data.SortFieldComparer.Compare(Object o1, Object o2)
   at System.Array.SorterGenericArray.SwapIfGreater(Int32 a, Int32 b)
   at System.Array.SorterGenericArray.PickPivotAndPartition(Int32 lo, Int32 hi)
   at System.Array.SorterGenericArray.IntroSort(Int32 lo, Int32 hi, Int32 depthLimit)
   at System.Array.SorterGenericArray.IntrospectiveSort(Int32 left, Int32 length)
   --- End of inner exception stack trace ---
   at System.Array.SorterGenericArray.IntrospectiveSort(Int32 left, Int32 length)
   at System.Array.Sort(Array keys, Array items, Int32 index, Int32 length, IComparer comparer)
   at System.Array.Sort(Array array, IComparer comparer)
   at MS.Internal.Data.SortFieldComparer.SortHelper(ArrayList al, IComparer comparer)
   at System.Windows.Data.ListCollectionView.PrepareLocalArray()
   at System.Windows.Data.ListCollectionView.RefreshOverride()
   at System.Windows.Data.CollectionView.RefreshInternal()
   at System.ComponentModel.SortDescriptionCollection.InsertItem(Int32 index, SortDescription item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at Flow.Launcher.Plugin.WebSearch.SettingsControl.Sort(String sortBy, ListSortDirection direction) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.WebSearch\SettingsControl.xaml.cs:line 126
   at Flow.Launcher.Plugin.WebSearch.SettingsControl.SortByColumn(Object sender, RoutedEventArgs e) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.WebSearch\SettingsControl.xaml.cs:line 99
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.GridViewColumnHeader.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.Controls.GridViewColumnHeader.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
`

**Comment by LinguaOccultus** [comment]
Maybe an easy way would be to add a number field to each where one simply can insert a number for its position and then let it sort this way in an additional column. Drag and drop would be better, of course.

**Comment by onesounds** [comment]
Yeah, I think drag and drop is better. but it's hard for me. 😔 I'll give it a try. 
If I fail, I'll consider adding a group field as the next best thing.

**Comment by deefrawley** [comment]
Issue #1956 created for the favicon sorting exception

**Comment by LinguaOccultus** [comment]
Thanks for opening the issue for the exception; was not sure how to handle it so I mentioned it here as we are talking. ;-)

So, you are the developer of the plugin or just a helping programmer? I see much potential in Flow Launcher generally and have tested a few of those applications but found this one the best so far. The Run PowerToy also has its potential, but it a bit more basic for the moment and Microsofts development often stays there so many of us replace their applications with third party ones.

However, I guess, a bit better management of the search engines would help; especially with many of them. I am a programmer, too (and also a media designer), but just fnished my education, so I am still at the very beginning and not of much help. ;-) However, I normally have more ideas then most developers welcome! :-D I do not know how you implemented it and what the problem is excatly, but if editing the existing list is not so easy, maybe a separate windows for editing the list might help or work better? Depending on what is the problem ... Maybe both options we talked about could be joined since even when dragging and dropping, the plugin needs to take track of the changed positions and would surely need some kind of ID (or number) anyway. So, a general implementation of those could be later improved by allowing drag and drop. And the other way round, you can already can implement it with a possible later drag and drop implementation in mind which can be technically prepared already.

Sorry if I am not so helpful but maybe discussing this a bit helps with inspiration; especially when you have all the work I can do this at least! :-D

**Comment by LinguaOccultus** [comment]
One more suggestion: On the screenshot below you can see a part of my search engines list. As you can see, I am using their names also to mention the command I gave them to quickly overview them. Maybe it would be a good idea to make another column especially for those to have a quick overview and see what is in use already?

My browser shows them inline in the list as another option (second screenshot).

![image](https://user-images.githubusercontent.com/90448229/222857776-1d14c8ba-6a0b-4d23-bb94-9618ddcbb993.png)

![image](https://user-images.githubusercontent.com/90448229/222857902-b03e6cb4-adf5-4157-9903-b6b0f3e651d8.png)

**Comment by LinguaOccultus** [comment]
Cool, if the developers here are open for suggestions — which is not that often the case — i'll have a look then. I am using Discord anyway.

**Comment by jjw24** [comment]
Of course we are, how else is flow going to get better :)

**Comment by LinguaOccultus** [comment]
Good to know. I am going to recall all the other things I became aware of and gather all of the suggestions to report them in here. However, I will do separate threads as it is surely intended! ;-) Unfortunately, GitHub still has no direct personal messages to my knowledge and so, some off-topic oder overhead is unavoidable I guees. :-D

But I think the quality of a program is not how much features it has, it is, how well their are implemented. There are so much programs out there releasing one unfinished and unpolished feature after another instead of sticking to them until done that it is extremely annoying! And often, it is simple things like making a long list (in my case it IS a long list, however) of custom search engines manageble. Under this conditions, I will stick around here for some time.

Also, after finally not ill anymore, i will find some time to join Discord also. Just saw the email notification for the answer on the thread here.

**Comment by jjw24** [comment]
Hope you are feeling better soon.

>Good to know. I am going to recall all the other things I became aware of and gather all of the suggestions to report them in here. However, I will do separate threads as it is surely intended! ;-) Unfortunately, GitHub still has no direct personal messages to my knowledge and so, some off-topic oder overhead is unavoidable I guees. :-D

Yes, please keep one bug/suggestion per issue.

Use GitHub Discussions for design & questions, other general sparse conversation topics can be in Discord. You can also pm in Discord if you need to.
