### ISSUE TITLE
flow crashes when making custom extension

### ISSUE THREAD

**Issue by DeepVoyager253** [Flow-Launcher/Flow.Launcher#1964]
Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues/new
1. upload log file: C:\Users\eyalb\AppData\Roaming\FlowLauncher\Logs\1.14.0\2023-03-06.txt
2. copy below exception message

Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\eyalb\AppData\Local\Microsoft\WindowsApps\pythonw.exe
Node Path: 
Date: 03/06/2023 21:58:15
Exception:
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Flow.Launcher.ReportWindow.Hyperlink(String textBeforeUrl, String url) in C:\projects\flow-launcher\Flow.Launcher\ReportWindow.xaml.cs:line 79
   at Flow.Launcher.ReportWindow.SetException(Exception exception) in C:\projects\flow-launcher\Flow.Launcher\ReportWindow.xaml.cs:line 53
   at Flow.Launcher.ReportWindow..ctor(Exception exception) in C:\projects\flow-launcher\Flow.Launcher\ReportWindow.xaml.cs:line 23
   at Flow.Launcher.Helper.ErrorReporting.Report(Exception e) in C:\projects\flow-launcher\Flow.Launcher\Helper\ErrorReporting.cs:line 17
   at Flow.Launcher.Helper.ErrorReporting.DispatcherUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\Helper\ErrorReporting.cs:line 30
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2023-03-06.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10902332/2023-03-06.txt)

**Comment by deefrawley** [comment]
Are you making a plugin and get this error? If so, posting an issue in the main repo is not the correct way to get assistance as we have no idea what code you have written. Please close the issue and perhaps join the Discord so people can help troubleshoot your code.
If it is another issue please elaborate on what you mean, what you were doing/typing when the crash occurred.

**Comment by DeepVoyager253** [comment]
> Are you making a plugin and get this error? If so, posting an issue in the main repo is not the correct way to get assistance as we have no idea what code you have written. Please close the issue and perhaps join the Discord so people can help troubleshoot your code. If it is another issue please elaborate on what you mean, what you were doing/typing when the crash occurred.

what is the discord? ill be glad to join. essentially, my problem is not the plugin, first i thought it was because i made my own one following a guide, but then, i just cloned the hello world example for python from the repo, and i still get this error.

**Comment by DeepVoyager253** [comment]
i simply forgot to install flowlauncher. how silly
