### ISSUE TITLE
Error message - submitting as requested

### ISSUE THREAD

**Issue by Neversaynever10001** [Flow-Launcher/Flow.Launcher#1970]
Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 03/10/2023 18:41:16
Exception:
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Program Files\Everything\Everything.exe' with working directory 'C:\Users\Pro7S\AppData\Local\FlowLauncher\app-1.14.0'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingSearchManager.ClickToInstallEverythingAsync(ActionContext _) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingSearchManager.cs:line 54
   at Flow.Launcher.ViewModel.MainViewModel.OpenR
[2023-03-10.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10939746/2023-03-10.txt)
esultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 277
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by deefrawley** [comment]
Hi. In the Explorer Plugin settings have you entered a path to your Everything install? It seems it can't find it

**Comment by Neversaynever10001** [comment]
Hi Damien - I’m very much an amateur so I’m not sure, but here’s a screenshot of the settings! 

 



 

Kind regards  |  Charlotte

**Comment by deefrawley** [comment]
That's ok. The screenshot didn't come through.
Does it lookk like this?

![image](https://user-images.githubusercontent.com/18594055/224288856-2a9246b2-1904-4a4d-a6ec-a42d5db6f1a6.png)

**Comment by deefrawley** [comment]
Yep try removing that last part, then when you exit out of the settings window, bring up Flow again and hit the F5 key to reload all the plugins.

**Comment by Neversaynever10001** [comment]
Thanks Damien – I wish all tech support was as good as yours! 😉

 

Have a great weekend, Charlotte.
