### ISSUE TITLE
Got problem in opening flow

### ISSUE THREAD

**Issue by KOMNOOB** [Flow-Launcher/Flow.Launcher#1975]
[2023-03-12.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10949859/2023-03-12.txt)

Exception Message : 
Flow Launcher version: 1.12.1
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 03/12/2023 07:55:50
Exception:
System.IO.FileNotFoundException: Unable to find the specified file.
   at System.IO.FileSystem.ReplaceFile(String sourceFullPath, String destFullPath, String destBackupFullPath, Boolean ignoreMetadataErrors)
   at System.IO.File.Replace(String sourceFileName, String destinationFileName, String destinationBackupFileName, Boolean ignoreMetadataErrors)
   at System.IO.File.Replace(String sourceFileName, String destinationFileName, String destinationBackupFileName)
   at Flow.Launcher.Infrastructure.Storage.JsonStorage`1.TryLoadBackup() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Storage\JsonStorage.cs:line 80
   at Flow.Launcher.Infrastructure.Storage.JsonStorage`1.Load() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Storage\JsonStorage.cs:line 52
   at Flow.Launcher.ViewModel.MainViewModel..ctor(Settings settings) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 86
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 74
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 52
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by KOMNOOB** [comment]
I had installed.But I got error so I reinstalled.It was not fixed.Kindly tell me what to do now.

**Comment by deefrawley** [comment]
Upgrade to the latest version of Flow which should fix this - you are running v1.12 and the latest is v1.14

**Comment by KOMNOOB** [comment]
Thx it worked
