### ISSUE TITLE
Flow 1.14 frequently crashing, unusable...

### ISSUE THREAD

**Issue by cyber2e** [Flow-Launcher/Flow.Launcher#1987]
Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\shenw\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 03/16/2023 19:54:41
Exception:
文件管理器 Exception: 
Websites: https://github.com/Flow-Launcher/Flow.Launcher
Author: Jeremy Wu
Version: 3.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: The path is empty. (Parameter 'path')
 ---> System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetRelativePath(String relativeTo, String path, StringComparison comparisonType)
   at Flow.Launcher.Plugin.SharedCommands.FilesFolders.PathContains(String parentPath, String subPath, Boolean allowEqual) in /_/Flow.Launcher.Plugin/SharedCommands/FilesFolders.cs:line 252
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Collections.Generic.HashSet`1.RemoveWhere(Predicate`1 match)
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 129
   at Flow.Launcher.Plugin.Explorer.Main.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Main.cs:line 88
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 840
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2023-03-16.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/10994859/2023-03-16.txt)

**Comment by jjw24** [comment]
What action are you trying to do and what's the file or folder path you are trying to excute/navigate?

**Comment by cyber2e** [comment]
Hi,

I try to use action keyword "n" + search term to search Notion.  I
installed the plugin "Notion Search" and has set the action keyword as "n".
But almost crashes every time.

Shen

**Comment by jjw24** [comment]
Oh ok, so without the Notion plugin flow is working fine?

If that's the case it may just be an issue with the Notion plugin itself. Last I remmember the plugin author has a slight issue that was being fixed.

**Comment by deefrawley** [comment]
Hi. It has been a month with no update so closing this issue. If it still persists then raise an issue in the Notion plugin repo. Any other problems feel free to reach out to the Flow team. Thanks

**Comment by dharrison27** [comment]
Yeah, the issue remains, untouched in nearly a year with (as of rn) 60 issues raised without a single reply. 

It seems to be that the plugin is using a depreciated part of setuptools, trying to import pkg_resources that is no longer defined. See: https://setuptools.pypa.io/en/latest/pkg_resources.html

**Comment by deefrawley** [comment]
That is a lot of issues with no response. Will try to reach out to the plugin author and see if we can get the issue resolved otherwise will talk to the team to see if we delist the plugin for now.
