### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by LLLLLC** [Flow-Launcher/Flow.Launcher#2035]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

After installing the plugin from the plugin store, the software will not automatically restart, and after manually refreshing with F5, the following error message appears.

### To Reproduce

1. Start portable software.
2. After installing any plugin on the settings page, the software did not automatically restart after the plugin installation was completed.
3. Press F5 to refresh, error occurred.

### Screenshots

![image](https://user-images.githubusercontent.com/49516367/230644414-7e22103b-749b-40af-adc5-6c9892e6ec95.png)
Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues/new
1. upload log file: F:\easykits\flow\Flow-Launcher-Portable\FlowLauncher\app-1.14.0\UserData\Logs\1.14.0\2023-04-08.txt
2. copy below exception message

Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 04/08/2023 00:30:28
Exception:
System.InvalidOperationException: Failed initializing notifications
 ---> System.IO.IOException: 无法在易变父项下创建稳定子项。
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternalCore(String subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.Initialize()
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.CreateToastNotifier()
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show(CustomizeToast customize)
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show()
   at Flow.Launcher.Notification.Show(String title, String subTitle, String iconPath) in C:\projects\flow-launcher\Flow.Launcher\Notification.cs:line 35
   at Flow.Launcher.ViewModel.MainViewModel.ReloadPluginDataAsync() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 191
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Flow Launcher Version

1.14.0

### Windows Build Number

10.0.22621.1413

### Error Log

<details>

```shell

R00:16:09.6690+08:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
00:16:09.6690+08:00 - ERROR -  - 
Exception full name: System.IO.FileNotFoundException
Error status: UNKNOWN
Class name: Win32
Calling method: ExeProgram
Program path: F:\easykits\vs\Ide\common7\ide\devenv.exe
InnerException number: 1
Exception message: F:\easykits\vs\Ide\common7\ide\devenv.exe
Exception error type: HResult -2147024894
Exception thrown in called method: System.Diagnostics.FileVersionInfo GetVersionInfo(System.String)
Possible interpretation of the error: File not found when trying to load the program from F:\easykits\vs\Ide\common7\ide\devenv.exe
Possible resolution: Not yet known
00:16:09.6690+08:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
00:16:09.6690+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Windows Settings> is <34ms>
00:16:09.6921+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Browser Bookmarks> is <50ms>
00:16:09.6921+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Plugins Manager> is <54ms>
00:16:09.8764+08:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
00:16:09.8764+08:00 - ERROR -  - 
Exception full name: System.Runtime.InteropServices.COMException
Error status: UNKNOWN
Class name: IShellLinkW
Calling method: retrieveTargetPath
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Windows Media Player Legacy.lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Not yet known
```
</details>

**Comment by Garulf** [comment]
Looks like a duplicate of #2054 (And many others). Please continue discussion there. Thank you.
