### ISSUE TITLE
BUG: Crash on Refresh

### ISSUE THREAD

**Issue by gnimor** [Flow-Launcher/Flow.Launcher#2052]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

When running a refresh (pressing F5) I get the following crash with FlowLauncher:

```
Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.18363.0
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 04/17/2023 08:24:39
Exception:
System.InvalidOperationException: The calling thread must be STA, because many UI components require this.
   at System.Windows.Input.InputManager..ctor()
   at System.Windows.Input.InputManager.GetCurrentInputManagerImpl()
   at System.Windows.Input.KeyboardNavigation..ctor()
   at System.Windows.FrameworkElement.FrameworkServices..ctor()
   at System.Windows.FrameworkElement.EnsureFrameworkServices()
   at System.Windows.FrameworkElement..ctor()
   at System.Windows.Controls.Control..ctor()
   at System.Windows.Window..ctor()
   at Flow.Launcher.Msg..ctor() in C:\projects\flow-launcher\Flow.Launcher\Msg.xaml.cs:line 19
   at Flow.Launcher.Notification.LegacyShow(String title, String subTitle, String iconPath) in C:\projects\flow-launcher\Flow.Launcher\Notification.cs:line 44
   at Flow.Launcher.Notification.Show(String title, String subTitle, String iconPath) in C:\projects\flow-launcher\Flow.Launcher\Notification.cs:line 26
   at Flow.Launcher.ViewModel.MainViewModel.ReloadPluginDataAsync() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 191
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### Flow Launcher Version

1.14.0

### Windows Build Number

OS Version: Microsoft Windows NT 10.0.18363.0

**Comment by dharrison27** [comment]
@gnimor your windows version is 10.0.18363.0 so I'd update Windows first then try again?

**Comment by gnimor** [comment]
This is a company controlled laptop - so I cannot run updates. Anyway I guess the following exception:

System.InvalidOperationException: The calling thread must be STA, because many UI components require this.

is not really related to an "old" operating system.
