### ISSUE TITLE
C:\Users\nguye\AppData\Roaming\FlowLauncher\Logs\1.14.0\2023-04-17.txt

### ISSUE THREAD

**Issue by vietnguyenusa** [Flow-Launcher/Flow.Launcher#2059]
Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 04/17/2023 19:03:16
Exception:
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Program Files\Everything\Everything.exe' with working directory 'C:\Users\nguye\AppData\Local\FlowLauncher\app-1.14.0'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingSearchManager.ClickToInstallEverythingAsync(ActionContext _) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingSearchManager.cs:line 54
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 277
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by deefrawley** [comment]
Hi, could you please try installing the prerelease version and let us know if that fixes the issue?

https://github.com/Flow-Launcher/Prereleases/releases/tag/v1.14.0.7149

Thanks
