### ISSUE TITLE
.

### ISSUE THREAD

**Issue by louispham812** [Flow-Launcher/Flow.Launcher#2063]
[2023-04-18.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/11263554/2023-04-18.txt)

Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\HoangLouis\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 04/18/2023 22:22:37
Exception:
SpotifyAPI.Web.APIException: Player command failed: Premium required
   at SpotifyAPI.Web.Http.APIConnector.ProcessErrors(IResponse response)
   at SpotifyAPI.Web.Http.APIConnector.DoRequest(IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.SendAPIRequestDetailed(Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers)
   at SpotifyAPI.Web.Http.APIConnector.Put(Uri uri, IDictionary`2 parameters, Object body)
   at SpotifyAPI.Web.PlayerClient.ResumePlayback()
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPluginClient.Play() in C:\Users\fpwal\Repos\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPluginClient.cs:line 148
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPlugin.<>c__DisplayClass18_0.<GetPlaying>b__2(ActionContext _) in C:\Users\fpwal\Repos\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPlugin.cs:line 216
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 219
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 277
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by deefrawley** [comment]
Please follow the issue creation guide. Creating an issue with a single period as a title is not helpful.
This error is for the Spotify Premium plugin. You need spotify Premium to use it.
