### ISSUE TITLE
C:\Users\ahuyl\AppData\Roaming\FlowLauncher\Logs\1.14.0\2023-04-18.txt

### ISSUE THREAD

**Issue by AHuyLy** [Flow-Launcher/Flow.Launcher#2064]
Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 04/18/2023 23:00:12
Exception:
System.IO.IOException: The process cannot access the file 'C:\Users\ahuyl\AppData\Local\Temp\Droplex\Everything1_4_1_1009.exe' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at Droplex.Downloader.Get(String url, String filePath)
   at Droplex.DroplexPackage.Drop(App app, String zipExtractPath)
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingDownloadHelper.PromptDownloadIfNotInstallAsync(String installedLocation, IPublicAPI api) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingDownloadHelper.cs:line 47
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingSearchManager.ClickToInstallEverythingAsync(ActionContext _) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingSearchManager.cs:line 44
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 277
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by deefrawley** [comment]
Hi, could you please try installing the prerelease version and let us know if that fixes the issue?

https://github.com/Flow-Launcher/Prereleases/releases/tag/v1.14.0.7149

Thanks

**Comment by deefrawley** [comment]
Hi @AHuyLy - is this still an issue in the current Flow version?
