### ISSUE TITLE
Failed to open Files UWP as Spotify's containment folder

### ISSUE THREAD

**Issue by pratyakshm** [Flow-Launcher/Flow.Launcher#2076]
[2023-04-20.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/11286827/2023-04-20.txt)

Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.25336.0
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 04/20/2023 19:11:35
Exception:
System.ComponentModel.Win32Exception (5): An error occurred trying to start process 'C:\Program Files\WindowsApps\49306atecsolution.FilesUWP_2.4.61.0_x64__et10x9a9vyk8t\Files.App\Files.exe' with working directory 'C:\WINDOWS\system32'. Access is denied.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Flow.Launcher.PublicAPIInstance.OpenDirectory(String DirectoryPath, String FileName) in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 210
   at Flow.Launcher.Plugin.Program.Programs.Win32.<ContextMenus>b__54_4(ActionContext _) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Program\Programs\Win32.cs:line 245
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 219
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 277
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by pratyakshm** [comment]
@VictoriousRaptor The latter worked!

**Comment by pratyakshm** [comment]
Should I still test with files pre-release build?
