### ISSUE TITLE
Please help with this error

### ISSUE THREAD

**Issue by thisis2023whystillneedingusername** [Flow-Launcher/Flow.Launcher#2079]
Got this error mesage when doing web search with Flow Launcher. Error log is attached below. Please help, thanks!

Flow Launcher version: 1.14.1
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 04/21/2023 20:46:50
Exception:
System.ComponentModel.Win32Exception (0x800401F5): An error occurred trying to start process 'https://www.google.com/search?q=google' with working directory 'D:\Downloads\FlowLauncher'. Application not found
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Flow.Launcher.Plugin.SharedCommands.SearchWeb.OpenInBrowserTab(String url, String browserPath, Boolean inPrivate, String privateArg) in /_/Flow.Launcher.Plugin/SharedCommands/SearchWeb.cs:line 108
   at Flow.Launcher.PublicAPIInstance.OpenUri(Uri uri, Nullable`1 inPrivate) in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 221
   at Flow.Launcher.PublicAPIInstance.OpenUrl(String url, Nullable`1 inPrivate) in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 242
   at Flow.Launcher.Plugin.WebSearch.Main.<>c__DisplayClass9_1.<QueryAsync>b__1(ActionContext c) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.WebSearch\Main.cs:line 79
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 219
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 277
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2023-04-21.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/11295817/2023-04-21.txt)

**Comment by deefrawley** [comment]
Hi. What is your default browser?

**Comment by thisis2023whystillneedingusername** [comment]
> 

Thanks for the quick reply. My default browser is Microsoft Edge.

So here's what happened: I uninstalled a software with something called Revouninstaller Pro, which was supposed to delete leftover files after the uninstallaton, but this time something must have gone wrong, because strange things started to happen, first I noticed that the Microsoft Edge icon on my task bar stopped working(broken file link), and then I couldn't use Flow Launcher to do web search anymore. I tried to reinstall Flow again, tried to install an older version and the portable version, all got the same error.

**Comment by deefrawley** [comment]
You do need to be careful with those advanced uninstallers as their after uninstall scanners can sometimes remove more than you think.
It looks like it has uninstalled or possibly broken your Edge install. Try reinstalling that and see how you go.

**Comment by thisis2023whystillneedingusername** [comment]
> You do need to be careful with those advanced uninstallers as their after uninstall scanners can sometimes remove more than you think. It looks like it has uninstalled or possibly broken your Edge install. Try reinstalling that and see how you go.

SOLVED! Reinstalling Edge fixed it! Thank you so much!
