### ISSUE TITLE
Error when trying to unpause spotify

### ISSUE THREAD

**Issue by Michou-G** [Flow-Launcher/Flow.Launcher#2083]
[2023-04-22.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/11301181/2023-04-22.txt)
Flow Launcher version: 1.14.1
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 04/22/2023 13:26:26
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPluginClient.Play() in C:\Users\fpwal\Repos\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPluginClient.cs:line 146
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPlugin.<>c__DisplayClass18_0.<GetPlaying>b__2(ActionContext _) in C:\Users\fpwal\Repos\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPlugin.cs:line 216
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 219
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 277
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Michou-G** [comment]
Already fixed it by logging out from spotify and logging back in.
