### ISSUE TITLE
Flow Launcher version: 1.14.0 OS Version: Microsoft Windows NT 10.0.22621.0 IntPtr Length: 8 x64: True

### ISSUE THREAD

**Issue by TiKieii** [Flow-Launcher/Flow.Launcher#2090]
[2023-04-25.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/11313286/2023-04-25.txt)

**Comment by deefrawley** [comment]
```00:59:30.0492+07:00 - FATAL - UnHandledException - 
## Exception

System.NullReferenceException: Object reference not set to an instance of an object.
   Source: Flow.Launcher.Plugin.SpotifyPremium
   TargetAssembly: Flow.Launcher.Plugin.SpotifyPremium, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
   TargetModule: Flow.Launcher.Plugin.SpotifyPremium.dll
   TargetSite: Void Play()
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPluginClient.Play() in C:\Users\fpwal\Repos\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPluginClient.cs:line 146
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPlugin.<>c__DisplayClass18_0.<GetPlaying>b__2(ActionContext _) in C:\Users\fpwal\Repos\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPlugin.cs:line 216
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 219
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 277
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by deefrawley** [comment]
Hi @TiKieii - is this still an issue with the current version of Flow?
