### ISSUE TITLE
BUG: FlowLauncher crash when i write "-yt" with or without link

### ISSUE THREAD

**Issue by Arnemix** [Flow-Launcher/Flow.Launcher#2121]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Flow Launcher version: 1.15.0
OS Version: 22621.1555
IntPtr Length: 8
x64: True

Python Path: C:\Users\amind\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 05/06/2023 14:59:45
Exception:
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Flow.Launcher.ReportWindow.Hyperlink(String textBeforeUrl, String url) in C:\projects\flow-launcher\Flow.Launcher\ReportWindow.xaml.cs:line 79
   at Flow.Launcher.ReportWindow.SetException(Exception exception) in C:\projects\flow-launcher\Flow.Launcher\ReportWindow.xaml.cs:line 53
   at Flow.Launcher.ReportWindow..ctor(Exception exception) in C:\projects\flow-launcher\Flow.Launcher\ReportWindow.xaml.cs:line 23
   at Flow.Launcher.Helper.ErrorReporting.Report(Exception e) in C:\projects\flow-launcher\Flow.Launcher\Helper\ErrorReporting.cs:line 15
   at Flow.Launcher.Helper.ErrorReporting.DispatcherUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\Helper\ErrorReporting.cs:line 28
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.15.0

### Windows Build Number

10.0.22621.1555

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by Garulf** [comment]
@DeepVoyager253

**Comment by DeepVoyager253** [comment]
> @DeepVoyager253 are you able to look at this?

I figured out the problem was coming from the yt_dlp installation, so I tried opening pip on the flow python installation, when I realized, this is only on the flow launcher python installation. This also could be why it's passing the unit tests. so I changed it to my private python instance, and it worked fine. it could be because Flow runs python 3.8. I think the best way to resolve this is to have my plugin use python 3.11. I'll try changing the python version and get a fresh install of the plugin. I'll update soon.

**Comment by Garulf** [comment]
On second look I don't see an error from the plugin in the error log. This might be a Flow thing?

**Comment by VictoriousRaptor** [comment]
> On second look I don't see an error from the plugin in the error log. This might be a Flow thing?

Is the URL format of the plugin's issue page correct?

**Comment by DeepVoyager253** [comment]
. 

> > On second look I don't see an error from the plugin in the error log. This might be a Flow thing?
> 
> Is the URL format of the plugin's issue page correct? Which plugin is `yt`?

I'm not sure as when I switch to my private python installation it works fine

**Comment by deefrawley** [comment]
> > On second look I don't see an error from the plugin in the error log. This might be a Flow thing?
> 
> Is the URL format of the plugin's issue page correct? Which plugin is `yt`?

YouTube downloader.
There is a duplicate issue in the plugins repo. Suggest we close this and point the OP to that one.

**Comment by VictoriousRaptor** [comment]
Please check https://github.com/DeepVoyager253/FlowLauncherYTDownload/issues/2
