### ISSUE TITLE
BUG: System.IO.IOException: The process cannot access the file 'C:\Users\theph\AppData\Local\Temp\Droplex\Everything1_4_1_1009'

### ISSUE THREAD

**Issue by thephung-kk** [Flow-Launcher/Flow.Launcher#2126]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Flow Launcher version: 1.15.0
OS Version: 22621.1555
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 05/09/2023 10:50:21
Exception:
System.IO.IOException: The process cannot access the file 'C:\Users\theph\AppData\Local\Temp\Droplex\Everything1_4_1_1009' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at Droplex.Downloader.Get(String url, String filePath)
   at Droplex.DroplexPackage.Drop(App app, String zipExtractPath)
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingDownloadHelper.PromptDownloadIfNotInstallAsync(String installedLocation, IPublicAPI api) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingDownloadHelper.cs:line 47
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingSearchManager.ClickToInstallEverythingAsync(ActionContext _) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingSearchManager.cs:line 45
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 277
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.15.0

### Windows Build Number

OS Version: 22621.1555

### Error Log

[2023-05-09.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/11427054/2023-05-09.txt)

**Comment by deefrawley** [comment]
Hi. Were you using search with Everything or trying to install it?

**Comment by jjw24** [comment]
Hi there, please exit flow and remove this folder C:\Users\theph\AppData\Local\Temp\Droplex. Should work after doing so.

Please reopen issue if still a problem.
