### ISSUE TITLE
BUG: Edge New Feature Workspaces Crash Browser Bookmarks

### ISSUE THREAD

**Issue by changeforan** [Flow-Launcher/Flow.Launcher#2158]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

The new feature of Edge [Workspaces](https://blogs.windows.com/msedgedev/2023/04/05/edge-workspaces-preview/) will somehow save the Workspaces as a bookmark which can not be loaded by the current ChromiumBookmarkLoader, and crash the browser bookmarks plugin.

### To Reproduce

1. Upgrade Microsoft Edge to 111.0.1661.51 (or higher)
2. Create a Workspaces
3. Restart Flow-Launcher

### Flow Launcher Version

1.15.0

### Windows Build Number

10.0.22000.1936

### Error Log

<details>

```shell

10:49:32.8786+08:00 - ERROR - PluginManager.InitializePluginsAsync - Fail to Init plugin: Browser Bookmarks
EXCEPTION OCCURS: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at JsonElement System.Text.Json.JsonElement.GetProperty(string propertyName)
   at void Flow.Launcher.Plugin.BrowserBookmark.ChromiumBookmarkLoader.EnumerateFolderBookmark(JsonElement folderElement, List<Bookmark> bookmarks, string source) in C:/projects/flow-launcher/Plugins/Flow.Launcher.Plugin.BrowserBookmark/ChromiumBookmarkLoader.cs:line 61
   at List<Bookmark> Flow.Launcher.Plugin.BrowserBookmark.ChromiumBookmarkLoader.LoadBookmarksFromFile(string path, string source) in C:/projects/flow-launcher/Plugins/Flow.Launcher.Plugin.BrowserBookmark/ChromiumBookmarkLoader.cs:line 44
   at List<Bookmark> Flow.Launcher.Plugin.BrowserBookmark.ChromiumBookmarkLoader.LoadBookmarks(string browserDataPath, string name) in C:/projects/flow-launcher/Plugins/Flow.Launcher.Plugin.BrowserBookmark/ChromiumBookmarkLoader.cs:line 27
   at List<Bookmark> Flow.Launcher.Plugin.BrowserBookmark.EdgeBookmarkLoader.LoadEdgeBookmarks() in C:/projects/flow-launcher/Plugins/Flow.Launcher.Plugin.BrowserBookmark/EdgeBookmarkLoader.cs:line 16
   at List<Bookmark> Flow.Launcher.Plugin.BrowserBookmark.EdgeBookmarkLoader.GetBookmarks() in C:/projects/flow-launcher/Plugins/Flow.Launcher.Plugin.BrowserBookmark/EdgeBookmarkLoader.cs:line 24
   at List<Bookmark> Flow.Launcher.Plugin.BrowserBookmark.Commands.BookmarkLoader.LoadAllBookmarks(Settings setting) in C:/projects/flow-launcher/Plugins/Flow.Launcher.Plugin.BrowserBookmark/Commands/BookmarkLoader.cs:line 42
   at void Flow.Launcher.Plugin.BrowserBookmark.Main.Init(PluginInitContext context) in C:/projects/flow-launcher/Plugins/Flow.Launcher.Plugin.BrowserBookmark/Main.cs:line 32
   at Task Flow.Launcher.Plugin.IPlugin.Flow.Launcher.Plugin.IAsyncPlugin.InitAsync(PluginInitContext context)+() => { } in /_/Flow.Launcher.Plugin/Interfaces/IPlugin.cs:line 33
   at async Task<long> Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(string message, Func<Task> action) in C:/projects/flow-launcher/Flow.Launcher.Infrastructure/Stopwatch.cs:line 34
   at async Task Flow.Launcher.Core.Plugin.PluginManager.InitializePluginsAsync(IPublicAPI api)+(?) => { } in C:/projects/flow-launcher/Flow.Launcher.Core/Plugin/PluginManager.cs:line 125

```
</details>

**Comment by VictoriousRaptor** [comment]
Hi, I can't find how to open workspace in Edge so could you provide us your bookmark file as an example? Of course please remove any sensitive data before uploading it.

**Comment by Krzemien97** [comment]
I got the same error. Please take a look at my Bookmarks file:
[Bookmarks.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/11638246/Bookmarks.txt)

**Comment by Luxosity** [comment]
Resolution is to delete any workspaces you have created in Edge, close Edge, kill any open edge processes in task manager, enable Bookmarks Plugin in Flow Launcher, close and reopen Flow Launcher and I was able to use the plugin. Might not need all these steps but they are the steps I took!

I've done this successfully twice now on my business and personal computer.

**Comment by nathanrwiley** [comment]
I suspect I'm in the same boat. I have been extensively using Edge Workspaces since the feature was released, so the "resolution" posted by Luxosity is not viable for me.

```
Flow Launcher version: 1.16.0
OS Version: 22621.1992
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 08/03/2023 07:32:55
Exception:
Browser Bookmarks Exception: 
Websites: https://github.com/Flow-Launcher/Flow.Launcher
Author: qianlifeng, Ioannis G.
Version: 3.1.2
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: The given key was not present in the dictionary.
 ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at Flow.Launcher.Plugin.BrowserBookmark.ChromiumBookmarkLoader.EnumerateFolderBookmark(JsonElement folderElement, List`1 bookmarks, String source) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\ChromiumBookmarkLoader.cs:line 60
   at Flow.Launcher.Plugin.BrowserBookmark.ChromiumBookmarkLoader.LoadBookmarksFromFile(String path, String source) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\ChromiumBookmarkLoader.cs:line 43
   at Flow.Launcher.Plugin.BrowserBookmark.ChromiumBookmarkLoader.LoadBookmarks(String browserDataPath, String name) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\ChromiumBookmarkLoader.cs:line 26
   at Flow.Launcher.Plugin.BrowserBookmark.EdgeBookmarkLoader.LoadEdgeBookmarks() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\EdgeBookmarkLoader.cs:line 13
   at Flow.Launcher.Plugin.BrowserBookmark.EdgeBookmarkLoader.GetBookmarks() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\EdgeBookmarkLoader.cs:line 21
   at Flow.Launcher.Plugin.BrowserBookmark.Commands.BookmarkLoader.LoadAllBookmarks(Settings setting) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\Commands\BookmarkLoader.cs:line 42
   at Flow.Launcher.Plugin.BrowserBookmark.Main.LoadBookmarksIfEnabled() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\Main.cs:line 44
   at Flow.Launcher.Plugin.BrowserBookmark.Main.Query(Query query) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\Main.cs:line 54
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 850
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Attack825** [comment]
Same situation
