### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by iamagoodacc** [Flow-Launcher/Flow.Launcher#2206]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Unable to open theme gallery, and create a new theme

### To Reproduce

1. go into app
2. go to appearance
3. cannot open theme gallery nor get help by clicking 'How to create a theme'

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/136936807/e464656d-9e79-49a4-9415-0aca173de3f7)

### Flow Launcher Version

1.15.0

### Windows Build Number

10.0.22000.2057

### Error Log

<details>

```shell

Flow Launcher version: 1.15.0
OS Version: 22000.2057
IntPtr Length: 8
x64: True

Python Path: D:\Python\pythonw.exe
Node Path: 
Date: 06/28/2023 13:21:50
Exception:
System.ComponentModel.Win32Exception (5): An error occurred trying to start process 'https://github.com/Flow-Launcher/Flow.Launcher/discussions/1438' with working directory 'C:\Users\wangz\AppData\Local\FlowLauncher\app-1.15.0'. Access is denied.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Flow.Launcher.Plugin.SharedCommands.SearchWeb.OpenInBrowserTab(String url, String browserPath, Boolean inPrivate, String privateArg) in /_/Flow.Launcher.Plugin/SharedCommands/SearchWeb.cs:line 108
   at Flow.Launcher.PublicAPIInstance.OpenUri(Uri uri, Nullable`1 inPrivate) in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 228
   at Flow.Launcher.PublicAPIInstance.OpenUrl(String url, Nullable`1 inPrivate) in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 249
   at Flow.Launcher.SettingWindow.OnRequestNavigate(Object sender, RequestNavigateEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\SettingWindow.xaml.cs:line 219
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Documents.Hyperlink.NavigateToUri(IInputElement sourceElement, Uri targetUri, String targetWindow)
   at System.Windows.Documents.Hyperlink.OnClick()
   at System.Windows.Documents.Hyperlink.OnMouseLeftButtonUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.ContentElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


```
</details>

**Comment by iamagoodacc** [comment]
Fixed.
