### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by TMADZ2007** [Flow-Launcher/Flow.Launcher#2220]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

1. I add the link to use YT downloader to download mp3 and it crashes everytime I hit entear

### Flow Launcher Version

1.15

### Windows Build Number

10.0.19045.2006

### Error Log

Flow Launcher version: 1.15.0
OS Version: 19045.2006
IntPtr Length: 8
x64: True

Python Path: C:\Users\TMADZ\AppData\Local\Programs\Python\Python311\pythonw.exe
Node Path: 
Date: 07/05/2023 15:49:16
Exception:
System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\TMADZ\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\TMADZ\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
             ^^^^^^^^^^^^^
  File "C:\Users\TMADZ\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TMADZ\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TMADZ\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TMADZ\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\TMADZ\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\main.py", line 68, in <module>
    YoutubeDownload()
  File "C:\Users\TMADZ\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\flowlauncher\FlowLauncher.py", line 33, in __init__
    results = request_method(*request_parameters)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TMADZ\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\main.py", line 53, in download_audio
    video = youtube.streams.filter(only_audio=True).first()
            ^^^^^^^^^^^^^^^
  File "C:\Users\TMADZ\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\TMADZ\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\TMADZ\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
             ^^^^^^^^^^^^^
  File "C:\Users\TMADZ\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TMADZ\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TMADZ\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TMADZ\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.<>c__DisplayClass19_0.<<ParseResults>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 139
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 277
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by deefrawley** [comment]
Hi, this is a problem with the plugin. Can you please post in that repo as ti seems the plugin has issues 

https://github.com/DeepVoyager253/FlowLauncherYTDownload/issues
