### ISSUE TITLE
BUG: this opens every time flow launches

### ISSUE THREAD

**Issue by Dhappa771** [Flow-Launcher/Flow.Launcher#2251]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Flow Launcher version: 1.16.0
OS Version: 19045.3208
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 07/21/2023 00:41:54
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Dictionary.Main.Save() in C:\Users\Null\Documents\Projects\Flow.Launcher.Dictionary\src\Dictionary.cs:line 375
   at Flow.Launcher.Core.Plugin.PluginManager.Save() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 56
   at Flow.Launcher.PublicAPIInstance.SaveAppAllSettings() in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 84
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 105
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 51
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.16.0

### Windows Build Number

10.0.19045.3208

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

[2023-07-21.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/12113397/2023-07-21.txt)

**Comment by deefrawley** [comment]
This is showing the Dictionary plugin as the source of the issue. Can you perhaps uninstall and reinstall that?
Have you downloaded the dictionary file as per https://github.com/harrynull/Flow.Launcher.Dictionary

**Comment by jjw24** [comment]
Same as issues identified in https://github.com/harrynull/Flow.Launcher.Dictionary/issues/21.

@Dhappa771 are you using the latest Dictionary version 2.3.2?
