### ISSUE TITLE
BUG: Not able to open file containing folder

### ISSUE THREAD

**Issue by creative-aarush** [Flow-Launcher/Flow.Launcher#2255]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Flow Launcher version: 1.16.0
OS Version: 22621.1992
IntPtr Length: 8
x64: True

Python Path: C:\Users\creat\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 07/25/2023 13:59:46
Exception:
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Program Files (x86)\Everything\Everything.exe' with working directory 'C:\WINDOWS\system32'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at Flow.Launcher.PublicAPIInstance.OpenDirectory(String DirectoryPath, String FileNameOrFilePath) in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 245
   at Flow.Launcher.Plugin.Program.Programs.Win32.<ContextMenus>b__54_4(ActionContext _) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Program\Programs\Win32.cs:line 249
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 221
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 286
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

![chrome_d8CycCsGji](https://github.com/Flow-Launcher/Flow.Launcher/assets/130273894/fe951550-19eb-4d05-bcd4-a48d45f54064)
![Flow Launcher_xyOE7kUeVS](https://github.com/Flow-Launcher/Flow.Launcher/assets/130273894/9327153d-1ea8-42da-ac70-1e17772eee9b)

### Flow Launcher Version

1.16.0

### Windows Build Number

22621.1992

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

[2023-07-25.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/12158906/2023-07-25.txt)

**Comment by z1nc0r3** [comment]
Please check whether your **Everything Path** is correct.

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/64279853/64f0bc03-1f9f-4e82-8c92-8dc32ce4a9a4)

**Comment by creative-aarush** [comment]
It is same as shown in the picture,

**Comment by deefrawley** [comment]
If it is the same as is shown in z1nc0r3's screenshot then you have the wrong directory (the error is looking in Program Files (x86) instead of Program Fiiles).
Can you check where you Everything install is and make sure it matches the path in the Explorer plugin settings?

**Comment by jjw24** [comment]
Can you clear out "Everything Path" field, close settings window and restart flow. You should get a prompt asking you to install everything, choose to let flow automatically install it for you.

Once done and you are still getting an error, please post the log here again and a screenshot of your "Everything Path" in settings.
