### ISSUE TITLE
BUG: Lancher (portable) crashes immediataly

### ISSUE THREAD

**Issue by wowiwax** [Flow-Launcher/Flow.Launcher#2259]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Launcher crashes immediately after typing somethign in. Its possible to open the command line but then it crashes.

### To Reproduce

1. Start Luancher using shortctu Alt+Space
2. Start typing something in
3. Launcher immediataly crashes

### Flow Launcher Version

1.16 (Portable)

### Windows Build Number

10.0.19044.2965

### Error Log

Flow Launcher version: 1.16.0
OS Version: 19044.2965
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 07/27/2023 07:23:06
Exception:
Explorer Exception: 
Websites: https://github.com/Flow-Launcher/Flow.Launcher
Author: Jeremy Wu
Version: 3.1.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Das System kann die angegebene Datei nicht finden. (0x80070002)
 ---> System.IO.FileNotFoundException: Das System kann die angegebene Datei nicht finden. (0x80070002)
   at Microsoft.Search.Interop.CSearchQueryHelperClass.GenerateSQLFromUserQuery(String pszQuery)
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.QueryConstructor.FilesAndFolders(ReadOnlySpan`1 userSearchString) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\QueryConstructor.cs:line 80
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndexSearchManager.WindowsIndexFilesAndFoldersSearchAsync(ReadOnlySpan`1 querySearchString, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\WindowsIndexSearchManager.cs:line 52
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.WindowsIndexSearchManager.SearchAsync(String search, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\WindowsIndexSearchManager.cs:line 87
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 100
   at Flow.Launcher.Plugin.Explorer.Main.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Main.cs:line 62
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 193
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 813
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
hey there, the error message seems to suggest the system can not find the stated file. Did you just type one letter or was there a specific query you typed?
