### ISSUE TITLE
BUG: from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions pyo3_runtime.PanicException: Python API call failed

### ISSUE THREAD

**Issue by kylernocturnalnerd** [Flow-Launcher/Flow.Launcher#2261]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

When creating a python plugin sometimes libraries fail to load.
In my case, _cffi_backend seems to not load even when import path is set correctly.

Below are the relevant errors:
```
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: ModuleNotFoundError: No module named '_cffi_backend'
thread '<unnamed>' panicked at 'Python API call failed', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\pyo3-0.18.3\src\err\mod.rs:790:5
```
...
```
from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
pyo3_runtime.PanicException: Python API call failed
```
I can confirm that the library works in other contexts:

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/84939608/ccee552f-f8f2-412b-b3d4-348a0b9ba557)

### To Reproduce

1. Install the Hello World Python Plugin `pm install Hello World Python by Flow Launcher`
2. add paramiko to requirements
3. `pip install -r requirements.txt -t ./lib`
4. add `import paramiko` to main.py
5. reload flow launcher
6. activate plugin with `hp`

### Flow Launcher Version

1.16.0

### Windows Build Number

 22621.1992

### Error Log

<details>

```shell
Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues
1. upload log file: C:\Users\krobinson\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.16.0\UserData\Logs\1.16.0\2023-07-28.txt
2. copy below exception message

Flow Launcher version: 1.16.0
OS Version: 22621.1992
IntPtr Length: 8
x64: True

Python Path: C:\Users\krobinson\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.16.0\UserData\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 07/28/2023 14:50:08
Exception:
Hello World Python Exception: 
Websites: https://github.com/Flow-Launcher/Flow.Launcher.Plugin.HelloWorldPython
Author: Flow Launcher
Version: 1.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: ModuleNotFoundError: No module named '_cffi_backend'
thread '<unnamed>' panicked at 'Python API call failed', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\pyo3-0.18.3\src\err\mod.rs:790:5
stack backtrace:
   0:     0x7ff9c8e79552 - PyInit__rust
   1:     0x7ff9c8e88bab - PyInit__rust
   2:     0x7ff9c8e771ca - PyInit__rust
   3:     0x7ff9c8e7929b - PyInit__rust
   4:     0x7ff9c8e7b24a - PyInit__rust
   5:     0x7ff9c8e7aeb0 - PyInit__rust
   6:     0x7ff9c8e7b926 - PyInit__rust
   7:     0x7ff9c8e15349 - PyInit__rust
   8:     0x7ff9c8e150a9 - PyInit__rust
   9:     0x7ff9c90cdc2d - PyInit__openssl
  10:     0x7ff9c8e13611 - PyInit__rust
  11:     0x7ff9c8cd9708 - PyInit__rust
  12:     0x7ff9c8c4dba0 - <unknown>
  13:     0x7ff9c8e0d587 - PyInit__rust
  14:     0x7ff9c8c4de36 - PyInit__rust
  15:     0x7ff9c95ebf70 - PyMapping_GetItemString
  16:     0x7ff9c95ec147 - PyMapping_GetItemString
  17:     0x7ff9c95ec0a5 - PyMapping_GetItemString
  18:     0x7ff9c95d9f18 - PyObject_CallFunctionObjArgs
  19:     0x7ff9c963e35e - PyVectorcall_Call
  20:     0x7ff9c963e22f - PySequence_GetItem
  21:     0x7ff9c95e49d3 - PyEval_EvalFrameDefault
  22:     0x7ff9c95dc7f8 - PyEval_EvalCodeWithName
  23:     0x7ff9c95ddf7f - PyFunction_Vectorcall
  24:     0x7ff9c95e3118 - PyEval_EvalFrameDefault
  25:     0x7ff9c95e0ca6 - PyEval_EvalFrameDefault
  26:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
  27:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
  28:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
  29:     0x7ff9c95dde9d - PyFunction_Vectorcall
  30:     0x7ff9c961887b - PyObject_CallMethodObjArgs
  31:     0x7ff9c9618384 - PyObject_CallMethodIdObjArgs
  32:     0x7ff9c96558f1 - PyArg_ParseStackAndKeywords_SizeT
  33:     0x7ff9c963ca48 - PyImport_ImportModuleLevelObject
  34:     0x7ff9c96c1e1e - PyPickleBuffer_GetBuffer
  35:     0x7ff9c95e71d1 - PyEval_EvalFrameDefault
  36:     0x7ff9c95dc7f8 - PyEval_EvalCodeWithName
  37:     0x7ff9c95bc78b - PyEval_EvalCodeEx
  38:     0x7ff9c95bc6e9 - PyEval_EvalCode
  39:     0x7ff9c95bc8ed - PyEval_EvalCodeEx
  40:     0x7ff9c95bc7f7 - PyEval_EvalCodeEx
  41:     0x7ff9c95d9f18 - PyObject_CallFunctionObjArgs
  42:     0x7ff9c963e35e - PyVectorcall_Call
  43:     0x7ff9c963e22f - PySequence_GetItem
  44:     0x7ff9c95e49d3 - PyEval_EvalFrameDefault
  45:     0x7ff9c95dc7f8 - PyEval_EvalCodeWithName
  46:     0x7ff9c95ddf7f - PyFunction_Vectorcall
  47:     0x7ff9c95e3118 - PyEval_EvalFrameDefault
  48:     0x7ff9c95e0ca6 - PyEval_EvalFrameDefault
  49:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
  50:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
  51:     0x7ff9c95dde9d - PyFunction_Vectorcall
  52:     0x7ff9c961887b - PyObject_CallMethodObjArgs
  53:     0x7ff9c9618384 - PyObject_CallMethodIdObjArgs
  54:     0x7ff9c96558f1 - PyArg_ParseStackAndKeywords_SizeT
  55:     0x7ff9c963ca48 - PyImport_ImportModuleLevelObject
  56:     0x7ff9c96c1e1e - PyPickleBuffer_GetBuffer
  57:     0x7ff9c95e71d1 - PyEval_EvalFrameDefault
  58:     0x7ff9c95dc7f8 - PyEval_EvalCodeWithName
  59:     0x7ff9c95bc78b - PyEval_EvalCodeEx
  60:     0x7ff9c95bc6e9 - PyEval_EvalCode
  61:     0x7ff9c95bc8ed - PyEval_EvalCodeEx
  62:     0x7ff9c95bc7f7 - PyEval_EvalCodeEx
  63:     0x7ff9c95d9f18 - PyObject_CallFunctionObjArgs
  64:     0x7ff9c963e35e - PyVectorcall_Call
  65:     0x7ff9c963e22f - PySequence_GetItem
  66:     0x7ff9c95e49d3 - PyEval_EvalFrameDefault
  67:     0x7ff9c95dc7f8 - PyEval_EvalCodeWithName
  68:     0x7ff9c95ddf7f - PyFunction_Vectorcall
  69:     0x7ff9c95e3118 - PyEval_EvalFrameDefault
  70:     0x7ff9c95e0ca6 - PyEval_EvalFrameDefault
  71:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
  72:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
  73:     0x7ff9c95dde9d - PyFunction_Vectorcall
  74:     0x7ff9c961887b - PyObject_CallMethodObjArgs
  75:     0x7ff9c9618384 - PyObject_CallMethodIdObjArgs
  76:     0x7ff9c96558f1 - PyArg_ParseStackAndKeywords_SizeT
  77:     0x7ff9c963ca48 - PyImport_ImportModuleLevelObject
  78:     0x7ff9c96c1e1e - PyPickleBuffer_GetBuffer
  79:     0x7ff9c95e71d1 - PyEval_EvalFrameDefault
  80:     0x7ff9c95dc7f8 - PyEval_EvalCodeWithName
  81:     0x7ff9c95bc78b - PyEval_EvalCodeEx
  82:     0x7ff9c95bc6e9 - PyEval_EvalCode
  83:     0x7ff9c95bc8ed - PyEval_EvalCodeEx
  84:     0x7ff9c95bc7f7 - PyEval_EvalCodeEx
  85:     0x7ff9c95d9f18 - PyObject_CallFunctionObjArgs
  86:     0x7ff9c963e35e - PyVectorcall_Call
  87:     0x7ff9c963e22f - PySequence_GetItem
  88:     0x7ff9c95e49d3 - PyEval_EvalFrameDefault
  89:     0x7ff9c95dc7f8 - PyEval_EvalCodeWithName
  90:     0x7ff9c95ddf7f - PyFunction_Vectorcall
  91:     0x7ff9c95e3118 - PyEval_EvalFrameDefault
  92:     0x7ff9c95e0ca6 - PyEval_EvalFrameDefault
  93:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
  94:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
  95:     0x7ff9c95dde9d - PyFunction_Vectorcall
  96:     0x7ff9c961887b - PyObject_CallMethodObjArgs
  97:     0x7ff9c9618384 - PyObject_CallMethodIdObjArgs
  98:     0x7ff9c96558f1 - PyArg_ParseStackAndKeywords_SizeT
  99:     0x7ff9c963ca48 - PyImport_ImportModuleLevelObject
 100:     0x7ff9c96c1e1e - PyPickleBuffer_GetBuffer
 101:     0x7ff9c95e71d1 - PyEval_EvalFrameDefault
 102:     0x7ff9c95dc7f8 - PyEval_EvalCodeWithName
 103:     0x7ff9c95bc78b - PyEval_EvalCodeEx
 104:     0x7ff9c95bc6e9 - PyEval_EvalCode
 105:     0x7ff9c95bc8ed - PyEval_EvalCodeEx
 106:     0x7ff9c95bc7f7 - PyEval_EvalCodeEx
 107:     0x7ff9c95d9f18 - PyObject_CallFunctionObjArgs
 108:     0x7ff9c963e35e - PyVectorcall_Call
 109:     0x7ff9c963e22f - PySequence_GetItem
 110:     0x7ff9c95e49d3 - PyEval_EvalFrameDefault
 111:     0x7ff9c95dc7f8 - PyEval_EvalCodeWithName
 112:     0x7ff9c95ddf7f - PyFunction_Vectorcall
 113:     0x7ff9c95e3118 - PyEval_EvalFrameDefault
 114:     0x7ff9c95e0ca6 - PyEval_EvalFrameDefault
 115:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
 116:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
 117:     0x7ff9c95dde9d - PyFunction_Vectorcall
 118:     0x7ff9c961887b - PyObject_CallMethodObjArgs
 119:     0x7ff9c9618384 - PyObject_CallMethodIdObjArgs
 120:     0x7ff9c96558f1 - PyArg_ParseStackAndKeywords_SizeT
 121:     0x7ff9c963ca48 - PyImport_ImportModuleLevelObject
 122:     0x7ff9c96c1e1e - PyPickleBuffer_GetBuffer
 123:     0x7ff9c95e71d1 - PyEval_EvalFrameDefault
 124:     0x7ff9c95dc7f8 - PyEval_EvalCodeWithName
 125:     0x7ff9c95bc78b - PyEval_EvalCodeEx
 126:     0x7ff9c95bc6e9 - PyEval_EvalCode
 127:     0x7ff9c95bc8ed - PyEval_EvalCodeEx
 128:     0x7ff9c95bc7f7 - PyEval_EvalCodeEx
 129:     0x7ff9c95d9f18 - PyObject_CallFunctionObjArgs
 130:     0x7ff9c963e35e - PyVectorcall_Call
 131:     0x7ff9c963e22f - PySequence_GetItem
 132:     0x7ff9c95e49d3 - PyEval_EvalFrameDefault
 133:     0x7ff9c95dc7f8 - PyEval_EvalCodeWithName
 134:     0x7ff9c95ddf7f - PyFunction_Vectorcall
 135:     0x7ff9c95e3118 - PyEval_EvalFrameDefault
 136:     0x7ff9c95e0ca6 - PyEval_EvalFrameDefault
 137:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
 138:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
 139:     0x7ff9c95dde9d - PyFunction_Vectorcall
 140:     0x7ff9c961887b - PyObject_CallMethodObjArgs
 141:     0x7ff9c9618384 - PyObject_CallMethodIdObjArgs
 142:     0x7ff9c96558f1 - PyArg_ParseStackAndKeywords_SizeT
 143:     0x7ff9c963ca48 - PyImport_ImportModuleLevelObject
 144:     0x7ff9c96c1e1e - PyPickleBuffer_GetBuffer
 145:     0x7ff9c95e71d1 - PyEval_EvalFrameDefault
 146:     0x7ff9c95dc7f8 - PyEval_EvalCodeWithName
 147:     0x7ff9c95bc78b - PyEval_EvalCodeEx
 148:     0x7ff9c95bc6e9 - PyEval_EvalCode
 149:     0x7ff9c95bbcd6 - PyFuture_FromASTObject
 150:     0x7ff9c95bbc65 - PyFuture_FromASTObject
 151:     0x7ff9c969d9bb - PyRun_SimpleFileExFlags
 152:     0x7ff9c969d7cc - PyRun_SimpleFileExFlags
 153:     0x7ff9c969d697 - PyRun_SimpleFileExFlags
 154:     0x7ff9c97a7583 - PyRun_AnyFileExFlags
 155:     0x7ff9c97565b9 - Py_gitversion
 156:     0x7ff9c95feeb0 - Py_RunMain
 157:     0x7ff9c95febb5 - Py_RunMain
 158:     0x7ff9c95fe6b9 - Py_Main
 159:     0x7ff718501262 - <unknown>
 160:     0x7ffa963e26ad - BaseThreadInitThunk
 161:     0x7ffa970caa68 - RtlUserThreadStart
Traceback (most recent call last):
  File "C:\Users\krobinson\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.16.0\UserData\Plugins\Hello World Python-1.0.0\main.py", line 11, in <module>
    import paramiko
  File "C:\Users\krobinson\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.16.0\UserData\Plugins\Hello World Python-1.0.0\lib\paramiko\__init__.py", line 22, in <module>
    from paramiko.transport import (
  File "C:\Users\krobinson\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.16.0\UserData\Plugins\Hello World Python-1.0.0\lib\paramiko\transport.py", line 33, in <module>
    from cryptography.hazmat.primitives.ciphers import algorithms, Cipher, modes
  File "C:\Users\krobinson\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.16.0\UserData\Plugins\Hello World Python-1.0.0\lib\cryptography\hazmat\primitives\ciphers\__init__.py", line 11, in <module>
    from cryptography.hazmat.primitives.ciphers.base import (
  File "C:\Users\krobinson\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.16.0\UserData\Plugins\Hello World Python-1.0.0\lib\cryptography\hazmat\primitives\ciphers\base.py", line 10, in <module>
    from cryptography.exceptions import (
  File "C:\Users\krobinson\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.16.0\UserData\Plugins\Hello World Python-1.0.0\lib\cryptography\exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
pyo3_runtime.PanicException: Python API call failed

 ---> System.IO.InvalidDataException: ModuleNotFoundError: No module named '_cffi_backend'
thread '<unnamed>' panicked at 'Python API call failed', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\pyo3-0.18.3\src\err\mod.rs:790:5
stack backtrace:
   0:     0x7ff9c8e79552 - PyInit__rust
   1:     0x7ff9c8e88bab - PyInit__rust
   2:     0x7ff9c8e771ca - PyInit__rust
   3:     0x7ff9c8e7929b - PyInit__rust
   4:     0x7ff9c8e7b24a - PyInit__rust
   5:     0x7ff9c8e7aeb0 - PyInit__rust
   6:     0x7ff9c8e7b926 - PyInit__rust
   7:     0x7ff9c8e15349 - PyInit__rust
   8:     0x7ff9c8e150a9 - PyInit__rust
   9:     0x7ff9c90cdc2d - PyInit__openssl
  10:     0x7ff9c8e13611 - PyInit__rust
  11:     0x7ff9c8cd9708 - PyInit__rust
  12:     0x7ff9c8c4dba0 - <unknown>
  13:     0x7ff9c8e0d587 - PyInit__rust
  14:     0x7ff9c8c4de36 - PyInit__rust
  15:     0x7ff9c95ebf70 - PyMapping_GetItemString
  16:     0x7ff9c95ec147 - PyMapping_GetItemString
  17:     0x7ff9c95ec0a5 - PyMapping_GetItemString
  18:     0x7ff9c95d9f18 - PyObject_CallFunctionObjArgs
  19:     0x7ff9c963e35e - PyVectorcall_Call
  20:     0x7ff9c963e22f - PySequence_GetItem
  21:     0x7ff9c95e49d3 - PyEval_EvalFrameDefault
  22:     0x7ff9c95dc7f8 - PyEval_EvalCodeWithName
  23:     0x7ff9c95ddf7f - PyFunction_Vectorcall
  24:     0x7ff9c95e3118 - PyEval_EvalFrameDefault
  25:     0x7ff9c95e0ca6 - PyEval_EvalFrameDefault
  26:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
  27:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
  28:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
  29:     0x7ff9c95dde9d - PyFunction_Vectorcall
  30:     0x7ff9c961887b - PyObject_CallMethodObjArgs
  31:     0x7ff9c9618384 - PyObject_CallMethodIdObjArgs
  32:     0x7ff9c96558f1 - PyArg_ParseStackAndKeywords_SizeT
  33:     0x7ff9c963ca48 - PyImport_ImportModuleLevelObject
  34:     0x7ff9c96c1e1e - PyPickleBuffer_GetBuffer
  35:     0x7ff9c95e71d1 - PyEval_EvalFrameDefault
  36:     0x7ff9c95dc7f8 - PyEval_EvalCodeWithName
  37:     0x7ff9c95bc78b - PyEval_EvalCodeEx
  38:     0x7ff9c95bc6e9 - PyEval_EvalCode
  39:     0x7ff9c95bc8ed - PyEval_EvalCodeEx
  40:     0x7ff9c95bc7f7 - PyEval_EvalCodeEx
  41:     0x7ff9c95d9f18 - PyObject_CallFunctionObjArgs
  42:     0x7ff9c963e35e - PyVectorcall_Call
  43:     0x7ff9c963e22f - PySequence_GetItem
  44:     0x7ff9c95e49d3 - PyEval_EvalFrameDefault
  45:     0x7ff9c95dc7f8 - PyEval_EvalCodeWithName
  46:     0x7ff9c95ddf7f - PyFunction_Vectorcall
  47:     0x7ff9c95e3118 - PyEval_EvalFrameDefault
  48:     0x7ff9c95e0ca6 - PyEval_EvalFrameDefault
  49:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
  50:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
  51:     0x7ff9c95dde9d - PyFunction_Vectorcall
  52:     0x7ff9c961887b - PyObject_CallMethodObjArgs
  53:     0x7ff9c9618384 - PyObject_CallMethodIdObjArgs
  54:     0x7ff9c96558f1 - PyArg_ParseStackAndKeywords_SizeT
  55:     0x7ff9c963ca48 - PyImport_ImportModuleLevelObject
  56:     0x7ff9c96c1e1e - PyPickleBuffer_GetBuffer
  57:     0x7ff9c95e71d1 - PyEval_EvalFrameDefault
  58:     0x7ff9c95dc7f8 - PyEval_EvalCodeWithName
  59:     0x7ff9c95bc78b - PyEval_EvalCodeEx
  60:     0x7ff9c95bc6e9 - PyEval_EvalCode
  61:     0x7ff9c95bc8ed - PyEval_EvalCodeEx
  62:     0x7ff9c95bc7f7 - PyEval_EvalCodeEx
  63:     0x7ff9c95d9f18 - PyObject_CallFunctionObjArgs
  64:     0x7ff9c963e35e - PyVectorcall_Call
  65:     0x7ff9c963e22f - PySequence_GetItem
  66:     0x7ff9c95e49d3 - PyEval_EvalFrameDefault
  67:     0x7ff9c95dc7f8 - PyEval_EvalCodeWithName
  68:     0x7ff9c95ddf7f - PyFunction_Vectorcall
  69:     0x7ff9c95e3118 - PyEval_EvalFrameDefault
  70:     0x7ff9c95e0ca6 - PyEval_EvalFrameDefault
  71:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
  72:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
  73:     0x7ff9c95dde9d - PyFunction_Vectorcall
  74:     0x7ff9c961887b - PyObject_CallMethodObjArgs
  75:     0x7ff9c9618384 - PyObject_CallMethodIdObjArgs
  76:     0x7ff9c96558f1 - PyArg_ParseStackAndKeywords_SizeT
  77:     0x7ff9c963ca48 - PyImport_ImportModuleLevelObject
  78:     0x7ff9c96c1e1e - PyPickleBuffer_GetBuffer
  79:     0x7ff9c95e71d1 - PyEval_EvalFrameDefault
  80:     0x7ff9c95dc7f8 - PyEval_EvalCodeWithName
  81:     0x7ff9c95bc78b - PyEval_EvalCodeEx
  82:     0x7ff9c95bc6e9 - PyEval_EvalCode
  83:     0x7ff9c95bc8ed - PyEval_EvalCodeEx
  84:     0x7ff9c95bc7f7 - PyEval_EvalCodeEx
  85:     0x7ff9c95d9f18 - PyObject_CallFunctionObjArgs
  86:     0x7ff9c963e35e - PyVectorcall_Call
  87:     0x7ff9c963e22f - PySequence_GetItem
  88:     0x7ff9c95e49d3 - PyEval_EvalFrameDefault
  89:     0x7ff9c95dc7f8 - PyEval_EvalCodeWithName
  90:     0x7ff9c95ddf7f - PyFunction_Vectorcall
  91:     0x7ff9c95e3118 - PyEval_EvalFrameDefault
  92:     0x7ff9c95e0ca6 - PyEval_EvalFrameDefault
  93:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
  94:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
  95:     0x7ff9c95dde9d - PyFunction_Vectorcall
  96:     0x7ff9c961887b - PyObject_CallMethodObjArgs
  97:     0x7ff9c9618384 - PyObject_CallMethodIdObjArgs
  98:     0x7ff9c96558f1 - PyArg_ParseStackAndKeywords_SizeT
  99:     0x7ff9c963ca48 - PyImport_ImportModuleLevelObject
 100:     0x7ff9c96c1e1e - PyPickleBuffer_GetBuffer
 101:     0x7ff9c95e71d1 - PyEval_EvalFrameDefault
 102:     0x7ff9c95dc7f8 - PyEval_EvalCodeWithName
 103:     0x7ff9c95bc78b - PyEval_EvalCodeEx
 104:     0x7ff9c95bc6e9 - PyEval_EvalCode
 105:     0x7ff9c95bc8ed - PyEval_EvalCodeEx
 106:     0x7ff9c95bc7f7 - PyEval_EvalCodeEx
 107:     0x7ff9c95d9f18 - PyObject_CallFunctionObjArgs
 108:     0x7ff9c963e35e - PyVectorcall_Call
 109:     0x7ff9c963e22f - PySequence_GetItem
 110:     0x7ff9c95e49d3 - PyEval_EvalFrameDefault
 111:     0x7ff9c95dc7f8 - PyEval_EvalCodeWithName
 112:     0x7ff9c95ddf7f - PyFunction_Vectorcall
 113:     0x7ff9c95e3118 - PyEval_EvalFrameDefault
 114:     0x7ff9c95e0ca6 - PyEval_EvalFrameDefault
 115:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
 116:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
 117:     0x7ff9c95dde9d - PyFunction_Vectorcall
 118:     0x7ff9c961887b - PyObject_CallMethodObjArgs
 119:     0x7ff9c9618384 - PyObject_CallMethodIdObjArgs
 120:     0x7ff9c96558f1 - PyArg_ParseStackAndKeywords_SizeT
 121:     0x7ff9c963ca48 - PyImport_ImportModuleLevelObject
 122:     0x7ff9c96c1e1e - PyPickleBuffer_GetBuffer
 123:     0x7ff9c95e71d1 - PyEval_EvalFrameDefault
 124:     0x7ff9c95dc7f8 - PyEval_EvalCodeWithName
 125:     0x7ff9c95bc78b - PyEval_EvalCodeEx
 126:     0x7ff9c95bc6e9 - PyEval_EvalCode
 127:     0x7ff9c95bc8ed - PyEval_EvalCodeEx
 128:     0x7ff9c95bc7f7 - PyEval_EvalCodeEx
 129:     0x7ff9c95d9f18 - PyObject_CallFunctionObjArgs
 130:     0x7ff9c963e35e - PyVectorcall_Call
 131:     0x7ff9c963e22f - PySequence_GetItem
 132:     0x7ff9c95e49d3 - PyEval_EvalFrameDefault
 133:     0x7ff9c95dc7f8 - PyEval_EvalCodeWithName
 134:     0x7ff9c95ddf7f - PyFunction_Vectorcall
 135:     0x7ff9c95e3118 - PyEval_EvalFrameDefault
 136:     0x7ff9c95e0ca6 - PyEval_EvalFrameDefault
 137:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
 138:     0x7ff9c95e0bbd - PyEval_EvalFrameDefault
 139:     0x7ff9c95dde9d - PyFunction_Vectorcall
 140:     0x7ff9c961887b - PyObject_CallMethodObjArgs
 141:     0x7ff9c9618384 - PyObject_CallMethodIdObjArgs
 142:     0x7ff9c96558f1 - PyArg_ParseStackAndKeywords_SizeT
 143:     0x7ff9c963ca48 - PyImport_ImportModuleLevelObject
 144:     0x7ff9c96c1e1e - PyPickleBuffer_GetBuffer
 145:     0x7ff9c95e71d1 - PyEval_EvalFrameDefault
 146:     0x7ff9c95dc7f8 - PyEval_EvalCodeWithName
 147:     0x7ff9c95bc78b - PyEval_EvalCodeEx
 148:     0x7ff9c95bc6e9 - PyEval_EvalCode
 149:     0x7ff9c95bbcd6 - PyFuture_FromASTObject
 150:     0x7ff9c95bbc65 - PyFuture_FromASTObject
 151:     0x7ff9c969d9bb - PyRun_SimpleFileExFlags
 152:     0x7ff9c969d7cc - PyRun_SimpleFileExFlags
 153:     0x7ff9c969d697 - PyRun_SimpleFileExFlags
 154:     0x7ff9c97a7583 - PyRun_AnyFileExFlags
 155:     0x7ff9c97565b9 - Py_gitversion
 156:     0x7ff9c95feeb0 - Py_RunMain
 157:     0x7ff9c95febb5 - Py_RunMain
 158:     0x7ff9c95fe6b9 - Py_Main
 159:     0x7ff718501262 - <unknown>
 160:     0x7ffa963e26ad - BaseThreadInitThunk
 161:     0x7ffa970caa68 - RtlUserThreadStart
Traceback (most recent call last):
  File "C:\Users\krobinson\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.16.0\UserData\Plugins\Hello World Python-1.0.0\main.py", line 11, in <module>
    import paramiko
  File "C:\Users\krobinson\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.16.0\UserData\Plugins\Hello World Python-1.0.0\lib\paramiko\__init__.py", line 22, in <module>
    from paramiko.transport import (
  File "C:\Users\krobinson\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.16.0\UserData\Plugins\Hello World Python-1.0.0\lib\paramiko\transport.py", line 33, in <module>
    from cryptography.hazmat.primitives.ciphers import algorithms, Cipher, modes
  File "C:\Users\krobinson\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.16.0\UserData\Plugins\Hello World Python-1.0.0\lib\cryptography\hazmat\primitives\ciphers\__init__.py", line 11, in <module>
    from cryptography.hazmat.primitives.ciphers.base import (
  File "C:\Users\krobinson\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.16.0\UserData\Plugins\Hello World Python-1.0.0\lib\cryptography\hazmat\primitives\ciphers\base.py", line 10, in <module>
    from cryptography.exceptions import (
  File "C:\Users\krobinson\Downloads\Flow-Launcher-Portable\FlowLauncher\app-1.16.0\UserData\Plugins\Hello World Python-1.0.0\lib\cryptography\exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
pyo3_runtime.PanicException: Python API call failed

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 193
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 813
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```
</details>

**Comment by deefrawley** [comment]
It looks like paramiko has a dependency on a low level Rust library it pulls in. Is that being packaged properly into the Flow local library path? @Garulf might be able to assist more.

**Comment by Garulf** [comment]
Packages using compiled code are restricted to the version of Python used to install them.

So if you install the `paramiko` using Python 3.8 it will not work with any other versions of Python.
