### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by 1975Tanker** [Flow-Launcher/Flow.Launcher#2262]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues
1. upload log file: C:\Users\hi\AppData\Roaming\FlowLauncher\Logs\1.16.0\2023-07-29.txt
2. copy below exception message

Flow Launcher version: 1.16.0
OS Version: 19045.3208
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 07/29/2023 13:03:39
Exception:
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'MsiExec.exe \Everything.exe' with working directory 'C:\Users\hi\AppData\Local\FlowLauncher\app-1.16.0'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingSearchManager.ClickToInstallEverythingAsync(ActionContext _) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingSearchManager.cs:line 55
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 286
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

[2023-07-29.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/12206397/2023-07-29.txt)

### Flow Launcher Version

1.16.0

### Windows Build Number

19045.3208

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by jjw24** [comment]
This looks like an issue with you trying to install Everything via Flow. Could you try reinstalling it.
