### ISSUE TITLE
BUG: Cannot install any plugin

### ISSUE THREAD

**Issue by Winches** [Flow-Launcher/Flow.Launcher#2264]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

[log file](https://github.com/Flow-Launcher/Flow.Launcher/files/12209271/2023-07-30.txt)
Cannot download any plugin or check update.

### To Reproduce

1. Find plugin in store.
2. Install plguin.

### Screenshots

- Http proxy
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/7054776/1e0bd4cc-58ed-47e3-b98a-4ffa28d8e9e5)
- Check update
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/7054776/75fcae8c-ac5d-4d74-a094-3f4a2f995f87)
- Install everything
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/7054776/a6150a4d-b677-442b-b933-e42f10da5406)

### Flow Launcher Version

1.16.0

### Windows Build Number

10.0.22621.2070

### Error Log

<details>

```shell

Exception:
System.Net.Http.HttpRequestException: 不知道这样的主机。 (http:80)
 ---> System.Net.Sockets.SocketException (11001): 不知道这样的主机。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Droplex.Downloader.Get(String url, String filePath)
   at Droplex.DroplexPackage.Drop(App app, String zipExtractPath)
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingDownloadHelper.PromptDownloadIfNotInstallAsync(String installedLocation, IPublicAPI api) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingDownloadHelper.cs:line 46
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingSearchManager.ClickToInstallEverythingAsync(ActionContext _) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingSearchManager.cs:line 45
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 286
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```
</details>

**Comment by z1nc0r3** [comment]
Did you try installing a plugin using a _direct connection_ (without proxy)?
