### ISSUE TITLE
BUG: Window Walker Exception - FlowPluginException - Parameter 'destinationArray'

### ISSUE THREAD

**Issue by vemundha** [Flow-Launcher/Flow.Launcher#2288]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [ ] I am using the latest version of Flow Launcher.

### Problem Description

Please open new issue in: https://www.windowwalker.com/
1. upload log file: C:\Users\vemhal2\AppData\Roaming\FlowLauncher\Logs\1.16.0\2023-08-14.txt
2. copy below exception message

Flow Launcher version: 1.16.0
OS Version: 22631.2191
IntPtr Length: 8
x64: True

Python Path: C:\Users\vemhal2\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 08/14/2023 07:44:47
Exception:
Window Walker Exception: 
Websites: https://www.windowwalker.com/
Author: betadele
Version: 2.2.2
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
 ---> System.ArgumentException: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Flow.Plugin.WindowWalker.Components.OpenWindows.get_Windows() in D:\a\Flow.Plugin.WindowWalker\Flow.Plugin.WindowWalker\Components\OpenWindows.cs:line 33
   at Flow.Plugin.WindowWalker.Components.SearchController.OpenWindowsWithModel() in D:\a\Flow.Plugin.WindowWalker\Flow.Plugin.WindowWalker\Components\SearchController.cs:line 51
   at Flow.Plugin.WindowWalker.Components.SearchController.GetResult(String searchText, Boolean searchWindowsAcrossAllVDesktop) in D:\a\Flow.Plugin.WindowWalker\Flow.Plugin.WindowWalker\Components\SearchController.cs:line 41
   at Flow.Plugin.WindowWalker.Main.Query(Query query) in D:\a\Flow.Plugin.WindowWalker\Flow.Plugin.WindowWalker\Main.cs:line 74
   at Flow.Launcher.Plugin.IPlugin.<>c__DisplayClass3_0.<Flow.Launcher.Plugin.IAsyncPlugin.QueryAsync>b__0() in /_/Flow.Launcher.Plugin/Interfaces/IPlugin.cs:line 35
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 193
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 813
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandle
[2023-08-14.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/12331760/2023-08-14.txt)
r)

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.16.0

### Windows Build Number

Win11 22631.2191

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by taooceros** [comment]
Seems to be a racing bug. Move to https://github.com/taooceros/Flow.Plugin.WindowWalker/issues/48
