### ISSUE TITLE
BUG: Browser Bookmarks crashes

### ISSUE THREAD

**Issue by Shazzik** [Flow-Launcher/Flow.Launcher#2302]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Using the "b" shortcut for browser bookmarks gives a "Flow Launcher got an error" message. I am using Edge as my browser.

Log file: [2023-08-21.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/12401712/2023-08-21.txt)

### Flow Launcher Version

1.16.1

### Windows Build Number

19045.3324

### Error Log

Flow Launcher version: 1.16.1
OS Version: 19045.3324
IntPtr Length: 8
x64: True

Python Path: C:\Users\anser\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 08/21/2023 21:25:09
Exception:
Browser Bookmarks Exception: 
Websites: https://github.com/Flow-Launcher/Flow.Launcher
Author: qianlifeng, Ioannis G.
Version: 3.1.3
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: The given key was not present in the dictionary.
 ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at Flow.Launcher.Plugin.BrowserBookmark.ChromiumBookmarkLoader.EnumerateFolderBookmark(JsonElement folderElement, List`1 bookmarks, String source) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\ChromiumBookmarkLoader.cs:line 60
   at Flow.Launcher.Plugin.BrowserBookmark.ChromiumBookmarkLoader.LoadBookmarksFromFile(String path, String source) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\ChromiumBookmarkLoader.cs:line 43
   at Flow.Launcher.Plugin.BrowserBookmark.ChromiumBookmarkLoader.LoadBookmarks(String browserDataPath, String name) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\ChromiumBookmarkLoader.cs:line 26
   at Flow.Launcher.Plugin.BrowserBookmark.EdgeBookmarkLoader.LoadEdgeBookmarks() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\EdgeBookmarkLoader.cs:line 13
   at Flow.Launcher.Plugin.BrowserBookmark.EdgeBookmarkLoader.GetBookmarks() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\EdgeBookmarkLoader.cs:line 21
   at Flow.Launcher.Plugin.BrowserBookmark.Commands.BookmarkLoader.LoadAllBookmarks(Settings setting) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\Commands\BookmarkLoader.cs:line 42
   at Flow.Launcher.Plugin.BrowserBookmark.Main.LoadBookmarksIfEnabled() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\Main.cs:line 44
   at Flow.Launcher.Plugin.BrowserBookmark.Main.Query(Query query) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\Main.cs:line 54
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 850
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
From a glance, potentially caused by the browser you are using, maybe they updated something.

What browser and it's version are you using?

**Comment by Shazzik** [comment]
> From a glance, potentially caused by the browser you are using, maybe they updated something.
> 
> What browser and it's version are you using?

Thank

**Comment by Shazzik** [comment]
Thank you for your answer!

I'm using Edge as my browser, the default Windows pre-installed one, not a beta build or anything.

As for the version of Edge I was using at the time of the bug: I'm not sure, but it was the latest one as my browser auto-updates every time I launch it.

I've since uninstalled the browser bookmarks plugin in order to reinstall it (hoping it would fix the issue), but I couldn't find it in the plugin store. I thus downloaded the latest portable version of Flow and as soon as I typed "b" in Flow I got the error, it didn't crash Flow though. But when I restarted Flow I got a notification saying "Fail to Init Plugins: Browser Bookmarks - fail to load and would be disabled, please contact plugin creator for help", and the plugin was disabled in my plugin manager.

The version of Edge I'm currently using is: Version 116.0.1938.81 (Official build) (64-bit). It appears to be the latest.

**Comment by Shazzik** [comment]
Flow version 1.16.2 seems to have fixed the issue, thanks everyone ❤
