### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Whyguy0417** [Flow-Launcher/Flow.Launcher#2353]
[2023-09-18.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/12648523/2023-09-18.txt)
Exception:
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\KittellWyL\AppData\Roaming\FlowLauncher\Plugins\Shortcuts-1.0.6\Config\shortcuts.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at Flow.Launcher.Plugin.ShortcutPlugin.Repositories.ShortcutsRepository.SaveShortcuts()
   at Flow.Launcher.Plugin.ShortcutPlugin.Repositories.ShortcutsRepository.AddShortcut(Shortcut shortcut)
   at Flow.Launcher.Plugin.ShortcutPlugin.Repositories.CommandsRepository.<>c__DisplayClass43_0.<CreateFileShortcutHandler>b__0()
   at Flow.Launcher.Plugin.ShortcutPlugin.Extensions.ResultExtensions.<>c__DisplayClass4_0.<SingleResult>b__0(ActionContext _)
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 221
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 286
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by deefrawley** [comment]
This error appears to be happening with the Shortcuts plugin. Please post the issue there

https://github.com/mantasjasikenas/flow-launcher-shortcuts-plugin
