### ISSUE TITLE
BUG: Setting topmost query gives exception error

### ISSUE THREAD

**Issue by angurishu** [Flow-Launcher/Flow.Launcher#2358]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Even though it does work, I get an exception error when I want to put something as the topmost query. I wanted to use the general converter and improved currency convertor plugins, so I installed those, found the python folder, and that was the last thing I did. When I try to set something as the top query after that, this occurs; it didn't previously.

### To Reproduce

1. Search something
2. Press right arrow key for extra options for whatever you searched
3. Click Set as topmost in this query

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/29866281/ebcc2397-2579-4cb6-a9be-1570a90dc703)

### Flow Launcher Version

1.16.1

### Windows Build Number

Microsoft Windows [Version 10.0.22621.2283]

### Error Log

<details>

```shell


Message:
Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues
1. upload log file: C:\Users\Shane\AppData\Roaming\FlowLauncher\Logs\1.16.1\2023-09-26.txt
2. copy below exception message

Flow Launcher version: 1.16.1
OS Version: 22621.2283
IntPtr Length: 8
x64: True

Python Path: C:\Python311\pythonw.exe
Node Path: 
Date: 09/26/2023 12:50:35
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Flow.Launcher.Storage.UserSelectedRecord.GenerateQueryAndResultHashCode(Query query, Result result) in C:\projects\flow-launcher\Flow.Launcher\Storage\UserSelectedRecord.cs:line 59
   at Flow.Launcher.Storage.UserSelectedRecord.Add(Result result) in C:\projects\flow-launcher\Flow.Launcher\Storage\UserSelectedRecord.cs:line 80
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 286
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

File: 
[2023-09-26.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/12724166/2023-09-26.txt)


```
</details>

**Comment by angurishu** [comment]
Okay, I reinstalled flow launcher to the latest version and it was working fine until I installed the better currency plugin:
https://github.com/LeLocTai/Flow.Launcher.Plugin.CurrencyPP

**Comment by deefrawley** [comment]
Hi. Is it the same error and does it happen the same way (setting topmost query via context menu)?
Can you also upgrade Flow to the latest version and see if that helps (1.16.2)?

**Comment by deefrawley** [comment]
Please update to the latest version and if the problem persists we can reopen the issue. Thanks
