### ISSUE TITLE
BUG: Error when creating shortcut with shortcut plugin

### ISSUE THREAD

**Issue by legolasdimir** [Flow-Launcher/Flow.Launcher#2361]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

I have installed and attempted to add a shortcut using the shortcut plugin version 1.0.6 using the command 
```
q add URL obsidian://show-plugin?id=%20
```

Here is the exception message that came up
```
Flow Launcher version: 1.16.2
OS Version: 22621.2283
IntPtr Length: 8
x64: True

Python Path: C:\Users\bryan.pruett\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 09/26/2023 08:21:31
Exception:
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\bryan.pruett\AppData\Roaming\FlowLauncher\Plugins\Shortcuts-1.0.6\Config\shortcuts.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at Flow.Launcher.Plugin.ShortcutPlugin.Repositories.ShortcutsRepository.SaveShortcuts()
   at Flow.Launcher.Plugin.ShortcutPlugin.Repositories.ShortcutsRepository.AddShortcut(Shortcut shortcut)
   at Flow.Launcher.Plugin.ShortcutPlugin.Repositories.CommandsRepository.<>c__DisplayClass42_0.<CreateUrlShortcutHandler>b__0()
   at Flow.Launcher.Plugin.ShortcutPlugin.Extensions.ResultExtensions.<>c__DisplayClass4_0.<SingleResult>b__0(ActionContext _)
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 221
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 286
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### To Reproduce

1. Install shortcuts version 1.0.6
2. add a shortcut using the following command

```
q add URL obsidian://show-plugin?id=%20
```

### Flow Launcher Version

1.16.2

### Windows Build Number

Microsoft Windows [Version 10.0.22621.2283]

### Error Log

[2023-09-26.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/12728745/2023-09-26.txt)

**Comment by deefrawley** [comment]
Hi,
Could you raise this in the plugin repo please?
https://github.com/mantasjasikenas/flow-launcher-shortcuts-plugin
thanks
