### ISSUE TITLE
BUG: error when copy from plugin Base Converter

### ISSUE THREAD

**Issue by scorpionTaj** [Flow-Launcher/Flow.Launcher#2362]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Flow Launcher version: 1.16.2
OS Version: 22621.2283
IntPtr Length: 8
x64: True

Python Path: C:\Program Files\Python311\pythonw.exe
Node Path: C:\Users\scorpion\AppData\Roaming\nvm\v18.16.0\node.exe
Date: 09/26/2023 18:31:23
Exception:
System.MissingMethodException: Method not found: 'Void Flow.Launcher.Plugin.IPublicAPI.CopyToClipboard(System.String)'.
   at BarLauncher.EasyHelper.Flow.Launcher.Service.FlowLauncherSystemService.CopyTextToClipboard(String text)
   at BarLauncher.BaseConverter.Lib.Service.BaseResultFinder.<>c__DisplayClass20_0.<GetConvertResults>b__0() in D:\a\BarLauncher-BaseConverter\BarLauncher-BaseConverter\BarLauncher.BaseConverter.Lib\Service\BaseResultFinder.cs:line 237
   at BarLauncher.EasyHelper.Service.BarLauncherContextServiceBase.<>c__DisplayClass8_0.<GetActionResult>b__0()
   at BarLauncher.EasyHelper.Flow.Launcher.Service.ResultService.<>c__DisplayClass5_0.<MapResults>b__0(ActionContext e)
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 221
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 286
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/96800858/1ddd0f5d-8626-4f7c-9a71-4d8e52a1f90b)

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/96800858/02282a0e-dde9-456a-a423-513c513980ef)

### Flow Launcher Version

1.16.2

### Windows Build Number

10.0.22621.2283

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by taooceros** [comment]
I suggest you to file an issue on https://github.com/gissehel/BarLauncher-BaseConverter.
