### ISSUE TITLE
BUG: error after updating

### ISSUE THREAD

**Issue by nuayoung** [Flow-Launcher/Flow.Launcher#2371]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Got an error after updating to the latest version. Attached below is the log.

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

[2023-09-30.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/12770978/2023-09-30.txt)

### Flow Launcher Version

1.16.2

### Windows Build Number

10.0.22621.2070

### Error Log

<details>

```shell

Flow Launcher version: 1.16.2
OS Version: 22621.2070
IntPtr Length: 8
x64: True

Python Path: C:\Users\nuayo\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 09/30/2023 03:30:13
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Flow.Launcher.ViewModel.SettingWindowViewModel.DisplayPluginQuery(String queryToDisplay, PluginPair plugin, Int32 actionKeywordPosition) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\SettingWindowViewModel.cs:line 388
   at Flow.Launcher.SettingWindow.OnExternalPluginInstallClick(Object sender, RoutedEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\SettingWindow.xaml.cs:line 292
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


```
</details>

**Comment by taooceros** [comment]
This seems to be an error happening during installing a new plugin?
