### ISSUE TITLE
BUG: Browsers Bookmark Plugin

### ISSUE THREAD

**Issue by 1208nn** [Flow-Launcher/Flow.Launcher#2375]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

* can not be load when start up
* error when re-enable it and active it through the search box
* in ver 1.16.1 works well
* uninstalled and reinstalled times and error again

### To Reproduce

1. Alt+tab
2. input its active chars(mine is `bm`)

### Flow Launcher Version

1.16.2

### Windows Build Number

win 10 stable latest

### Error Log

```
浏览器书签 Exception: 
Websites: https://github.com/Flow-Launcher/Flow.Launcher
Author: qianlifeng, Ioannis G.
Version: 3.1.4
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: The given key was not present in the dictionary.
 ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at Flow.Launcher.Plugin.BrowserBookmark.ChromiumBookmarkLoader.EnumerateFolderBookmark(JsonElement folderElement, List`1 bookmarks, String source) in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\ChromiumBookmarkLoader.cs:line 68
   at Flow.Launcher.Plugin.BrowserBookmark.ChromiumBookmarkLoader.LoadBookmarksFromFile(String path, String source) in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\ChromiumBookmarkLoader.cs:line 43
   at Flow.Launcher.Plugin.BrowserBookmark.ChromiumBookmarkLoader.LoadBookmarks(String browserDataPath, String name) in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\ChromiumBookmarkLoader.cs:line 26
   at Flow.Launcher.Plugin.BrowserBookmark.EdgeBookmarkLoader.LoadEdgeBookmarks() in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\EdgeBookmarkLoader.cs:line 13
   at Flow.Launcher.Plugin.BrowserBookmark.EdgeBookmarkLoader.GetBookmarks() in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\EdgeBookmarkLoader.cs:line 21
   at Flow.Launcher.Plugin.BrowserBookmark.Commands.BookmarkLoader.LoadAllBookmarks(Settings setting) in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\Commands\BookmarkLoader.cs:line 42
   at Flow.Launcher.Plugin.BrowserBookmark.Main.LoadBookmarksIfEnabled() in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\Main.cs:line 44
   at Flow.Launcher.Plugin.BrowserBookmark.Main.Query(Query query) in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\Main.cs:line 54
   at Flow.Launcher.Plugin.IPlugin.<>c__DisplayClass3_0.<Flow.Launcher.Plugin.IAsyncPlugin.QueryAsync>b__0() in /_/Flow.Launcher.Plugin/Interfaces/IPlugin.cs:line 35
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 193
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 813
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by deefrawley** [comment]
What browsers are you loading bookmarks from (in the Settings)?

**Comment by 1208nn** [comment]
for the main three, on my pc, any of installed browsers will cause it.

i has not try other browsers.

chrome 46.0
Edge latest (117)
Firefox 118.0

tried uninstall chrome and Firefox(only error when they are installed)
