### ISSUE TITLE
BUG: flow launcher Fend calculator causes crash

### ISSUE THREAD

**Issue by Toreuse** [Flow-Launcher/Flow.Launcher#2376]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

after installing Fend Calculator all commands end in error message 'Flow launcher got an error'

### To Reproduce

1. install Fend Calculator
2. ...
3. ...

### Flow Launcher Version

1.16.2

### Windows Build Number

19045.3448

### Error Log

<details>

```shell

Flow Launcher version: 1.16.2
OS Version: 19045.3448
IntPtr Length: 8
x64: True

Python Path: C:\Users\pvipo\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 10/01/2023 14:45:45
Exception:
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Flow.Launcher.PublicAPIInstance.OpenUrl(String url, Nullable`1 inPrivate) in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 279
   at Flow.Launcher.Plugin.WebSearch.Main.<>c__DisplayClass9_1.<QueryAsync>b__1(ActionContext c) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.WebSearch\Main.cs:line 76
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 221
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 286
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


```
</details>

**Comment by jjw24** [comment]
Hi there, please submit this error to the Fend calculator repository so the author can address it.
