### ISSUE TITLE
BUG: edge bookmarks search fail

### ISSUE THREAD

**Issue by thomasTAT** [Flow-Launcher/Flow.Launcher#2386]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [ ] I am using the latest version of Flow Launcher.

### Problem Description

BUG: edge bookmarks search fail

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.16.2

### Windows Build Number

22621.2361

### Error Log

Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues
1. upload log file: C:\Users\thoma\AppData\Roaming\FlowLauncher\Logs\1.16.2\2023-10-07.txt
2. copy below exception message

Flow Launcher version: 1.16.2
OS Version: 22621.2361
IntPtr Length: 8
x64: True

Python Path: C:\Users\thoma\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 10/07/2023 23:29:59
Exception:
Browser Bookmarks Exception: 
Websites: https://github.com/Flow-Launcher/Flow.Launcher
Author: qianlifeng, Ioannis G.
Version: 3.1.4
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: The given key was not present in the dictionary.
 ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at Flow.Launcher.Plugin.BrowserBookmark.ChromiumBookmarkLoader.EnumerateFolderBookmark(JsonElement folderElement, List`1 bookmarks, String source) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\ChromiumBookmarkLoader.cs:line 60
   at Flow.Launcher.Plugin.BrowserBookmark.ChromiumBookmarkLoader.LoadBookmarksFromFile(String path, String source) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\ChromiumBookmarkLoader.cs:line 43
   at Flow.Launcher.Plugin.BrowserBookmark.ChromiumBookmarkLoader.LoadBookmarks(String browserDataPath, String name) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\ChromiumBookmarkLoader.cs:line 26
   at Flow.Launcher.Plugin.BrowserBookmark.EdgeBookmarkLoader.LoadEdgeBookmarks() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\EdgeBookmarkLoader.cs:line 13
   at Flow.Launcher.Plugin.BrowserBookmark.EdgeBookmarkLoader.GetBookmarks() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\EdgeBookmarkLoader.cs:line 21
   at Flow.Launcher.Plugin.BrowserBookmark.Commands.BookmarkLoader.LoadAllBookmarks(Settings setting) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\Commands\BookmarkLoader.cs:line 42
   at Flow.Launcher.Plugin.BrowserBookmark.Main.LoadBookmarksIfEnabled() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\Main.cs:line 44
   at Flow.Launcher.Plugin.BrowserBookmark.Main.Query(Query query) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\Main.cs:line 54
   at Flow.Launcher.Plugin.IPlugin.<>c__DisplayClass3_0.<Flow.Launcher.Plugin.IAsyncPlugin.QueryAsync>b__0() in /_/Flow.Launcher.Plugin/Interfaces/IPlugin.cs:line 35
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 193
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 813
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by thomasTAT** [comment]
able to search chrome bookmark.

**Comment by VictoriousRaptor** [comment]
Fixed in #2378. Please try our latest prerelease or wait for next stable release.
