### ISSUE TITLE
浏览器书签插件 崩溃

### ISSUE THREAD

**Issue by photkey** [Flow-Launcher/Flow.Launcher#2391]
LOG：[2023-10-13.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/12885351/2023-10-13.txt)

Flow Launcher version: 1.16.2
OS Version: 22621.2428
IntPtr Length: 8
x64: True

Python Path: D:\MySoft\FlowLauncher\app-1.16.2\UserData\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 10/13/2023 00:55:23
Exception:
浏览器书签 Exception: 
Websites: https://github.com/Flow-Launcher/Flow.Launcher
Author: qianlifeng, Ioannis G.
Version: 3.1.4
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Unable to load DLL 'SQLite.Interop.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
 ---> System.DllNotFoundException: Unable to load DLL 'SQLite.Interop.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
   at System.Data.SQLite.UnsafeNativeMethods.sqlite3_open_interop(Byte[] utf8Filename, Byte[] vfsName, SQLiteOpenFlagsEnum flags, Int32 extFuncs, IntPtr& db)
   at System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
   at System.Data.SQLite.SQLiteConnection.Open()
   at Flow.Launcher.Plugin.BrowserBookmark.FirefoxBookmarkLoaderBase.GetBookmarksFromPath(String placesPath) in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\FirefoxBookmarkLoader.cs:line 38
   at Flow.Launcher.Plugin.BrowserBookmark.FirefoxBookmarkLoader.GetBookmarks() in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\FirefoxBookmarkLoader.cs:line 59
   at Flow.Launcher.Plugin.BrowserBookmark.Commands.BookmarkLoader.LoadAllBookmarks(Settings setting) in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\Commands\BookmarkLoader.cs:line 35
   at Flow.Launcher.Plugin.BrowserBookmark.Main.LoadBookmarksIfEnabled() in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\Main.cs:line 44
   at Flow.Launcher.Plugin.BrowserBookmark.Main.Query(Query query) in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\Main.cs:line 54
   at Flow.Launcher.Plugin.IPlugin.<>c__DisplayClass3_0.<Flow.Launcher.Plugin.IAsyncPlugin.QueryAsync>b__0() in /_/Flow.Launcher.Plugin/Interfaces/IPlugin.cs:line 35
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 193
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 813
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by zhj9709** [comment]
我书签功能会突然失效，看了下日志好像也没报错，关闭书签插件后重新启用又正常了

**Comment by zhj9709** [comment]
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/13991774/dc286fe0-f233-458d-825b-c025bb2a8b55)

我会出现这样的问题，但我看日志里也没报错
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/13991774/26965525-a48d-4593-b4d7-a7b73efdc932)

**Comment by taooceros** [comment]
试试重装书签插件？

**Comment by taooceros** [comment]
@photkey please check the prerelease https://github.com/Flow-Launcher/Prereleases/releases

**Comment by deefrawley** [comment]
No update, closing
