### ISSUE TITLE
BUG: Browser Bookmarks plugin not working

### ISSUE THREAD

**Issue by zhj9709** [Flow-Launcher/Flow.Launcher#2395]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

BrowserBookmark plugin not working.

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/13991774/4bbe2b4b-cf77-4e40-8bd8-5a8b4e976ed6)

When I unchecked chrome and re-checked chrome, it started working fine.

### To Reproduce

1. alt+space to show flow launcher
2. Enter keywork b

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/13991774/9d7e2d6a-6e7a-441e-8cff-565cfa09638a)

### Flow Launcher Version

v1.16.1,  v1.16.2

### Windows Build Number

Windows11 22635.2483

### Error Log

```shell
09:04:09.2956+08:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
09:04:09.2956+08:00 - ERROR -  - 
Exception full name: System.IO.FileNotFoundException
Error status: UNKNOWN
Class name: Win32
Calling method: ExeProgram
Program path: C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.3.17.0_x64__8wekyb3d8bbwe\msrdc.exe
InnerException number: 1
Exception message: C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.3.17.0_x64__8wekyb3d8bbwe\msrdc.exe
Exception error type: HResult -2147024894
Exception thrown in called method: System.Diagnostics.FileVersionInfo GetVersionInfo(System.String)
Possible interpretation of the error: File not found when trying to load the program from C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_1.3.17.0_x64__8wekyb3d8bbwe\msrdc.exe
Possible resolution: Not yet known
09:04:09.2956+08:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
09:04:10.2123+08:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
09:04:10.2123+08:00 - ERROR -  - 
Exception full name: System.Runtime.InteropServices.COMException
Error status: UNKNOWN
Class name: IShellLinkW
Calling method: retrieveTargetPath
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Windows Media Player Legacy.lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Not yet known
09:04:10.2123+08:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
09:04:10.2557+08:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
09:04:10.2557+08:00 - ERROR -  - 
Exception full name: System.Runtime.InteropServices.COMException
Error status: UNKNOWN
Class name: IShellLinkW
Calling method: retrieveTargetPath
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\ODBC Data Sources (32-bit).lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Not yet known
09:04:10.2557+08:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------

```

**Comment by deefrawley** [comment]
> When I unchecked chrome and re-checked chrome, it started working fine.

Hi. Is this working now or does the error return when you restart Flow?

**Comment by zhj9709** [comment]
> > When I unchecked chrome and re-checked chrome, it started working fine.
> 
> Hi. Is this working now or does the error return when you restart Flow?

It can work normally most of the time, but occasionally it doesn't work. When I restart Flow, I may still have this problem after a while.

**Comment by deefrawley** [comment]
Ok, will leave open and see if one of the team can assist

**Comment by taooceros** [comment]
Could you check the latest prerelease? We change the SQLite lib used in browser plugin.

**Comment by zhj9709** [comment]
> Could you check the latest prerelease? We change the SQLite lib used in browser plugin.

可以提供一下下载链接吗

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/13991774/b6670777-37c8-477f-b88a-6e53d25affcd)

**Comment by taooceros** [comment]
https://github.com/Flow-Launcher/Prereleases/releases

**Comment by zhj9709** [comment]
> https://github.com/Flow-Launcher/Prereleases/releases

更新了，但问题还是存在
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/13991774/b50a26f4-e49e-48fe-a6e9-5fdeb7dca72a)

**Comment by taooceros** [comment]
发下报错吧

**Comment by zhj9709** [comment]
> 发下报错吧，我回错问题了prerelease应该会修另一个issue
> 
> 你前面的报错是常见现象跟这个无关

```
00:00:11.4180+08:00 - INFO  - Updater.UpdateApp - Future Release <{
  "SHA1": "8F28D1D91AC6829EE310E7A217C9BC4416F0272C",
  "BaseUrl": null,
  "Filename": "FlowLauncher-1.16.2-full.nupkg",
  "Query": null,
  "Filesize": 93464021,
  "IsDelta": false,
  "StagingPercentage": null,
  "EntryAsString": "8F28D1D91AC6829EE310E7A217C9BC4416F0272C FlowLauncher-1.16.2-full.nupkg 93464021",
  "Version": {
    "Version": "1.16.2.0",
    "SpecialVersion": ""
  },
  "PackageName": "FlowLauncher"
}>
10:02:58.8081+08:00 - INFO  - App.OnStartup - Begin Flow Launcher startup ----------------------------------------------------
10:02:58.8081+08:00 - INFO  - App.OnStartup - Runtime info:
Flow Launcher version: 1.16.2
OS Version: 22635.2552
IntPtr Length: 8
x64: True
10:03:00.6127+08:00 - INFO  - ImageLoader.Initialize - Preload images cost <1623ms>
10:03:00.6127+08:00 - INFO  - ImageLoader.Initialize - Number of preload images is <88>, Images Number: 88, Unique Items 39
10:03:00.7218+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Plugin Indicator> is <45ms>
10:03:00.7218+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Process Killer> is <45ms>
10:03:00.7218+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <System Commands> is <64ms>
10:03:00.7218+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <URL> is <105ms>
10:03:00.7218+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Shell> is <105ms>
10:03:00.7218+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Web Searches> is <97ms>
10:03:00.7560+08:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://fastly.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
10:03:00.7924+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Windows Settings> is <193ms>
10:03:00.8111+08:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Preload programs cost <76ms>
10:03:00.8111+08:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Number of preload win32 programs <817>
10:03:00.8111+08:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Number of preload uwps <51>
10:03:00.8315+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Explorer> is <469ms>
10:03:00.8557+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Calculator> is <196ms>
10:03:00.9275+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Browser Bookmarks> is <292ms>
10:03:00.9275+08:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://gcore.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
10:03:00.9275+08:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://cdn.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
10:03:00.9275+08:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://raw.githubusercontent.com/Flow-Launcher/Flow.Launcher.PluginsManifest/plugin_api_v2/plugins.json
10:03:00.9469+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Program> is <415ms>
10:03:01.6299+08:00 - INFO  - CommunityPluginSource.FetchAsync - Loaded 134 plugins from https://raw.githubusercontent.com/Flow-Launcher/Flow.Launcher.PluginsManifest/plugin_api_v2/plugins.json
10:03:01.6299+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Plugins Manager> is <1003ms>
10:03:01.9758+08:00 - INFO  - App.OnStartup - Dependencies Info:
Python Path: 
Node Path: 
10:03:02.3281+08:00 - INFO  - App.OnStartup - End Flow Launcher startup ----------------------------------------------------  
10:03:02.3281+08:00 - INFO  - App.OnStartup - Startup cost <3988ms>
10:33:46.6252+08:00 - INFO  - App.OnStartup - Begin Flow Launcher startup ----------------------------------------------------
10:33:46.6252+08:00 - INFO  - App.OnStartup - Runtime info:
Flow Launcher version: 1.16.2
OS Version: 22635.2552
IntPtr Length: 8
x64: True
10:33:48.4112+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Process Killer> is <43ms>
10:33:48.4112+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Plugin Indicator> is <42ms>
10:33:48.4112+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <System Commands> is <57ms>
10:33:48.4112+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <URL> is <89ms>
10:33:48.4112+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Shell> is <95ms>
10:33:48.4112+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Web Searches> is <92ms>
10:33:48.4366+08:00 - INFO  - ImageLoader.Initialize - Preload images cost <1634ms>
10:33:48.4380+08:00 - INFO  - ImageLoader.Initialize - Number of preload images is <88>, Images Number: 88, Unique Items 39
10:33:48.4380+08:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://fastly.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
10:33:48.4776+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Windows Settings> is <187ms>
10:33:48.4959+08:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Preload programs cost <71ms>
10:33:48.4959+08:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Number of preload win32 programs <817>
10:33:48.4959+08:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Number of preload uwps <51>
10:33:48.5151+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Explorer> is <448ms>
10:33:48.5378+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Calculator> is <187ms>
10:33:48.6045+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Browser Bookmarks> is <273ms>
10:33:48.6116+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Program> is <374ms>
10:33:48.6116+08:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://gcore.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
10:33:48.6116+08:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://cdn.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
10:33:48.6116+08:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://raw.githubusercontent.com/Flow-Launcher/Flow.Launcher.PluginsManifest/plugin_api_v2/plugins.json
10:33:49.3116+08:00 - INFO  - CommunityPluginSource.FetchAsync - Loaded 134 plugins from https://raw.githubusercontent.com/Flow-Launcher/Flow.Launcher.PluginsManifest/plugin_api_v2/plugins.json
10:33:49.3145+08:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Plugins Manager> is <994ms>
10:33:49.6356+08:00 - INFO  - App.OnStartup - Dependencies Info:
Python Path: 
Node Path: 
10:33:49.8666+08:00 - INFO  - App.OnStartup - End Flow Launcher startup ----------------------------------------------------  
10:33:49.8666+08:00 - INFO  - App.OnStartup - Startup cost <3681ms>
10:34:22.0054+08:00 - INFO  - Updater.UpdateApp - Future Release <{
  "SHA1": "12EA585D8E9CEF1380D289C3C08C801130722DD4",
  "BaseUrl": null,
  "Filename": "FlowLauncher-1.16.2-full.nupkg",
  "Query": null,
  "Filesize": 103948370,
  "IsDelta": false,
  "StagingPercentage": null,
  "EntryAsString": "12EA585D8E9CEF1380D289C3C08C801130722DD4 FlowLauncher-1.16.2-full.nupkg 103948370",
  "Version": {
    "Version": "1.16.2.0",
    "SpecialVersion": ""
  },
  "PackageName": "FlowLauncher"
}>
```

这是今天的所有日志

**Comment by zillydev** [comment]
[2023-11-09.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/13304438/2023-11-09.txt)
Flow Launcher version: 1.16.2
OS Version: 19045.3570
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 11/09/2023 11:46:47
Exception:
Browser Bookmarks Exception: 
Websites: https://github.com/Flow-Launcher/Flow.Launcher
Author: qianlifeng, Ioannis G.
Version: 3.1.4
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: The given key was not present in the dictionary.
 ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at Flow.Launcher.Plugin.BrowserBookmark.ChromiumBookmarkLoader.EnumerateFolderBookmark(JsonElement folderElement, List`1 bookmarks, String source) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\ChromiumBookmarkLoader.cs:line 68
   at Flow.Launcher.Plugin.BrowserBookmark.ChromiumBookmarkLoader.LoadBookmarksFromFile(String path, String source) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\ChromiumBookmarkLoader.cs:line 43
   at Flow.Launcher.Plugin.BrowserBookmark.ChromiumBookmarkLoader.LoadBookmarks(String browserDataPath, String name) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\ChromiumBookmarkLoader.cs:line 26
   at Flow.Launcher.Plugin.BrowserBookmark.EdgeBookmarkLoader.LoadEdgeBookmarks() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\EdgeBookmarkLoader.cs:line 13
   at Flow.Launcher.Plugin.BrowserBookmark.EdgeBookmarkLoader.GetBookmarks() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\EdgeBookmarkLoader.cs:line 21
   at Flow.Launcher.Plugin.BrowserBookmark.Commands.BookmarkLoader.LoadAllBookmarks(Settings setting) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\Commands\BookmarkLoader.cs:line 42
   at Flow.Launcher.Plugin.BrowserBookmark.Main.LoadBookmarksIfEnabled() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\Main.cs:line 44
   at Flow.Launcher.Plugin.BrowserBookmark.Main.Query(Query query) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\Main.cs:line 54
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 850
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Trubador** [comment]
For the dev branch which is suppose to be the one in the windows installer the bookmarks plugin still won't work on my computer. I also see errors in the log file, seems to be it cant find a specific file but I can't get details of which file it is missing.

**Comment by Trubador** [comment]
I am pretty sure my issue with the bookmark plugin is because it can't parse the file paths I have that contain whitespace to get the png thumbnail for a link. Is there an option to disable thumbnails in the plugin or global?
In the mean time I will try to clean up my file paths

**Comment by Trubador** [comment]
I have just disabled the preview in Flow launcher and now the browser extension does not crash, it does not display icons or previews as expected but it can't find the bookmarks anyway.

**Comment by Trubador** [comment]
I have just disabled the preview in Flow Launcher and now the browser extension does not crash, it does not display icons or previews as expected but it can't find the bookmarks anyway.

**Comment by taooceros** [comment]
> I am pretty sure my issue with the bookmark plugin is because it can't parse the file paths I have that contain whitespace to get the png thumbnail for a link. Is there an option to disable thumbnails in the plugin or global? In the mean time I will try to clean up my file paths

that's from program plugin, and should probably unrelated to your problem

**Comment by taooceros** [comment]
> I have just disabled the preview in Flow launcher and now the browser extension does not crash, it does not display icons or previews as expected but it can't find the bookmarks anyway.

do you have any error report when preview is on? That seems to be very weird

**Comment by Trubador** [comment]
> > I have just disabled the preview in Flow launcher and now the browser extension does not crash, it does not display icons or previews as expected but it can't find the bookmarks anyway.
> 
> do you have any error report when preview is on? That seems to be very weird

Yes I will share it soon. Where can I find it?

**Comment by taooceros** [comment]
I think there should be a error window pop out?

**Comment by Trubador** [comment]
> I think there should be a error window pop out?

Flow Launcher version: 1.16.2
OS Version: 22621.2861
IntPtr Length: 8
x64: True

Python Path: C:\Users\caspe\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 12/18/2023 08:42:16
Exception:
Browser Bookmarks Exception: 
Websites: https://github.com/Flow-Launcher/Flow.Launcher
Author: qianlifeng, Ioannis G.
Version: 3.1.4
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: The given key was not present in the dictionary.
 ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at Flow.Launcher.Plugin.BrowserBookmark.ChromiumBookmarkLoader.EnumerateFolderBookmark(JsonElement folderElement, List`1 bookmarks, String source) in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\ChromiumBookmarkLoader.cs:line 60
   at Flow.Launcher.Plugin.BrowserBookmark.ChromiumBookmarkLoader.LoadBookmarksFromFile(String path, String source) in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\ChromiumBookmarkLoader.cs:line 43
   at Flow.Launcher.Plugin.BrowserBookmark.ChromiumBookmarkLoader.LoadBookmarks(String browserDataPath, String name) in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\ChromiumBookmarkLoader.cs:line 26
   at Flow.Launcher.Plugin.BrowserBookmark.EdgeBookmarkLoader.LoadEdgeBookmarks() in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\EdgeBookmarkLoader.cs:line 13
   at Flow.Launcher.Plugin.BrowserBookmark.EdgeBookmarkLoader.GetBookmarks() in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\EdgeBookmarkLoader.cs:line 21
   at Flow.Launcher.Plugin.BrowserBookmark.Commands.BookmarkLoader.LoadAllBookmarks(Settings setting) in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\Commands\BookmarkLoader.cs:line 42
   at Flow.Launcher.Plugin.BrowserBookmark.Main.LoadBookmarksIfEnabled() in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\Main.cs:line 44
   at Flow.Launcher.Plugin.BrowserBookmark.Main.Query(Query query) in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\Main.cs:line 54
   at Flow.Launcher.Plugin.IPlugin.<>c__DisplayClass3_0.<Flow.Launcher.Plugin.IAsyncPlugin.QueryAsync>b__0() in /_/Flow.Launcher.Plugin/Interfaces/IPlugin.cs:line 35
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 193
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 813
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


Log file:


[2023-12-18.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/13700852/2023-12-18.txt)

**Comment by jjw24** [comment]
Hey @Trubador could you test this PR build and see if it solves the issue please:

https://ci.appveyor.com/api/buildjobs/ry92b09lhr7cewfh/artifacts/Output%2FPackages%2FFlow-Launcher-Portable.zip

**Comment by Trubador** [comment]
@jjw24 thanks. it works now, when I close the everything program, the installed flow launcher, and open the portable you sent 💯 
Thanks a lot, it will save me a bunch of time :)
What change did you make and can you confirm if flow launcher or the plugin has issues with certain file paths?

**Comment by jjw24** [comment]
The error seems to be failing due to enumerating the data, which sometimes does not contain the key 'type' for reasons unknown, so @taooceros added a check to skip the step when that key doesn't exist - https://github.com/Flow-Launcher/Flow.Launcher/pull/2457/files# line 59. 

I don't know whether if it's because certain file path data doesn't contain the key or some dataset. Maybe taooceros be able to fill you in.

**Comment by Trubador** [comment]
thanks, please let me know when it is pushed to release so I can update my installed version :)

**Comment by jjw24** [comment]
Once that PR is merged in it will be available as a prerelease download, or if you prefer to wait I am aiming to release 1.17.0 before Christmas 25th Dec.

**Comment by Trubador** [comment]
I would prefer to install the pre Release for now 😁 can you instruct me how to do it ? Casper Rubæk ***@***.***
-------- Oprindelig besked --------Fra: Jeremy Wu ***@***.***> Dato: 18.12.2023  11.31  (GMT+01:00) Til: "Flow-Launcher/Flow.Launcher" ***@***.***> Cc: Casper Rubæk ***@***.***>, Mention ***@***.***> Emne: Re: [Flow-Launcher/Flow.Launcher] BUG: Browser Bookmarks plugin not working (Issue #2395) 
Once that PR is merged in it will be available as a prerelease download, or if you prefer to wait I am aiming to release 1.17.0 before Christmas 25th Dec.

**Comment by jjw24** [comment]
You can download it from here https://github.com/Flow-Launcher/Prereleases/releases.

**Comment by liang2zhu1** [comment]
@jjw24 Thanks for fixing the issue I ran into same key not found exception and your PR build fixed the issue for me. 

While the fix makes sense being defensive, I just want to give you an additional data point this (at least my case) might have something to do with the `Workspace` feature in Edge,  things worked for me perfectly for months until I created a new Workspace and the workspace favorites are automatically created in my Favorites. 

It's an interesting scenario doesn't look important to index those links as they are pertinent to a specific "workspace" anyway. 

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/4074892/28ab8f23-c3be-421f-a0ba-6577a70ce415)

**Comment by VictoriousRaptor** [comment]
> @jjw24 Thanks for fixing the issue I ran into same key not found exception and your PR build fixed the issue for me.
> 
> While the fix makes sense being defensive, I just want to give you an additional data point this (at least my case) might have something to do with the `Workspace` feature in Edge, things worked for me perfectly for months until I created a new Workspace and the workspace favorites are automatically created in my Favorites.
> 
> It's an interesting scenario doesn't look important to index those links as they are pertinent to a specific "workspace" anyway.
> 
> **[Update]** I was able to reproduce this on my another devbox with clean portable flow-launcher so I tried parse the file below with excerpted logic from `EnumerateFolderBookmark` but did not get any element with missing `type` information , did not debug further likely there's another file had problem. Anyway might not be the "workspace" feature as the data in there related appears all right
> 
> `C:\Users\<my-alias>\AppData\Local\Microsoft\Edge\User Data\Default\Bookmarks`
> 
> ![image](https://private-user-images.githubusercontent.com/4074892/294001225-28ab8f23-c3be-421f-a0ba-6577a70ce415.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1OTkxNTQsIm5iZiI6MTcwNDU5ODg1NCwicGF0aCI6Ii80MDc0ODkyLzI5NDAwMTIyNS0yOGFiOGYyMy1jM2JlLTQyMWYtYTBiYS02NTc3YTcwY2U0MTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDdUMDM0MDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTAzZjdhNGE2OGY3OGE0YzQ2MjMzMjE4OWZlOGUzMTQwNzdiYWE5MTdmMTdhNjViYWZkMjJiYmI3MGQ1MWQxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pA4UIclt0WYjBGe7LUft1h2xOI-zimi7kjwqrGPUv-w)

The workspace is handled in an earlier PR so it's possibly unrelated. Closing this issue since it's fixed. Feel free to reopen if the issue remains.
