### ISSUE TITLE
BUG: Can not install plugin

### ISSUE THREAD

**Issue by 3T1C** [Flow-Launcher/Flow.Launcher#2397]
### Checks

- [x] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description
- Can't install plugin 

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/49277107/50174a23-a0bd-4233-afa3-ce2b66f1fc85)

### Flow Launcher Version

1.16.2

### Windows Build Number

10.0.22621.2428

### Error Log

Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Flow.Launcher.ViewModel.SettingWindowViewModel.DisplayPluginQuery(String queryToDisplay, PluginPair plugin, Int32 actionKeywordPosition) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\SettingWindowViewModel.cs:line 388
   at Flow.Launcher.SettingWindow.OnExternalPluginInstallClick(Object sender, RoutedEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\SettingWindow.xaml.cs:line 292
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2023-10-24.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/13113002/2023-10-24.txt)

**Comment by deefrawley** [comment]
Hi. What plugin and what was the action or command you used?

**Comment by 3T1C** [comment]
> Hi. What plugin and what was the action or command you used?

I've tried all the plugins, but none of them could be installed. I get the error above every time I click install.

**Comment by taooceros** [comment]
I suppose this might be caused by the pluginsmanager plugin is not available in your flow. Could you type pm and see anything appear?

**Comment by 3T1C** [comment]
> I suppose this might be caused by the pluginsmanager plugin is not available in your flow. Could you type pm and see anything appear?

You're right. The plugins manager is currently not available in my flow.

**Comment by taooceros** [comment]
I suggest you to reinstall flow if you are not using the portable mode (or else the user data might get deleted). If you are using the portable mode, then download the pluginsmanager plugin manually and put that in `Plugins` folder whereever flow is in your computer. https://github.com/Flow-Launcher/Flow.Launcher.Plugin.PluginsManager

**Comment by 3T1C** [comment]
> I suggest you to reinstall flow if you are not using the portable mode (or else the user data might get deleted). If you are using the portable mode, then download the pluginsmanager plugin manually and put that in `Plugins` folder whereever flow is in your computer. https://github.com/Flow-Launcher/Flow.Launcher.Plugin.PluginsManager

It worked! Thank you for your help.
