### ISSUE TITLE
System.Diagnostics.Process.Kill() System.ComponentModel.Win32Exception (5): Access is denied.

### ISSUE THREAD

**Issue by petsuter** [Flow-Launcher/Flow.Launcher#2398]
```
Flow Launcher version: 1.9.3
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 10/26/2023 10:20:46
Exception:
System.AggregateException: One or more errors occurred. (Access is denied.)
 ---> System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.Process.Kill()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by petsuter** [comment]
This happens randomly from time to time.

**Comment by deefrawley** [comment]
Hi. Please update Flow as this is an old version and see if the problem persists.

**Comment by deefrawley** [comment]
Reopen if issue persists with 1.16.2

**Comment by JohnTheGr8** [comment]
@petsuter you are trying to kill processes that your user does not have the access to kill. This is expected behavior, and not an issue of flow launcher per se.

If you want to be able to kill any process from flow, run it as administrator.

**Comment by petsuter** [comment]
I'm not trying to kill any processes. I don't know why Flow tries to kill processes. I just open Flow and start typing a search keyword, but it crashes before I trigger anything.

I updated Flow now and will reopen the issue if it appears again. (But it was relatively rare.)
