### ISSUE TITLE
BUG: error occurs when clearing plugin search and pressing enter

### ISSUE THREAD

**Issue by ossipoff** [Flow-Launcher/Flow.Launcher#2406]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I am using the latest version of Flow Launcher.

### Problem Description

Error occurs when clearing plugin search and pressing enter.

Error only occurs if you have expanded one of the plugins you searched for.

And only if you expand it while you in the "search result".

### To Reproduce

1. Open settings
2. Go to plugins
3. Search for "commands"
4. Click on "System Commands" so it expands
5. Clear the search field and press enter on the keyboard
6. An error message occurs, but it seems that the search is carried out

### Flow Launcher Version

1.16.2

### Windows Build Number

22621.2506

### Error Log

<details>

```shell

Flow Launcher version: 1.16.2
OS Version: 22621.2506
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 10/31/2023 14:13:12
Exception:
System.ArgumentException: '-5,1' is not a valid value for property 'Width'.
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at Flow.Launcher.Plugin.Sys.SysSettings.ListView_SizeChanged(Object sender, SizeChangedEventArgs e) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Sys\SysSettings.xaml.cs:line 27
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.FrameworkElement.OnRenderSizeChanged(SizeChangedInfo sizeInfo)
   at System.Windows.ContextLayoutManager.fireSizeChangedEvents()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.AnimatedRenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```
</details>

[2023-10-31.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/13216804/2023-10-31.txt)

**Comment by taooceros** [comment]
That seems to related to a recent change in system command plugin to make the view looks better. We can either give it a small fix or revise the structure.
