### ISSUE TITLE
BUG: The new update of YoutubeDownloader by LordofTheEel is causing an exception related to f strings and raw strings

### ISSUE THREAD

**Issue by HellBri8nger** [Flow-Launcher/Flow.Launcher#2440]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

[2023-11-25.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/13463242/2023-11-25.txt)

Python Path: C:\Users\[UserName]\AppData\Local\Programs\Python\Python310\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 11/25/2023 12:39:33
Exception:
Youtube Downloader Exception: 
Websites: https://github.com/DeepVoyager253/FlowLauncherYTDownload
Author: LordOfTheEel; Eyal.Br
Version: 1.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException:   File "C:\Users\[UserName]\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\main.py", line 81
    os.system(f'explorer "{os.path.abspath(r".\Your Downloads")}"')
                                                                  ^
SyntaxError: f-string expression part cannot include a backslash

 ---> System.IO.InvalidDataException:   File "C:\Users\[UserName]\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\main.py", line 81
    os.system(f'explorer "{os.path.abspath(r".\Your Downloads")}"')
                                                                  ^
SyntaxError: f-string expression part cannot include a backslash

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 850
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

Just try to use the plugin and the bug appears no other steps needed

### Flow Launcher Version

1.16.2

### Windows Build Number

Windows 11 [Version 10.0.22631.2715] 

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by deefrawley** [comment]
Hi, Please post this issue in the plugin repo - https://github.com/DeepVoyager253/FlowLauncherYTDownload
