### ISSUE TITLE
BUG: Error on starting CPPreference plugin 

### ISSUE THREAD

**Issue by BotiOpra** [Flow-Launcher/Flow.Launcher#2446]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Flow Launcher version: 1.16.2
OS Version: 22621.2715
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 11/28/2023 22:23:51
Exception:
System.MissingMethodException: Method not found: 'Void Flow.Launcher.Plugin.SharedCommands.SearchWeb.NewTabInBrowser(System.String, System.String)'.
   at Flow.Launcher.Plugin.CPPreference.Main.<>c__DisplayClass6_1.<Query>b__3(ActionContext e)
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 221
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 286
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.16.2

### Windows Build Number

10.0.22621.2715

### Error Log

[2023-11-28.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/13492845/2023-11-28.txt)

**Comment by deefrawley** [comment]
Can you please raise this under the plugin repo. Thanks

https://github.com/peterschussheim/CPPreference-flow-plugin/issues
