### ISSUE TITLE
BUG: Flow launcher tells missing multiple plugin and shutdown with an error message after trying to search

### ISSUE THREAD

**Issue by Teenam** [Flow-Launcher/Flow.Launcher#2477]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [x] I am using the latest version of Flow Launcher.

### Problem Description

after the first reboot since installing flow launcher. It unrecognized multiple plugins when using the searching bar, most notably a search result saying Everything search is not running. I went into the plugin and pointed it at the .exe for everything. After that I stop flow launcher and run it again. Some searches later the error message pops up and here I am. I'm not sure how to reproduce the bug though.

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.16.2

### Windows Build Number

10.0.19044.3086

### Error Log

[2024-01-13.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/13928215/2024-01-13.txt)

Flow Launcher version: 1.16.2
OS Version: 19044.3086
IntPtr Length: 8
x64: True

Python Path: C:\Users\Admin\AppData\Local\Programs\Python\Python310\pythonw.exe
Node Path: 
Date: 01/13/2024 20:58:47
Exception:
System.ArgumentException: The index is equal to or greater than the length of the array, or the number of elements in the dictionary is greater than the available space from index to the end of the destination array.
   at System.Collections.Concurrent.ConcurrentDictionary`2.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.CopyTo(KeyValuePair`2[] array, Int32 index)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator(Int32 minIdx, Int32 maxIdx)+MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at Flow.Launcher.Infrastructure.Image.ImageCache.<>c__DisplayClass9_0.<<set_Item>g__SliceExtra|1>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Image\ImageCache.cs:line 80
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by z1nc0r3** [comment]
Does this issue still exist?

**Comment by taooceros** [comment]
I can reproduce it when testing Avalonia. Will take a look recently.

**Comment by taooceros** [comment]
Sorry the error I reproduce is the one shown on log. I suppose that doesn't match the bug title.

**Comment by Teenam** [comment]
> Does this issue still exist?

I have reinstalled flow launcher AND everything search and it seems to be working better. I reinstalled only flow launcher and it was still giving errors
