### ISSUE TITLE
BUG: Everything Service is not running

### ISSUE THREAD

**Issue by Flowting007** [Flow-Launcher/Flow.Launcher#2490]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

For the explorer plugin, I am unable to set my index search engine, content search engine, and dictionary recursive search engine to everything. When I do so, it states "everything service is not running". 

I just want to be able to access google drive files using flow launcher and I don't exactly know how. Please help, that would be kindly appreciated. Thank you!

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

<img width="745" alt="image" src="https://github.com/Flow-Launcher/Flow.Launcher/assets/156862842/4e279d52-8558-453d-89e0-55ab8945a37c">

### Flow Launcher Version

1.16.2

### Windows Build Number

22631.3007

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by deefrawley** [comment]
What is your Everything path set to in that taab?

**Comment by JohnTheGr8** [comment]
> I just want to be able to access google drive files using flow launcher and I don't exactly know how. Please help, that would be kindly appreciated. Thank you!

iirc this is not supported, neither from windows indexing nor from everything, because google drive uses a virtual filesystem for the local files

**Comment by deefrawley** [comment]
> iirc this is not supported, neither from windows indexing nor from everything, because google drive uses a virtual filesystem for the local files

It can if the drive is mapped through C:\Users\USER\My Drive. I can search my GD through this path (but not the virtual G drive it also creates).

**Comment by johnwalter1044** [comment]
Hello, new user here. I apologise in advance if this was reported already, i tried finding the same issue, and i think this is the same one, except i actually tried to install the Everything service through the Flow launcher, clicking "No" to automatically download and install it.  Then the Flow crashed.

[2024-01-29.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/14083240/2024-01-29.txt)


```
Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues
1. upload log file: C:\Users\brklj\AppData\Roaming\FlowLauncher\Logs\1.16.2\2024-01-29.txt
2. copy below exception message

Flow Launcher version: 1.16.2
OS Version: 19045.3930
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 01/29/2024 11:14:40
Exception:
System.IO.FileNotFoundException: Could not find file 'C:\Users\brklj\AppData\Local\FlowLauncher\app-1.16.2\Plugins\Explorer-3.1.4\Droplex.Configuration.yml'.
File name: 'C:\Users\brklj\AppData\Local\FlowLauncher\app-1.16.2\Plugins\Explorer-3.1.4\Droplex.Configuration.yml'
   at Droplex.DropList.LoadConfigurationFile()
   at Droplex.DropList.TranslateConfigurations()
   at Droplex.DropList..ctor()
   at Droplex.DroplexPackage.Drop(App app, String zipExtractPath)
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingDownloadHelper.PromptDownloadIfNotInstallAsync(String installedLocation, IPublicAPI api) in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingDownloadHelper.cs:line 46
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingSearchManager.ClickToInstallEverythingAsync(ActionContext _) in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingSearchManager.cs:line 45
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 286
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by johnwalter1044** [comment]
Update: I don't know what i did, but i opened the Flow to search something, and Everything works now. Go figure. I'll answer any question or give any info if someone wants to resolve these errors in the future.
