### ISSUE TITLE
BUG: flow launcher got an error

### ISSUE THREAD

**Issue by qerwlkjh** [Flow-Launcher/Flow.Launcher#2511]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [ ] I am using the latest version of Flow Launcher.

### Problem Description

Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues
1. upload log file: C:\Program Files\Flow-Launcher-Portable\FlowLauncher\app-1.16.2\UserData\Logs\1.16.2\2024-01-28.txt
2. copy below exception message

Flow Launcher version: 1.16.2
OS Version: 22631.3085
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 01/28/2024 21:45:40
Exception:
System.AggregateException: One or more errors occurred. (アクセス許可で禁じられた方法でソケットにアクセスしようとしました。 (npmmirror.com:80))
 ---> System.Net.Http.HttpRequestException: アクセス許可で禁じられた方法でソケットにアクセスしようとしました。 (npmmirror.com:80)
 ---> System.Net.Sockets.SocketException (10013): アクセス許可で禁じられた方法でソケットにアクセスしようとしました。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Droplex.Downloader.Get(String url, String filePath)
   at Droplex.DroplexPackage.Drop(App app, String zipExtractPath)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Flow.Launcher.Core.ExternalPlugins.Environments.PythonEnvironment.InstallEnvironment() in C:\projects\flow-launcher\Flow.Launcher.Core\ExternalPlugins\Environments\PythonEnvironment.cs:line 35
   at Flow.Launcher.Core.ExternalPlugins.Environments.AbstractPluginEnvironment.Setup() in C:\projects\flow-launcher\Flow.Launcher.Core\ExternalPlugins\Environments\AbstractPluginEnvironment.cs:line 74
   at Flow.Launcher.Core.Plugin.PluginsLoader.Plugins(List`1 metadatas, PluginsSettings settings) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginsLoader.cs:line 26
   at Flow.Launcher.Core.Plugin.PluginManager.LoadPlugins(PluginsSettings settings) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 109
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 72
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 51
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2024-01-28.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/14076069/2024-01-28.txt)

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.16.2

### Windows Build Number

windows 11 pro OS build 22631.3085 

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

[2024-01-28.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/14076079/2024-01-28.txt)

**Comment by z1nc0r3** [comment]
Can you provide more details about the issue and how to reproduce it if possible?
