### ISSUE TITLE
BUG: Everything Service not working crashing Flow Launcher

### ISSUE THREAD

**Issue by EdwardPeepoHands** [Flow-Launcher/Flow.Launcher#2522]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I am using the latest version of Flow Launcher.

### Problem Description

Fresh install. 
Tells me "Everything Service is not running".
When selected it offers me to select a file path or just hit "no" and it will install the Service.
Hitting "no" and prompting it to install, results in a crash. 

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

![grafik](https://github.com/Flow-Launcher/Flow.Launcher/assets/44322341/ecfbaa44-38f2-4784-be32-9789538781e0)

### Flow Launcher Version

1.16.2

### Windows Build Number

22631.3007

### Error Log

<details>

```shell


Flow Launcher version: 1.16.2
OS Version: 22631.3007
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 02/03/2024 23:33:00
Exception:
System.IO.FileNotFoundException: Could not find file 'C:\Users\leonb\AppData\Local\FlowLauncher\app-1.16.2\Plugins\Explorer-3.1.4\Droplex.Configuration.yml'.
File name: 'C:\Users\leonb\AppData\Local\FlowLauncher\app-1.16.2\Plugins\Explorer-3.1.4\Droplex.Configuration.yml'
   at Droplex.DropList.LoadConfigurationFile()
   at Droplex.DropList.TranslateConfigurations()
   at Droplex.DropList..ctor()
   at Droplex.DroplexPackage.Drop(App app, String zipExtractPath)
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingDownloadHelper.PromptDownloadIfNotInstallAsync(String installedLocation, IPublicAPI api) in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingDownloadHelper.cs:line 46
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingSearchManager.ClickToInstallEverythingAsync(ActionContext _) in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingSearchManager.cs:line 45
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 286
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2024-02-03.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/14154473/2024-02-03.txt)


```
</details>

**Comment by EdwardPeepoHands** [comment]
[2024-02-03_logfile.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/14154475/2024-02-03_logfile.txt)


cant copy paste the logfile since its to long

**Comment by deefrawley** [comment]
```
System.IO.FileNotFoundException: Could not find file 'C:\Users\leonb\AppData\Local\FlowLauncher\app-1.16.2\Plugins\Explorer-3.1.4\Droplex.Configuration.yml'.
   Source: Droplex
   TargetAssembly: Droplex, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null
   TargetModule: Droplex.dll
   TargetSite: System.String LoadConfigurationFile()
   at Droplex.DropList.LoadConfigurationFile()
   at Droplex.DropList.TranslateConfigurations()
   at Droplex.DropList..ctor()
   at Droplex.DroplexPackage.Drop(App app, String zipExtractPath)
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingDownloadHelper.PromptDownloadIfNotInstallAsync(String installedLocation, IPublicAPI api) in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingDownloadHelper.cs:line 46
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingSearchManager.ClickToInstallEverythingAsync(ActionContext _) in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingSearchManager.cs:line 45
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 286
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

This seems to be the error. Same as reported in #2490 
Can you restart Flow and see if that fixes it as that helped the user in that issue

**Comment by EdwardPeepoHands** [comment]
I  have restartet Flow, My PC and reinstalled Flow + Everything. Still the same issue

**Comment by EdwardPeepoHands** [comment]
ok. I deinstalled flow, and installed it as admin and now i can install Everything search without any issues.
