### ISSUE TITLE
BUG: Node.js-based plugins don't work

### ISSUE THREAD

**Issue by Yusyuriv** [Flow-Launcher/Flow.Launcher#2553]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

I installed Flow Launcher for the first time today. None of the Node.js-based plugins worked for me. Even the official Hello World one. After some digging, I managed to make them work. Initially I would get this exception:
```
Exception:
Hello World Node.js Exception:
Websites: https://github.com/Flow-Launcher/Flow.Launcher.Plugin.HelloWorldNodeJS
Author: Flow Launcher
Version: 1.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.ObjectModel.Collection`1.set_Item(Int32 index, T value)
   at Flow.Launcher.Core.Plugin.NodePlugin.RequestAsync(JsonRPCRequestModel request, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\NodePlugin.cs:line 31
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
```
This was caused by [NodePlugin.cs#L31](https://github.com/Flow-Launcher/Flow.Launcher/blob/f5b1b4f8/Flow.Launcher.Core/Plugin/NodePlugin.cs#L31). I don't really know much about C#, but I did what made sense to me, replaced this line, and this exception stopped appearing: 
```diff
+ if (_startInfo.ArgumentList.Count > 1)
+ {
+     _startInfo.ArgumentList.RemoveAt(1);
+ }
+ _startInfo.ArgumentList.Add(JsonSerializer.Serialize(request));
- _startInfo.ArgumentList[1] = JsonSerializer.Serialize(request);
```
Even though the exception was gone, plugins still didn't work. After some debugging on the C# side I realized that it's because Node.js-based plugins simply don't respond with anything. I examined the code of the Hello World plugin and came to the conclusion that it won't respond only if it doesn't receive `method` property it uses to decide what to send in response. While debugging the C# side, I noticed that `Method` and `Parameters` properties used in plugins are capitalized in C# but not capitalized in JS/TS. After I capitalized them in JS, plugins started working. I tested this on the official Hello World plugin and on How Long to Beat plugin. Below are the changes to [main.js](https://github.com/Flow-Launcher/Flow.Launcher.Plugin.HelloWorldNodeJS/blob/8a4c267b/main.js) in the Hello World plugin after which the plugin started working:
```diff
const open = require('./node_modules/open')

- const { method, parameters } = JSON.parse(process.argv[2])
+ const { Method, Parameters } = JSON.parse(process.argv[2])

if (Method === "query") {
	console.log(JSON.stringify(
		{
			"result": [{
				"Title": "Hello World Typescript",
- 				"Subtitle": "Showing your query parameters: " + parameters + ". Click to open Flow's website",
+ 				"Subtitle": "Showing your query parameters: " + Parameters + ". Click to open Flow's website",
				"JsonRPCAction": {
                    "method": "do_something_for_query",
                    "parameters": ["https://github.com/Flow-Launcher/Flow.Launcher"]
                },
				"IcoPath": "Images\\app.png"
			}]
		}
	));
}

- if (method === "do_something_for_query") {
- 	url = parameters[0]
+ if (Method === "do_something_for_query") {
+ 	url = Parameters[0]
	do_something_for_query(url)
}

function do_something_for_query(url) {
	open(url);
}
```

### To Reproduce

1. Install the plugin: `pm install Hello World Node.js by Flow Launcher`
2. Now try to use it: `hn` which results in `Failed to respond!`

### Screenshots

Before any changes:
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/3993179/6149380b-5f65-4fc7-9965-d22c1bbaf9aa)

After changes both in C# and in plugin's JS:
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/3993179/5babe817-2ad3-4c88-be32-994870d58e1d)

### Flow Launcher Version

1.17.1

### Windows Build Number

10.0.23580.1000

### Error Log

<details>

```shell
Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues
1. upload log file: C:\Users\username\AppData\Roaming\FlowLauncher\Logs\1.17.1\2024-02-08.txt
2. copy below exception message

Flow Launcher version: 1.17.1
OS Version: 23580.1000
IntPtr Length: 8
x64: True

Python Path: C:\Users\username\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: C:\Users\username\AppData\Roaming\FlowLauncher\Environments\Node.js\Node-v16.18.0\node-v16.18.0-win-x64\node.exe
Date: 02/08/2024 09:45:52
Exception:
Hello World Node.js Exception:
Websites: https://github.com/Flow-Launcher/Flow.Launcher.Plugin.HelloWorldNodeJS
Author: Flow Launcher
Version: 1.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.ObjectModel.Collection`1.set_Item(Int32 index, T value)
   at Flow.Launcher.Core.Plugin.NodePlugin.RequestAsync(JsonRPCRequestModel request, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\NodePlugin.cs:line 31
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 195
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 221
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 294
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```
</details>

Log doesn't contain any relevant information, so instead I just put the full exception message a part of which I quoted in the problem description.

**Comment by lihuelworks** [comment]
Same thing here, and Flow Launcher makes it notoriously difficult to stick with a version (even disabling automatic udpates)

**Comment by Yusyuriv** [comment]
More info on why setting the `ArgumentList` value by index works with Python plugins, but not Node plugins: [`PythonPlugin.cs#L57`](https://github.com/Flow-Launcher/Flow.Launcher/blob/f5b1b4f830eb423be029f6024530f80808ad8940/Flow.Launcher.Core/Plugin/PythonPlugin.cs#L53C1-L59C10) creates that index in the `InitAsync` method:
```cs
_startInfo.ArgumentList.Add(context.CurrentPluginMetadata.ExecuteFilePath);
_startInfo.ArgumentList.Add(""); // This adds the last element to the collection
                                 // used to communicate with plugins
```
while [`NodePlugin.cs#L45`](https://github.com/Flow-Launcher/Flow.Launcher/blob/f5b1b4f830eb423be029f6024530f80808ad8940/Flow.Launcher.Core/Plugin/NodePlugin.cs#L42C1-L47C10) does not do that. Adding the same line in `NodePlugin.cs` fixes the issue on Flow Launcher's side:

```cs
_startInfo.ArgumentList.Add(context.CurrentPluginMetadata.ExecuteFilePath);
_startInfo.ArgumentList.Add(""); // This fixes the issue
_startInfo.WorkingDirectory = context.CurrentPluginMetadata.PluginDirectory;
```

Node plugins still won't work if they're expecting `method` and `parameters` uncapitalized, but that's an easy fix on their side. Flow Launcher still needs to update its [official Hello World plugin](https://github.com/Flow-Launcher/Flow.Launcher.Plugin.HelloWorldNodeJS/blob/8a4c267b/main.js) to use the capitalized properties.
