### ISSUE TITLE
BUG: Flow Launcher does not support symbolic links

### ISSUE THREAD

**Issue by Farravid** [Flow-Launcher/Flow.Launcher#2588]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

I'm trying to sym link the settings of Flow Launcher and I'm getting an error everytime I open it or save the settings.
I'd like to be able to create a symlink to the different settings in order to build my dotfiles.

[2024-02-25.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/14397199/2024-02-25.txt)
 

### To Reproduce

1. Create a symbolic link to the Settings.json 
2. Open Flow Launcher

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/51139214/9f91d01d-e4a4-4501-bc1b-bbff622c3272)

### Flow Launcher Version

1.17.2

### Windows Build Number

10.0.22631.3155]

### Error Log

<details>

```shell

Flow Launcher version: 1.17.2
OS Version: 22631.3155
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 02/25/2024 18:29:32
Exception:
System.IO.IOException: This application does not support the current operation on symbolic links.
   at System.IO.FileSystem.ReplaceFile(String sourceFullPath, String destFullPath, String destBackupFullPath, Boolean ignoreMetadataErrors)
   at Flow.Launcher.Infrastructure.Storage.JsonStorage`1.AtomicWriteSetting() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Storage\JsonStorage.cs:line 209
   at Flow.Launcher.Infrastructure.Storage.JsonStorage`1.Save() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Storage\JsonStorage.cs:line 189
   at Flow.Launcher.ViewModel.SettingWindowViewModel.Save() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\SettingWindowViewModel.cs:line 149
   at Flow.Launcher.PublicAPIInstance.SaveAppAllSettings() in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 86
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 108
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 51
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2024-02-25.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/14397207/2024-02-25.txt)


```
</details>

**Comment by taooceros** [comment]
we use an atomic way to save files in order to prevent various reported setting lost. I assume that doesn't work with symlink, in which nothing we can do now.

Maybe we can use some more sophisticated database structure to store settings, but not in the current stage.

**Comment by Farravid** [comment]
Hmm okay, thanks for replying!
