### ISSUE TITLE
BUG: error when everything service is not running

### ISSUE THREAD

**Issue by BenjaminBE4** [Flow-Launcher/Flow.Launcher#2621]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Flow launcher gets an error when pressing the "Warning: Everything service is not running" button

Flow Launcher version: 1.17.2
OS Version: 22631.3296
IntPtr Length: 8
x64: True

Python Path: C:\Users\benja\AppData\Local\Programs\Python\Python310\pythonw.exe
Node Path: 
Date: 03/27/2024 01:19:54
Exception:
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'MsiExec.exe \Everything.exe' with working directory 'C:\_Portable\FlowLauncher'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingSearchManager.ClickToInstallEverythingAsync(ActionContext _) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingSearchManager.cs:line 55
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 294
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate cal
[2024-03-27.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/14765914/2024-03-27.txt)
lback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

1. Enable Everything search file indexing
2. Close the everything service
3. Press the "Warning: Everything service is not running" button

### Screenshots

![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/32206728/786349c0-2697-45bc-b79d-ea33841c3e7d)

### Flow Launcher Version

1.17.2 Portable

### Windows Build Number

Microsoft Windows [Version 10.0.22631.3296]

### Error Log

[2024-03-27.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/14765945/2024-03-27.txt)

**Comment by z1nc0r3** [comment]
Can you please specify which version of Everything you are using?

**Comment by BenjaminBE4** [comment]
Everything 1.4.1.1024

**Comment by z1nc0r3** [comment]
Please make sure the **_Everything Path_** is set correctly in the _Explorer > Everything Setting_

**Comment by deefrawley** [comment]
Please update to the latest version of Flow and if the problem persists we can reopen the issue. Thanks.
