### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by kiraje** [Flow-Launcher/Flow.Launcher#2642]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [ ] I am using the latest version of Flow Launcher.

### Problem Description

Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues

[2024-04-09.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/14919335/2024-04-09.txt)
2. copy below exception message

Flow Launcher version: 1.17.2
OS Version: 22621.3374
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 04/09/2024 11:39:21
Exception:
System.IO.FileNotFoundException: Could not find file 'C:\Users\Dustin\AppData\Local\FlowLauncher\app-1.17.2\Plugins\Explorer-3.1.5\Droplex.Configuration.yml'.
File name: 'C:\Users\Dustin\AppData\Local\FlowLauncher\app-1.17.2\Plugins\Explorer-3.1.5\Droplex.Configuration.yml'
   at Droplex.DropList.LoadConfigurationFile()
   at Droplex.DropList.TranslateConfigurations()
   at Droplex.DropList..ctor()
   at Droplex.DroplexPackage.Drop(App app, String zipExtractPath)
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingDownloadHelper.PromptDownloadIfNotInstallAsync(String installedLocation, IPublicAPI api) in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingDownloadHelper.cs:line 46
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingSearchManager.ClickToInstallEverythingAsync(ActionContext _) in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingSearchManager.cs:line 45
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 294
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.17.2

### Windows Build Number

22621.3374

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by deefrawley** [comment]
Please let us know what you were doing when the error occurred.

**Comment by kiraje** [comment]
> Please let us know what you were doing when the error occurred.

Fixed by reinstall Flow Launcher

**Comment by z1nc0r3** [comment]
I am closing the issue now. Reopen if any further discussion is needed.
