### ISSUE TITLE
BUG: Unable to work in Window11 Insider

### ISSUE THREAD

**Issue by kiin21** [Flow-Launcher/Flow.Launcher#2671]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I am using the latest version of Flow Launcher.

### Problem Description

System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'C:\Users\PC\AppData\Local\Microsoft\PowerToys\PowerToys Run\Plugins\Everything\Everything64.dll' with working directory 'C:\Users\PC\AppData\Local\FlowLauncher\app-1.16.2'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingSearchManager.ClickToInstallEverythingAsync(ActionContext _) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingSearchManager.cs:line 55
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 286
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.16.2

### Windows Build Number

10.0.26100.1

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by deefrawley** [comment]
Check your Everything folder setting in Flow as I don't know why it's looking in the PowerToys directory.
```An error occurred trying to start process 'C:\Users\PC\AppData\Local\Microsoft\PowerToys\PowerToys Run\Plugins\Everything\Everything64.dll'```

**Comment by kiin21** [comment]
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/139786046/6e17f1fa-bdab-4f0b-8a31-0b23cc7ada8b)

Here is it

**Comment by deefrawley** [comment]
That's a PowerrToys plugin. Are you using Flow or PowerToys Run?

**Comment by kiin21** [comment]
I use both of them, but everything is not installed properly
![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/139786046/a135bba0-fcd4-4910-b7cb-d0504739b51d)

**Comment by deefrawley** [comment]
That screenshot is PowerToys run, not Flow.  Please open an issue in their repo.
