### ISSUE TITLE
Crash after wake up from power save

### ISSUE THREAD

**Issue by Xander011977** [Flow-Launcher/Flow.Launcher#2702]
Flow Launcher version: 1.14.1
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\s.wolski\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 05/18/2024 13:11:22
Exception:
System.InvalidOperationException: Failed initializing notifications
 ---> System.UnauthorizedAccessException: Access to the registry key 'HKEY_CURRENT_USER\SOFTWARE\Classes\CLSID\{1c2195e8-bab1-17a7-13a6-5933166acd16}\LocalServer32' is denied.
   at void Microsoft.Win32.RegistryKey.Win32Error(int errorCode, string str)
   at RegistryKey Microsoft.Win32.RegistryKey.CreateSubKeyInternalCore(string subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions registryOptions)
   at void Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.RegisterComServer(Type activatorType, string exePath)
   at void Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.RegisterActivator(Type activatorType)
   at Type Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.CreateAndRegisterActivator()
   at void Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.Initialize()
   at static Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat()
   --- End of inner exception stack trace ---
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.CreateToastNotifier()
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show(CustomizeToast customize)
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show()
   at Flow.Launcher.Notification.ShowInternal(String title, String subTitle, String iconPath) in C:\projects\flow-launcher\Flow.Launcher\Notification.cs:line 47
   at Flow.Launcher.Notification.<>c__DisplayClass2_0.<Show>b__0() in C:\projects\flow-launcher\Flow.Launcher\Notification.cs:line 26
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Flow.Launcher.Notification.Show(String title, String subTitle, String iconPath) in C:\projects\flow-launcher\Flow.Launcher\Notification.cs:line 24
   at Flow.Launcher.PublicAPIInstance.ShowMsg(String title, String subTitle, String iconPath, Boolean useMainWindowAsOwner) in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 96
   at Flow.Launcher.Core.Plugin.PluginManager.InitializePluginsAsync(IPublicAPI api) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 161
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 81
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 52
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Xander011977** [comment]
Solved after reinstall (new version 1.16.2)

**Comment by Garulf** [comment]
> Solved after reinstall (new version 1.16.2)

Glad you were able to find a solution to your problem!
