### ISSUE TITLE
BUG:  System.UriFormatException: Invalid URI

### ISSUE THREAD

**Issue by nishutheintrovert** [Flow-Launcher/Flow.Launcher#2703]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I am using the latest version of Flow Launcher.

### Problem Description

"Flow Launcher got an error" window popped up when trying to open a website link using preinstalled web search extension.
Exception message showed on the window as said above : 
Flow Launcher version: 1.18.0
OS Version: 19045.4412
IntPtr Length: 8
x64: True

Python Path: C:\Users\nishi\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 05/19/2024 21:40:42
Exception:
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Flow.Launcher.PublicAPIInstance.OpenUrl(String url, Nullable`1 inPrivate) in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 279
   at Flow.Launcher.Plugin.WebSearch.Main.<>c__DisplayClass9_1.<QueryAsync>b__1(ActionContext c) in D:\a\Flow.Launcher\Flow.Launcher\Plugins\Flow.Launcher.Plugin.WebSearch\Main.cs:line 76
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 307
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

1. ... open flow launcher search bar.
2. ... input action keyword ( preinstalled web address plugin) to trigger plugin.
3. ... enter youtube playlist address
4. ... enter

### Screenshots

![Screenshot (21)](https://github.com/Flow-Launcher/Flow.Launcher/assets/165758390/e90e11f4-8d36-4a54-bb31-f38144ab3150)
![Screenshot (22)](https://github.com/Flow-Launcher/Flow.Launcher/assets/165758390/7a64bf78-0a7d-41da-b960-2c3f2d2f18ae)
![Screenshot (23)](https://github.com/Flow-Launcher/Flow.Launcher/assets/165758390/27c558f6-9e88-4614-a448-c316c5659c61)

### Flow Launcher Version

1.18.0

### Windows Build Number

10.0.19045.4412

### Error Log

[2024-05-19.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/15370063/2024-05-19.txt)

**Comment by nishutheintrovert** [comment]
found the problem, if I remove the 'https:\\' from screenshot 1, I won't get any errors, I'm closing this since it's just a issue caused cause of my workaround to search website itself instead of a search engine or website query.

**Comment by nishutheintrovert** [comment]
found the problem, if I remove the 'https:\' from screenshot 1, I won't get any errors, I'm closing this since it's just a issue caused cause of my workaround to search website itself instead of a search engine or website query.
