### ISSUE TITLE
BUG: System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by ReKylee** [Flow-Launcher/Flow.Launcher#2706]
### Checks

- [x] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Flow Launcher version: 1.18.0
OS Version: 19045.4412
IntPtr Length: 8
x64: True

Python Path: C:\Python312\pythonw.exe
Node Path: 
Date: 05/20/2024 15:09:08
Exception:
System.UnauthorizedAccessException: Access to the path 'D:\Program Files\FlowLauncher\app-1.18.0\UserData\Cache\Image.cache' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Flow.Launcher.Infrastructure.Storage.BinaryStorage`1.TryLoadAsync(T defaultData) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Storage\BinaryStorage.cs:line 49
   at Flow.Launcher.Infrastructure.Image.ImageLoader.LoadStorageToConcurrentDictionaryAsync() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Image\ImageLoader.cs:line 84
   at Flow.Launcher.Infrastructure.Image.ImageLoader.InitializeAsync() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Image\ImageLoader.cs:line 37
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 82
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 51
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

just happened on startup

### Flow Launcher Version

1.18.0

### Windows Build Number

19045.4412

### Error Log

<details>

```shell

Flow Launcher version: 1.18.0
OS Version: 19045.4412
IntPtr Length: 8
x64: True

Python Path: C:\Python312\pythonw.exe
Node Path: 
Date: 05/20/2024 15:09:08
Exception:
System.UnauthorizedAccessException: Access to the path 'D:\Program Files\FlowLauncher\app-1.18.0\UserData\Cache\Image.cache' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Flow.Launcher.Infrastructure.Storage.BinaryStorage`1.TryLoadAsync(T defaultData) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Storage\BinaryStorage.cs:line 49
   at Flow.Launcher.Infrastructure.Image.ImageLoader.LoadStorageToConcurrentDictionaryAsync() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Image\ImageLoader.cs:line 84
   at Flow.Launcher.Infrastructure.Image.ImageLoader.InitializeAsync() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Image\ImageLoader.cs:line 37
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 82
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 51
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


```
</details>

**Comment by Garulf** [comment]
Windows "Program Files" folder typically has very restrictive file permissions. 

Please check Flow Launcher has access. As far as I know Flow Launcher doesn't really support being installed in this directory.

**Comment by ReKylee** [comment]
It's not installed in window's "Program Files" folder, but on a separate hard drive. should've mentioned that.

**Comment by jjw24** [comment]
The error shows access issue, maybe as mentioned check flow has access to everything in that location.

Closing, if required further discussion please reopen.
