### ISSUE TITLE
Error when Flow Launcher is starting

### ISSUE THREAD

**Issue by skakspilleren** [Flow-Launcher/Flow.Launcher#2736]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

All I can say is that the problem arises when first starting the program.
Since I have set FL to launch at start-up I am presented with an error
shortly after booting into Windows 11.

### To Reproduce

As stated above I have Flow Launcher starting automatically at start up. This is when the problem arises.

### Flow Launcher Version

1.18.0

### Windows Build Number

10.0.22631.3593

### Error Log

Flow Launcher version: 1.18.0
OS Version: 22631.3593
IntPtr Length: 8
x64: True

Python Path: C:\Users\...\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 05/29/2024 06:26:28
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ClipboardR.ClipboardR.Save()
   at Flow.Launcher.Core.Plugin.PluginManager.Save() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 58
   at Flow.Launcher.PublicAPIInstance.SaveAppAllSettings() in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 84
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 108
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 51
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by skakspilleren** [comment]
The problem persists after having reinstalled the already up-to-date ClipboardR plugin and rebooting.
I'll head over to rainyl. Thank you.
