### ISSUE TITLE
BUG: CurrencyPP throws error when run

### ISSUE THREAD

**Issue by Tequinzyy** [Flow-Launcher/Flow.Launcher#2766]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

[2024-06-09.txt](https://github.com/user-attachments/files/15750838/2024-06-09.txt)

### To Reproduce

1. run it
2. get Failed to respond
3. ...

### Flow Launcher Version

1.18.0

### Windows Build Number

10.0.19045.4291

### Error Log

Flow Launcher version: 1.18.0
OS Version: 19045.4291
IntPtr Length: 8
x64: True

Python Path: C:\Users\Dreck\AppData\Local\Programs\Python\Python312\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 06/09/2024 14:05:33
Exception:
CurrencyPP Exception: 
Websites: https://github.com/LeLocTai/Flow.Launcher.Plugin.CurrencyPP
Author: Le Loc Tai
Version: 3.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: C:\Users\Dreck\AppData\Roaming\FlowLauncher\Plugins\CurrencyPP-3.0.1\src\exchange.py:164: SyntaxWarning: invalid escape sequence '\d'
  elif re.search('\d', validated):

 ---> System.IO.InvalidDataException: C:\Users\Dreck\AppData\Roaming\FlowLauncher\Plugins\CurrencyPP-3.0.1\src\exchange.py:164: SyntaxWarning: invalid escape sequence '\d'
  elif re.search('\d', validated):

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 264
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 230
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 307
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by deefrawley** [comment]
Hi, not much can be done I'm afraid. You can try raising this in the plugin repo but it has been archived and is not actively maintained. There is another currency conversion plugin you can try. Thanks.
