### ISSUE TITLE
Flow launcher got an error

### ISSUE THREAD

**Issue by one3711** [Flow-Launcher/Flow.Launcher#2788]
[2024-06-18.txt](https://github.com/user-attachments/files/15879389/2024-06-18.txt)

Flow Launcher version: 1.18.0
OS Version: 22631.3737
IntPtr Length: 8
x64: True

Python Path: C:\Users\junej\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 06/18/2024 07:28:33
Exception:
System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\junej\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\main.py", line 93, in <module>
    YoutubeDownload()
  File "C:\Users\junej\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\flowlauncher\FlowLauncher.py", line 33, in __init__
    results = request_method(*request_parameters)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\junej\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\main.py", line 88, in download_video
    video_file = video.download(output_path = download_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\junej\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\pytube\streams.py", line 314, in download
    for chunk in request.stream(
  File "C:\Users\junej\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\pytube\request.py", line 153, in stream
    raise MaxRetriesExceeded()
pytube.exceptions.MaxRetriesExceeded

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 243
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 248
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteResultAsync(JsonRPCResult result) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 117
   at Flow.Launcher.Core.Plugin.JsonRPCPluginBase.<>c__DisplayClass18_0.<<ParseResults>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPluginBase.cs:line 89
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 307
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by taooceros** [comment]
The error is related Youtube Downloader

**Comment by deefrawley** [comment]
Hi @one3711 - can you please raise this issue in the YouTube downloader repo rather than the main Flow one? Thanks.
