### ISSUE TITLE
Exception when using the context menu for uninstall plugin

### ISSUE THREAD

**Issue by taooceros** [Flow-Launcher/Flow.Launcher#282]
```c#
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Flow.Launcher.Plugin.PluginsManager.ContextMenu.<>c__DisplayClass5_0.<LoadContextMenus>b__1(ActionContext _) in D:\Document\Dotnet\Flow.Launcher\Plugins\Flow.Launcher.Plugin.PluginsManager\ContextMenu.cs:line 42
   at Flow.Launcher.ViewModel.MainViewModel.<InitializeKeyCommands>b__20_7(Object index) in D:\Document\Dotnet\Flow.Launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 189
   at Flow.Launcher.ViewModel.RelayCommand.Execute(Object parameter) in D:\Document\Dotnet\Flow.Launcher\Flow.Launcher\ViewModel\RelayCommand.cs:line 25
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)```

**Comment by jjw24** [comment]
this should be fixed
