### ISSUE TITLE
Flow Launcher got an error BUG: 

### ISSUE THREAD

**Issue by Malesin** [Flow-Launcher/Flow.Launcher#2829]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Flow Launcher version: 1.18.0
OS Version: 22621.3810
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 07/09/2024 08:46:54
Exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.FileSystem.ReplaceFile(String sourceFullPath, String destFullPath, String destBackupFullPath, Boolean ignoreMetadataErrors)
   at Flow.Launcher.Infrastructure.Storage.JsonStorage`1.AtomicWriteSetting() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Storage\JsonStorage.cs:line 209
   at Flow.Launcher.Infrastructure.Storage.JsonStorage`1.Save() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Storage\JsonStorage.cs:line 189
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Flow.Launcher.PublicAPIInstance.SavePluginSettings() in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 198
   at Flow.Launcher.Core.Plugin.PluginManager.Save() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 64
   at Flow.Launcher.PublicAPIInstance.SaveAppAllSettings() in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 84
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 108
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 51
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

1. ...
2. ...
3. ...
aaa

### Flow Launcher Version

1.18.0

### Windows Build Number

10.0.22621.3810

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by taooceros** [comment]
Does it occur to you consistently?
