### ISSUE TITLE
Error while using Explorer plugin to open folders. 

### ISSUE THREAD

**Issue by Jalaj1087** [Flow-Launcher/Flow.Launcher#2843]
When I am trying to open any folder it shows this error in the launcher.
Right now I am using Onecommander as my default file manager (it changes the registry to make it a default file manager)
I have downloaded everything for the plugin. 

[2024-07-17.txt](https://github.com/user-attachments/files/16260802/2024-07-17.txt)

Exception message:

Flow Launcher version: 1.18.0
OS Version: 19045.4651
IntPtr Length: 8
x64: True

Python Path: C:\Users\admin\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 07/17/2024 11:15:10
Exception:
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Program Files\totalcmd\TOTALCMD64.exe' with working directory 'C:\Users\admin\AppData\Local\FlowLauncher\app-1.18.0'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at Flow.Launcher.PublicAPIInstance.OpenDirectory(String DirectoryPath, String FileNameOrFilePath) in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 245
   at Flow.Launcher.Plugin.Explorer.Search.ResultManager.OpenFolder(String folderPath, String fileNameOrFilePath) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\ResultManager.cs:line 299
   at Flow.Launcher.Plugin.Explorer.Search.ResultManager.<>c__DisplayClass12_0.<CreateOpenCurrentFolderResult>b__0(ActionContext _) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\ResultManager.cs:line 227
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 307
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Jalaj1087** [comment]
Sorry for the inconvenience, I resolved my problem with some tweaking. 

But I have a query

**Comment by Jalaj1087** [comment]
But I have a query, is it possible for flow to open Onecommander when opening a folder.. 
I know there is a file manager option. So can you guide me so I can use Onecommander

**Comment by z1nc0r3** [comment]
Hi, did you try adding a new file manager through this?

![image](https://github.com/user-attachments/assets/5b1bb743-ed89-41ad-9b9f-99ac8f30bfc8)

**Comment by Jalaj1087** [comment]
Yes. But when I tried it the above error is coming. Can you assist me with adding onecommander specifically?

**Comment by z1nc0r3** [comment]
Please try using these configurations with the path of the `OneCommander.exe`

![image](https://github.com/user-attachments/assets/e0c1d8a2-b065-46e7-8b1b-f685256e8cc8)

**Comment by Jalaj1087** [comment]
Worked like a charm. Much thanks for it.
