### ISSUE TITLE
BUG: YouTube Downloader Plugin Not Working 

### ISSUE THREAD

**Issue by therealpigeonman** [Flow-Launcher/Flow.Launcher#2858]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [ ] I am using the latest version of Flow Launcher.

### Problem Description

Flow Launcher version: 1.18.0
OS Version: 22000.2538
IntPtr Length: 8
x64: True

Python Path: C:\Users\Win11\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 07/23/2024 13:57:51
Exception:
System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\Win11\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\Win11\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
             ^^^^^^^^^^^^^
  File "C:\Users\Win11\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Win11\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Win11\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Win11\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Win11\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\main.py", line 93, in <module>
    YoutubeDownload()
  File "C:\Users\Win11\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\flowlauncher\FlowLauncher.py", line 33, in __init__
    results = request_method(*request_parameters)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Win11\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\main.py", line 78, in download_audio
    video = youtube.streams.filter(only_audio = True).first()
            ^^^^^^^^^^^^^^^
  File "C:\Users\Win11\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\Win11\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\pytube\__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\Win11\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
             ^^^^^^^^^^^^^
  File "C:\Users\Win11\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Win11\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Win11\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Win11\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 243
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 248
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteResultAsync(JsonRPCResult result) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 117
   at Flow.Launcher.Core.Plugin.JsonRPCPluginBase.<>c__DisplayClass18_0.<<ParseResults>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPluginBase.cs:line 89
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 307
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.18.0

### Windows Build Number

10.0.22000.2538

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by z1nc0r3** [comment]
it looks like an issue related to the plugin : [FlowLauncherYTDownload](https://github.com/DeepVoyager253/FlowLauncherYTDownload). Please raise an issue on the plugin page. Thanks
