### ISSUE TITLE
BUG: Error downloading directory database(dicitionary plugin)

### ISSUE THREAD

**Issue by CodeBy-Ali** [Flow-Launcher/Flow.Launcher#2862]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I am using the latest version of Flow Launcher.

### Problem Description

Flow Launcher version: 1.18.0
OS Version: 19045.4717
IntPtr Length: 8
x64: True

Python Path: C:\Users\Muhammad ALi Hassan\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 07/29/2024 07:01:37
Exception:
System.Net.WebException: An exception occurred during a WebClient request.
 ---> System.IO.IOException: The response ended prematurely, with at least 202853572 additional bytes expected.
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebClient.DownloadBitsAsync(WebRequest request, Stream writeStream, AsyncOperation asyncOp, Action`3 completionDelegate)
   --- End of inner exception stack trace ---
   at Dictionary.DictDownloadManager.PerformDownload() in C:\Users\Null\Documents\Projects\Flow.Launcher.Dictionary\src\DictDownloadManager.cs:line 62
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.18.0

### Windows Build Number

19045.4717

### Error Log

[2024-07-29.txt](https://github.com/user-attachments/files/16406352/2024-07-29.txt)

**Comment by z1nc0r3** [comment]
[Flow.Launcher.Dictionary](https://github.com/harrynull/Flow.Launcher.Dictionary) related issue, so it is good to create a ticket on the plugin page. Also check your connection status, _FL Proxy Settings_ in the meantime.
