### ISSUE TITLE
BUG: This comes up when opening setting

### ISSUE THREAD

**Issue by Sinnamonnn** [Flow-Launcher/Flow.Launcher#2877]
[2024-08-06.txt](https://github.com/user-attachments/files/16517114/2024-08-06.txt)

Flow Launcher version: 1.18.0
OS Version: 19045.4651
IntPtr Length: 8
x64: True

Python Path: C:\Users\DJ\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 08/06/2024 20:12:36
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Flow.Launcher.SettingWindow.OnLoaded(Object sender, RoutedEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\SettingWindow.xaml.cs:line 61
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by z1nc0r3** [comment]
Have you done any _hot-key_ changes recently?

**Comment by Sinnamonnn** [comment]
yes, made it the windows key

**Comment by z1nc0r3** [comment]
We can't use the Win key directly and it is disabled through the Settings. Did you change it through the Settings.json? If so, then please revert that change. There is a plugin for that called **Win Hotkey** and you should try it.

**Comment by VictoriousRaptor** [comment]
Should we validate hotkey when loading jsons?

**Comment by z1nc0r3** [comment]
> Should we validate hotkey when loading jsons?

Yeah, that would be a good solution IMO.
