### ISSUE TITLE
BUG: A lot of third-party plugins not working on portable version

### ISSUE THREAD

**Issue by heldheld** [Flow-Launcher/Flow.Launcher#2880]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Not sure why this is happening, but a lot of my third-party plugins work, and changing any setting on these plugins just resets itself on restart of Flow Launcher. Also, the default settings for plugins are not auto-populated, they are just empty.

The errors I get all give the same thing: FileNotFoundError: Unable to locate Launcher directory
I don't understand why it would be unable to locate the files?
The log I attached is from trying to use Emoji+.

Reinstalling the plugins didn't work.

For some reason, Dictionary is working fine, so it's not all third-party plugins I have but I think most.

### To Reproduce

1. Download Portable Version
2. Install third-party plugins (examples: Emoji+, Github Notifications, CurrencyPP, General Converter)
3. Try to run them, or change settings.

### Screenshots

![image](https://github.com/user-attachments/assets/ec72d090-2be5-4634-8546-642998aaa5a4)

![image](https://github.com/user-attachments/assets/65140722-f67b-4ad7-b6d6-7143ba843fff)

### Flow Launcher Version

1.18.0

### Windows Build Number

10.0.19045.4717

### Error Log

<details>

```shell

Flow Launcher version: 1.18.0
OS Version: 19045.4717
IntPtr Length: 8
x64: True

Python Path: C:\Users\heldheld\AppData\Local\Programs\Python\Python312\pythonw.exe
Node Path: 
Date: 08/07/2024 17:30:19
Exception:
Emoji+ Exception: 
Websites: https://github.com/Garulf/emoji-plus
Author: Garulf
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\heldheld\Documents\Portable Programs\Flow Launcher Portable\app-1.18.0\UserData\Plugins\Emoji+-2.0.0\run.py", line 9, in <module>
    from plugin.emoji import Emoji
  File "C:\Users\heldheld\Documents\Portable Programs\Flow Launcher Portable\app-1.18.0\UserData\Plugins\Emoji+-2.0.0\plugin\emoji.py", line 7, in <module>
    from flox import Flox, utils, ICON_BROWSER, ICON_COPY
  File "C:\Users\heldheld\Documents\Portable Programs\Flow Launcher Portable\app-1.18.0\UserData\Plugins\Emoji+-2.0.0\lib\flox\__init__.py", line 46, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\heldheld\Documents\Portable Programs\Flow Launcher Portable\app-1.18.0\UserData\Plugins\Emoji+-2.0.0\run.py", line 9, in <module>
    from plugin.emoji import Emoji
  File "C:\Users\heldheld\Documents\Portable Programs\Flow Launcher Portable\app-1.18.0\UserData\Plugins\Emoji+-2.0.0\plugin\emoji.py", line 7, in <module>
    from flox import Flox, utils, ICON_BROWSER, ICON_COPY
  File "C:\Users\heldheld\Documents\Portable Programs\Flow Launcher Portable\app-1.18.0\UserData\Plugins\Emoji+-2.0.0\lib\flox\__init__.py", line 46, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 264
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 230
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 307
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```
</details>

**Comment by heldheld** [comment]
Found the issue.

Apparently it's a problem if I rename the folder that Flow Launcher Portable is in. If it is anything other then FlowLauncher, I get these errors. Any way to compensate for this? It's not super important but it does feel a little silly to not be able to rename the main folder.

**Comment by heldheld** [comment]
It does seem there are still issues.
Some plugins still just don't want to save any settings, and will not work.
I can set them in the Settings window, but when I try to use the plugin it just doesn't work and as soon as I restart Flow Launcher, the settings are just gone.
Could this have to do with me using the Portable Version somehow?
I will list all plugins I use that are affected:

ChatGPT
DropboxFinder (will save the token, but not the folder path)
Github Notifications
Minecraft Multi Launcher
Steam Search
TenorGIF

Curiously, some third-party plugins DO work now, that didn't work before I renamed the main folder back to FlowLauncher. Among them:
CurrencyPP
Emoji+
General Converter

**Comment by Garulf** [comment]
Yes some of these plugins were designed to work with Wox *and* Flow Launcher. unfortunately the only reliable way to tell the launcher's apart at run time was using the folder names. This has been fixed but these plugins have not been updated yet.

**Comment by heldheld** [comment]
> Yes some of these plugins were designed to work with Wox _and_ Flow Launcher. unfortunately the only reliable way to tell the launcher's apart at run time was using the folder names. This has been fixed but these plugins have not been updated yet.

Ah okay. So, is the conclusion that those plugins will not work with the Portable Version until they are updated? Because the folder names are default atm and those plugins don't work.

**Comment by Garulf** [comment]
Plugins should work regardless of what mode Flow Launcher is in as long as the folder name is kept default.

**Comment by heldheld** [comment]
> Plugins should work regardless of what mode Flow Launcher is in as long as the folder name is kept default.

In that case, I still have an issue. The plugins in the aforementioned list do not work. Settings I put in are also not saved upon restart of Flow Launcher. Also when I make a completely new Portable Version with default settings.

**Comment by Garulf** [comment]
> > Plugins should work regardless of what mode Flow Launcher is in as long as the folder name is kept default.
> 
> In that case, I still have an issue. The plugins in the aforementioned list do not work, even though the folder name is default. Settings I put in for those plugins are also not saved upon restart of Flow Launcher. Also when I make a completely new Portable Version with default settings, they still don't work.

Settings not saving is a different issue. FLow Launcher changed how it saves settings and these plugins have not been updated to fix that yet.

**Comment by heldheld** [comment]
> Settings not saving is a different issue. Flow Launcher changed how it saves settings and these plugins have not been updated to fix that yet.

I see what you're saying. Thanks for explaining all of this. Is it reasonable to ask the developers (I see some plugins in the list are by you) to update this? Most notably the Steam Search is one I use a lot.

**Comment by heldheld** [comment]
@Garulf *bumping* this issue since it's gotten the stale label.

**Comment by jjw24** [comment]
If an issue hasn't been made to the Steam Search plugin repo It might be good to do so. Besides that plugin what's another one that you use often and not working. I can take a look at the two plugins in my spare time.

**Comment by heldheld** [comment]
> If an issue hasn't been made to the Steam Search plugin repo It might be good to do so. Besides that plugin what's another one that you use often and not working. I can take a look at the two plugins in my spare time.

Thanks for the response and the offer!

I've made an issue for the Steam Search plugin just now: https://github.com/Garulf/Steam-Search/issues/66
Besides that one, I'd love to be able to use TenorGIF and Minecraft Multi Launcher. The other ones are not that important to me.

**Comment by enoversum** [comment]
> > If an issue hasn't been made to the Steam Search plugin repo It might be good to do so. Besides that plugin what's another one that you use often and not working. I can take a look at the two plugins in my spare time.
> 
> Thanks for the response and the offer!
> 
> I've made an issue for the Steam Search plugin just now: [Garulf/Steam-Search#66](https://github.com/Garulf/Steam-Search/issues/66) Besides that one, I'd love to be able to use TenorGIF and Minecraft Multi Launcher. The other ones are not that important to me.

I just came across this issue as well, and also the one with settings not saving. It appears all of Garulf's plugins haven't been updated to work with the 'new' way of FL saving settings. I cannot save settings and also get the same error on another plugin of his.
