### ISSUE TITLE
dialog box prompted to open an issue

### ISSUE THREAD

**Issue by nihalxkumar** [Flow-Launcher/Flow.Launcher#2886]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [ ] I am using the latest version of Flow Launcher.

### Problem Description

After using spotify premium plugin dialog box prompted to open an issue. Never happened before.
It seems to me that plugin and everything are still working fine.

### Screenshots

can share the logs file if required.

### Flow Launcher Version

1.18.0

### Windows Build Number

10.0.22631.3958

### Error Log

<details>

```shell
Flow Launcher version: 1.18.0
OS Version: 22631.3958
IntPtr Length: 8
x64: True

Python Path: C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\pythonw.exe
Node Path: C:\Users\Lenovo\AppData\Roaming\FlowLauncher\Environments\Node.js\Node-v16.18.0\node-v16.18.0-win-x64\node.exe
Date: 08/12/2024 14:03:08
Exception:
System.AggregateException: One or more errors occurred. (Unexpected character encountered while parsing value: U. Path '', line 0, position 0.)
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: U. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at SpotifyAPI.Web.Http.NewtonsoftJSONSerializer.DeserializeResponse[T](IResponse response)
   at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.SendAPIRequestDetailed(Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers)
   at SpotifyAPI.Web.Http.APIConnector.Post(Uri uri, IDictionary`2 parameters, Object body)
   at SpotifyAPI.Web.PlayerClient.SkipNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPluginClient.Skip() in D:\a\Flow.Launcher.Plugin.SpotifyPremium\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPluginClient.cs:line 207
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPlugin.<>c__DisplayClass37_0.<SingleResultInList>b__0(ActionContext _) in D:\a\Flow.Launcher.Plugin.SpotifyPremium\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPlugin.cs:line 568
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 307
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
</details>

**Comment by z1nc0r3** [comment]
duplicate #2857
