### ISSUE TITLE
BUG: Click to select node.js folder

### ISSUE THREAD

**Issue by agldiasdigital** [Flow-Launcher/Flow.Launcher#2901]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I am using the latest version of Flow Launcher.

### Problem Description

Error displayed when click to define node.js folder:

Flow Launcher version: 1.19.0
OS Version: 19045.4780
IntPtr Length: 8
x64: True

Python Path: C:\Python311\pythonw.exe
Node Path: 
Date: 08/16/2024 10:33:58
Exception:
System.ArgumentException: Filter string you provided is not valid. The filter string must contain a description of the filter, followed by the vertical bar (|) and the filter pattern. The strings for different filtering options must also be separated by the vertical bar. Example: "Text files (*.txt)|*.txt|All files (*.*)|*.*" (Parameter 'value')
   at System.Windows.Forms.FileDialog.set_Filter(String value)
   at Flow.Launcher.SettingPages.ViewModels.SettingsPaneGeneralViewModel.GetFileFromDialog(String title, String filter) in C:\projects\flow-launcher\Flow.Launcher\SettingPages\ViewModels\SettingsPaneGeneralViewModel.cs:line 144
   at Flow.Launcher.SettingPages.ViewModels.SettingsPaneGeneralViewModel.SelectNode() in C:\projects\flow-launcher\Flow.Launcher\SettingPages\ViewModels\SettingsPaneGeneralViewModel.cs:line 195
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

1. Open Flow Settings
2. Click on "select" button to select node.js folder
3. Get error

### Flow Launcher Version

1.19.0

### Windows Build Number

19045.4780

### Error Log

[2024-08-16.txt](https://github.com/user-attachments/files/16637693/2024-08-16.txt)

**Comment by Mystinals** [comment]
Attaching my log.txt as contribution for the same error reported by @agldiasdigital 
[2024-08-18.txt](https://github.com/user-attachments/files/16651054/2024-08-18.txt)

**Comment by jjw24** [comment]
Fix available in prerelease https://github.com/Flow-Launcher/Prereleases/releases/tag/v1.19.0.9132

Alternatively leave it blank and start using a js/ts plugin flow will prompt to install node.js for you instead and this will install without issues.
