### ISSUE TITLE
BUG: flow launcher error

### ISSUE THREAD

**Issue by TheGr8Coder** [Flow-Launcher/Flow.Launcher#2922]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [ ] I am using the latest version of Flow Launcher.

### Problem Description

[2024-08-22.txt]
Log: (https://github.com/user-attachments/files/16711509/2024-08-22.txt)

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.19.0

### Windows Build Number

10.0.22621.4037

### Error Log

Flow Launcher version: 1.19.0
OS Version: 22621.4037
IntPtr Length: 8
x64: True

Python Path: C:\Users\win10\AppData\Local\FlowLauncher\app-1.19.0\UserData\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 08/22/2024 19:13:40
Exception:
System.Net.WebException: An exception occurred during a WebClient request.
 ---> System.IO.IOException: The response ended prematurely, with at least 56052932 additional bytes expected.
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebClient.DownloadBitsAsync(WebRequest request, Stream writeStream, AsyncOperation asyncOp, Action`3 completionDelegate)
   --- End of inner exception stack trace ---
   at Dictionary.DictDownloadManager.PerformDownload() in C:\Users\Null\Documents\Projects\Flow.Launcher.Dictionary\src\DictDownloadManager.cs:line 62
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
Please let us know how you got this error and how to reproduce it.

**Comment by jjw24** [comment]
Looks like it's an error from the dictionary plugin trying download the required data on first use.
