### ISSUE TITLE
BUG: Select Node Path in Settings

### ISSUE THREAD

**Issue by yankikucuk** [Flow-Launcher/Flow.Launcher#2930]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Getting an error when trying to define node path in settings.

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.19.0

### Windows Build Number

22631.4037

### Error Log

<details>

```shell

Flow Launcher version: 1.19.0
OS Version: 22631.4037
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 08/24/2024 19:18:33
Exception:
System.ArgumentException: Filter string you provided is not valid. The filter string must contain a description of the filter, followed by the vertical bar (|) and the filter pattern. The strings for different filtering options must also be separated by the vertical bar. Example: "Text files (*.txt)|*.txt|All files (*.*)|*.*" (Parameter 'value')
   at System.Windows.Forms.FileDialog.set_Filter(String value)
   at Flow.Launcher.SettingPages.ViewModels.SettingsPaneGeneralViewModel.GetFileFromDialog(String title, String filter) in C:\projects\flow-launcher\Flow.Launcher\SettingPages\ViewModels\SettingsPaneGeneralViewModel.cs:line 144
   at Flow.Launcher.SettingPages.ViewModels.SettingsPaneGeneralViewModel.SelectNode() in C:\projects\flow-launcher\Flow.Launcher\SettingPages\ViewModels\SettingsPaneGeneralViewModel.cs:line 195
   at CommunityToolkit.Mvvm.Input.RelayCommand.Execute(Object parameter)
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```
[2024-08-24.txt](https://github.com/user-attachments/files/16737354/2024-08-24.txt)
</details>

**Comment by jjw24** [comment]
Dup #2901
