### ISSUE TITLE
BUG: Json Error Message

### ISSUE THREAD

**Issue by ohhsodead** [Flow-Launcher/Flow.Launcher#2943]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Got an error message after the music started playing. I didn't have any actual issues but thought you would want the log for the issue it thrown. Thanks for the plugin, first time using FlowLauncher and your plugin is much appreciated! 

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.19.0

### Windows Build Number

19045.4780

### Error Log

Flow Launcher version: 1.19.0
OS Version: 19045.4780
IntPtr Length: 8
x64: True

Python Path: C:\Users\OhItsAsh\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 08/29/2024 22:51:25
Exception:
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: o. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at SpotifyAPI.Web.Http.NewtonsoftJSONSerializer.DeserializeResponse[T](IResponse response)
   at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.SendAPIRequestDetailed(Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers)
   at SpotifyAPI.Web.Http.APIConnector.Put(Uri uri, IDictionary`2 parameters, Object body)
   at SpotifyAPI.Web.PlayerClient.ResumePlayback()
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPluginClient.Play() in D:\a\Flow.Launcher.Plugin.SpotifyPremium\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPluginClient.cs:line 149
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPlugin.<>c__DisplayClass19_0.<GetPlaying>b__2() in D:\a\Flow.Launcher.Plugin.SpotifyPremium\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPlugin.cs:line 227
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPlugin.<>c__DisplayClass37_0.<SingleResultInList>b__0(ActionContext _) in D:\a\Flow.Launcher.Plugin.SpotifyPremium\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPlugin.cs:line 568
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
Hi there, this issue is fixed. Back up your security.store file (because it will get deleted) and update the Spotify plugin.
