### ISSUE TITLE
BUG: Error when trying to have XYPlorer as the default explorer

### ISSUE THREAD

**Issue by dianedef** [Flow-Launcher/Flow.Launcher#2952]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Flow can't open XYPlorer

### To Reproduce

1. Install XYplorer
2. Add the path to XYPlorer.exe in the settings of FLow Launch instead of Windows explorer to open folders by default
3. I ry to open a folder with Flow Launcher, I get this error!

### Screenshots

Windows version : ![image](https://github.com/user-attachments/assets/853f01df-6214-4ef4-9ea4-39c77eedbb99)

### Flow Launcher Version

1.19.0

### Windows Build Number

Microsoft Windows [version 10.0.22631.4112]

### Error Log

Flow Launcher version: 1.19.0
OS Version: 22631.4112
IntPtr Length: 8
x64: True

Python Path: C:\Users\Shadow\AppData\Local\FlowLauncher\app-1.19.0\UserData\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 09/03/2024 16:23:26
Exception:
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Program Files (x86)\XYplorer.exe' with working directory 'C:\WINDOWS\system32'. Le fichier spécifié est introuvable.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at Flow.Launcher.PublicAPIInstance.OpenDirectory(String DirectoryPath, String FileNameOrFilePath) in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 246
   at Flow.Launcher.Plugin.Explorer.Search.ResultManager.OpenFolder(String folderPath, String fileNameOrFilePath) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\ResultManager.cs:line 346
   at Flow.Launcher.Plugin.Explorer.Search.ResultManager.<>c__DisplayClass14_0.<CreateOpenCurrentFolderResult>b__0(ActionContext c) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\ResultManager.cs:line 263
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by taooceros** [comment]
> Le fichier spécifié est introuvable.

I don't think it's from flow side? Maybe you get some kind of path or arguments wrong?

**Comment by dianedef** [comment]
You are very right, how did you know?

I forgot to add the parent folder of the .exe
I also add to remove the "/O /A /S /T" in the query otherwise it would not work. Now it's working! Thank you :D!

**Comment by taooceros** [comment]
It's very easy to make this kind of mistake🤣 I've made it a couple times.
