### ISSUE TITLE
Flow launcher got an error

### ISSUE THREAD

**Issue by burakcosar** [Flow-Launcher/Flow.Launcher#2953]
[2024-09-04.txt](https://github.com/user-attachments/files/16860337/2024-09-04.txt)

Flow Launcher version: 1.19.0
OS Version: 22631.4112
IntPtr Length: 8
x64: True

Python Path: C:\Users\burak\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 09/04/2024 06:10:46
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ClipboardR.ClipboardR.Save()
   at Flow.Launcher.Core.Plugin.PluginManager.Save() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 59
   at Flow.Launcher.PublicAPIInstance.SaveAppAllSettings() in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 84
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 108
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 51
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
See if it is fine by disabling ClipboardR.

**Comment by burakcosar** [comment]
> See if it is fine by disabling ClipboardR.

It's been a while since I turned that off. The error came long after that

**Comment by burakcosar** [comment]
fixed.

**Comment by jjw24** [comment]
There is another clipboard plugin you can try out if you like.
