### ISSUE TITLE
Flow launcher got an error: Plugins failed to load

### ISSUE THREAD

**Issue by cgmilan29** [Flow-Launcher/Flow.Launcher#2957]
[2024-09-05.txt](https://github.com/user-attachments/files/16883104/2024-09-05.txt)

Flow Launcher version: 1.19.0
OS Version: 22631.4112
IntPtr Length: 8
x64: True

Python Path: C:\Users\Dell\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 09/05/2024 08:04:42
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ClipboardR.ClipboardR.Save()
   at Flow.Launcher.Core.Plugin.PluginManager.Save() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 59
   at Flow.Launcher.PublicAPIInstance.SaveAppAllSettings() in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 84
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 108
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 51
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

![image](https://github.com/user-attachments/assets/dad87182-7e7a-4cd6-8bee-adf2bf0d651d)

![image](https://github.com/user-attachments/assets/007fc1a1-fb20-40c1-a643-5a7030ee6564)

**Comment by jjw24** [comment]
Try disable ClipboardR plugin, see if the rest will load.
