### ISSUE TITLE
BUG: Exception when using: pm install if plugin is already installed

### ISSUE THREAD

**Issue by stefanroelofs** [Flow-Launcher/Flow.Launcher#2962]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

First of all thanks for the new feature: 

> Plugin zip file can now be installed locally.

When i use the following command:
`pm install N:\Software\Flowlauncher\ProjectLauncher.zip`

But the plugin is already installed (so I should have used pm update),  I get this exception.

[2024-09-06.txt](https://github.com/user-attachments/files/16903937/2024-09-06.txt)

Flow Launcher version: 1.19.0
OS Version: 22621.4037
IntPtr Length: 8
x64: True

Python Path: C:\Users\710\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 09/06/2024 08:40:53
Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Flow.Launcher.Plugin.PluginsManager.PluginsManager.InstallSourceKnown(String url)
   at Flow.Launcher.Plugin.PluginsManager.PluginsManager.<>c__DisplayClass21_0.<InstallFromLocalPath>b__0(ActionContext e) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.PluginsManager\PluginsManager.cs:line 514
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

One more remark: There is no way to downgrade a plugin once installed. 
Thanks!

### To Reproduce

1. Install plugin via local plugin zip
2. Install the same plugin again

### Flow Launcher Version

1.19.0

### Windows Build Number

10.0.22621.4037

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by Jack251970** [comment]
I think this is already fixed in the latest version.

https://github.com/Flow-Launcher/Flow.Launcher/blob/d2e63ab437de099fc01fbc047fe9281375a672c2/Plugins/Flow.Launcher.Plugin.PluginsManager/PluginsManager.cs#L585-L586

Let me know if you encounter this issue again.
