### ISSUE TITLE
BUG: Notion by Amin Sallah

### ISSUE THREAD

**Issue by andreghl** [Flow-Launcher/Flow.Launcher#2964]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

I believe the problem results from the Notion package by [Amin Sallah](https://github.com/AminSallah/Flow.Launcher.Plugin.Notion/tree/main?tab=readme-ov-file). I am however unable to open the app (to access flow launcher settings and uninstall the app).

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

![{CE1C5E9E-FFCA-43F3-8552-C16A853403C5}](https://github.com/user-attachments/assets/e5c98919-2511-4d79-a3b0-d1771fa6aeb3)

### Flow Launcher Version

1.19.1

### Windows Build Number

10.0.22631.4112

### Error Log

Error Message:

Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues
1. upload log file: C:\Users\Hp\AppData\Roaming\FlowLauncher\Logs\1.19.1\2024-09-07.txt
2. copy below exception message

Flow Launcher version: 1.19.1
OS Version: 22631.4112
IntPtr Length: 8
x64: True

Python Path: C:\Users\Hp\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 09/07/2024 22:52:26
Exception:
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Flow.Launcher.Plugin.Notion.Main.OnVisibilityChanged(Object _, VisibilityChangedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
Hi there, you can remove the plugin manually by going to flow's user data folder -> plugins -> remove the folder.

Also best to post the issue over at the repo to help him investigate and fix: https://github.com/AminSallah/Flow.Launcher.Plugin.Notion
