### ISSUE TITLE
BUG: Cannot open theme folder

### ISSUE THREAD

**Issue by Raivolz** [Flow-Launcher/Flow.Launcher#2965]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I am using the latest version of Flow Launcher.

### Problem Description

Cannot open theme folder/any folder button is not working

### To Reproduce

1. Goto Settings
2. Goto Appearence
3. Click Open theme folder

### Screenshots

![image](https://github.com/user-attachments/assets/9487c09b-17dc-440b-8e23-d63d86e4a51b)

### Flow Launcher Version

1.19.1

### Windows Build Number

Microsoft Windows [Version 10.0.22631.4112]

### Error Log

[Error Log](https://github.com/user-attachments/files/16922992/2024-09-08.txt)

**Exception Message**: 

Flow Launcher version: 1.19.1
OS Version: 22631.4112
IntPtr Length: 8
x64: True

Python Path: C:\Users\rsraj\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 09/08/2024 22:15:05
Exception:
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Program Files\totalcmd\TOTALCMD64.exe' with working directory 'C:\Users\rsraj\AppData\Local\FlowLauncher\app-1.19.1'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at Flow.Launcher.PublicAPIInstance.OpenDirectory(String DirectoryPath, String FileNameOrFilePath) in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 246
   at Flow.Launcher.SettingPages.ViewModels.SettingsPaneThemeViewModel.OpenThemesFolder() in C:\projects\flow-launcher\Flow.Launcher\SettingPages\ViewModels\SettingsPaneThemeViewModel.cs:line 421
   at CommunityToolkit.Mvvm.Input.RelayCommand.Execute(Object parameter)
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by taooceros** [comment]
looks like the issue is with your total commander setup?

**Comment by Jack251970** [comment]
Already fixed in #3552
