### ISSUE TITLE
BUG: PowerToys plugin execution

### ISSUE THREAD

**Issue by danteasy** [Flow-Launcher/Flow.Launcher#2975]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [ ] I am using the latest version of Flow Launcher.

### Problem Description

Flow Launcher version: 1.18.0
OS Version: 22631.2861
IntPtr Length: 8
x64: True

Python Path: C:\Python312\pythonw.exe
Node Path: 
Date: 09/16/2024 22:10:30
Exception:
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Users\Yevhenii\AppData\Local\PowerToys\PowerToys.exe' with working directory 'C:\Users\Yevhenii\AppData\Local\FlowLauncher\app-1.18.0'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Flow.Launcher.Plugin.PowerToys.OpenPowerToysSettingsAction.Execute()
   at Flow.Launcher.Plugin.PowerToys.PowerToys.<>c__DisplayClass4_0.<MapActionToResult>b__0(ActionContext _)
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 307
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

1. Install PowerToys plugin from plugin store.
2. Open flow launcher
3. type "ptoys" and then choose "Open powertoys settings"

### Flow Launcher Version

1.18.0

### Windows Build Number

11.23.12

### Error Log

[2024-09-16.txt](https://github.com/user-attachments/files/17019429/2024-09-16.txt)

**Comment by deefrawley** [comment]
Hi. Please update to the latest version of Flow and see if the issue persists.. That is why we put that checkbox in the issue template, to get you to check that first.

**Comment by jjw24** [comment]
This error may also relate to the PowerToys plugin, it's worth reporting it over at the plugin repo instead. You can find the link to the repo in the plugin settings as a some hut icon.
