### ISSUE TITLE
BUG: Crash happens when I do basic calculator

### ISSUE THREAD

**Issue by wynhou** [Flow-Launcher/Flow.Launcher#3000]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I am using the latest version of Flow Launcher.

### Problem Description

Hard crash constantly when I try to search or do some basic math calculations, error log added.

### To Reproduce

1. Open launcher
2. Start entering in a calculation like 9+12
3. Hard crash

### Flow Launcher Version

1.19.2

### Windows Build Number

22631.4108

### Error Log

Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues
1. upload log file: C:\Users\Wyn\AppData\Roaming\FlowLauncher\Logs\1.19.2\2024-09-27.txt
2. copy below exception message

Flow Launcher version: 1.19.2
OS Version: 26100.1876
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 09/27/2024 13:04:06
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Controls.Primitives.Popup.OnWindowResize(Object sender, AutoResizedEventArgs e)
   at System.Windows.Interop.HwndSource.Resize(Size newSize)
   at System.Windows.Interop.HwndSource.OnLayoutUpdated(Object obj, EventArgs args)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.AnimatedRenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by VictoriousRaptor** [comment]
Hi, does this crash happen when performing other seaches?
