### ISSUE TITLE
BUG: Unable to launch flow launcher

### ISSUE THREAD

**Issue by Boldsen** [Flow-Launcher/Flow.Launcher#3020]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

I am unable to launch the application at all since today, tried to update to the newest version, didn't work.
The exception is CultureNotFoundException: Culture is not supported. (Parameter 'culture')
4096 (0x1000) is an invalid culture identifier.

Every time i even click on the error popup, a new popup appears, even if i click the X button a new one appears just as the first one closes.

Log attached

### To Reproduce

1. Try to launch the application

### Flow Launcher Version

1.19.2

### Windows Build Number

10.0.22631.4169

### Error Log

<details>

```shell

17:35:08.8280+02:00 - INFO  - App.OnStartup - Begin Flow Launcher startup ----------------------------------------------------
17:35:08.8280+02:00 - INFO  - App.OnStartup - Runtime info:
Flow Launcher version: 1.19.2
OS Version: 22631.4169
IntPtr Length: 8
x64: True

...

17:35:09.8642+02:00 - INFO  - App.OnStartup - End Flow Launcher startup ----------------------------------------------------  
17:35:09.8642+02:00 - INFO  - App.OnStartup - Startup cost <1087ms>
17:35:09.9370+02:00 - FATAL - UnHandledException - 
## Exception

```
System.Globalization.CultureNotFoundException: Culture is not supported. (Parameter 'culture')
4096 (0x1000) is an invalid culture identifier.
   Source: System.Private.CoreLib
   TargetAssembly: System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
   TargetModule: System.Private.CoreLib.dll
   TargetSite: Void .ctor(Int32, Boolean)
   at System.Globalization.CultureInfo..ctor(Int32 culture, Boolean useUserOverride)
   at System.Windows.Input.InputLanguageSource.get_CurrentInputLanguage()
   at System.Windows.Documents.TextSelection.EnsureCaret(Boolean isBlinkEnabled, Boolean isSelectionActive, CaretScrollMethod scrollMethod)
   at System.Windows.Documents.TextSelection.System.Windows.Documents.ITextSelection.UpdateCaretAndHighlight()
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   at System.Windows.UIElement.Focus()
   at Flow.Launcher.MainWindow.OnLoaded(Object sender, RoutedEventArgs _) in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 200
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

## Environment
* Command Line: C:\Users\boldd\AppData\Local\FlowLauncher\app-1.19.2\Flow.Launcher.dll
* Timestamp: 10/11/2024 17:35:09
* Flow Launcher version: 1.19.2
* OS Version: 22631.4169
* IntPtr Length: 8
* x64: True
* Python Path: C:\Python312\pythonw.exe
* Node Path: C:\Program Files\nodejs\node.exe
* CLR Version: 7.0.20
* Installed .NET Framework: 
   * v4 Client 4.8.09032
   * v4 Full 4.8.09032
   * v4.0 Client 4.0.0.0

```
</details>

**Comment by VictoriousRaptor** [comment]
Hi, could you please post your system language, region settings and keyboard layout? 

Possible solution: https://github.com/microsoft/PowerToys/issues/24172#issuecomment-1449476792

**Comment by Boldsen** [comment]
All my system language settings looked normal (the same as before this issue), for some reason hitting Shift+Alt to change keyboard languages (even though i have no other keyboard languages installed on my pc, so literally nothing happened) it fixed the issue.
Issue started to occur after plugging in a new mouse (I think)
