### ISSUE TITLE
BUG: 使用everything报错

### ISSUE THREAD

**Issue by zhangyanyu2** [Flow-Launcher/Flow.Launcher#3031]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

索引搜索引擎更改为everything后报错，无法搜索文件

### Screenshots

![屏幕截图 2024-10-15 230928](https://github.com/user-attachments/assets/fea8301b-4273-43c3-b4a2-46e89f4bc452)
![屏幕截图 2024-10-15 230943](https://github.com/user-attachments/assets/3616d746-2886-4c29-af91-528aa116ecbc)
![屏幕截图 2024-10-15 231150](https://github.com/user-attachments/assets/e18d8af0-9ca1-4eb5-b7f9-7b7cb7e0e5e9)

### Flow Launcher Version

1.19.2

### Windows Build Number

26100.2033

### Error Log

Everything Search Exception:
 Flow.Launcher.Plugin.Explorer.Exceptions.SearchException: Error in the application.
 ---> Flow.Launcher.Plugin.Explorer.Search.Everything.Exceptions.IPCErrorException: Error in the application.
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingApi.CheckAndThrowExceptionOnError() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingAPI.cs:line 176
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingApi.SearchAsync(EverythingSearchOption option, CancellationToken token)+MoveNext() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingAPI.cs:line 130
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingApi.SearchAsync(EverythingSearchOption option, CancellationToken token)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingSearchManager.SearchAsync(String search, CancellationToken token)+MoveNext() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingSearchManager.cs:line 73
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingSearchManager.SearchAsync(String search, CancellationToken token)+MoveNext() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingSearchManager.cs:line 73
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingSearchManager.SearchAsync(String search, CancellationToken token)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 112
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 112
   --- End of inner exception stack trace ---
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 129
   at Flow.Launcher.Plugin.Explorer.Main.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Main.cs:line 62

**Comment by taooceros** [comment]
which version of everything are you using?
