### ISSUE TITLE
BUG: Flow.Launcher.Plugin.Explorer error when change Index Search engine to Everything

### ISSUE THREAD

**Issue by prpjzz** [Flow-Launcher/Flow.Launcher#3037]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

When I leave it at the default setting (which is Windows Index), everything is normal, but if I switch to Method Everything, it comes up, and I can't find anything from the device (of course I installed Everything and I'm using it).

### To Reproduce

1. Open Flow Launcher Settings
2. Go to Plugins → Explorer and change Index Search Engine to Everything.
3. Alt + Space and search with any keyword → Boom, error appears.

### Screenshots

Use With Everything settings.
![image](https://github.com/user-attachments/assets/b8408e00-983b-4ee0-897e-30c6a6393610)

Use Windows Index Settings.
![image](https://github.com/user-attachments/assets/b5ffe7a7-e387-44df-be98-644e0f2fa9c2)

### Flow Launcher Version

1.19.3

### Windows Build Number

10.0.19044.4780

### Error Log

```shell

Everything Search Exception:
 Flow.Launcher.Plugin.Explorer.Exceptions.SearchException: Error in the application.
 ---> Flow.Launcher.Plugin.Explorer.Search.Everything.Exceptions.IPCErrorException: Error in the application.
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingApi.CheckAndThrowExceptionOnError() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingAPI.cs:line 176
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingApi.SearchAsync(EverythingSearchOption option, CancellationToken token)+MoveNext() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingAPI.cs:line 130
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingApi.SearchAsync(EverythingSearchOption option, CancellationToken token)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingSearchManager.SearchAsync(String search, CancellationToken token)+MoveNext() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingSearchManager.cs:line 73
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingSearchManager.SearchAsync(String search, CancellationToken token)+MoveNext() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingSearchManager.cs:line 73
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingSearchManager.SearchAsync(String search, CancellationToken token)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 136
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 136
   --- End of inner exception stack trace ---
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 136
   at Flow.Launcher.Plugin.Explorer.Main.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Main.cs:line 88

```

**Comment by deefrawley** [comment]
Which version of Everything are you using?

**Comment by prpjzz** [comment]
I using v1.4.1.1026 Lite (x86 version).
![image](https://github.com/user-attachments/assets/ee8bb92f-b3dd-4db0-acbc-f1cbb0b50429)

**Comment by prpjzz** [comment]
I think my problem is using Lite version, when it cuts some features such as SDK. I'm trying to download and reinstall the normal version.

**Comment by prpjzz** [comment]
After I downloaded and installed the normal version, everything came back. Thank you. This is partly my fault for not reading everything's FAQs carefully.

**Comment by deefrawley** [comment]
All good, glad you got it sorted.
