### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by sansy182** [Flow-Launcher/Flow.Launcher#3038]
Flow Launcher version: 1.19.0
OS Version: 26100.2033
IntPtr Length: 8
x64: True

Python Path: C:\Users\trung\AppData\Local\Programs\Python\Python310\pythonw.exe
Node Path: 
Date: 10/21/2024 15:04:36
Exception:
System.NotSupportedException: No imaging component suitable to complete this operation was found.
 ---> System.Runtime.InteropServices.COMException (0x88982F50): The component cannot be found. (0x88982F50)
   --- End of inner exception stack trace ---
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at Flow.Launcher.Infrastructure.Image.ImageLoader.InitializeAsync() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Image\ImageLoader.cs:line 44
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 86
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 51
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   [2024-10-21.txt](https://github.com/user-attachments/files/17466964/2024-10-21.txt)

**Comment by deefrawley** [comment]
Hi,
Looks like an image cache issue. Can you uninstall and reinstall the latest Flow version?

**Comment by sansy182** [comment]
Fixed, thanks
