### ISSUE TITLE
BUG: Everything 1.5 Alpha not detected by launcher

### ISSUE THREAD

**Issue by Zefa-161** [Flow-Launcher/Flow.Launcher#3041]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Presumably due to running Everything 1.5 alpha, flow launcher doesn't see that everything is installed and indeed running.

### To Reproduce

1. Download Everything 1.5a
2. Change search option to everything
3. Try search for something 
4. Click the shown dialogue 

### Screenshots

![image](https://github.com/user-attachments/assets/5dfa0901-f3d0-493a-ba12-725c811b587c)

### Flow Launcher Version

1.19.3

### Windows Build Number

26100.2033

### Error Log

<details>

```shell

Python Path: C:\Users\nethe\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: C:\Users\nethe\AppData\Roaming\FlowLauncher\Environments\Node.js\Node-v16.18.0\node-v16.18.0-win-x64\node.exe
Date: 10/22/2024 20:43:27
Exception:
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Program Files\Everything 1.5a\Everything.exe' with working directory 'C:\Users\nethe\AppData\Local\FlowLauncher\app-1.19.3'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingSearchManager.ClickToInstallEverythingAsync(ActionContext _) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingSearchManager.cs:line 55
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


```
</details>
[2024-10-22.txt](https://github.com/user-attachments/files/17481326/2024-10-22.txt)

**Comment by deefrawley** [comment]
See this post for 1.5a

https://github.com/Flow-Launcher/Flow.Launcher/issues/1716

**Comment by Zefa-161** [comment]
@deefrawley I followed taooceros advice on the post and added the line "alpha_instance=0" to the ini config file, restarted everything and then I tried restarting my pc and I'm still getting the same error.
