### ISSUE TITLE
BUG: The "Everything" process fails to start

### ISSUE THREAD

**Issue by seangallison** [Flow-Launcher/Flow.Launcher#3042]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Everything did not launch on reboot after updating NordVPN

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.19.2

### Windows Build Number

10.0.22631.4317

### Error Log

Flow Launcher version: 1.19.2
OS Version: 22631.4317
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 10/23/2024 18:58:53
Exception:
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'MsiExec.exe \Everything.exe' with working directory 'C:\Windows\system32'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingSearchManager.ClickToInstallEverythingAsync(ActionContext _) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingSearchManager.cs:line 55
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by deefrawley** [comment]
Is the path to Everything still valid?

Also update Flow to the latest version.
