### ISSUE TITLE
BUG: Flow launcher got an error

### ISSUE THREAD

**Issue by KBelmin** [Flow-Launcher/Flow.Launcher#3043]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Flow Launcher version: 1.19.3
OS Version: 19045.1889
IntPtr Length: 8
x64: True

Python Path: C:\Users\Belmin\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 10/24/2024 12:31:26
Exception:
System.IO.IOException: Unable to remove the file to be replaced.
   at System.IO.FileSystem.ReplaceFile(String sourceFullPath, String destFullPath, String destBackupFullPath, Boolean ignoreMetadataErrors)
   at Flow.Launcher.Infrastructure.Storage.JsonStorage`1.AtomicWriteSetting() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Storage\JsonStorage.cs:line 209
   at Flow.Launcher.Infrastructure.Storage.JsonStorage`1.Save() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Storage\JsonStorage.cs:line 189
   at Flow.Launcher.Core.Plugin.JsonRPCPluginSettings.Save() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPluginSettings.cs:line 102
   at Flow.Launcher.Core.Plugin.JsonRPCPluginBase.Save() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPluginBase.cs:line 156
   at Flow.Launcher.Core.Plugin.PluginManager.Save() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 59
   at Flow.Launcher.PublicAPIInstance.SaveAppAllSettings() in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 84
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 108
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 58
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 51
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

1. Restart windows

### Flow Launcher Version

1.19.3

### Windows Build Number

19045.1889

### Error Log

<details>

```shell

Replace this line with the important log contents.

```

[2024-10-24.txt](https://github.com/user-attachments/files/17505559/2024-10-24.txt)

**Comment by taooceros** [comment]
Could you describe more about how to reproduce?

**Comment by KBelmin** [comment]
> Could you describe more about how to reproduce?

There is nothing to describe, whenever I restart (and flow starts - because autorun) it shows this error message. (I could still use it but this message popped up before)

Also bitdefender started to see flow as a infection suddenly, is this normal?

**Comment by taooceros** [comment]
> Also bitdefender started to see flow as a infection suddenly, is this normal?

I don't know? this error means that flow is trying to modify its setting files atomically, but failed. does it happen often or only occasionally?

**Comment by KBelmin** [comment]
> > Also bitdefender started to see flow as a infection suddenly, is this normal?
> 
> I don't know? this error means that flow is trying to modify its setting files atomically, but failed. does it happen often or only occasionally?

Now it happens everytime I try to start flow launcher. maybe I will try to do a full reinstall and hope it gets back to normal.

**Comment by taooceros** [comment]
Pretty weird. I will check the diff. On the other hand it can happen due to malformed setting spec from some plugins. Have you installed some python plugin lately and find the issue appear?

**Comment by KBelmin** [comment]
> Pretty weird. I will check the diff. On the other hand it can happen due to malformed setting spec from some plugins. Have you installed some python plugin lately and find the issue appear?

Hey, yes I installed the timer one which is pretty cool but when I tried to set a timer Bitdefender just completely closed everything and marked flow etc. as infected. I am going crazy is this normal? Is it safe to use flow and the plugins? But also why does Bitdefender start to flag flow etc.?

**Comment by jjw24** [comment]
Flow itself should not get flagged. Be mindful when installing plugins, always good to checkout their repo readme as well as issues section to ensure nothing is flagged with the plugin by the community.

Uninstall timer plugin and see if you still get the same issue.
