### ISSUE TITLE
BUG: Bitwarden Plugin can't save client secret

### ISSUE THREAD

**Issue by InvitedToHell** [Flow-Launcher/Flow.Launcher#3055]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

As soon as I try to save a client secret inside of the bitwarden plugin, I get a Flow Launcher error.

### To Reproduce

1. Download the plugin
2. Enter any client secret
3. Save it and experience the crash

### Flow Launcher Version

1.19.3

### Windows Build Number

10.0.22631 Build 22631

### Error Log

<details>

```shell
Flow Launcher version: 1.19.3
OS Version: 22631.4317
IntPtr Length: 8
x64: True

Python Path: C:\Users\InvitedToHell\scoop\apps\flow-launcher\current\app-1.19.3\UserData\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: C:\Users\InvitedToHell\scoop\apps\flow-launcher\current\app-1.19.3\UserData\Environments\Node.js\Node-v16.18.0\node-v16.18.0-win-x64\node.exe
Date: 10/31/2024 00:08:35
Exception:
System.Exception: Failed to write credential. Error code: 8
   at Flow.Launcher.Plugin.BitwardenSearch.SecureCredentialManager.SaveCredential(String username, SecureString password) in D:\a\Flow.Launcher.Plugin.BitwardenSearch\Flow.Launcher.Plugin.BitwardenSearch\SecureCredentialManager.cs:line 59
   at Flow.Launcher.Plugin.BitwardenSearch.BitwardenFlowSettingPanel.SaveClientSecret() in D:\a\Flow.Launcher.Plugin.BitwardenSearch\Flow.Launcher.Plugin.BitwardenSearch\BitwardenFlowSettingPanel.xaml.cs:line 322
   at Flow.Launcher.Plugin.BitwardenSearch.BitwardenFlowSettingPanel.SaveClientSecretButton_Click(Object sender, RoutedEventArgs e) in D:\a\Flow.Launcher.Plugin.BitwardenSearch\Flow.Launcher.Plugin.BitwardenSearch\BitwardenFlowSettingPanel.xaml.cs:line 310
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
</details>

And more: [2024-10-31.txt](https://github.com/user-attachments/files/17579921/2024-10-31.txt)

**Comment by deefrawley** [comment]
Hi, can you please post in the plugin's repo so the author can investigate? Thanks

https://github.com/RedMageKnight/Flow.Launcher.Plugin.BitwardenSearch/issues

**Comment by InvitedToHell** [comment]
Sure thing! I also wondered why the crash message wanted me to open an issue here. I'll do so.
