### ISSUE TITLE
BUG: flow launcher error

### ISSUE THREAD

**Issue by vincentjegoj** [Flow-Launcher/Flow.Launcher#3098]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Flow Launcher version: 1.19.4
OS Version: 22631.4460
IntPtr Length: 8
x64: True

Python Path: C:\Users\Jego J\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 11/27/2024 17:38:45
Exception:
System.AggregateException: One or more errors occurred. (Not found.)
 ---> SpotifyAPI.Web.APIException: Not found.
   at SpotifyAPI.Web.Http.APIConnector.ProcessErrors(IResponse response)
   at SpotifyAPI.Web.Http.APIConnector.DoRequest(IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request)
   at SpotifyAPI.Web.Http.APIConnector.SendAPIRequestDetailed(Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers)
   at SpotifyAPI.Web.Http.APIConnector.Post(Uri uri, IDictionary`2 parameters, Object body)
   at SpotifyAPI.Web.PlayerClient.SkipNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPluginClient.Skip() in D:\a\Flow.Launcher.Plugin.SpotifyPremium\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPluginClient.cs:line 226
   at Flow.Launcher.Plugin.SpotifyPremium.SpotifyPlugin.<>c__DisplayClass40_0.<SingleResultInList>b__0(ActionContext _) in D:\a\Flow.Launcher.Plugin.SpotifyPremium\Flow.Launcher.Plugin.SpotifyPremium\SpotifyPlugin.cs:line 617
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.19.4

### Windows Build Number

22631.4460

### Error Log

[2024-11-27.txt](https://github.com/user-attachments/files/17932244/2024-11-27.txt)

**Comment by deefrawley** [comment]
Hi, this seems to be with the Spotify plugin. Can you please raise the issue there for the plugin author to investigate? Thanks,

https://github.com/fow5040/Flow.Launcher.Plugin.SpotifyPremium/issues
