### ISSUE TITLE
BUG: PowerToys Plugin

### ISSUE THREAD

**Issue by joespinoza** [Flow-Launcher/Flow.Launcher#3108]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

plugin crash

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

![Captura de pantalla 2024-12-03 210608](https://github.com/user-attachments/assets/d86a3371-6e38-4c3a-a800-ade49ae08c76)

### Flow Launcher Version

1.19.4

### Windows Build Number

27754.1000

### Error Log

Python Path: C:\Users\Joe Espinoza\AppData\Local\Programs\Python\Python312\pythonw.exe
Node Path: 
Date: 12/03/2024 21:02:04
Exception:
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Users\Joe Espinoza\AppData\Local\PowerToys\PowerToys.exe' with working directory 'C:\WINDOWS\system32'. El sistema no puede encontrar el archivo especificado.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Flow.Launcher.Plugin.PowerToys.OpenPowerToysSettingsAction.Execute()
   at Flow.Launcher.Plugin.PowerToys.PowerToys.<>c__DisplayClass4_0.<MapActionToResult>b__0(ActionContext _)
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2024-12-03.txt](https://github.com/user-attachments/files/18002835/2024-12-03.txt)

**Comment by deefrawley** [comment]
Hi, Could you please post this in the plugin repo so the author can investigate? Thanks.

https://github.com/PederBirk/Flow.Launcher.Plugin.PowerToys/issues
