### ISSUE TITLE
BUG: EXCEPTION OCCURS: System.ArgumentOutOfRangeException: Index was out of range.

### ISSUE THREAD

**Issue by kudlav** [Flow-Launcher/Flow.Launcher#3109]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

```
Flow Launcher version: 1.19.4
OS Version: 26100.2314
IntPtr Length: 8
x64: True

Python Path: C:\Users\Vladan\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 12/04/2024 23:19:13
Exception:
Záložky prohlížeče Exception: 
Websites: https://github.com/Flow-Launcher/Flow.Launcher
Author: qianlifeng, Ioannis G.
Version: 3.3.3
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Flow.Launcher.Plugin.BrowserBookmark.FirefoxBookmarkLoader.get_PlacesPath() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\FirefoxBookmarkLoader.cs:line 119
   at Flow.Launcher.Plugin.BrowserBookmark.FirefoxBookmarkLoader.GetBookmarks() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\FirefoxBookmarkLoader.cs:line 60
   at Flow.Launcher.Plugin.BrowserBookmark.Commands.BookmarkLoader.LoadAllBookmarks(Settings setting) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\Commands\BookmarkLoader.cs:line 35
   at Flow.Launcher.Plugin.BrowserBookmark.Main.LoadBookmarksIfEnabled() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\Main.cs:line 43
   at Flow.Launcher.Plugin.BrowserBookmark.Main.Query(Query query) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.BrowserBookmark\Main.cs:line 53
   at Flow.Launcher.Plugin.IPlugin.<>c__DisplayClass3_0.<Flow.Launcher.Plugin.IAsyncPlugin.QueryAsync>b__0() in /_/Flow.Launcher.Plugin/Interfaces/IPlugin.cs:line 35
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 248
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 247
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 276
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### Flow Launcher Version

1.19.4

### Windows Build Number

26100.2314

### Error Log

<details>

```

23:23:14.3679+01:00 - INFO  - App.OnStartup - Begin Flow Launcher startup ----------------------------------------------------
23:23:14.3700+01:00 - INFO  - App.OnStartup - Runtime info:
Flow Launcher version: 1.19.4
OS Version: 26100.2314
IntPtr Length: 8
x64: True
23:23:14.6328+01:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <URL> is <14ms>
23:23:14.6328+01:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Process Killer> is <2ms>
23:23:14.6328+01:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Plugin Indicator> is <3ms>
23:23:14.6328+01:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <System Commands> is <2ms>
23:23:14.6531+01:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://fastly.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
23:23:14.6531+01:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Web Searches> is <30ms>
23:23:14.6531+01:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Shell> is <33ms>
23:23:14.6775+01:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Windows Settings> is <45ms>
23:23:14.6775+01:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Calculator> is <52ms>
23:23:14.6775+01:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Preload programs cost <12ms>
23:23:14.6812+01:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Number of preload win32 programs <149>
23:23:14.6812+01:00 - INFO  - Flow.Launcher.Plugin.Program.Main - Number of preload uwps <30>
23:23:14.6812+01:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <VS Code Workspaces> is <53ms>
23:23:14.6998+01:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://gcore.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
23:23:14.6998+01:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://cdn.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
23:23:14.6998+01:00 - INFO  - CommunityPluginSource.FetchAsync - Loading plugins from https://raw.githubusercontent.com/Flow-Launcher/Flow.Launcher.PluginsManifest/plugin_api_v2/plugins.json
23:23:14.7153+01:00 - ERROR - PluginManager.InitializePluginsAsync - Fail to Init plugin: Browser Bookmarks
EXCEPTION OCCURS: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at T System.Collections.Generic.List<T>.get_Item(int index)
   at string Flow.Launcher.Plugin.BrowserBookmark.FirefoxBookmarkLoader.get_PlacesPath() in C:/projects/flow-launcher/Plugins/Flow.Launcher.Plugin.BrowserBookmark/FirefoxBookmarkLoader.cs:line 119
   at List<Bookmark> Flow.Launcher.Plugin.BrowserBookmark.FirefoxBookmarkLoader.GetBookmarks() in C:/projects/flow-launcher/Plugins/Flow.Launcher.Plugin.BrowserBookmark/FirefoxBookmarkLoader.cs:line 60
   at List<Bookmark> Flow.Launcher.Plugin.BrowserBookmark.Commands.BookmarkLoader.LoadAllBookmarks(Settings setting) in C:/projects/flow-launcher/Plugins/Flow.Launcher.Plugin.BrowserBookmark/Commands/BookmarkLoader.cs:line 35
   at void Flow.Launcher.Plugin.BrowserBookmark.Main.LoadBookmarksIfEnabled() in C:/projects/flow-launcher/Plugins/Flow.Launcher.Plugin.BrowserBookmark/Main.cs:line 43
   at void Flow.Launcher.Plugin.BrowserBookmark.Main.Init(PluginInitContext context) in C:/projects/flow-launcher/Plugins/Flow.Launcher.Plugin.BrowserBookmark/Main.cs:line 32
   at Task Flow.Launcher.Plugin.IPlugin.Flow.Launcher.Plugin.IAsyncPlugin.InitAsync(PluginInitContext context)+() => { } in /_/Flow.Launcher.Plugin/Interfaces/IPlugin.cs:line 33
   at async Task<long> Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(string message, Func<Task> action) in C:/projects/flow-launcher/Flow.Launcher.Infrastructure/Stopwatch.cs:line 34
   at async Task Flow.Launcher.Core.Plugin.PluginManager.InitializePluginsAsync(IPublicAPI api)+(?) => { } in C:/projects/flow-launcher/Flow.Launcher.Core/Plugin/PluginManager.cs:line 170

23:23:14.7153+01:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Program> is <92ms>
23:23:14.7153+01:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Explorer> is <92ms>
23:23:14.7438+01:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Emoji+> is <110ms>
23:23:14.7438+01:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <CurrencyPP> is <110ms>
23:23:14.7438+01:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Windows Terminal profiles> is <83ms>
23:23:14.8088+01:00 - INFO  - CommunityPluginSource.FetchAsync - Loaded 206 plugins from https://fastly.jsdelivr.net/gh/Flow-Launcher/Flow.Launcher.PluginsManifest@plugin_api_v2/plugins.json
23:23:14.8088+01:00 - INFO  - PluginManager.InitializePlugins - Total init cost for <Plugins Manager> is <184ms>


```
</details>

**Comment by kudlav** [comment]
Same in Flow Launcher 1.19.5

**Comment by kudlav** [comment]
I've found a workaround.

1. Turn off _Load Browser From_ `Firefox` checkbox
2. Add custom _Bookmark Data_
   - _Browser Engine_: _Firefox_
   - _Data Directory Path_: `C:\Users\USER\AppData\Roaming\Mozilla\Firefox\Profiles\MYPROFILE`

**Comment by Jack251970** [comment]
@kudlav @mwasowski It looks like the your profile files are different from standard FireFox browser. Could you please share your profile file in `C:\Users\{UserName}\AppData\Roaming\Mozilla\Firefox\profiles.ini`?

**Comment by mwasowski** [comment]
> AppData\Roaming\Mozilla\Firefox\profiles.ini

Crap, late answer but there you go
```ini
[Install308046B0AF4A39CB]
Default=Profiles/u37qsk18.default
Locked=1

[Profile0]
Name=default
IsRelative=1
Path=Profiles/u37qsk18.default
Default=1

[General]
StartWithLastProfile=1
Version=2

[Install4AF667F84F86C49E]
Default=Profiles/u37qsk18.default
Locked=1

[BackgroundTasksProfiles]
MozillaBackgroundTask-4AF667F84F86C49E-defaultagent=84x4q1wm.MozillaBackgroundTask-4AF667F84F86C49E-defaultagent
MozillaBackgroundTask-308046B0AF4A39CB-defaultagent=zh7c3px6.MozillaBackgroundTask-308046B0AF4A39CB-defaultagent


```

**Comment by Jack251970** [comment]
> > AppData\Roaming\Mozilla\Firefox\profiles.ini
> 
> Crap, late answer but there you go
> 
> [Install308046B0AF4A39CB]
> Default=Profiles/u37qsk18.default
> Locked=1
> 
> [Profile0]
> Name=default
> IsRelative=1
> Path=Profiles/u37qsk18.default
> Default=1
> 
> [General]
> StartWithLastProfile=1
> Version=2
> 
> [Install4AF667F84F86C49E]
> Default=Profiles/u37qsk18.default
> Locked=1
> 
> [BackgroundTasksProfiles]
> MozillaBackgroundTask-4AF667F84F86C49E-defaultagent=84x4q1wm.MozillaBackgroundTask-4AF667F84F86C49E-defaultagent
> MozillaBackgroundTask-308046B0AF4A39CB-defaultagent=zh7c3px6.MozillaBackgroundTask-308046B0AF4A39CB-defaultagent

This file looks good and I do not think it will trigger the issue above.

**Comment by mwasowski** [comment]
Can I help debug this somehow?

**Comment by Jack251970** [comment]
> Can I help debug this somehow?

Yeah, could you please check if our release version (1.19.5 or 1.20.0) can load Firefox bookmarks with `Firefox` checkbox. According to your profile file, I guess it can work (not sure) https://[github.com/Flow-Launcher/Flow.Launcher/releases](https://github.com/Flow-Launcher/Flow.Launcher/releases)

If it cannot work, could you please check if our pre-released version can do this thing? (https://github.com/Flow-Launcher/Prereleases)

Thanks!

**Comment by mwasowski** [comment]
> > Can I help debug this somehow?
> 
> Yeah, could you please check if our release version (1.19.5 or 1.20.0) can load Firefox bookmarks with `Firefox` checkbox. According to your profile file, I guess it can work (not sure) https://[github.com/Flow-Launcher/Flow.Launcher/releases](https://github.com/Flow-Launcher/Flow.Launcher/releases)
> 
> If it cannot work, could you please check if our pre-released version can do this thing? (https://github.com/Flow-Launcher/Prereleases)
> 
> Thanks!

I was on 1.19.5. Can confirm that updating to 1.20.0 fixed the issue for me. Removing the previous workaround with manual path to folder using `Other` type (that didn't actually work), upon hitting `b` I see my bookmarks after enabling Firefox and toggling the plugin on and off.

**Comment by Jack251970** [comment]
> > > Can I help debug this somehow?
> > 
> > 
> > Yeah, could you please check if our release version (1.19.5 or 1.20.0) can load Firefox bookmarks with `Firefox` checkbox. According to your profile file, I guess it can work (not sure) https://[github.com/Flow-Launcher/Flow.Launcher/releases](https://github.com/Flow-Launcher/Flow.Launcher/releases)
> > If it cannot work, could you please check if our pre-released version can do this thing? (https://github.com/Flow-Launcher/Prereleases)
> > Thanks!
> 
> I was on 1.19.5. Can confirm that updating to 1.20.0 fixed the issue for me. Removing the previous workaround with manual path to folder using `Other` type (that didn't actually work), upon hitting `b` I see my bookmarks after enabling Firefox and toggling the plugin on and off.

Good! Glad to help.

**Comment by kudlav** [comment]
Hi, I'm using v2.0.1, Flow Launcher is no longer crashing, but still requires setting the path manually to load bookmarks from Firefox.

`profiles.ini`:
```ini
[Install9DED23DF4360B491]
Default=Profiles/wrmpsrem.default-release
Locked=1

[Profile1]
Name=guest
IsRelative=1
Path=Profiles/60v2gtz1.guest

[Profile0]
Name=vladan
IsRelative=1
Path=Profiles/wrmpsrem.default-release
Default=1

[General]
StartWithLastProfile=1
Version=2

[BackgroundTasksProfiles]
MozillaBackgroundTask-9DED23DF4360B491-defaultagent=a5kn0gdx.MozillaBackgroundTask-9DED23DF4360B491-defaultagent
```

**Comment by Jack251970** [comment]
Thanks for your reply! I will take a look later

**Comment by Jack251970** [comment]
@kudlav Your profile file looks well. The final parsed database path is located at `C:\Users\{UserName}\AppData\Roaming\Mozilla\Firefox\Profiles/wrmpsrem.default-release\places.sqlite`.
