### ISSUE TITLE
BUG: Error after trying to close the app or download database for dictionary plugin

### ISSUE THREAD

**Issue by AghoyPandaaa** [Flow-Launcher/Flow.Launcher#3124]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

Flow Launcher version: 1.19.4
OS Version: 22631.4391
IntPtr Length: 8
x64: True

Python Path: C:\Users\AghoyPandaaa\AppData\Local\Programs\Python\Python312\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 12/13/2024 21:35:24
Exception:
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'StreamJsonRpc.JsonRpc'.
   at Microsoft.Verify.NotDisposed(IDisposableObservable disposedValue, String message)
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Flow.Launcher.Core.Plugin.JsonRPCPluginV2.DisposeAsync() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPluginV2.cs:line 146
   at Flow.Launcher.Core.Plugin.ProcessStreamPluginV2.DisposeAsync() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\ProcessStreamPluginV2.cs:line 85
   at Flow.Launcher.Core.Plugin.PluginManager.DisposePluginsAsync() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 78
   at Flow.Launcher.MainWindow.OnClosing(Object sender, CancelEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 174
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

Just trying to quit the app!

### Flow Launcher Version

1.19.4

### Windows Build Number

Microsoft Windows [Version 10.0.22631.4391]

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by jjw24** [comment]
Do you have pyrepl plugin installed by any chance?

**Comment by AghoyPandaaa** [comment]
No I have not.

**Comment by AghoyPandaaa** [comment]
No I don't have the plugin. And also when I want to quit the app , the given error happens.
But restarting and every other feature works correctly.

**Comment by Jack251970** [comment]
Already fixed in #3432. From 1.20.0 version, Flow will silently handle those exceptions
