### ISSUE TITLE
BUG: Unable to set path search keyword in explorer plugin

### ISSUE THREAD

**Issue by cibere** [Flow-Launcher/Flow.Launcher#3125]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

In the explorer plugin, I am trying to change the keyword and enable the path search option to see what it does, however I receive an error when doing so.

Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues
1. upload log file: C:\Users\default.MyPC\AppData\Roaming\FlowLauncher\Logs\1.19.4\2024-12-12.txt
2. copy below exception message

Flow Launcher version: 1.19.4
OS Version: 22631.4602
IntPtr Length: 8
x64: True

Python Path: C:\Users\default.MyPC\AppData\Local\Programs\Python\Python313\python.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 12/13/2024 10:03:31
Exception:
System.ArgumentException: Both false in actionKeyword.Enabled and actionKeywordWindow.KeywordEnabled should suggest that the ShowDialog() result is false
   at Flow.Launcher.Plugin.Explorer.ViewModels.SettingsViewModel.EditActionKeyword(Object obj) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\ViewModels\SettingsViewModel.cs:line 296
   at Flow.Launcher.Plugin.Explorer.ViewModels.RelayCommand.Execute(Object parameter) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\ViewModels\RelayCommand.cs:line 25
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

1. Open flow settings
2. Go to explorer settings
3. Go to the keyword actions tab
4. try and change the path search keyword

### Screenshots

<img width="452" alt="Flow Launcher_5Ued0Bieac" src="https://github.com/user-attachments/assets/0aebd7f0-0a49-4cc3-93f0-8fc71d2e7a33" />

### Flow Launcher Version

1.19.4

### Windows Build Number

Microsoft Windows [Version 10.0.22631.4602]

### Error Log

[2024-12-12.txt](https://github.com/user-attachments/files/18129829/2024-12-12.txt)

**Comment by cibere** [comment]
Haven't been able to replicate it since then
