### ISSUE TITLE
BUG: Setting File Unable to delete the file being replaced

### ISSUE THREAD

**Issue by ArtosMukk** [Flow-Launcher/Flow.Launcher#3130]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

I have not noticed any noticeable changes in the program's operation, except for these periodically pop-up messages that are starting to annoy me.

Flow Launcher version: 1.19.4
OS Version: 19045.2130
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 12/14/2024 19:55:24
Exception:
System.IO.IOException: Unable to delete the file being replaced.
   at System.IO.FileSystem.ReplaceFile(String sourceFullPath, String destFullPath, String destBackupFullPath, Boolean ignoreMetadataErrors)
   at Flow.Launcher.Infrastructure.Storage.JsonStorage`1.AtomicWriteSetting() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Storage\JsonStorage.cs:line 209
   at Flow.Launcher.Infrastructure.Storage.JsonStorage`1.Save() in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Storage\JsonStorage.cs:line 189
   at Flow.Launcher.ViewModel.SettingWindowViewModel.Save() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\SettingWindowViewModel.cs:line 40
   at Flow.Launcher.SettingWindow.OnClosed(Object sender, EventArgs e) in C:\projects\flow-launcher\Flow.Launcher\SettingWindow.xaml.cs:line 52
   at System.Windows.Window.WmDestroy()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### To Reproduce

1. ...
2. ...
3. ...

### Flow Launcher Version

1.19.4

### Windows Build Number

19045.2130

### Error Log

[2024-12-14.txt](https://github.com/user-attachments/files/18137090/2024-12-14.txt)

**Comment by z1nc0r3** [comment]
Please describe the pop-up messages that you're getting.

**Comment by ArtosMukk** [comment]
> Please describe the pop-up messages that you're getting.

Honestly speaking, I haven't received this error since the report. There was a message about a crash (although the program worked fine) and a request to create an issue here, a field from which it was suggested to copy the text that I pasted into the Problem Description and a txt file that was also suggested to be attached to the issue (Error Log - 2024-12-14.txt)

**Comment by Jack251970** [comment]
Look like Flow Launcher cannot delete temporary or backup file. Please check your setting file in 

`%AppData\Roaming\FlowLauncher\Settings\Plugins\Flow.Launcher.Plugin.Shell\Settings.json` &
`%AppData\Roaming\FlowLauncher\Settings\Plugins\Flow.Launcher.Plugin.Shell\Settings.json.bk` &
`%AppData\Roaming\FlowLauncher\Settings\Plugins\Flow.Launcher.Plugin.Shell\Settings.tmp`。

**Comment by Jack251970** [comment]
Fixed in #3668. 1.20.1 release
