### ISSUE TITLE
BUG: "Object reference not set to an instance of an object at ClipboardR.ClipboardR.Save()" on startup

### ISSUE THREAD

**Issue by AuroraStarstorm** [Flow-Launcher/Flow.Launcher#3137]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I am using the latest version of Flow Launcher.

### Problem Description

Unsure, flow launcher seems to function but appears at every startup and restart of flow launcher.

Flow Launcher version: 1.19.4
OS Version: 22631.4602
IntPtr Length: 8
x64: True

Python Path: C:\Users\kyleb\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 12/18/2024 17:34:22
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ClipboardR.ClipboardR.Save()
   at Flow.Launcher.Core.Plugin.PluginManager.Save() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 59
   at Flow.Launcher.PublicAPIInstance.SaveAppAllSettings() in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 84
   at Flow.Launcher.PublicAPIInstance.RestartApp() in C:\projects\flow-launcher\Flow.Launcher\PublicAPIInstance.cs:line 64
   at Flow.Launcher.Plugin.Sys.Main.<Commands>b__16_12(ActionContext c) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Sys\Main.cs:line 337
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Flow Launcher Version

1.19.4

### Windows Build Number

10.0.22631.4602

### Error Log

[2024-12-18.txt](https://github.com/user-attachments/files/18186853/2024-12-18.txt)

**Comment by Jack251970** [comment]
You can try [Clipboard+](https://github.com/Jack251970/Flow.Launcher.Plugin.ClipboardPlus) which is developed on the `ClipboardR`. (`ClipboardR` is no longer maintained)

**Comment by AuroraStarstorm** [comment]
Thanks
