### ISSUE TITLE
BUG: Python Exception

### ISSUE THREAD

**Issue by Vxrtrauter** [Flow-Launcher/Flow.Launcher#3147]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [ ] I am using the latest version of Flow Launcher.

### Problem Description

When -yt <youtube link> is being ran and video is being selected, it encounters an error

### To Reproduce

1. -yt <link>
2. Select mp4
3. .BOOM ERROR

### Flow Launcher Version

1.19.4

### Windows Build Number

Microsoft Windows [Version 10.0.26100.2605]

### Error Log

<details>

```shell

Flow Launcher version: 1.19.4
OS Version: 26100.2605
IntPtr Length: 8
x64: True

Python Path: C:\Users\shayaa\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 12/25/2024 14:36:24
Exception:
System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\shayaa\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\main.py", line 93, in <module>
    YoutubeDownload()
  File "C:\Users\shayaa\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\flowlauncher\FlowLauncher.py", line 33, in __init__
    results = request_method(*request_parameters)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shayaa\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\main.py", line 87, in download_video
    video = youtube.streams.get_highest_resolution()
            ^^^^^^^^^^^^^^^
  File "C:\Users\shayaa\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\shayaa\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
                                                ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shayaa\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\pytube\__main__.py", line 160, in streaming_data
    self.bypass_age_gate()
  File "C:\Users\shayaa\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\pytube\__main__.py", line 257, in bypass_age_gate
    innertube_response = innertube.player(self.video_id)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shayaa\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\pytube\innertube.py", line 448, in player
    return self._call_api(endpoint, query, self.base_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shayaa\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\pytube\innertube.py", line 390, in _call_api
    response = request._execute_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shayaa\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-0.1.2\lib\pytube\request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 634, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 643, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 243
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 248
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteResultAsync(JsonRPCResult result) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 117
   at Flow.Launcher.Core.Plugin.JsonRPCPluginBase.<>c__DisplayClass18_0.<<ParseResults>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPluginBase.cs:line 89
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)



```
</details>

**Comment by Lucas256-cmd** [comment]
This is a plugin related issue, you can place your issue in the repository of the plugin. Assuming you use FlowLauncherYTDownload, you can do that here https://github.com/DeepVoyager253/FlowLauncherYTDownload. But looked here myself and I think it is a known issue. Google probably implemented something new again to block downloaders. Apperently this plugin does work: AnyVideo Downloader.
