### ISSUE TITLE
BUG: "Everything" plugin not working

### ISSUE THREAD

**Issue by ThissMyUsernamE** [Flow-Launcher/Flow.Launcher#3148]
### Checks

- [ ] I have checked that this issue has not already been reported.

- [X] I am using the latest version of Flow Launcher.

### Problem Description

I have installed Everything 1.5a but flow launcher doesn't pick it up.

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

![image](https://github.com/user-attachments/assets/bed2444a-a7a1-4445-8278-8c7b23d00035)

### Flow Launcher Version

1.19.4

### Windows Build Number

22631.4602

### Error Log

Flow Launcher version: 1.19.4
OS Version: 22631.4602
IntPtr Length: 8
x64: True

Python Path: C:\Users\akotl\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 12/26/2024 11:19:13
Exception:
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Program Files\Everything 1.5a\Everything.exe' with working directory 'C:\Users\akotl\AppData\Local\FlowLauncher\app-1.19.4'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Flow.Launcher.Plugin.Explorer.Search.Everything.EverythingSearchManager.ClickToInstallEverythingAsync(ActionContext _) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\Everything\EverythingSearchManager.cs:line 55
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by deefrawley** [comment]
Flow doesn't play well with the 1.5 alpha of Everything. Follow this guide to get it working

https://github.com/Flow-Launcher/Flow.Launcher/issues/1716
