### ISSUE TITLE
Colors plugin installation error (Plugin Manager)

### ISSUE THREAD

**Issue by kubalav** [Flow-Launcher/Flow.Launcher#323]
I try to install Colors plugin via Plugin Manager. I use portable version Flow Launcher 1.7.0.
Log:
```
2021-02-03 09:02:58.9054|ERROR|PluginsManager.InstallOrUpdate|-------------------------- Begin exception --------------------------
2021-02-03 09:02:58.9054|ERROR|PluginsManager.InstallOrUpdate|An error occured while downloading plugin
2021-02-03 09:02:58.9054|ERROR|PluginsManager.InstallOrUpdate|Exception full name:
 <System.IO.IOException>
2021-02-03 09:02:58.9054|ERROR|PluginsManager.InstallOrUpdate|Exception message:
 <Source and destination path must have identical roots. Move will not work across volumes.>
2021-02-03 09:02:58.9173|ERROR|PluginsManager.InstallOrUpdate|Exception stack trace:
 <   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at Flow.Launcher.Plugin.PluginsManager.PluginsManager.Install(UserPlugin plugin, String downloadedFilePath) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.PluginsManager\PluginsManager.cs:line 349
   at Flow.Launcher.Plugin.PluginsManager.PluginsManager.InstallOrUpdate(UserPlugin plugin) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.PluginsManager\PluginsManager.cs:line 136>
2021-02-03 09:02:58.9173|ERROR|PluginsManager.InstallOrUpdate|Exception source:
 <System.IO.FileSystem>
2021-02-03 09:02:58.9173|ERROR|PluginsManager.InstallOrUpdate|Exception target site:
 <Void Move(System.String, System.String)>
2021-02-03 09:02:58.9173|ERROR|PluginsManager.InstallOrUpdate|Exception HResult:
 <-2146232800>
2021-02-03 09:02:58.9173|ERROR|PluginsManager.InstallOrUpdate|-------------------------- End exception --------------------------
```

**Comment by taooceros** [comment]
Is portable version of v1.7.0 working? Because seems that the installed version has some issue generated in the build process, which cause v1.7.0 load assembly fail a lot.

@jjw24 Would you please take a look on this issue, since I am not quite sure how the installation process work?

**Comment by kubalav** [comment]
I updated portable version from 1.6.0 to 1.7.0 and it works except Everything plugin (old version 1.2.0) I want to update it, but error occurred:
```
2021-02-03 09:23:07.8501|ERROR|PluginsManager.RequestUpdate|-------------------------- Begin exception --------------------------
2021-02-03 09:23:07.8501|ERROR|PluginsManager.RequestUpdate|Update failed for Everything
2021-02-03 09:23:07.8501|ERROR|PluginsManager.RequestUpdate|Exception full name:
 <System.IO.IOException>
2021-02-03 09:23:07.8527|ERROR|PluginsManager.RequestUpdate|Exception message:
 <Source and destination path must have identical roots. Move will not work across volumes.>
2021-02-03 09:23:07.8527|ERROR|PluginsManager.RequestUpdate|Exception stack trace:
 <   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at Flow.Launcher.Plugin.PluginsManager.PluginsManager.Install(UserPlugin plugin, String downloadedFilePath) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.PluginsManager\PluginsManager.cs:line 349
   at Flow.Launcher.Plugin.PluginsManager.PluginsManager.<>c__DisplayClass18_1.<<RequestUpdate>b__7>d.MoveNext() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.PluginsManager\PluginsManager.cs:line 233>
2021-02-03 09:23:07.8527|ERROR|PluginsManager.RequestUpdate|Exception source:
 <System.IO.FileSystem>
2021-02-03 09:23:07.8527|ERROR|PluginsManager.RequestUpdate|Exception target site:
 <Void Move(System.String, System.String)>
2021-02-03 09:23:07.8527|ERROR|PluginsManager.RequestUpdate|Exception HResult:
 <-2146232800>
2021-02-03 09:23:07.8527|ERROR|PluginsManager.RequestUpdate|-------------------------- End exception --------------------------
```

**Comment by taooceros** [comment]
I think it is the same issue.

**Comment by jjw24** [comment]
> Is portable version of v1.7.0 working? Because seems that the installed version has some issue generated in the build process, which cause v1.7.0 load assembly fail a lot.
> 
> @jjw24 Would you please take a look on this issue, since I am not quite sure how the installation process work?

this 1.7.0 build is from CI, let me check.

**Comment by jjw24** [comment]
i think the issue is the Move method used by PluginsManager. @kubalav are you using the portable on a different drive?

**Comment by jjw24** [comment]
@kubalav could you try this build and see if the problem is resolved please:
https://ci.appveyor.com/api/buildjobs/lpligmo5l7ibv1r7/artifacts/Output%2FPackages%2FFlow-Launcher-v1.7.0.exe

**Comment by kubalav** [comment]
@jjw24 It working! Thank you.
