### ISSUE TITLE
didn't work

### ISSUE THREAD

**Issue by WallBreakerNO4** [Flow-Launcher/Flow.Launcher#354]
Flow Launcher version: 1.7.1
OS Version: Microsoft Windows NT 10.0.19041.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 02/20/2021 20:20:14
Exception:
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Flow.Launcher.Infrastructure.Http.Http.UpdateProxy(ProxyProperty property) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Http\Http.cs:line 61
   at Flow.Launcher.Infrastructure.Http.Http.set_Proxy(HttpProxy value) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Http\Http.cs:line 43
   at Flow.Launcher.App.<OnStartupAsync>b__14_0() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 66
   at Flow.Launcher.Infrastructure.Stopwatch.NormalAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 59
   at Flow.Launcher.App.OnStartupAsync(Object sender, StartupEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 50
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2021-02-20.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/6014920/2021-02-20.txt)

**Comment by taooceros** [comment]
Seems that the error comes from proxy phrase. Are you using the http proxy?

**Comment by taooceros** [comment]
By the way, just personal curious, are you guo zhifan🤔?

**Comment by WallBreakerNO4** [comment]
> 似乎错误来自代理词组。您正在使用http代理吗？

yes, I'm using Clash

**Comment by WallBreakerNO4** [comment]
> 对了，只是个人好奇，你是郭志范🤔？

how did you know that?

**Comment by taooceros** [comment]
> > 对了，只是个人好奇，你是郭志范🤔？
> 
> how did you know that?

We are on the same high school before. 🧐🤯

**Comment by taooceros** [comment]
> > 似乎错误来自代理词组。您正在使用http代理吗？
> 
> yes, I'm using Clash

Would you please share me with your proxy setting of Flow?

**Comment by WallBreakerNO4** [comment]
> > > Seems that the error comes from proxy phrase. Are you using the http proxy?
> > 
> > 
> > yes, I'm using Clash
> 
> Would you please share me with your proxy setting of Flow?

I just install it, I didn't change any setting

**Comment by taooceros** [comment]
OK, I have taken a look, and the crash isn't from the parse of proxy, but another error. Will take a look soon.

2021-02-20 20:19:20.8584|FATAL|UnHandledException| ## Exception ``` System.NullReferenceException: Object reference not set to an instance of an object. Source: Flow.Launcher TargetAssembly: Flow.Launcher, Version=1.7.1.0, Culture=neutral, PublicKeyToken=null TargetModule: Flow.Launcher.dll TargetSite: Void Dispose() at Flow.Launcher.App.Dispose() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 167 at Flow.Launcher.App.Main() in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 44 ```

**Comment by taooceros** [comment]
@WallBreakerNO4 try this build https://ci.appveyor.com/api/buildjobs/q54n016vqjox5b7s/artifacts/Output%2FPackages%2FFlow-Launcher-v1.7.1.exe

**Comment by taooceros** [comment]
This seems a crucial bug for new users, so if it works for you @WallBreakerNO4, we will soon create a small release for the bug fix.

**Comment by WallBreakerNO4** [comment]
> > > 对了，只是个人好奇，你是郭志范🤔？
> > 
> > 
> > how did you know that?
> 
> We are on the same high school before. 🧐🤯

By the way, you mean watch high school, I don't remember you

**Comment by taooceros** [comment]
> By the way, you mean watch high school, I don't remember you

Vanke Meisha Academy
