### ISSUE TITLE
Application crash from time to time

### ISSUE THREAD

**Issue by solymr** [Flow-Launcher/Flow.Launcher#357]
**Describe the bug/issue**
Flow launcher just crash from time to time on my windows.
Seems the crash happens randomly. for example, sometimes I left my computer for launch, and when I came back and continue using it, sometimes I just found the hotkey to activate it did not work. And then I checked the tray icon, just to see it was not here. There was no error notification.
Reopen the app can fix it temporarily, but the crash will happen again later.
I found something in my event viewer. Pasted it below, hope it helps.
It happens at current version (1.7.1), but one or two versions before it has the same bug.

**Screenshots**

**Your System**
Windows build number:  10.0.19042.804
Flow Launcher version: 1.7.1

**Flow Launcher Error Log**
[2021-02-21.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/6017339/2021-02-21.txt)

**Windows Event Viewer Log #1**
Application: Flow.Launcher.exe
CoreCLR Version: 4.700.20.56602
.NET Core Version: 3.1.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Flow.Launcher.Infrastructure.Http.Http.GetStreamAsync(String url, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Http\Http.cs:line 138
   at Flow.Launcher.Core.Updater.GitHubUpdateManager(String repository) in C:\projects\flow-launcher\Flow.Launcher.Core\Updater.cs:line 118
   at Flow.Launcher.Core.Updater.UpdateApp(IPublicAPI api, Boolean silentUpdate) in C:\projects\flow-launcher\Flow.Launcher.Core\Updater.cs:line 41
   at Flow.Launcher.App.<AutoUpdates>b__16_1(Object s, ElapsedEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\App.xaml.cs:line 125
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Windows Event Viewer Log #2**
错误应用程序名称: Flow.Launcher.exe，版本: 1.7.1.0，时间戳: 0x5fb3100b
错误模块名称: KERNELBASE.dll，版本: 10.0.19041.804，时间戳: 0x0e9c5eae
异常代码: 0xe0434352
错误偏移量: 0x000000000002d759
错误进程 ID: 0xb18
错误应用程序启动时间: 0x01d707f32d8e043f
错误应用程序路径: C:\Users\solymr\AppData\Local\FlowLauncher\app-1.7.1\Flow.Launcher.exe
错误模块路径: C:\WINDOWS\System32\KERNELBASE.dll
报告 ID: 9dbd95d2-4b4c-486e-b7cc-18e1971c7eb5
错误程序包全名: 
错误程序包相对应用程序 ID:

**Comment by taooceros** [comment]
Will take a look now. It seems a bug of we don't cover taskcancelledexception in auto update checking. Therefore, if the update check timeout, the error will be uncaught. However, why should that crash the program?

**Comment by taooceros** [comment]
@solymr try this build https://ci.appveyor.com/api/buildjobs/c2cdwvfraojyfq7p/artifacts/Output%2FPackages%2FFlow-Launcher-v1.7.1.exe

**Comment by solymr** [comment]
> @solymr try this build https://ci.appveyor.com/api/buildjobs/c2cdwvfraojyfq7p/artifacts/Output%2FPackages%2FFlow-Launcher-v1.7.1.exe

Tried yesterday，but it crashed again at night.
I turned off auto update today, just to see if it will crash again.

**Comment by taooceros** [comment]
> > @solymr try this build https://ci.appveyor.com/api/buildjobs/c2cdwvfraojyfq7p/artifacts/Output%2FPackages%2FFlow-Launcher-v1.7.1.exe
> 
> Tried yesterday，but it crashed again at night.
> I turned off auto update today, just to see if it will crash again.

Thank you, I will reopen it.

**Comment by taooceros** [comment]
@solymr try this one https://ci.appveyor.com/api/buildjobs/a3casa1a6x3xac3b/artifacts/Output%2FPackages%2FFlow-Launcher-v1.7.2.exe
My bad, I use the wrong exception handling

**Comment by solymr** [comment]
> @solymr try this one https://ci.appveyor.com/api/buildjobs/a3casa1a6x3xac3b/artifacts/Output%2FPackages%2FFlow-Launcher-v1.7.2.exe
> My bad, I use the wrong exception handling

Thank you! For now v1.7.2 has fixed this problem for me.
