### ISSUE TITLE
Search Crashing due to Windows Index Search service not running

### ISSUE THREAD

**Issue by mragtronx8** [Flow-Launcher/Flow.Launcher#581]
i upgraded to v 1.8.
when i start to search for a file; flow is immediately crashing and giving an error.

Please advise.

**Comment by jjw24** [comment]
Can you attach the log please, located at %APPDATA%\FlowLauncher\Logs

**Comment by taooceros** [comment]
We have changed some error reporting strategy in 1.8.0. Poping an error doesn't mean Flow crash.

**Comment by wangtaicheng** [comment]
@jjw24 `
Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues/new
1. upload log file: C:\Users\Administrator\AppData\Roaming\FlowLauncher\Logs\1.8.0\2021-07-21.txt
2. copy below exception message

Flow Launcher version: 1.8.0
OS Version: Microsoft Windows NT 10.0.17763.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 07/21/2021 07:58:50
Exception:
System.Runtime.InteropServices.COMException (0x80070422): Retrieving the COM class factory for component with CLSID {7D096C5F-AC08-4F1F-BEB7-5C22C517CE39} failed due to the following error: 80070422 无法启动服务，原因可能是已被禁用或与其相关联的设备没有启动。 (0x80070422).
   at Flow.Launcher.Plugin.Explorer.Search.WindowsIndex.QueryConstructor.CreateQueryHelper() in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\WindowsIndex\QueryConstructor.cs:line 38
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.WindowsIndexFilesAndFoldersSearchAsync(Query query, String querySearchString, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 181
   at Flow.Launcher.Plugin.Explorer.Search.SearchManager.SearchAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Search\SearchManager.cs:line 61
   at Flow.Launcher.Plugin.Explorer.Main.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Main.cs:line 61
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass111_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 555
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 529
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

`

**Comment by jjw24** [comment]
@wangtaicheng this issue should be caused by the Windows Indexing turned off. When turned on it should be (search `indexing options`): 
![image](https://user-images.githubusercontent.com/26427004/126419794-7e945861-c1de-4c43-a2df-1cea1c094938.png)

if it's turned off, can you turn it back on?

**Comment by mragtronx8** [comment]
am only using Everything indexer.
I disabled windows indexer due to problems with it.

Is there a way to re-route to Everything Indexer.

**Comment by jjw24** [comment]
@mragtronx8 you can disable Explorer plugin, that will re-route to Everything so to speak

**Comment by mragtronx8** [comment]
Solved

**Comment by jjw24** [comment]
Working on a fix
