### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by WatchTheory** [Flow-Launcher/Flow.Launcher#645]
Error message came up. 

Flow Launcher version: 1.8.2
OS Version: Microsoft Windows NT 10.0.19043.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 08/11/2021 16:54:35
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Plugin.WindowWalker.Main.Dispose(Boolean disposing) in D:\a\Microsoft.Plugin.WindowWalker\Microsoft.Plugin.WindowWalker\Main.cs:line 177
   at Microsoft.Plugin.WindowWalker.Main.Dispose() in D:\a\Microsoft.Plugin.WindowWalker\Microsoft.Plugin.WindowWalker\Main.cs:line 194
   at Flow.Launcher.Core.Plugin.PluginManager.DisposePluginsAsync() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 68
   at Flow.Launcher.MainWindow.OnClosing(Object sender, CancelEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\MainWindow.xaml.cs:line 55
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
Hey how's it going, this is coming from WindowWalker, can you check what version of it you are using? There is a new update out v2.0.1.

**Comment by WatchTheory** [comment]
I had no idea, I am usually checking for update twice a week. Thanks for letting me knw.

**Comment by jjw24** [comment]
no it's absolutely fine, if you have an issue do let us know so we can fix, because it's going to happen to someone else as well. There is no expectation for our users to be able to read logs, and if you are not sure which plugin that is causing this, it's all good to just throw it here.

**Comment by WatchTheory** [comment]
I will keep my eye out for anyone more of those message. Much appreciated @jjw24
