### ISSUE TITLE
Exception: System.ArgumentException: Unexpected null value

### ISSUE THREAD

**Issue by dcavacec** [Flow-Launcher/Flow.Launcher#669]
[2021-08-28.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/7070849/2021-08-28.txt)

Flow Launcher version: 1.8.2
OS Version: Microsoft Windows NT 10.0.19042.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 08/28/2021 09:37:05
Exception:
System.ArgumentException: Unexpected null value
   at Flow.Launcher.Plugin.Explorer.Views.ActionKeywordView.set_Enabled(Nullable`1 value) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Views\ExplorerSettings.xaml.cs:line 341
   at Flow.Launcher.Plugin.Explorer.Views.ActionKeywordSetting.OnDoneButtonClick(Object sender, RoutedEventArgs e) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.Explorer\Views\ActionKeywordSetting.xaml.cs:line 82
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by taooceros** [comment]
Could you explain how you reproduce it?
Does it happens when you don't enter anything in the action keyword setting window for explorer plugin?

**Comment by dcavacec** [comment]
Attempting to change the keyword for File Content Search, regardless of the value I input. 

![flowLauncherUpdateExplorerFileKeyword](https://user-images.githubusercontent.com/69704029/131222922-01a0f8ec-e6ee-49a3-b776-c2ef0ce762c2.PNG)
![flowLauncherUpdateExplorerFileKeyword_Error](https://user-images.githubusercontent.com/69704029/131222926-57c59f55-bfb9-4abc-9dd6-5396a7c7a26f.PNG)

**Comment by taooceros** [comment]
So every value will trigger the exception?

**Comment by taooceros** [comment]
I see the problem, but not sure what cause that. It is because the enable checkbox is unable to display, so causing a null exception.

@jjw24 would you like to take a look on this? I am currently quite busy.

**Comment by taooceros** [comment]
Ok it's a serious bug because the `File Content Search` doesn't contain option to enable or disable, so the NPE is reproducible regardless which actionkeyword is going to be changed.

**Comment by jjw24** [comment]
> I see the problem, but not sure what cause that. It is because the enable checkbox is unable to display, so causing a null exception.
> 
> @jjw24 would you like to take a look on this? I am currently quite busy.

sorry for the late reply. I will look into this if you havent started yet @taooceros
