### ISSUE TITLE
Invalid Data Exception on every python plugin

### ISSUE THREAD

**Issue by CoreParadox** [Flow-Launcher/Flow.Launcher#677]
Flow Launcher version: 1.8.2
OS Version: Microsoft Windows NT 10.0.19043.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 09/04/2021 11:27:25
Exception:
System.IO.InvalidDataException: Steam Search|Traceback (most recent call last):
  File "C:\Users\Core\AppData\Roaming\FlowLauncher\Plugins\Steam Search-1.0.11\main.py", line 12, in <module>
    SteamSearch()
  File "C:\Users\Core\AppData\Roaming\FlowLauncher\Plugins\Steam Search-1.0.11\plugin\steam_search.py", line 20, in __init__
    self._steam_folder = Noneeam
NameError: name 'Noneeam' is not defined

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 275
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 286
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass111_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 563
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 564
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by taooceros** [comment]
@Garulf

**Comment by taooceros** [comment]
Would you please provide more info?

What you have typed? What you are trying to do? Etc.

**Comment by Garulf** [comment]
Seems the environmental variable I'm using to determine Window's system drive is not set.

**Comment by CoreParadox** [comment]
> Seems the environmental variable I'm using to determine Window's system drive is not set.
> 
> Not sure where "Noneeam" is coming from. Which version of Python are you using?

I've tried 2.7 and 3.9, currently I'm using whatever version is embedded.

**Comment by CoreParadox** [comment]
> Would you please provide more info?
> 
> What you have typed? What you are trying to do? Etc.

Simply invoking several python plugins results in error (st, e, roll) before even providing each with params.

here's two additional stacks

```
Flow Launcher version: 1.8.2
OS Version: Microsoft Windows NT 10.0.19043.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 09/04/2021 17:18:43
Exception:
System.IO.InvalidDataException: RollDice|Traceback (most recent call last):
  File "C:\Users\Clock\AppData\Roaming\FlowLauncher\Plugins\RollDice-1.0\main.py", line 4, in <module>
    from plugin import RollDice
ModuleNotFoundError: No module named 'plugin'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 275
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 286
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass111_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 553
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 527
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

```
Python Path: 
Date: 09/04/2021 17:19:02
Exception:
System.IO.InvalidDataException: Fancy Emoji|Traceback (most recent call last):
  File "C:\Users\Clock\AppData\Roaming\FlowLauncher\Plugins\Fancy Emoji-1.0.1\plugin.py", line 5, in <module>
    from flowlauncher import FlowLauncher
ModuleNotFoundError: No module named 'flowlauncher'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 275
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 286
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass111_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 553
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 527
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Garulf** [comment]
Flow's embedded Python is fairly new and some plugins have not been updated to handle its "quirks". I know `fanchyemoji` has not been updated to work properly. 

Steam-Search has been written to use embbeded python and user installed python. But does require version 3.5 or higher.

**Comment by CoreParadox** [comment]
> Flow's embedded Python is fairly new and some plugins have not been updated to handle its "quirks". I know `fanchyemoji` has not been updated to work properly and the error from the other plugin looks like it has not been updated as well.
> 
> Steam-Search has been written to use embbeded python and user installed python. But does require version 3.5 or higher (embedded python is 3.8 iirc).
> 
> EDIT: If you'd like I added fallback fix for your first error message in Steam-Search [here](https://github.com/Garulf/Steam-Search/releases).

I guess I could just be picking a bunch of plugins that just are randomly broken, but steam-search still crashes, along with others on python 3.9 installed at C:/python39
![image](https://user-images.githubusercontent.com/6187665/132145190-d6f99a4f-ab04-46e7-b541-6dcc7b955e5b.png)
![Flow Launcher_2021-09-05_19-05-58](https://user-images.githubusercontent.com/6187665/132145200-7134df25-0ef4-4c0d-ba53-1a6abfdee38d.jpg)

```
Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues/new
1. upload log file: C:\Users\Clock\AppData\Roaming\FlowLauncher\Logs\1.8.3\2021-09-05.txt
2. copy below exception message

Flow Launcher version: 1.8.3
OS Version: Microsoft Windows NT 10.0.19043.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 09/05/2021 19:04:09
Exception:
System.IO.InvalidDataException: Steam Search|Traceback (most recent call last):
  File "C:\Users\Clock\AppData\Roaming\FlowLauncher\Plugins\Steam Search-1.1.0\main.py", line 12, in <module>
    SteamSearch()
  File "C:\Users\Clock\AppData\Roaming\FlowLauncher\Plugins\Steam Search-1.1.0\plugin\steam_search.py", line 28, in __init__
    super().__init__()
  File "C:\Users\Clock\AppData\Roaming\FlowLauncher\Plugins\Steam Search-1.1.0\lib\flox\flox.py", line 82, in __init__
    super().__init__()
  File "C:\Users\Clock\AppData\Roaming\FlowLauncher\Plugins\Steam Search-1.1.0\lib\flox\launcher.py", line 28, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\Clock\AppData\Roaming\FlowLauncher\Plugins\Steam Search-1.1.0\lib\flox\flox.py", line 89, in _query
    self.query(query)
  File "C:\Users\Clock\AppData\Roaming\FlowLauncher\Plugins\Steam Search-1.1.0\plugin\steam_search.py", line 122, in query
    self.load_games()
  File "C:\Users\Clock\AppData\Roaming\FlowLauncher\Plugins\Steam Search-1.1.0\plugin\steam_search.py", line 69, in load_games
    self.add_manifest(manifest, path)
  File "C:\Users\Clock\AppData\Roaming\FlowLauncher\Plugins\Steam Search-1.1.0\plugin\steam_search.py", line 85, in add_manifest
    manifest = vdf.load(open(file))
  File "C:\Users\Clock\AppData\Roaming\FlowLauncher\Plugins\Steam Search-1.1.0\lib\vdf\__init__.py", line 211, in load
    return parse(fp, **kwargs)
  File "C:\Users\Clock\AppData\Roaming\FlowLauncher\Plugins\Steam Search-1.1.0\lib\vdf\__init__.py", line 97, in parse
    for lineno, line in enumerate(fp, 1):
  File "C:\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 157: character maps to <undefined>

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 275
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 286
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass111_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 553
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 527
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Garulf** [comment]
@CoreParadox Thanks for bringing this error to my attention!
[Pre-release v1.1.2](https://github.com/Garulf/Steam-Search/releases/tag/v1.1.2) should fix your problem, please give it a try. 

Also, I added a log for any files that cause this issue (The log file is named "Steam-Search.log and is located in the plugins folder). If you're up to it please post an issue with the contents of the "troublesome" files so I can take a look at what's causing these errors [here](https://github.com/Garulf/Steam-Search/issues).

If you have any other issues with Steam-Search I can help you better there.

**Comment by Ma-ve** [comment]
> @CoreParadox

> > Would you please provide more info?
> > What you have typed? What you are trying to do? Etc.
> 
> Simply invoking several python plugins results in error (st, e, roll) before even providing each with params.
> 
> here's two additional stacks
> ...
> ```
> Python Path: 
> Date: 09/04/2021 17:19:02
> Exception:
> System.IO.InvalidDataException: Fancy Emoji|Traceback (most recent call last):
>   File "C:\Users\Clock\AppData\Roaming\FlowLauncher\Plugins\Fancy Emoji-1.0.1\plugin.py", line 5, in <module>
>     from flowlauncher import FlowLauncher
> ModuleNotFoundError: No module named 'flowlauncher'
> 
>    at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
>    at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 275
>    at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 286
>    at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
> --- End of stack trace from previous location ---
>    at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
>    at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
>    at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass111_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 553
> --- End of stack trace from previous location ---
>    at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 527
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> ```

Hey! Just came across this thread: I've update FancyEmoji to support the embedded Python, as of version 1.0.6 😎
