### ISSUE TITLE
 Error when activate translate plugin Direct Traslate 

### ISSUE THREAD

**Issue by 7yang7** [Flow-Launcher/Flow.Launcher#696]
Flow Launcher version: 1.8.3
OS Version: Microsoft Windows NT 10.0.19042.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 09/22/2021 21:43:24
Exception:
System.IO.InvalidDataException: Direct Translate|Traceback (most recent call last):
  File "C:\Users\Yang\AppData\Roaming\FlowLauncher\Plugins\Direct Translate-1.0.0\main.py", line 2, in <module>
    from textblob import TextBlob, exceptions
ModuleNotFoundError: No module named 'textblob'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 275
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 286
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass111_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 563
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 527
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Zeroto521** [comment]
> File "C:\Users\Yang\AppData\Roaming\FlowLauncher\Plugins\Direct Translate-1.0.0\main.py", line 2, in
> from textblob import TextBlob, exceptions
> ModuleNotFoundError: No module named 'textblob'

Could you please check your python environment has `textblob` or not?

**Comment by 7yang7** [comment]
I just install flow.launcher and that's it ? Do you need to install python additionally?

**Comment by Zeroto521** [comment]
Please follow here https://github.com/Drimix20/Flow.Launcher.Plugin.DirectTranslate#installation

![image](https://user-images.githubusercontent.com/25895405/134447941-bd57b40e-00a8-42ff-9e84-35636a31673e.png)

**Comment by taooceros** [comment]
I think currently flow will download embedded python, which don't include pip.

**Comment by 7yang7** [comment]
Offers only search in Google
![image](https://user-images.githubusercontent.com/71559582/134448485-793533f1-7e23-4c0e-be4d-4befe45ae886.png)

**Comment by taooceros** [comment]
I would consider the direct translate plugin doesn't update to the new embedded python installed by Flow. This is the current workaround for this. Install python separately and install the required lib for python with command line `pip install *`. And then set the python path in Flow to the python path you installed, and restart Flow.
https://github.com/Drimix20/Flow.Launcher.Plugin.DirectTranslate/issues/1

**Comment by taooceros** [comment]
Hi, sorry for the late response. For that, I think you may need to raise an issue in the plugin repo to tell the owner about that. The owner maybe doesn't notice that flow is changing to use the portable python, which requires manually add module path.

**Comment by taooceros** [comment]
https://github.com/Drimix20/Flow.Launcher.Plugin.DirectTranslate
I think it would be better for you to raise the issue instead of me🧐
