### ISSUE TITLE
results not refreshing if keyword is the same as last time

### ISSUE THREAD

**Issue by liberize** [Flow-Launcher/Flow.Launcher#701]
I set `ctrl+shift+c` to trigger `cb` keyword, which shows clipboard history.
When i press the hotkey, the window shows, but the results are not updated, I have to press an extra space to see current clipboard history.

**To Reproduce**
1. install clipboard history plugin, and assign a hotkey to trigger it.
2. press the hotkey, see current history.
3. copy some text.
4. press the hotkey again, the text just copied not show until input changes.

**Screenshots**

**Your System**
Windows 10

**Flow Launcher Error Log**

**Comment by jjw24** [comment]
Hi @liberize, this fix will be going out with the 1.9.0 release, you can try the build out now [here](https://github.com/Flow-Launcher/Flow.Launcher/discussions/640)

**Comment by liberize** [comment]
@jjw24 The clipboard history plugin crashs every time it got triggered after I updated to the portable build.

```
Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues/new
1. upload log file: C:\Users\libo\AppData\Roaming\FlowLauncher\Logs\1.8.3\2021-09-27.txt
2. copy below exception message

Flow Launcher version: 1.8.3
OS Version: Microsoft Windows NT 10.0.19043.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 09/27/2021 13:56:01
Exception:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at System.Runtime.CompilerServices.RuntimeHelpers.GetSubArray[T](T[] array, Range range)
   at Flow.Launcher.Plugin.Query.get_SecondToEndSearch() in /_/Flow.Launcher.Plugin/Query.cs:line 84
   at Flow.Launcher.Plugin.ClipboardHistory.ClipboardHistory.<>c__DisplayClass3_0.<Query>b__0(String i)
   at System.Linq.Enumerable.WhereListIterator`1.ToList()
   at Flow.Launcher.Plugin.ClipboardHistory.ClipboardHistory.Query(Query query)
   at Flow.Launcher.Plugin.IPlugin.<>c__DisplayClass3_0.<Flow.Launcher.Plugin.IAsyncPlugin.QueryAsync>b__0() in /_/Flow.Launcher.Plugin/Interfaces/IPlugin.cs:line 35
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass111_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 561
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 535
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by liberize** [comment]
Btw, I disabled portable mode.

**Comment by jjw24** [comment]
Hi @liberize please re-download from the link again. it's caused by #681, and i removed it from the build.
