### ISSUE TITLE
When use LibreTranslate, It crashed. I don't know how to fix it 

### ISSUE THREAD

**Issue by fhwid** [Flow-Launcher/Flow.Launcher#723]
Flow Launcher version: 1.8.3
OS Version: Microsoft Windows NT 10.0.19042.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 10/04/2021 20:38:18
Exception:
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at Flow.Launcher.Plugin.LibreTranslate.LibreTranslate.QueryAsync(Query query, CancellationToken token) in D:\Document\Dotnet\Flow.LibreTranslate\Flow.LibreTranslate\Main.cs:line 89
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass111_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 571
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 572
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2021-10-04.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/7278036/2021-10-04.txt)

**Comment by taooceros** [comment]
Probably their api has changed. Let me take a look today.

**Comment by taooceros** [comment]
They have limited the api usage. Though, some mirror has been established, and I will switch to them later.

**Comment by taooceros** [comment]
[Flow.LibreTranslate.zip](https://github.com/Flow-Launcher/Flow.Launcher/files/7279345/Flow.LibreTranslate.zip)
I build a simple change and you can use it for now. Will update it in the future.

**Comment by fanhwid** [comment]
> [Flow.LibreTranslate.zip](https://github.com/Flow-Launcher/Flow.Launcher/files/7279345/Flow.LibreTranslate.zip) I build a simple change and you can use it for now. Will update it in the future.

It's OK now, Thank you very much!

**Comment by taooceros** [comment]
[Debug.zip](https://github.com/Flow-Launcher/Flow.Launcher/files/7304943/Debug.zip)
I update to another mirror
