### ISSUE TITLE
When checking for update, an error occurs

### ISSUE THREAD

**Issue by fhwid** [Flow-Launcher/Flow.Launcher#739]
Flow Launcher version: 1.8.3
OS Version: Microsoft Windows NT 10.0.19042.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 10/07/2021 22:48:31
Exception:
System.Exception: Couldn't acquire lock, is another instance running
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
   at Squirrel.UpdateManager.<acquireUpdateLock>b__32_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Squirrel.UpdateManager.CheckForUpdate(Boolean ignoreDeltaUpdates, Action`1 progress)
   at Flow.Launcher.Core.Updater.UpdateApp(IPublicAPI api, Boolean silentUpdate) in C:\projects\flow-launcher\Flow.Launcher.Core\Updater.cs:line 45
   at Flow.Launcher.ViewModel.SettingWindowViewModel.UpdateApp() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\SettingWindowViewModel.cs:line 49
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2021-10-07.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/7304696/2021-10-07.txt)

**Comment by taooceros** [comment]
> Same error，it happens everytime:
> 
> ```
> Flow Launcher version: 1.8.3
> OS Version: Microsoft Windows NT 10.0.19042.0
> IntPtr Length: 8
> x64: True
> 
> Python Path: 
> Date: 10/08/2021 14:28:02
> Exception:
> System.Text.Json.JsonException: The JSON value could not be converted to System.Collections.Generic.List`1[Flow.Launcher.Core.Updater+GithubRelease]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
>    at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
>    at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
>    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
>    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
>    at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
>    at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
>    at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
>    at Flow.Launcher.Core.Updater.GitHubUpdateManager(String repository) in C:\projects\flow-launcher\Flow.Launcher.Core\Updater.cs:line 120
>    at Flow.Launcher.Core.Updater.UpdateApp(IPublicAPI api, Boolean silentUpdate) in C:\projects\flow-launcher\Flow.Launcher.Core\Updater.cs:line 41
>    at Flow.Launcher.ViewModel.SettingWindowViewModel.UpdateApp() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\SettingWindowViewModel.cs:line 49
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> ```

I think this error may occur because you are in China😂 so unable to fetch the actual json value. We are considering moving some direct link to github to cdn, but haven't completed.

**Comment by jjw24** [comment]
> We are considering moving some direct link to github to cdn, but haven't completed.

@taooceros it's done/fixed in the dev branch right?
