### ISSUE TITLE
Flow Launcher errors out every couple of minutes

### ISSUE THREAD

**Issue by johnathanz** [Flow-Launcher/Flow.Launcher#771]
**Describe the bug/issue**
Flow Launcher works, but pop ups an error every couple of minutes

**To Reproduce**
Error is random and I can't reproduce on command. It comes up every couple of minutes. I've attached text in error window and Flow Launcher error log below.

**Screenshots**
![image](https://user-images.githubusercontent.com/1593039/138643076-e2226061-d541-4c30-a497-c51d5f7f5433.png)

**Your System**
```

Flow Launcher version: 1.8.3
OS Version: Microsoft Windows NT 10.0.19043.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 10/25/2021 17:05:06
Exception:
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Flow.Launcher.Plugin.WebSearch.Main.UpdateResultsFromSuggestionAsync(List`1 results, String keyword, String subtitle, SearchSource searchSource, Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.WebSearch\Main.cs:line 123
   at Flow.Launcher.Plugin.WebSearch.Main.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.WebSearch\Main.cs:line 99
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass111_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 563
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 564
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


```
**Flow Launcher Error Log**

[2021-10-25.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/7407586/2021-10-25.txt)

**Comment by jjw24** [comment]
> I did start my computer a couple of times since I first reported the error.

I see u found the ultimate cheat code for fixing all things computer

**Comment by jjw24** [comment]
Closing, please reopen if problem persists.
