### ISSUE TITLE
Windows 11 + Korean Input

### ISSUE THREAD

**Issue by onesounds** [Flow-Launcher/Flow.Launcher#791]
**Describe the bug/issue**
1. The Korean input is broken and entered. 
e.g 안녕하세요 (ㅇ ㅏ ㄴ ㅕ ㅎ ㅏ ㅅ ㅔ ㅇ ㅛ) -> 안하요 (녕세 is ignored during input.)
Hangul(Korean) is completed in the form of a combination of consonants and vowels, so you cannot test it. It can only be tested by installing Korean ime and typing it randomly.  

2. When Korean is entered in a situation where loading is performed, the flow ends with an error.

I tried not to report because the Korean IME was changed in Windows 11, but there was no sign of modification. When I look at the code to fix, it seems that there is a problem with progress bar when processing each letter. This problem can be reproduced in wox, and there is a similar kind of problem in Windows's basic app (mail). It is not reproduced in powertoy or library 6 beta. In other words, I think this problem can be corrected regardless of ime.

Please let me know if there is an expected cause.

**To Reproduce**
1. Type Korean in querybox

**Your System**
```
Windows build number: Windows 11 Pro Insider Preview 22489.1000
Flow Launcher version: 1.83 
```
**Flow Launcher Error Log**
System.ArgumentException: 요청한 거리가 관련 문서의 콘텐츠의 범위를 벗어납니다. (it's original text is 'Requested distance is outside the content of the associated document.')
   Source: PresentationFramework
   TargetAssembly: PresentationFramework, Version=5.0.10.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
   TargetModule: PresentationFramework.dll
   TargetSite: Void InitializeOffset(System.Windows.Documents.TextPointer, Int32, System.Windows.Documents.LogicalDirection)
   at System.Windows.Documents.TextPointer.InitializeOffset(TextPointer position, Int32 distance, LogicalDirection direction)
   at System.Windows.Documents.TextPointer.System.Windows.Documents.ITextPointer.CreatePointer(Int32 offset, LogicalDirection gravity)
   at System.Windows.Documents.CompositionAdorner.AttributeRange.AddCompositionLines()
   at System.Windows.Documents.CompositionAdorner.InvalidateAdorner()
   at System.Windows.Documents.TextEditor.OnTextViewUpdatedWorker(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by onesounds** [comment]
MS added 'Using Old IME' option. The problem has been resolved, so I close it.
