### ISSUE TITLE
Encoding error with Steam Search plugin

### ISSUE THREAD

**Issue by WallBreakerNO4** [Flow-Launcher/Flow.Launcher#891]
Flow Launcher version: 1.9.0
OS Version: Microsoft Windows NT 10.0.19043.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\zhifa\AppData\Roaming\FlowLauncher\PythonEmbeddable\pythonw.exe
Date: 12/11/2021 01:21:32
Exception:
System.IO.InvalidDataException: Steam Search|Traceback (most recent call last):
  File "C:\Users\zhifa\AppData\Roaming\FlowLauncher\Plugins\Steam Search-2.0.2\main.py", line 12, in <module>
    SteamSearch()
  File "C:\Users\zhifa\AppData\Roaming\FlowLauncher\Plugins\Steam Search-2.0.2\plugin\steam_search.py", line 16, in __init__
    super().__init__()
  File "C:\Users\zhifa\AppData\Roaming\FlowLauncher\Plugins\Steam Search-2.0.2\lib\flox\flox.py", line 104, in __init__
    super().__init__()
  File "C:\Users\zhifa\AppData\Roaming\FlowLauncher\Plugins\Steam Search-2.0.2\lib\flox\launcher.py", line 28, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\zhifa\AppData\Roaming\FlowLauncher\Plugins\Steam Search-2.0.2\lib\flox\flox.py", line 111, in _query
    self.query(query)
  File "C:\Users\zhifa\AppData\Roaming\FlowLauncher\Plugins\Steam Search-2.0.2\plugin\steam_search.py", line 19, in query
    games = self._steam.all_games()
  File "C:\Users\zhifa\AppData\Roaming\FlowLauncher\Plugins\Steam Search-2.0.2\plugin\helper.py", line 36, in all_games
    for game in library.games():
  File "C:\Users\zhifa\AppData\Roaming\FlowLauncher\Plugins\Steam Search-2.0.2\plugin\helper.py", line 81, in games
    _game_manifest = vdf.load(open(manifest, 'r'))
  File "C:\Users\zhifa\AppData\Roaming\FlowLauncher\Plugins\Steam Search-2.0.2\lib\vdf\__init__.py", line 211, in load
    return parse(fp, **kwargs)
  File "C:\Users\zhifa\AppData\Roaming\FlowLauncher\Plugins\Steam Search-2.0.2\lib\vdf\__init__.py", line 97, in parse
    for lineno, line in enumerate(fp, 1):
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 134: illegal multibyte sequence

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 625
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 589
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by taooceros** [comment]
it looks like the issue is because of the encoding of gbk and the steam plugin. Contact @Garulf here https://github.com/Garulf/Steam-Search

**Comment by taooceros** [comment]
@WallBreakerNO4 do you find that error after upgrading to 1.9.0 or installing steam search plugin?

**Comment by Garulf** [comment]
Please try this newer version: https://github.com/Garulf/Steam-Search/releases/tag/v2.1.0
