### ISSUE TITLE
Error occurs when launching Number Converter plugin

### ISSUE THREAD

**Issue by yfzm** [Flow-Launcher/Flow.Launcher#898]
[2021-12-12.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/7698406/2021-12-12.txt)

Flow Launcher version: 1.9.0
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/12/2021 17:00:10
Exception:
System.IO.InvalidDataException: Number Converter|Traceback (most recent call last):
  File "C:\Users\bywind\AppData\Roaming\FlowLauncher\Plugins\Number Converter-1.0.0\main.py", line 11, in <module>
    from flowlauncher import FlowLauncher
ModuleNotFoundError: No module named 'flowlauncher'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 625
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 626
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by yfzm** [comment]
It tends to I have not installed flowlauncher with `pip`... sorry to bother. I will close the issue.

**Comment by jjw24** [comment]
Hey how's it going, actually I see you are using v1, if you update to the latest version of the plugin, you won't need to install anything.

**Comment by yfzm** [comment]
After running `pip install flowlauncher`, it works. I installed the Number Converter plugin from the plugin store in the settings window, and I checked the latest version of this plugin is v1.0.0. Am I missing something here?

**Comment by jjw24** [comment]
My mistake, I mistook it for another plugin. You are right, it's v1 and needs manual install.

I will get in contact with @liberize and hopefully a version without needing to manual pip install is released soon.
