### ISSUE TITLE
Crash when I try to use the "Window Services" plugin

### ISSUE THREAD

**Issue by Dominiquini** [Flow-Launcher/Flow.Launcher#899]
I installed and try to use the plugin "Windows Services", by "Garulf", and the application throw this error:

----------------------------------------
Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues/new
1. upload log file: C:\Users\Rafael Dominiquini\AppData\Roaming\FlowLauncher\Logs\1.9.0\2021-12-12.txt
2. copy below exception message

Flow Launcher version: 1.9.0
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/12/2021 14:39:31
Exception:
System.IO.InvalidDataException: Window Services|Traceback (most recent call last):
  File "C:\Users\Rafael Dominiquini\AppData\Roaming\FlowLauncher\Plugins\Window Services-1.1.1\run.py", line 12, in <module>
    WindowServices()
  File "C:\Users\Rafael Dominiquini\AppData\Roaming\FlowLauncher\Plugins\Window Services-1.1.1\lib\flox\flox.py", line 82, in __init__
    super().__init__()
  File "C:\Users\Rafael Dominiquini\AppData\Roaming\FlowLauncher\Plugins\Window Services-1.1.1\lib\flox\launcher.py", line 28, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\Rafael Dominiquini\AppData\Roaming\FlowLauncher\Plugins\Window Services-1.1.1\lib\flox\flox.py", line 89, in _query
    self.query(query)
  File "C:\Users\Rafael Dominiquini\AppData\Roaming\FlowLauncher\Plugins\Window Services-1.1.1\plugin\window_services.py", line 32, in query
    services = s.get_services()
  File "C:\Users\Rafael Dominiquini\AppData\Roaming\FlowLauncher\Plugins\Window Services-1.1.1\plugin\services.py", line 37, in get_services
    services = sp.check_output("sc query type= service state= all", shell=True).decode("utf-8").split("\r\n\r\n")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 9892: invalid start byte

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 615
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 589
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
----------------------------------------

[2021-12-12.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/7699259/2021-12-12.txt)

OS Version: Windows 10 x64 Version 21H2 (OS Build 19044.1387)
Flow Launcher Version: 1.9.0

Thanks.

**Comment by Garulf** [comment]
Sorry for the late reply, This is a known issue with language encoding.... I should have a fix shortly

**Comment by Garulf** [comment]
Okay I have a fix in this release :https://github.com/Garulf/window-services/releases/tag/v1.1.3

Please give our Plugin Store time to detect the new version.
