### ISSUE TITLE
Flow Launcher got an error

### ISSUE THREAD

**Issue by pwhe23** [Flow-Launcher/Flow.Launcher#902]
Flow Launcher version: 1.9.0
OS Version: Microsoft Windows NT 10.0.19043.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/14/2021 10:44:46
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Flow.Launcher.ViewModel.MainViewModel.Show() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 749
   at Flow.Launcher.ViewModel.MainViewModel.ToggleFlowLauncher() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 727
   at Flow.Launcher.Helper.HotKeyMapper.OnToggleHotkey(Object sender, HotkeyEventArgs args) in C:\projects\flow-launcher\Flow.Launcher\Helper\HotKeyMapper.cs:line 29
   at NHotkey.HotkeyManagerBase.HandleHotkeyMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled, Hotkey& hotkey)
   at NHotkey.Wpf.HotkeyManager.HandleMessage(IntPtr hwnd, Int32 msg, IntPtr wparam, IntPtr lparam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by pwhe23** [comment]
[2021-12-14.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/7712955/2021-12-14.txt)

**Comment by taooceros** [comment]
Does it happen at startup?

**Comment by pwhe23** [comment]
Yes, as soon as the app launches. It worked fine yesterday. I installed it for the first time about 4 days ago.

**Comment by taooceros** [comment]
It happens everytime at startup?

**Comment by pwhe23** [comment]
Well I tried it 2 or 3 times this morning and it happened each time. However, I just tried it again and it launched just fine. Go figure  🤷

**Comment by taooceros** [comment]
I think it's because some racing issue. I will investigate it when I got time. Before fixing it, just restart when error pop out😂.
