### ISSUE TITLE
Exception issue upload

### ISSUE THREAD

**Issue by SplitGemini** [Flow-Launcher/Flow.Launcher#915]
Flow Launcher version: 1.9.0
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/18/2021 20:46:14
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Flow.Launcher.ViewModel.MainViewModel.Show() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 749
   at Flow.Launcher.ViewModel.MainViewModel.ToggleFlowLauncher() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 727
   at Flow.Launcher.Helper.HotKeyMapper.OnToggleHotkey(Object sender, HotkeyEventArgs args) in C:\projects\flow-launcher\Flow.Launcher\Helper\HotKeyMapper.cs:line 29
   at NHotkey.HotkeyManagerBase.HandleHotkeyMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled, Hotkey& hotkey)
   at NHotkey.Wpf.HotkeyManager.HandleMessage(IntPtr hwnd, Int32 msg, IntPtr wparam, IntPtr lparam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at

 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

log: 

[2021-12-18.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/7739244/2021-12-18.txt)

**Comment by taooceros** [comment]
Same as #902. A fix is in the progress.
