### ISSUE TITLE
Flow Launcher crashes when the computer is not connected to the internet

### ISSUE THREAD

**Issue by YFOMNN** [Flow-Launcher/Flow.Launcher#976]
Hi. I have experienced a bug where Flow launcher crashes with the following error message, every time I try to type something into the flow launcher instance when I am not connected to the internet. It crashes for each letter typed. I had done some testing with different plugin settings try to nail down the issue. I think the issue is the web search plugin's search query autocomplete option that causes flow launcher to crash, as it has no source parameter due to the lack of internet connection. Showing the search result as "not connected to the internet" or not showing a result at all would be a good exception. Thank you!

```
Flow Launcher version: 1.9.1
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True


Python Path: 
Date: 01/12/2022 16:52:32
Exception:
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Flow.Launcher.Plugin.WebSearch.Main.UpdateResultsFromSuggestionAsync(List`1 results, String keyword, String subtitle, SearchSource searchSource, Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.WebSearch\Main.cs:line 116
   at Flow.Launcher.Plugin.WebSearch.Main.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Plugins\Flow.Launcher.Plugin.WebSearch\Main.cs:line 92
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by taooceros** [comment]
Could you open the setting panel for websearch plugin and disable search suggestion? We will add a safe check for that soon.

**Comment by YFOMNN** [comment]
Yes, I have already done that. Hoping for the safe check to be implemented soon.
