### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by DInfanger** [Flow-Launcher/Flow.Launcher#982]
[2022-01-17.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/7881817/2022-01-17.txt)

Flow Launcher version: 1.9.1
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 01/17/2022 13:23:20
Exception:
System.InvalidOperationException: Cannot Reopen undo unit while another unit is already open.
   at MS.Internal.Documents.UndoManager.Reopen(IParentUndoUnit unit)
   at System.Windows.Documents.TextEditorTyping.DoTextInput(TextEditor This, String textData, Boolean isInsertKeyToggled, Boolean acceptControlCharacters)
   at System.Windows.Documents.TextEditorTyping.OnTextInput(Object sender, TextCompositionEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.TextCompositionManager.PostProcessInput(Object sender, ProcessInputEventArgs e)
   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.TextCompositionManager.PostProcessInput(Object sender, ProcessInputEventArgs e)
   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessTextInputAction(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler

**Comment by jjw24** [comment]
Hey how's it going?

What action were you doing when you had this error? How could I replicate it?

**Comment by DInfanger** [comment]
Hey, thanks for responding. I was using the calculator plugin. The crash was kind of random, I can't really reproduce it. I was just following the instruction displayed in the error message. Sorry for not being able to help more.

**Comment by jjw24** [comment]
Hey that's all good. I might close this issue for now, if it happens again please do let us know, hopefully there is a way to replicate.

Cheers.
