### ISSUE TITLE
steam-search plugin crash on open

### ISSUE THREAD

**Issue by WWG7211** [Flow-Launcher/Flow.Launcher#986]
https://github.com/Garulf/Steam-Search crashes on open
I have attempted to change the directory for the executable to point directly to the executable as well as to one of my game install directories, neither have worked

**To Reproduce**
1. have your steam games installed on more than one harddrive separate from the steam install directory
2. assign the steam path to the directory where steam is installed
3. experience crash

Flow Launcher version: 1.9.1
OS Version: Microsoft Windows NT 10.0.19043.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 01/19/2022 22:06:42
Exception:
System.IO.InvalidDataException: Steam Search|Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\FlowLauncher\Plugins\Steam Search-3.1.0\main.py", line 12, in <module>
    SteamSearch()
  File "C:\Users\Admin\AppData\Roaming\FlowLauncher\Plugins\Steam Search-3.1.0\lib\flox\__init__.py", line 107, in __init__
    super().__init__(self.api)
  File "C:\Users\Admin\AppData\Roaming\FlowLauncher\Plugins\Steam Search-3.1.0\lib\flox\launcher.py", line 30, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\Admin\AppData\Roaming\FlowLauncher\Plugins\Steam Search-3.1.0\lib\flox\__init__.py", line 113, in _query
    self.query(query)
  File "C:\Users\Admin\AppData\Roaming\FlowLauncher\Plugins\Steam Search-3.1.0\plugin\steam_search.py", line 16, in query
    games = self._steam.all_games()
  File "C:\Users\Admin\AppData\Roaming\FlowLauncher\Plugins\Steam Search-3.1.0\plugin\helper.py", line 52, in all_games
    for game in library.games():
  File "C:\Users\Admin\AppData\Roaming\FlowLauncher\Plugins\Steam Search-3.1.0\plugin\helper.py", line 98, in games
    game = SteamGame(_game_manifest["AppState"]["appid"], _game_manifest["AppState"]["name"], _game_manifest["AppState"]["installdir"], self._steam_path, self._library_path)
KeyError: 'AppState'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 301
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 321
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 211
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 623
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 587
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Hi @WWG7211 I saw your open issue on the plug-in's issue page. I will look into what's causing your crashing as soon as I can. In the mean time could you please provide your `library.vdf` on the plugins issue tracker: https://GitHub.com/garulf/steam-search/issues

**Comment by Garulf** [comment]
Please upgrade your Steam-Search plugin to v3.2.0 by typing:
```
pm update Steam Search
```

The plugin should no longer crash if one manifest file is malformed. 

Please feel free to submit you logs as they may help me get to the root of the issue. The log is located in the Plugin's directory.
