### ISSUE TITLE
No process is associated with this object error

### ISSUE THREAD

**Issue by terax6669** [Flow-Launcher/Flow.Launcher#988]
Your instructions seem wrong.
`1. upload log file: C:\Users\T\AppData\Roaming\FlowLauncher\Logs\1.9.1\2022-01-20.txt`
To be sure I've attached both `2022-01-20.txt` and `2022-01-21.txt`.

```
Flow Launcher version: 1.9.1
OS Version: Microsoft Windows NT 10.0.22000.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 01/21/2022 10:50:31
Exception:
System.AggregateException: One or more errors occurred. (No process is associated with this object.)
 ---> System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.Kill()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 624
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

[2022-01-20.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/7912226/2022-01-20.txt)
[2022-01-21.txt](https://github.com/Flow-Launcher/Flow.Launcher/files/7912227/2022-01-21.txt)

**Comment by taooceros** [comment]
Thank you for the report. This part of code is used to kill python process due to cancellation. I don't believe it happens consistently, so it shouldn't affect daily use.
I will add a safety check for that later.

**Comment by terax6669** [comment]
> I don't believe it happens consistently,

Not consistently, but often enough that it's an annoyance. Just had the same thing happen again. Can't wait for 1.10.0 ;)

**Comment by taooceros** [comment]
> > I don't believe it happens consistently,
> 
> Not consistently, but often enough that it's an annoyance. Just had the same thing happen again. Can't wait for 1.10.0 ;)

if that's the case, I will add a fix recently.

**Comment by taooceros** [comment]
@terax6669 could you take a test with this build. https://ci.appveyor.com/api/buildjobs/trey45b52i14mxx3/artifacts/Output%2FPackages%2FFlow-Launcher-Setup.exe

**Comment by petsuter** [comment]
I got the same error four times over the last two months. (So it would be impossible to test for the absence of this problem.)
